import httpx
import re
import asyncio
from urllib.parse import urljoin
from module_common import safe_fetch, make_finding
SENSITIVE_PATHS = [
    "/.env", "/.env.production", "/.env.development", "/.env.local", "/.env.staging",
    "/.env.example", "/env", "/environment", "/.env.prod", "/.env.dev", "/.env.test",
    "/.env.docker", "/.env.dist", "/.env.bak", "/.env.old", "/env.yaml", "/env.yml",
    "/config", "/config.php", "/config.php.bak", "/config.php.old", "/config.php~",
    "/config.json", "/config.yml", "/config.yaml", "/config.xml", "/config.ini",
    "/configuration.php", "/configuration.yaml", "/configuration.json",
    "/app/config.php", "/app/config.yml", "/app/config.yaml",
    "/settings.py", "/settings.json", "/settings.yml", "/settings.php", "/settings.rb",
    "/secrets.yml", "/secrets.json", "/secret.yml", "/secret.json",
    "/credentials.json", "/credentials.yml", "/credentials.xml",
    "/wp-config.php", "/wp-config.php.bak", "/wp-config.php.old", "/wp-config.php~",
    "/wp-config-sample.php", "/wp-config.bak", "/wp-config.old",
    "/admin", "/administrator", "/manager", "/backend", "/cpanel", "/whm",
    "/panel", "/dashboard", "/admin.php", "/login.php", "/login.aspx",
    "/login.jsp", "/administrator/index.php", "/admin/login.php",
    "/adminpanel", "/cp", "/controlpanel", "/admin/", "/administrator/",
    "/manager/", "/backend/", "/cpanel/", "/panel/", "/dashboard/",
    "/backup.zip", "/backup.tar.gz", "/backup.sql", "/backup.db",
    "/backup.tar", "/backup.gz", "/backup.7z", "/backup.bak",
    "/dump.sql", "/dump.rdb", "/database.sql", "/db.sql",
    "/db_backup.sql", "/db-dump.sql", "/mysql.sql",
    "/wp-content/backup.zip", "/wp-content/backup.sql",
    "/backup/", "/_backup/", "/backups/",
    "/backup.sql.gz", "/mydb.sql", "/data.sql",
    "/site-backup.tar.gz", "/full-backup.tar.gz",
    "/sql-backup.sql", "/mysqldump.sql", "/pgdump.sql",
    "/database.yml", "/database.php", "/database.config",
    "/db.yml", "/db.json", "/db-config.php",
    "/databases.yml", "/connection.yml",
    "/app/database.php", "/app/database.yml",
    "/phpmyadmin/", "/phpMyAdmin/", "/pma/", "/mysql/",
    "/adminer.php", "/adminer-4.7.8.php", "/adminer-*.php",
    "/sqlite.db", "/data.db", "/app.db", "/storage.db",
    "/database.db", "/db.sqlite", "/db.sqlite3",
    "/error.log", "/access.log", "/debug.log", "/application.log",
    "/log.txt", "/logs/", "/log/",
    "/var/log/system.log", "/storage/logs/laravel.log",
    "/wp-content/debug.log", "/wp-content/debug.log.1",
    "/error_log", "/install.log", "/setup.log",
    "/cron.log", "/mail.log", "/auth.log",
    "/apache.log", "/nginx.log", "/php-error.log",
    "/syslog", "/messages.log", "/boot.log",
    "/dmesg", "/lastlog", "/wtmp", "/btmp",
    "/.git/config", "/.gitignore", "/.git/HEAD",
    "/.git/index", "/.git/description",
    "/.git/logs/HEAD", "/.git/packed-refs",
    "/.git/refs/heads/master", "/.git/ORIG_HEAD",
    "/.git/FETCH_HEAD", "/.svn/entries", "/.svn/wc.db",
    "/.svn/all-wcprops", "/.svn/text-base/",
    "/.hg/", "/.hg/hgrc", "/.hg/store/",
    "/.bzr/", "/.bzr/branch/",
    "/.DS_Store", "/Thumbs.db",
    "/crossdomain.xml", "/clientaccesspolicy.xml",
    "/sitemap.xml", "/robots.txt", "/security.txt",
    "/humans.txt", "/well-known/security.txt",
    "/.htaccess", "/.htpasswd", "/.htgroup", "/.htdigest",
    "/.aws/credentials", "/.aws/config",
    "/.aws/credentials.json", "/.aws/config.json",
    "/.azure/credentials", "/.azure/config",
    "/.azure/credentials.json", "/.azure/config.json",
    "/.gcloud/credentials", "/.gcloud/config",
    "/.gcloud/credentials.json", "/.gcloud/config.json",
    "/.ssh/id_rsa", "/.ssh/id_rsa.pub", "/.ssh/authorized_keys",
    "/.ssh/config", "/.ssh/known_hosts",
    "/.ssh/id_dsa", "/.ssh/id_ecdsa", "/.ssh/id_ed25519",
    "/.npmrc", "/.dockercfg", "/.s3cfg", "/.netrc",
    "/id_rsa", "/id_rsa.pub", "/authorized_keys",
    "/.git-credentials", "/.gitconfig",
    "/api/swagger.json", "/api/swagger.yaml", "/api/swagger.yml",
    "/api/openapi.json", "/api/openapi.yaml",
    "/api/docs", "/api/v1/", "/api/v2/", "/api/v3/",
    "/swagger/", "/swagger-ui/", "/swagger-resources",
    "/v2/api-docs", "/v3/api-docs",
    "/api/", "/rest/", "/graphql", "/graphiql", "/voyager",
    "/api/documentation",
    "/.travis.yml", "/.circleci/config.yml",
    "/.github/workflows/", "/.gitlab-ci.yml",
    "/Jenkinsfile", "/Dockerfile", "/docker-compose.yml",
    "/docker-compose.yaml", "/.dockerignore",
    "/Makefile", "/.gitmodules",
    "/bitbucket-pipelines.yml", "/azure-pipelines.yml",
    "/.gitlab-ci.yml", "/.circleci/", "/.github/",
    "/environment.ts", "/environment.prod.ts",
    "/.flaskenv", "/.env.yaml",
    "/build.env", "/package.env",
    "/security.txt", "/.well-known/security.txt",
    "/ssl.crt", "/ssl.key", "/server.crt", "/server.key",
    "/cert.pem", "/key.pem", "/fullchain.pem",
    "/privkey.pem", "/chain.pem",
    "/.well-known/", "/acme-challenge/",
    "/.git/objects/", "/.git/refs/",
    "/tmp/", "/temp/", "/cache/",
    "/files/", "/uploads/", "/upload/",
    "/downloads/", "/download/",
    "/assets/", "/static/", "/public/",
    "/phpinfo.php", "/info.php", "/test.php", "/debug.php",
    "/tests/", "/test/", "/testing/",
    "/phpunit.xml", "/phpunit.xml.dist",
    "/phpinfo.php.bak", "/info.php.bak",
    "/.phpunit.result.cache",
    "/actuator/health", "/actuator/info", "/actuator/env",
    "/actuator/beans", "/actuator/mappings",
    "/actuator/configprops", "/actuator/threaddump",
    "/actuator/heapdump", "/actuator/loggers",
    "/actuator/metrics", "/actuator/prometheus",
    "/actuator/", "/heapdump", "/heapdump.json",
    "/metrics", "/health", "/healthcheck",
    "/env", "/info", "/trace",
    "/__init__.py",
    "/.git/config", "/.git/HEAD", "/.git/refs",
    "/server-status", "/server-info", "/cgi-bin/",
    "/cgi-bin/test.cgi", "/cgi-bin/php", "/cgi-bin/status",
    "/aws.yml", "/aws.json", "/aws_config",
    "/google-services.json", "/GoogleService-Info.plist",
    "/firebase.json", "/firebase.php", "/firebase.config",
    "/Procfile", "/.slugignore", "/runtime.txt",
    "/requirements.txt", "/Pipfile", "/Pipfile.lock",
    "/Gemfile", "/Gemfile.lock", "/composer.json", "/composer.lock",
    "/package.json", "/package-lock.json", "/yarn.lock",
    "/yarn.lock", "/pnpm-lock.yaml", "/bower.json",
    "/Gruntfile.js", "/gulpfile.js", "/webpack.config.js",
    "/rollup.config.js", "/vite.config.js", "/tsconfig.json",
    "/.babelrc", "/.eslintrc", "/.prettierrc",
    "/.stylelintrc", "/.jshintrc",
    "/nginx.conf", "/apache.conf", "/httpd.conf",
    "/.htaccess.bak", "/.htaccess.old", "/.htaccess.sav",
    "/htaccess.txt", "/htpasswd",
    "/passwd", "/shadow", "/group",
    "/sudoers", "/sudoers.d/",
    "/mysql_history", "/psql_history", "/bash_history",
    "/zsh_history", "/fish_history",
    "/.mysql_history", "/.psql_history",
    "/.bash_history", "/.zsh_history",
    "/server.key", "/server.csr", "/server.crt",
    "/ca.key", "/ca.crt", "/ca.csr",
    "/client.key", "/client.crt", "/client.csr",
    "/private.key", "/private.pem", "/public.pem",
    "/certificate.pem", "/certificate.crt",
    "/keystore.jks", "/keystore", "/truststore.jks",
    "/.p12", "/.pfx", "/.jks",
    "/index.php.bak", "/index.php.old", "/index.php~",
    "/index.html.bak", "/index.html.old",
    "/.maintenance", "/maintenance.php",
    "/app/.env", "/app/config.php", "/app/settings.php",
    "/api/config", "/api/health", "/api/status",
    "/api/swagger.json", "/api/openapi.json",
    "/graphql", "/graphiql", "/graphql/explorer",
    "/v1/graphql", "/v2/graphql",
    "/actuator", "/actuator/health", "/actuator/info",
    "/.elasticbeanstalk/", "/ebextensions/",
    "/.platform/", "/.buildpacks",
    "/Vagrantfile", "/.vagrant/",
    "/.terraform/", "/terraform.tfstate",
    "/terraform.tfvars", "/backend.tf",
    "/.serverless/", "/serverless.yml",
    "/samconfig.toml", "/template.yaml",
    "/cloudformation.yaml", "/cloudformation.json",
    "/Pulumi.yaml", "/pulumi/",
    "/ansible.cfg", "/ansible/", "/playbook.yml",
    "/inventory.yml", "/hosts.ini",
    "/Dockerfile.prod", "/Dockerfile.dev",
    "/docker-entrypoint.sh", "/docker-entrypoint-initdb.d/",
    "/k8s/", "/kubernetes/", "/deployment.yaml",
    "/service.yaml", "/kustomization.yaml",
    "/Chart.yaml", "/helm/", "/values.yaml",
    "/.helmignore", "/templates/",
    "/Podfile", "/Podfile.lock",
    "/Cartfile", "/Cartfile.resolved",
    "/.swiftpm/", "/Package.swift",
    "/go.mod", "/go.sum", "/Gopkg.toml",
    "/Cargo.toml", "/Cargo.lock",
    "/build.gradle", "/gradle.properties",
    "/gradlew", "/gradlew.bat",
    "/pom.xml", "/settings.xml",
    "/.mvn/", "/mvnw",
    "/web.xml", "/application.xml",
    "/jboss-web.xml", "/glassfish-web.xml",
    "/context.xml", "/server.xml",
    "/tomcat-users.xml", "/catalina.policy",
    "/WEB-INF/web.xml", "/WEB-INF/applicationContext.xml",
    "/META-INF/context.xml",
    "/struts.xml", "/struts-config.xml",
    "/hibernate.cfg.xml", "/mybatis-config.xml",
    "/spring.xml", "/application.properties",
    "/application.yml", "/bootstrap.properties",
    "/bootstrap.yml", "/logback.xml",
    "/log4j.properties", "/log4j2.xml",
    "/logging.properties",
    "/appsettings.json", "/appsettings.Development.json",
    "/nlog.config", "/serilog.json",
    "/elastic-apm-agent.jar",
    "/newrelic.yml", "/newrelic/",
    "/datadog.yml", "/datadog/",
    "/appdynamics/", "/dynatrace/",
    "/.well-known/acme-challenge/",
    "/.well-known/assetlinks.json",
    "/.well-known/apple-app-site-association",
    "/.well-known/change-password",
    "/.well-known/dnt-policy.txt",
    "/.well-known/gpc.json",
    "/.well-known/keybase.txt",
    "/.well-known/matrix/",
    "/.well-known/nodeinfo",
    "/.well-known/openid-configuration",
    "/.well-known/pki-validation/",
    "/.well-known/webfinger",
    "/.well-known/webrtc",
    "/server-status", "/server-info",
    "/cgi-bin/", "/cgi-bin/test.cgi", "/cgi-bin/php5.cgi",
    "/sitemap.xml.gz", "/sitemaps.xml",
    "/sitemap_index.xml", "/sitemapindex.xml",
    "/sitemap1.xml", "/sitemap2.xml",
    "/rss.xml", "/atom.xml", "/feed.xml",
    "/robots.txt.bak", "/robots.txt.old",
    "/.svn/entries", "/.svn/wc.db",
    "/.svn/all-wcprops", "/.svn/prop-base/",
    "/.svn/text-base/", "/.svn/tmp/",
    "/CVS/", "/CVS/Root", "/CVS/Entries",
    "/.bzr.log", "/.bzr/README",
    "/.hgignore", "/.hgtags", "/.hg/branch",
    "/.DS_Store", "/.localized",
    "/thumbs.db", "/Thumbs.db:encryptable",
    "/.Trashes", "/.Spotlight-V100",
    "/.fseventsd", "/.vol",
    "/.apdisk", "/Desktop.ini",
    "/error.html", "/404.html", "/500.html",
    "/maintenance.html", "/under-construction.html",
    "/index.html", "/index.php", "/index.asp", "/index.aspx",
    "/default.aspx", "/default.asp", "/default.php",
    "/home.php", "/home.html",
    "/.bashrc", "/.bash_profile", "/.profile",
    "/.bash_logout", "/.inputrc",
    "/.vimrc", "/.viminfo", "/.exrc",
    "/.screenrc", "/.tmux.conf",
    "/.gitattributes", "/.mailmap",
    "/.editorconfig", "/.gitkeep",
    "/.nuget/", "/NuGet.Config",
    "/.dotnet/", "/global.json",
    "/project.json", "/project.lock.json",
    "/bundleconfig.json", "/tslint.json",
    "/.jscsrc", "/.jshintignore",
    "/.tern-project", "/jsconfig.json",
    "/.watchmanconfig", "/flow-typed/",
    "/.yarnrc", "/.yarn/",
    "/.npm/", "/.node_repl_history",
    "/.python-version", "/.pythonrc",
    "/.ruby-version", "/.ruby-gemset",
    "/.rbenv/", "/.rvm/",
    "/.bundler/", "/vendor/bundle/",
    "/.bundle/", "/vendor/cache/",
    "/.gem/", "/Gemfile.lock",
    "/composer.lock", "/vendor/",
    "/.php_cs", "/.php_cs.dist",
    "/.phpunit/", "/.phpunit_on_failure",
    "/phpunit.phar", "/phpunit",
    "/behat.yml", "/.behat/",
    "/codeception.yml", "/.codeception/",
    "/.perlcriticrc", "/perltidyrc",
    "/.coveralls.yml", "/.scrutinizer.yml",
    "/.codeclimate.yml", "/.codecov.yml",
    "/sonar-project.properties", "/sonar-project.json",
    "/.sensiolabs.yml", "/.styleci.yml",
    "/crowdin.yml", "/.tx/",
    "/.bootstrap.yml", "/.dockerignore",
    "/.ecr", "/.gitlab/",
    "/mercurial.ini", "/.hgrc",
    "/Procfile", "/.buildpacks",
    "/Aptfile", "/app.json",
    "/scalingo.json", "/.scalingo/",
    "/.platform.app.yaml", "/.platform/",
    "/artisan", "/.env.example",
    "/.php_cs.cache", "/.phpunit.result.cache",
    "/.phpunit_on_failure", "/.phpunit.php",
    "/.phpunit.xml", "/phpunit.xml",
    "/pint.json", "/.pint.json",
    "/.php-cs-fixer.php", "/.php-cs-fixer.dist.php",
    "/rector.php", "/rector.yaml",
    "/deptrac.yaml", "/deptrac.yml",
    "/phpstan.neon", "/phpstan.neon.dist",
    "/phpstan-baseline.neon",
    "/psalm.xml", "/psalm.xml.dist",
    "/psalm-baseline.xml",
    "/.phpdoc/", "/phpdoc.dist.xml",
    "/.phpmetrics.json", "/phpmetrics.json",
    "/infection.json", "/infection.json.dist",
    "/.phpbench/", "/phpbench.json",
    "/.dep/", "/deploy.php", "/deploy.yaml",
    "/.forge/", "/forge.yml",
    "/.envault", "/envault.json",
    "/auth.json", "/composer/auth.json",
    "/satis.json", "/packages.json",
    "/security-checker.php", "/security-checker",
    "/.capsule/", "/capsule.yml",
    "/.php_monitor/", "/php_monitor.yml",
    "/.php_watch/", "/php_watch.yml",
    "/.phplint.yml", "/.php-lint.yml",
    "/.php_cs.cache", "/.php_cs.php",
    "/.phpstorm.meta.php", "/.idea/",
    "/.vscode/", "/.vs/",
    "/phpdoc/", "/docs/",
    "/swagger/", "/redoc/",
    "/api/doc", "/api/documentation",
    "/v1/api-docs", "/v2/api-docs", "/v3/api-docs",
    "/openapi.json", "/openapi.yaml",
    "/swagger.json", "/swagger.yaml",
    "/.env.production", "/.env.development",
    "/.env.staging", "/.env.testing",
    "/.env.prod", "/.env.dev", "/.env.stage",
    "/.env.test", "/.env.local.php",
    "/.env.docker", "/.env.dist",
    "/.env.mysql", "/.env.postgres",
    "/.env.redis", "/.env.mongo",
    "/.env.aws", "/.env.gcp", "/.env.azure",
    "/.env.s3", "/.env.stripe",
    "/.env.mail", "/.env.smtp",
    "/.env.db", "/.env.database",
    "/.env.cache", "/.env.session",
    "/.env.queue", "/.env.log",
    "/.env.app", "/.env.api",
    "/.env.services", "/.env.integrations",
    "/.env.oauth", "/.env.auth",
    "/.env.pagination", "/.env.cors",
    "/.env.debug", "/.env.logging",
    "/.env.monitoring", "/.env.tracing",
    "/.env.features", "/.env.flags",
    "/.env.build", "/.env.docker-compose",
    "/.env.ci", "/.env.cd",
    "/.env.backup", "/.env.restore",
]

SENSITIVE_CONTENT_SIGNATURES = {
    "AWS Access Key": [r'AKIA[0-9A-Z]{16}'],
    "Private Key": [r'-----BEGIN\s+(RSA|EC|DSA|OPENSSH|PGP)\s+PRIVATE KEY'],
    "Database Credential": [r'(?i)(password|passwd|db_password|db_user).*[=:].*["\']?[a-zA-Z0-9]'],
    "API Key": [r'(?i)(api_key|apikey|api_secret)\s*[=:]\s*["\']?[A-Za-z0-9_\-]{16,}'],
    "JWT Token": [r'eyJ[A-Za-z0-9_\-]{10,}\.eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}'],
    "Connection String": [r'(?i)(mongodb|postgresql|mysql|redis)://[^\s\'"]+'],
    "GitHub Token": [r'(?i)gh[pousr]_[0-9a-zA-Z]{36}'],
    "Slack Token": [r'(?i)xox[abposr]-[0-9a-zA-Z\-]{10,}'],
    "Discord Webhook": [r'(?:https?://)?discord(?:app)?\.com/api/webhooks/'],
    "Database Dump": [r'(?i)(INSERT INTO|CREATE TABLE|DROP TABLE|SELECT \* FROM)'],
    "Stack Trace": [r'(?:at\s+[a-zA-Z0-9_.]+\(|Traceback \(most recent call last\)|Error:\s+\w+)'],
    "XML Config": [r'<configuration>|<\?xml version.*encoding'],
    "JSON Config": [r'"database"|"connection"|"credentials"|"secret"'],
    "Environment Variable": [r'(?i)(APP_ENV|DB_HOST|DB_PORT|DB_DATABASE|DB_USERNAME|DB_PASSWORD)\s*='],
    "IP Address": [r'\b(?:\d{1,3}\.){3}\d{1,3}\b'],
    "Email Address": [r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'],
    "PHP Error/Notice": [r'(?:PHP Notice|PHP Warning|PHP Fatal|PHP Parse error)'],
    "SQL Error": [r'(?:SQL syntax|MySQL Syntax|SQLSTATE|PDOException|You have an error in your SQL)'],
    "Path Disclosure": [r'(?:Warning: include|Warning: require|Fatal error: Call to undefined function)'],
    "Ruby Error": [r'(?:NameError|NoMethodError|ArgumentError|TypeError)'],
    "Python Error": [r'(?:Traceback|File ".*", line \d+|ModuleNotFoundError|ImportError)'],
    "Java Error": [r'(?:Exception in thread|at org\.|at com\.|at net\.|Caused by:)'],
    "ASP.NET Error": [r'(?:Server Error in|Runtime Error|Stack Trace:.*\.cs)'],
    "NPM Token": [r'(?i)npm.*_[a-z]+[_-]?token\s*[=:]\s*["\']?[A-Za-z0-9_\-]{20,}'],
    "Password in Config": [r'(?i)(password|passwd|pwd)\s*[=:]\s*["\']?[^\s\'"]{6,}["\']?'],
}

DIRECTORY_LISTING_INDICATORS = [
    "Index of /",
    "<title>Index of",
    "Parent Directory</a>",
    "Name</th><th>Last modified</th>",
    "Directory listing for",
]

async def _check_error_indicators(url: str, body: str, findings: list):
    for pat in ERROR_INDICATORS_EXTRA:
        try:
            if re.search(pat, body, re.I):
                findings.append(make_finding(
                    entity=f"Error indicator: {pat[:80]}...",
                    ftype="Error Page Detection",
                    source="SensitiveFilesHunter",
                    confidence="High",
                    color="red",
                    threat_level="Critical Risk",
                    tags=["error", "debug", "information-disclosure"],
                    raw_data=f"URL: {url}\nPattern: {pat}",
                ))
                return
        except Exception:
            pass

async def _check_path(path: str, base_url: str, domain: str, client: httpx.AsyncClient) -> list:
    findings = []
    url = urljoin(base_url, path)
    try:
        resp = await safe_fetch(client, 
            url, timeout=8.0, follow_redirects=False,
            headers={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36"},
        )
        status = resp.status_code
        if status in (200, 204, 401, 403, 500, 301, 302, 307, 308):
            body = resp.text[:10000] if hasattr(resp, "text") else ""
            content_type = resp.headers.get("content-type", "")
            content_length = len(resp.text) if hasattr(resp, "text") else 0

            tags = ["sensitive", "path"]
            exposed_data_types = []

            if status in (200, 204):
                for data_type, patterns in SENSITIVE_CONTENT_SIGNATURES.items():
                    for pat in patterns:
                        try:
                            if re.search(pat, body):
                                exposed_data_types.append(data_type)
                                tags.append(data_type.lower().replace(" ", "_"))
                                break
                        except:
                            pass

                is_dir_listing = any(indicator in body for indicator in DIRECTORY_LISTING_INDICATORS)
                if is_dir_listing:
                    tags.append("directory_listing")
                    exposed_data_types.append("Directory Listing")

                await _check_error_indicators(url, body, findings)

                has_default_creds = False
                default_cred_patterns = [
                    r'(?i)(?:default|admin|root).*(?:password|pass|login)',
                    r'(?i)(?:username|login|user)\s*[=:]\s*admin',
                    r'(?i)(?:password|pass)\s*[=:]\s*(?:admin|password|1234)',
                ]
                for pat in default_cred_patterns:
                    if re.search(pat, body):
                        has_default_creds = True
                        tags.append("default_credentials")
                        if "Default Credentials" not in exposed_data_types:
                            exposed_data_types.append("Default Credentials")
                        break

            severity = "Elevated Risk"
            color = "orange"
            if exposed_data_types:
                severity = "High Risk"
                color = "red"
                if "Private Key" in exposed_data_types or "AWS Access Key" in exposed_data_types:
                    severity = "Critical Risk"
                    color = "red"
            if status == 401:
                severity = "Medium Risk"
                color = "orange"
            if status == 403:
                severity = "Restricted Access"
                color = "orange"

            raw_parts = [f"HTTP {status}"]
            if exposed_data_types:
                raw_parts.append(f"Exposed: {', '.join(exposed_data_types[:3])}")
            raw_parts.append(f"Size: {content_length} bytes")
            raw_parts.append(f"Type: {content_type[:50]}")

            redirect_location = ""
            if status in (301, 302, 307, 308):
                redirect_location = resp.headers.get("location", "")
                raw_parts.append(f"Redirect: {redirect_location[:80]}")

            findings.append(make_finding(
                entity=url,
                ftype="Sensitive File/Path",
                source="SensitiveFilesHunter",
                confidence="High",
                color=color,
                threat_level=severity,
                status=f"HTTP {status}",
                tags=tags,
                raw_data=" | ".join(raw_parts),
            ))

            if content_length == 0 and status == 200:
                findings.append(make_finding(
                    entity=f"Empty response: {url}",
                    ftype="Empty Response",
                    source="SensitiveFilesHunter",
                    confidence="Medium",
                    color="yellow",
                    threat_level="Informational",
                    raw_data="Empty body returned (0 bytes)",
                    tags=["sensitive", "empty"],
                ))

            if exposed_data_types:
                for edt in exposed_data_types[:3]:
                    findings.append(make_finding(
                        entity=f"{url} - {edt}",
                        ftype=f"Exposed Data: {edt}",
                        source="SensitiveFilesHunter",
                        confidence="High",
                        color="red",
                        threat_level="Critical Risk" if edt in ("Private Key", "AWS Access Key", "Database Dump") else "High Risk",
                        status=f"HTTP {status}",
                        tags=["exposed-data", edt.lower().replace(" ", "_")],
                        raw_data=f"URL: {url}\nData Type: {edt}",
                    ))

        elif status in (301, 302, 307, 308):
            location = resp.headers.get("location", "")
            findings.append(make_finding(
                entity=url,
                ftype="Sensitive Path (Redirect)",
                source="SensitiveFilesHunter",
                confidence="Medium",
                color="slate",
                threat_level="Informational",
                status=f"HTTP {status} -> {location[:80]}",
                tags=["redirect"],
            ))

    except Exception:
        pass
    return findings

SENSITIVE_PATHS_EXTRA = [
    "/.env.backup", "/.env.orig", "/.env.save", "/.env.swp", "/.env.old",
    "/.env.local.php", "/.env.production.local", "/.env.development.local",
    "/.env.staging.local", "/.env.testing.local", "/.env.docker.local",
    "/env.json", "/env.xml", "/env.list",
    "/config/database.php", "/config/app.php", "/config/auth.php",
    "/config/cache.php", "/config/session.php", "/config/mail.php",
    "/config/services.php", "/config/filesystems.php", "/config/logging.php",
    "/config/hashing.php", "/config/broadcasting.php", "/config/queue.php",
    "/config/cors.php", "/config/view.php",
    "/app/Config/Database.php", "/app/Config/App.php",
    "/app/config/config.php", "/app/config/database.php",
    "/include/config.php", "/include/db.php",
    "/includes/config.php", "/includes/database.php",
    "/lib/config.php", "/lib/db.php",
    "/core/config.php", "/core/database.php",
    "/system/config.php", "/system/database.php",
    "/private/config.php", "/private/database.php",
    "/protected/config.php", "/protected/database.php",
    "/config.default.php", "/config.sample.php",
    "/config.inc.php", "/config.inc",
    "/configuration.sample.php", "/configuration.default.php",
    "/settings.inc", "/settings.default.php",
    "/wp-config-sample.php", "/wp-config.bak", "/wp-config.old",
    "/wp-config.php~", "/wp-config.php.bak", "/wp-config.php.old",
    "/wp-config.php.save", "/wp-config.php.swp",
    "/wp-config.php.orig", "/wp-config.php.local",
    "/wp-config-production.php", "/wp-config-staging.php",
    "/wp-config-development.php", "/wp-config-testing.php",
    "/admin/config.php", "/admin/database.php",
    "/admin/settings.php", "/admin/configuration.php",
    "/administrator/config.php", "/administrator/database.php",
    "/administrator/settings.php",
    "/dashboard/config.php", "/dashboard/database.php",
    "/panel/config.php", "/panel/database.php",
    "/api/config.php", "/api/database.php",
    "/v1/config.php", "/v2/config.php", "/v3/config.php",
    "/wp-content/plugins/", "/wp-content/themes/", "/wp-content/uploads/",
    "/wp-content/languages/", "/wp-content/upgrade/",
    "/wp-content/cache/", "/wp-content/wflogs/",
    "/wp-includes/rest-api/", "/wp-includes/js/",
    "/wp-admin/js/", "/wp-admin/css/",
    "/wp-admin/includes/", "/wp-admin/network/",
    "/wp-json/wp/v2/", "/wp-json/wp/v2/users",
    "/xmlrpc.php", "/xmlrpc.php?rsd",
    "/wp-cron.php", "/wp-activate.php", "/wp-signup.php",
    "/wp-mail.php", "/wp-links-opml.php",
    "/wp-trackback.php", "/wp-comments-post.php",
    "/readme.html", "/readme.txt", "/license.txt",
    "/install.php", "/upgrade.php", "/setup.php",
    "/install/index.php", "/upgrade/index.php",
    "/INSTALL.txt", "/INSTALL.md", "/UPGRADE.txt",
    "/CHANGELOG.txt", "/CHANGELOG.md", "/CHANGE_LOG.txt",
    "/RELEASE_NOTES.txt", "/RELEASE_NOTES.md",
    "/VERSION.txt", "/VERSION.md", "/version.txt",
    "/COPYRIGHT.txt", "/COPYRIGHT.md",
    "/LICENSE.txt", "/LICENSE.md", "/LICENSE",
    "/README.txt", "/README.md", "/README",
    "/CONTRIBUTING.md", "/CONTRIBUTORS.txt",
    "/AUTHORS.txt", "/AUTHORS.md",
    "/SECURITY.md", "/SECURITY.txt",
    "/CODE_OF_CONDUCT.md", "/SUPPORT.md",
    "/.github/FUNDING.yml", "/.github/ISSUE_TEMPLATE/",
    "/.github/PULL_REQUEST_TEMPLATE/",
    "/.github/dependabot.yml", "/.github/CODEOWNERS",
    "/.github/workflows/ci.yml", "/.github/workflows/deploy.yml",
    "/.github/workflows/test.yml", "/.github/workflows/build.yml",
    "/.github/workflows/release.yml", "/.github/workflows/cd.yml",
    "/.vscode/settings.json", "/.vscode/launch.json",
    "/.vscode/tasks.json", "/.vscode/extensions.json",
    "/.vscode/c_cpp_properties.json",
    "/.idea/workspace.xml", "/.idea/modules.xml",
    "/.idea/php.xml", "/.idea/vcs.xml",
    "/.idea/misc.xml", "/.idea/encodings.xml",
    "/.idea/deployment.xml", "/.idea/sqldialects.xml",
    "/.idea/dataSources.xml", "/.idea/dataSources.ids",
    "/.idea/webResources.xml", "/.idea/inspectionProfiles/",
    "/.idea/runConfigurations/", "/.idea/codeStyles/",
    "/.vs/ProjectSettings.json", "/.vs/slnx.sqlite",
    "/.vs/VSWorkspaceState.json",
    "/sftp-config.json", "/sftp.json",
    "/.remote-sync.json", "/.remote-sync-config.json",
    "/.filezilla", "/.filezilla.xml",
    "/.putty", "/putty.reg",
    "/deploy-config.php", "/deploy-config.json",
    "/deploy.php", "/deploy.yaml", "/deploy.yml",
    "/deploy.json", "/deploy.conf",
    "/.env.ci", "/.env.cd",
    "/ci.env", "/cd.env",
    "/.env.build", "/.env.release",
    "/cloudbuild.yaml", "/cloudbuild.json",
    "/app.yaml", "/app.json",
    "/runtime.yaml", "/runtime.json",
    "/functions.yaml", "/functions.json",
    "/worker.yaml", "/worker.json",
    "/queue.yaml", "/queue.json",
    "/cron.yaml", "/cron.json",
    "/dispatch.yaml", "/dispatch.json",
    "/index.yaml", "/index.json",
    "/datastore-indexes.xml", "/datastore-indexes.json",
    "/application.properties", "/application.yml",
    "/application.yaml", "/application.json",
    "/application-dev.properties", "/application-dev.yml",
    "/application-prod.properties", "/application-prod.yml",
    "/application-test.properties", "/application-test.yml",
    "/application-staging.properties", "/application-staging.yml",
    "/bootstrap.properties", "/bootstrap.yml",
    "/bootstrap-dev.properties", "/bootstrap-prod.properties",
    "/logback.xml", "/logback-spring.xml",
    "/log4j.properties", "/log4j2.xml",
    "/log4j2.properties", "/log4j2.yaml",
    "/logging.properties", "/logging.yml",
    "/logging-config.xml", "/logging-config.json",
    "/appsettings.json", "/appsettings.Development.json",
    "/appsettings.Production.json", "/appsettings.Staging.json",
    "/appsettings.Testing.json", "/appsettings.Local.json",
    "/appsettings.Docker.json", "/appsettings.Integration.json",
    "/appsettings.Azure.json", "/appsettings.AWS.json",
    "/appsettings.GCP.json",
    "/nlog.config", "/nlog.xml",
    "/serilog.json", "/serilog.config",
    "/elastic-apm-agent.jar", "/elastic-apm-agent.properties",
    "/newrelic.yml", "/newrelic/",
    "/datadog.yml", "/datadog/",
    "/appdynamics/", "/dynatrace/",
    "/cgi-bin/", "/cgi-bin/test.cgi", "/cgi-bin/php5.cgi",
    "/cgi-bin/php.cgi", "/cgi-bin/perl.cgi",
    "/cgi-bin/python.cgi", "/cgi-bin/ruby.cgi",
    "/cgi-bin/status", "/cgi-bin/admin.cgi",
    "/sitemap.xml.gz", "/sitemaps.xml",
    "/sitemap_index.xml", "/sitemapindex.xml",
    "/sitemap1.xml", "/sitemap2.xml", "/sitemap3.xml",
    "/rss.xml", "/atom.xml", "/feed.xml",
    "/rss2.xml", "/feed/rss/", "/feed/atom/",
    "/robots.txt.bak", "/robots.txt.old", "/robots.txt.save",
    "/.svn/entries", "/.svn/wc.db",
    "/.svn/all-wcprops", "/.svn/prop-base/",
    "/.svn/text-base/", "/.svn/tmp/",
    "/.svn/format", "/.svn/props/",
    "/CVS/", "/CVS/Root", "/CVS/Entries",
    "/CVS/Repository", "/CVS/Entries.Log",
    "/.bzr.log", "/.bzr/README",
    "/.bzr/branch-format", "/.bzr/checkout/",
    "/.hgignore", "/.hgtags", "/.hg/branch",
    "/.hg/hgrc", "/.hg/requires",
    "/.hg/00changelog.i", "/.hg/store/",
    "/.DS_Store", "/.localized",
    "/thumbs.db", "/Thumbs.db:encryptable",
    "/.Trashes", "/.Spotlight-V100",
    "/.fseventsd", "/.vol",
    "/.apdisk", "/Desktop.ini",
    "/error.html", "/404.html", "/500.html",
    "/403.html", "/401.html", "/503.html",
    "/maintenance.html", "/under-construction.html",
    "/error.php", "/404.php", "/500.php",
    "/index.html", "/index.php", "/index.asp", "/index.aspx",
    "/default.aspx", "/default.asp", "/default.php",
    "/home.php", "/home.html",
    "/.bashrc", "/.bash_profile", "/.profile",
    "/.bash_logout", "/.inputrc",
    "/.bash_history", "/.bash_aliases",
    "/.zshrc", "/.zprofile", "/.zlogin",
    "/.zsh_history", "/.zlogout",
    "/.vimrc", "/.viminfo", "/.exrc",
    "/.screenrc", "/.tmux.conf",
    "/.gitattributes", "/.mailmap",
    "/.editorconfig", "/.gitkeep",
    "/.git-blame-ignore-revs",
    "/.nuget/", "/NuGet.Config",
    "/.dotnet/", "/global.json",
    "/project.json", "/project.lock.json",
    "/bundleconfig.json", "/tslint.json",
    "/.jscsrc", "/.jshintignore",
    "/.tern-project", "/jsconfig.json",
    "/.watchmanconfig", "/flow-typed/",
    "/.yarnrc", "/.yarn/",
    "/.npm/", "/.node_repl_history",
    "/.node-gyp/", "/.npmrc",
    "/.python-version", "/.pythonrc",
    "/.ruby-version", "/.ruby-gemset",
    "/.rbenv/", "/.rvm/",
    "/.bundler/", "/vendor/bundle/",
    "/.bundle/", "/vendor/cache/",
    "/.gem/", "/Gemfile.lock",
    "/composer.lock", "/vendor/",
    "/.php_cs", "/.php_cs.dist",
    "/.phpunit/", "/.phpunit_on_failure",
    "/phpunit.phar", "/phpunit",
    "/behat.yml", "/.behat/",
    "/codeception.yml", "/.codeception/",
    "/.perlcriticrc", "/perltidyrc",
    "/.coveralls.yml", "/.scrutinizer.yml",
    "/.codeclimate.yml", "/.codecov.yml",
    "/sonar-project.properties", "/sonar-project.json",
    "/.sensiolabs.yml", "/.styleci.yml",
    "/crowdin.yml", "/.tx/",
    "/.bootstrap.yml", "/.dockerignore",
    "/.ecr", "/.gitlab/",
    "/mercurial.ini", "/.hgrc",
    "/Procfile", "/.buildpacks",
    "/Aptfile", "/app.json",
    "/scalingo.json", "/.scalingo/",
    "/.platform.app.yaml", "/.platform/",
    "/artisan", "/.env.example",
    "/.php_cs.cache", "/.phpunit.result.cache",
    "/.phpunit_on_failure", "/.phpunit.php",
    "/.phpunit.xml", "/phpunit.xml",
    "/pint.json", "/.pint.json",
    "/.php-cs-fixer.php", "/.php-cs-fixer.dist.php",
    "/rector.php", "/rector.yaml",
    "/deptrac.yaml", "/deptrac.yml",
    "/phpstan.neon", "/phpstan.neon.dist",
    "/phpstan-baseline.neon",
    "/psalm.xml", "/psalm.xml.dist",
    "/psalm-baseline.xml",
    "/.phpdoc/", "/phpdoc.dist.xml",
    "/.phpmetrics.json", "/phpmetrics.json",
    "/infection.json", "/infection.json.dist",
    "/.phpbench/", "/phpbench.json",
    "/.dep/", "/deploy.php", "/deploy.yaml",
    "/.forge/", "/forge.yml",
    "/.envault", "/envault.json",
    "/auth.json", "/composer/auth.json",
    "/satis.json", "/packages.json",
    "/security-checker.php", "/security-checker",
    "/.capsule/", "/capsule.yml",
    "/.php_monitor/", "/php_monitor.yml",
    "/.php_watch/", "/php_watch.yml",
    "/.phplint.yml", "/.php-lint.yml",
    "/.phpstorm.meta.php", "/.idea/",
    "/phpdoc/", "/docs/",
    "/swagger/", "/redoc/",
    "/api/doc", "/api/documentation",
    "/v1/api-docs", "/v2/api-docs", "/v3/api-docs",
    "/openapi.json", "/openapi.yaml",
    "/swagger.json", "/swagger.yaml",
    "/.env.backup", "/.env.restore",
    "/config/backup/", "/config/restore/",
    "/restore.php", "/restore.json",
    "/migrate.php", "/migration.php",
    "/migrate.json", "/migration.json",
    "/seed.php", "/seeder.php",
    "/seed.json", "/seeder.json",
    "/rollback.php", "/rollback.json",
    "/db/migrate/", "/db/seeds/",
    "/database/migrations/", "/database/seeds/",
    "/migrations/", "/seeds/",
    "/schema.sql", "/schema.json",
    "/structure.sql", "/structure.json",
    "/data.sql", "/data.json",
    "/dump.sql", "/dump.json",
    "/mysqldump.sql", "/pgdump.sql",
    "/mongodump.archive", "/mongodump.json",
    "/redis-dump.rdb", "/redis-dump.json",
    "/dump.rdb", "/dump.aof",
    "/backup.sql", "/backup.tar",
    "/backup.tar.gz", "/backup.zip",
    "/backup.7z", "/backup.rar",
    "/backup.db", "/backup.sqlite",
    "/backup.mysql", "/backup.pgsql",
    "/backup.sql.gz", "/backup.sql.bz2",
    "/db_backup.sql", "/database_backup.sql",
    "/site_backup.tar.gz", "/full_backup.tar.gz",
    "/data_backup.tar.gz", "/code_backup.tar.gz",
    "/www_backup.tar.gz", "/web_backup.tar.gz",
    "/htdocs_backup.tar.gz", "/html_backup.tar.gz",
    "/backup/", "/_backup/", "/backups/",
    "/backup-old/", "/backup-2024/", "/backup-2025/",
    "/backup-2026/", "/backup-2023/",
    "/wp-content/backup/", "/wp-content/backups/",
    "/wp-content/uploads/backup/",
    "/storage/backups/", "/app/storage/backups/",
    "/var/backups/", "/home/backups/",
    "/.temp/", "/.tmp/", "/temp/", "/tmp/",
    "/temp.zip", "/tmp.zip", "/temp.tar.gz",
    "/cache/", "/cached/", "/.cache/",
    "/runtime/", "/.runtime/",
    "/storage/", "/app/storage/",
    "/storage/framework/", "/storage/logs/",
    "/storage/app/", "/storage/debugbar/",
    "/public/storage/", "/public/build/",
    "/public/hot", "/public/mix-manifest.json",
    "/uploads/", "/upload/", "/files/", "/file/",
    "/downloads/", "/download/",
    "/assets/", "/static/", "/public/",
    "/dist/", "/build/", "/www/", "/htdocs/",
    "/html/", "/public_html/", "/wwwroot/",
    "/phpinfo.php", "/info.php", "/test.php", "/debug.php",
    "/phpinfo.php.bak", "/info.php.bak",
    "/test.html", "/test.asp", "/test.aspx",
    "/debug.log", "/error.log",
    "/access.log", "/access_log",
    "/error_log", "/error.log",
    "/wp-content/debug.log", "/wp-content/debug.log.1",
    "/storage/logs/laravel.log", "/storage/logs/worker.log", "/storage/logs/queue.log",
    "/var/log/system.log", "/var/log/auth.log",
    "/var/log/apache2/", "/var/log/nginx/",
    "/var/log/mysql/", "/var/log/postgresql/",
    "/var/log/redis/", "/var/log/mongodb/",
    "/apache.log", "/nginx.log", "/php-error.log",
    "/php_errors.log", "/php-errors.log",
    "/php_error.log", "/php_error_log",
    "/mysql.log", "/mysql_error.log",
    "/postgresql.log", "/pgsql.log",
    "/redis.log", "/mongodb.log",
    "/cron.log", "/mail.log", "/maillog",
    "/messages.log", "/boot.log", "/syslog",
    "/dmesg", "/lastlog", "/wtmp", "/btmp",
    "/.bash_history", "/.sh_history",
    "/.ksh_history", "/.csh_history",
    "/.mysql_history", "/.psql_history",
    "/.python_history", "/.node_history",
    "/.sqlite_history", "/.redis_history",
    "/history.txt", "/history.log",
    "/command_history", "/shell_history",
    "/.lesshst", "/.nano_history",
    "/.viminfo", "/.viminfx",
    "/.Xauthority", "/.ICEauthority",
    "/.serverauth.*", "/.xauth",
    "/.asoundrc", "/.pulse",
    "/.config/", "/.config/user-dirs.dirs",
    "/.local/", "/.local/share/",
    "/.dbus/", "/.gconf/",
    "/.gnupg/", "/.gnupg/secring.gpg",
    "/.gnupg/pubring.gpg", "/.gnupg/private-keys-v1.d/",
    "/.ssh/", "/.ssh/id_rsa",
    "/.ssh/id_rsa.pub", "/.ssh/id_rsa.ppk",
    "/.ssh/id_dsa", "/.ssh/id_dsa.pub",
    "/.ssh/id_ecdsa", "/.ssh/id_ecdsa.pub",
    "/.ssh/id_ed25519", "/.ssh/id_ed25519.pub",
    "/.ssh/authorized_keys", "/.ssh/authorized_keys2",
    "/.ssh/known_hosts", "/.ssh/config",
    "/.ssh/identity", "/.ssh/identity.pub",
    "/.ssh/encrypted", "/.ssh/random_seed",
    "/.ssh/environment", "/.ssh/rc",
    "/ssh_host_rsa_key", "/ssh_host_dsa_key",
    "/ssh_host_ecdsa_key", "/ssh_host_ed25519_key",
    "/ssh_host_key", "/ssh_known_hosts",
    "/id_rsa", "/id_rsa.pub", "/id_rsa.ppk",
    "/id_dsa", "/id_ecdsa",
    "/id_ed25519", "/id_ed25519.pub",
    "/authorized_keys", "/authorized_keys2",
    "/known_hosts", "/identity",
    "/identity.pub", "/secret_key",
    "/secret.key", "/private.key",
    "/private.pem", "/public.pem",
    "/private_key", "/public_key",
    "/server.key", "/server.pem",
    "/server.key.pem", "/server.crt",
    "/server.cert", "/server.csr",
    "/client.key", "/client.pem",
    "/client.crt", "/client.cert",
    "/ca.key", "/ca.crt", "/ca.pem",
    "/ca-chain.pem", "/ca-bundle.pem",
    "/intermediate.key", "/intermediate.crt",
    "/fullchain.pem", "/fullchain.crt",
    "/chain.pem", "/chain.crt",
    "/privkey.pem", "/privkey.key",
    "/cert.pem", "/cert.crt", "/cert.key",
    "/ssl.crt", "/ssl.key", "/ssl.pem",
    "/ssl-cert.pem", "/ssl-cert.key",
    "/ssl-certificate.pem", "/ssl-private-key.pem",
    "/keystore.jks", "/keystore",
    "/truststore.jks", "/truststore",
    "/cacerts.jks", "/cacerts",
    "/.p12", "/.pfx", "/.jks",
    "/certificate.p12", "/certificate.pfx",
    "/keystore.p12", "/keystore.pfx",
    "/cert.p12", "/key.p12",
    "/.kube/", "/.kube/config",
    "/.kube/config.json", "/.kube/kubeconfig",
    "/kubeconfig.yaml", "/kubeconfig.yml",
    "/admin.conf", "/admin.kubeconfig",
    "/bootstrap-kubelet.conf",
    "/.azure/", "/.azure/credentials",
    "/.azure/config", "/.azure/msi_credentials",
    "/.azure/azureProfile.json",
    "/.azure/aksServicePrincipal.json",
    "/.azure/service_principal.json",
    "/.aws/", "/.aws/credentials",
    "/.aws/config", "/.aws/credentials.json",
    "/.aws/config.json", "/.aws/credentials.txt",
    "/.aws/credentials.ini", "/.aws/config.ini",
    "/.aws/identity.creds",
    "/.gcloud/", "/.gcloud/credentials",
    "/.gcloud/credentials.json",
    "/.gcloud/credentials.db",
    "/.gcloud/config.json", "/.gcloud/config",
    "/.gcloud/application_default_credentials.json",
    "/.gcloud/access_tokens.db",
    "/.gcloud/legacy_credentials/",
    "/.google/", "/.google/credentials",
    "/.google/credentials.json",
    "/application_default_credentials.json",
    "/service-account.json", "/service-account-key.json",
    "/service_account.json", "/service_account_key.json",
    "/google-services.json", "/GoogleService-Info.plist",
    "/google-services.php", "/google-services.xml",
    "/firebase.json", "/firebase.php",
    "/firebase.config", "/firebase.config.json",
    "/firebase-credentials.json",
    "/.npmrc", "/.npmrc.bak",
    "/.yarnrc", "/.yarnrc.yml",
    "/.pnpmrc", "/.pnpm.yaml",
    "/.s3cfg", "/.s3cfg.bak",
    "/.s3cfg.old", "/.s3cfg.save",
    "/.netrc", "/.netrc.bak",
    "/.netrc.old", "/_netrc",
    "/.dockercfg", "/.dockerconfigjson",
    "/.docker/config.json",
    "/.docker/credentials",
    "/config.json", "/config.json.bak",
    "/docker-compose.yml", "/docker-compose.yaml",
    "/docker-compose.override.yml",
    "/docker-compose.prod.yml", "/docker-compose.dev.yml",
    "/docker-compose.staging.yml",
    "/docker-compose.local.yml",
    "/Dockerfile", "/Dockerfile.prod",
    "/Dockerfile.dev", "/Dockerfile.staging",
    "/Dockerfile.test", "/Dockerfile.build",
    "/Dockerfile.nginx", "/Dockerfile.php",
    "/Dockerfile.node", "/Dockerfile.python",
    "/Dockerfile.go", "/Dockerfile.java",
    "/docker-entrypoint.sh",
    "/docker-entrypoint-initdb.d/",
    "/.dockerignore",
    "/docker-compose.override.yml",
    "/docker-stack.yml", "/docker-stack.yaml",
    "/docker-swarm.yml", "/docker-swarm.yaml",
    "/Vagrantfile", "/Vagrantfile.bak",
    "/.vagrant/", "/.vagrant/machines/",
    "/.vagrant/provisioners/",
    "/.terraform/", "/.terraform.lock.hcl",
    "/terraform.tfstate", "/terraform.tfstate.backup",
    "/terraform.tfvars", "/terraform.tfvars.json",
    "/terraform.tfvars.example",
    "/backend.tf", "/backend.tf.json",
    "/main.tf", "/main.tf.json",
    "/variables.tf", "/variables.tf.json",
    "/outputs.tf", "/outputs.tf.json",
    "/providers.tf", "/providers.tf.json",
    "/versions.tf", "/versions.tf.json",
    "/.terraformrc", "/terraform.rc",
    "/.serverless/", "/serverless.yml",
    "/serverless.yaml", "/serverless.json",
    "/serverless.env.yml", "/serverless.env.yaml",
    "/samconfig.toml", "/samconfig.yaml",
    "/template.yaml", "/template.yml",
    "/template.json",
    "/cloudformation.yaml", "/cloudformation.yml",
    "/cloudformation.json", "/cloudformation.template",
    "/Pulumi.yaml", "/Pulumi.yml",
    "/Pulumi.json", "/pulumi/",
    "/pulumi.state", "/pulumi.stack.json",
    "/.pulumi/", "/.pulumi/stacks/",
    "/ansible.cfg", "/ansible/",
    "/ansible/hosts", "/ansible/inventory",
    "/ansible/playbook.yml", "/ansible/playbook.yaml",
    "/ansible/vars.yml", "/ansible/group_vars/",
    "/ansible/host_vars/", "/ansible/roles/",
    "/playbook.yml", "/playbook.yaml",
    "/inventory.yml", "/inventory.yaml",
    "/inventory.ini", "/hosts.ini",
    "/hosts.yml", "/hosts.yaml",
    "/group_vars/", "/host_vars/",
    "/roles/", "/requirements.yml",
    "/collections/", "/collections.yml",
    "/galaxy.yml",
    "/k8s/", "/kubernetes/",
    "/k8s/deployment.yaml", "/k8s/service.yaml",
    "/k8s/ingress.yaml", "/k8s/configmap.yaml",
    "/k8s/secret.yaml", "/k8s/namespace.yaml",
    "/k8s/persistentvolumeclaim.yaml",
    "/k8s/horizontalpodautoscaler.yaml",
    "/deployment.yaml", "/deployment.yml",
    "/service.yaml", "/service.yml",
    "/ingress.yaml", "/ingress.yml",
    "/configmap.yaml", "/configmap.yml",
    "/secret.yaml", "/secret.yml",
    "/kustomization.yaml", "/kustomization.yml",
    "/Chart.yaml", "/Chart.yml",
    "/helm/", "/helmfile.yaml",
    "/values.yaml", "/values.yml",
    "/values.prod.yaml", "/values.dev.yaml",
    "/values.staging.yaml",
    "/templates/", "/templates/NOTES.txt",
    "/.helmignore",
    "/requirements.yaml", "/requirements.lock",
    "/Podfile", "/Podfile.lock",
    "/Cartfile", "/Cartfile.resolved",
    "/Cartfile.private",
    "/.swiftpm/", "/Package.swift",
    "/go.mod", "/go.sum",
    "/Gopkg.toml", "/Gopkg.lock",
    "/glide.yaml", "/glide.lock",
    "/vendor.conf", "/vendor/vendor.json",
    "/Cargo.toml", "/Cargo.lock",
    "/cargo-config", "/.cargo/config",
    "/build.gradle", "/build.gradle.kts",
    "/settings.gradle", "/settings.gradle.kts",
    "/gradle.properties",
    "/gradle/wrapper/gradle-wrapper.properties",
    "/gradlew", "/gradlew.bat",
    "/local.properties",
    "/pom.xml", "/pom.xml.bak",
    "/pom.properties",
    "/settings.xml", "/settings.xml.bak",
    "/.mvn/", "/mvnw", "/mvnw.cmd",
    "/web.xml", "/application.xml",
    "/jboss-web.xml", "/glassfish-web.xml",
    "/context.xml", "/server.xml",
    "/tomcat-users.xml", "/catalina.policy",
    "/catalina.properties", "/logging.properties",
    "/WEB-INF/web.xml", "/WEB-INF/applicationContext.xml",
    "/META-INF/context.xml",
    "/struts.xml", "/struts-config.xml",
    "/hibernate.cfg.xml", "/mybatis-config.xml",
    "/spring.xml", "/application.properties",
    "/application.yml", "/bootstrap.properties",
    "/bootstrap.yml", "/logback.xml",
    "/log4j.properties", "/log4j2.xml",
    "/logging.properties",
    "/appsettings.json", "/appsettings.Development.json",
    "/nlog.config", "/serilog.json",
    "/wp-content/debug.log", "/wp-content/debug.log.1",
    "/wp-content/debug.log.2", "/wp-content/debug.log.3",
    "/wp-content/upgrade/", "/wp-content/backup-db/",
    "/wp-content/aiowps_backups/",
    "/wp-content/uploads/wp-all-backup/",
    "/wp-content/uploads/backupbuddy_backups/",
    "/wp-content/uploads/backupwordpress-*/",
    "/wp-content/uploads/sucuri/",
    "/wp-content/uploads/ithemes-security/",
    "/wp-content/uploads/backup/",
    "/wp-content/uploads/wp-backup-plus/",
]

ERROR_INDICATORS_EXTRA = [
    r"Notice: Undefined (variable|index|offset)",
    r"Fatal error: (Call to undefined function|Class not found|Cannot redeclare)",
    r"Warning: (include|require|session_start|Cannot modify header)",
    r"Parse error: syntax error",
    r"Catchable fatal error",
    r"Recoverable fatal error",
    r"Deprecated: (Function|Method|Call)",
    r"Strict Standards:",
    r"<b>Warning</b>:\s*",
    r"<b>Fatal error</b>:\s*",
    r"<b>Parse error</b>:\s*",
    r"<b>Notice</b>:\s*",
    r"SQL syntax.*MySQL",
    r"Table '.*' doesn't exist",
    r"Unknown column '.*' in",
    r"Duplicate entry '.*' for key",
    r"mysql_connect",
    r"SQLSTATE\[",
    r"PDOException",
    r"MysqliException",
    r"ProgrammingError",
    r"IntegrityError",
    r"OperationalError",
    r"Stack trace:",
    r"#0\s+.*\.php\(.*\):",
    r"thrown in .* on line",
    r"Debug:",
    r"DEBUG MODE",
    r"System Error",
    r"Application Error",
    r"An error occurred",
    r"Oops! Something went wrong",
    r"Internal Server Error",
    r"Whoops!",
    r"There has been a error",
    r"The following error occurred",
    r"Error occurred:",
    r"Error \(",
    r"Exception \(",
    r"In /app/",
    r"In /var/www/",
    r"In /home/",
    r"In /opt/",
]

async def crawl(target: str, client: httpx.AsyncClient):
    findings = []
    domain = target.strip().lower()
    if domain.startswith("http"):
        from urllib.parse import urlparse
        domain = urlparse(domain).netloc

    base_url = f"https://{domain}"

    all_paths = list(dict.fromkeys(SENSITIVE_PATHS + SENSITIVE_PATHS_EXTRA))

    batch_size = 20
    for i in range(0, len(all_paths), batch_size):
        batch = all_paths[i:i + batch_size]
        tasks = [_check_path(p, base_url, domain, client) for p in batch]
        batch_results = await asyncio.gather(*tasks, return_exceptions=True)
        for res in batch_results:
            if isinstance(res, list):
                findings.extend(res)

    if not any(f.status not in ("Redirect",) and f.threat_level != "Informational" for f in findings):
        http_url = f"http://{domain}"
        try:
            resp = await safe_fetch(client, 
                http_url, timeout=5.0,
                headers={"User-Agent": "Mozilla/5.0"},
            )
            if resp.status_code in (200, 301, 302):
                for i in range(0, len(all_paths), batch_size):
                    batch = all_paths[i:i + batch_size]
                    tasks = [_check_path(p, http_url, domain, client) for p in batch]
                    batch_results = await asyncio.gather(*tasks, return_exceptions=True)
                    for res in batch_results:
                        if isinstance(res, list):
                            findings.extend(res)
        except Exception:
            pass

    summary_type_counts = {}
    for f in findings:
        if f.type and f.type not in ("Sensitive File/Path", "Sensitive Path (Redirect)", "Empty Response"):
            summary_type_counts[f.type] = summary_type_counts.get(f.type, 0) + 1

    if summary_type_counts:
        categories = ", ".join([f"{k}({v})" for k, v in list(summary_type_counts.items())[:5]])
        findings.append(make_finding(
            entity=f"Sensitive files scan complete: {len(findings)} hits for {domain}. Categories: {categories}",
            ftype="SensitiveFilesHunter Summary",
            source="SensitiveFilesHunter",
            confidence="High",
            color="purple",
            threat_level="Informational",
            tags=["summary"],
        ))
    elif findings:
        findings.append(make_finding(
            entity=f"Sensitive files scan complete: {len(findings)} paths found for {domain}",
            ftype="SensitiveFilesHunter Summary",
            source="SensitiveFilesHunter",
            confidence="Medium",
            color="purple",
            threat_level="Informational",
            tags=["summary"],
        ))

    return findings
