use serde::{Serialize, Deserialize};
use std::time::Instant;

#[derive(Serialize, Deserialize, Clone)]
pub struct ProgressEvent {
    pub event: String,
    pub module: String,
    pub status: String,
    pub ts: u64,
    pub total: Option<u64>,
    pub progress: Option<u64>,
}

impl ProgressEvent {
    pub fn new(module: &str, status: &str) -> Self {
        Self { event: "progress".into(), module: module.into(), status: status.into(), ts: now_ms(), total: None, progress: None }
    }
    pub fn with_progress(module: &str, status: &str, progress: u64, total: u64) -> Self {
        Self { event: "progress".into(), module: module.into(), status: status.into(), ts: now_ms(), total: Some(total), progress: Some(progress) }
    }
}

#[macro_export]
macro_rules! progress {
    ($module:expr, $status:expr) => {
        println!("{}", serde_json::to_string(&crate::common::ProgressEvent::new($module, $status)).unwrap());
    };
}

#[macro_export]
macro_rules! progress_done {
    ($module:expr) => {
        println!("{}", serde_json::to_string(&crate::common::ProgressEvent::new($module, "done")).unwrap());
    };
}

fn now_ms() -> u64 { std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_millis() as u64 }

pub struct ScopedTimer {
    pub label: String,
    pub start: Instant,
}

impl ScopedTimer {
    pub fn new(label: &str) -> Self { Self { label: label.into(), start: Instant::now() } }
}

impl Drop for ScopedTimer {
    fn drop(&mut self) {
        let elapsed = self.start.elapsed().as_millis();
        eprintln!("[timing] {}: {}ms", self.label, elapsed);
    }
}

#[macro_export]
macro_rules! timed {
    ($label:expr) => { let _timer = crate::common::ScopedTimer::new($label); };
}

#[derive(Serialize, Deserialize)]
pub struct SubdomainResult { pub subdomain: String, pub resolution: Option<String>, pub source: String }

#[derive(Serialize, Deserialize)]
pub struct PortResult { pub port: u16, pub service: String, pub state: String }

#[derive(Serialize, Deserialize)]
pub struct PortBanner { pub port: u16, pub service: String, pub banner: Option<String>, pub os_hint: Option<String> }

#[derive(Serialize, Deserialize, Default)]
pub struct DnsResult { pub a: Vec<String>, pub aaaa: Vec<String>, pub mx: Vec<String>, pub ns: Vec<String>, pub txt: Vec<String>, pub cname: Vec<String>, pub soa: Option<String>, pub srv: Vec<String>, pub ptr: Vec<String>, pub caa: Vec<String>, pub zone_transfer: Option<String> }

#[derive(Serialize, Deserialize)]
pub struct WebtechResult { pub url: String, pub status: Option<u16>, pub server: Option<String>, pub tech: Vec<String>, pub headers: Vec<(String, String)> }

#[derive(Serialize, Deserialize)]
pub struct EmailResult { pub domain: String, pub patterns: Vec<String>, pub count: usize }

#[derive(Serialize, Deserialize)]
pub struct CrawlResult { pub url: String, pub title: Option<String>, pub links: Vec<String>, pub meta: Vec<(String, String)>, pub status: Option<u16>, pub scripts: Vec<String>, pub forms: Vec<WebFormInfo>, pub api_endpoints: Vec<String>, pub spa_framework: Option<String>, pub js_files: Vec<String> }

#[derive(Serialize, Deserialize)]
pub struct FormField { pub action: String, pub method: String, pub inputs: Vec<String> }

#[derive(Serialize, Deserialize)]
pub struct SensitiveResult { pub url: String, pub found: Vec<SensitiveFile> }
#[derive(Serialize, Deserialize)]
pub struct SensitiveFile { pub path: String, pub status: u16, pub size: Option<String> }

#[derive(Serialize, Deserialize)]
pub struct SecretResult { pub url: String, pub secrets: Vec<SecretFinding> }
#[derive(Serialize, Deserialize)]
pub struct SecretFinding { pub secret_type: String, pub value: String, pub location: String }

#[derive(Serialize, Deserialize)]
pub struct WafResult { pub url: String, pub waf: Option<String>, pub cdn: Option<String>, pub detected: bool, pub indicators: Vec<String> }

#[derive(Serialize, Deserialize)]
pub struct SocialResult { pub username: String, pub profiles: Vec<SocialProfile> }
#[derive(Serialize, Deserialize)]
pub struct SocialProfile { pub platform: String, pub url: String, pub exists: bool, pub status: Option<u16> }

#[derive(Serialize, Deserialize)]
pub struct CrtshResult { pub domain: String, pub certificates: Vec<CrtshEntry>, pub total: usize }
#[derive(Serialize, Deserialize)]
pub struct CrtshEntry { pub id: Option<i64>, pub issuer: Option<String>, pub issued: Option<String>, pub expired: Option<String>, pub sans: Vec<String> }

#[derive(Serialize, Deserialize)]
pub struct VulnResult { pub target: String, pub vulnerabilities: Vec<Vulnerability> }
#[derive(Serialize, Deserialize)]
pub struct Vulnerability { pub cve_id: Option<String>, pub name: String, pub severity: String, pub description: String, pub remediation: Option<String> }

#[derive(Serialize, Deserialize)]
pub struct CloudResult { pub target: String, pub providers: Vec<CloudProvider>, pub buckets: Vec<CloudBucket> }
#[derive(Serialize, Deserialize)]
pub struct CloudProvider { pub name: String, pub services: Vec<String>, pub confidence: String }
#[derive(Serialize, Deserialize)]
pub struct CloudBucket { pub url: String, pub provider: String, pub exists: bool, pub accessible: bool }

#[derive(Serialize, Deserialize)]
pub struct WebAnalysisResult { pub url: String, pub forms: Vec<WebFormInfo>, pub api_endpoints: Vec<String>, pub spa_framework: Option<String>, pub js_files: Vec<String> }
#[derive(Serialize, Deserialize)]
pub struct WebFormInfo { pub action: String, pub method: String, pub inputs: Vec<InputField> }
#[derive(Serialize, Deserialize)]
pub struct InputField { pub name: String, pub type_field: String, pub required: bool }

#[derive(Serialize, Deserialize)]
pub struct CertInfo { pub subject: String, pub issuer: String, pub valid_from: String, pub valid_to: String, pub sans: Vec<String>, pub fingerprint: String, pub self_signed: bool }

#[derive(Serialize, Deserialize)]
pub struct AllDeepResult {
    pub target: String, pub duration_ms: u64,
    pub subdomains: Vec<SubdomainResult>, pub ports: Vec<PortResult>,
    pub banners: Vec<PortBanner>, pub dns: DnsResult,
    pub emails: EmailResult, pub webtech: WebtechResult,
    pub crawl: CrawlResult, pub sensitive: SensitiveResult,
    pub secrets: SecretResult, pub waf: WafResult,
    pub social: SocialResult, pub crtsh: CrtshResult,
    pub vulns: VulnResult, pub cloud: CloudResult,
    pub cert_info: Option<CertInfo>,
}

pub fn build_client(timeout_secs: u64) -> Option<reqwest::Client> {
    reqwest::Client::builder()
        .danger_accept_invalid_certs(true)
        .timeout(std::time::Duration::from_secs(timeout_secs))
        .build().ok()
}

pub fn normalize_url(url: &str) -> String {
    if url.starts_with("http") { url.to_string() } else { format!("https://{}", url) }
}
pub const COMMON_PREFIXES: &[&str] = &[
    "www", "mail", "ftp", "admin", "api", "dev", "staging", "vpn", "cdn", "blog", "app", "webmail",
    "remote", "portal", "ssh", "git", "jenkins", "jira", "smtp", "imap", "pop3", "autodiscover", "m", "mobile",
    "chat", "forum", "help", "support", "docs", "wiki", "status", "tracker", "monitor", "dashboard", "analytics", "metrics",
    "logs", "sync", "static", "assets", "media", "img", "upload", "download", "files", "backup", "cpanel", "whm",
    "server", "ns1", "ns2", "ns3", "ns4", "ns5", "ns6", "ns7", "ns8", "ns9", "ns10", "mx1",
    "mx2", "mx3", "mx4", "mx5", "owa", "exchange", "gateway", "firewall", "proxy", "cache", "dns", "ldap",
    "radius", "test", "stage", "demo", "beta", "dev2", "prod", "production", "develop", "stg", "qa", "uat",
    "gitlab", "ci", "cd", "deploy", "release", "build", "docker", "k8s", "kubernetes", "grafana", "prometheus", "kibana",
    "elastic", "logstash", "nagios", "zabbix", "puppet", "chef", "ansible", "terraform", "consul", "vault", "minio", "storage",
    "stream", "video", "audio", "cdn2", "origin", "edge", "waf", "redirect", "socket", "ws", "wss", "mqtt",
    "redis", "memcache", "mongo", "postgres", "mysql2", "oracle", "auth", "login", "signin", "signup", "register", "sso",
    "oauth", "token", "keys", "cert", "ssl", "tls", "https", "secure", "security", "safe", "protect", "guard",
    "bot", "spider", "crawler", "scanner", "vuln", "cve", "patch", "update", "upgrade", "version", "release", "changelog",
    "roadmap", "feature", "bug", "issue", "ticket", "contact", "about", "team", "company", "career", "job", "apply",
    "hr", "benefits", "press", "news", "article", "post", "tutorial", "guide", "manual", "documentation", "api-docs", "swagger",
    "redoc", "graphql", "rest", "soap", "xml", "json", "rpc", "grpc", "websocket", "notification", "push", "alert",
    "webhook", "callback", "endpoint", "service", "micro", "soa", "crm", "erp", "hrms", "lms", "cms", "ecommerce",
    "shop", "store", "cart", "checkout", "payment", "billing", "invoice", "subscription", "plan", "pricing", "account", "profile",
    "settings", "preferences", "config", "configuration", "setup", "install", "uninstall", "search", "find", "lookup", "query", "report",
    "export", "import", "file", "document", "pdf", "image", "photo", "picture", "gallery", "album", "video", "movie",
    "audio", "music", "podcast", "live", "tv", "radio", "streaming", "broadcast", "channel", "group", "community", "network",
    "social", "feed", "timeline", "activity", "message", "inbox", "sent", "draft", "trash", "spam", "archive", "label",
    "tag", "category", "section", "partner", "affiliate", "referral", "sponsor", "advertise", "promote", "campaign", "marketing", "seo",
    "sem", "ppc", "email", "newsletter", "privacy", "policy", "terms", "condition", "legal", "gdpr", "ccpa", "cookies",
    "consent", "compliance", "audit", "log", "history", "tracking", "insight", "intelligence", "report", "kpi", "metric", "performance",
    "speed", "optimize", "minify", "bundle", "webpack", "vite", "rollup", "esbuild", "babel", "typescript", "javascript", "node",
    "deno", "bun", "python", "ruby", "php", "java", "go", "rust", "react", "vue", "angular", "svelte",
    "next", "nuxt", "gatsby", "remix", "django", "flask", "laravel", "symfony", "rails", "spring", "database", "db",
    "sql", "nosql", "mongodb", "postgresql", "mysql", "mariadb", "oracle", "sqlserver", "cassandra", "couchdb", "dynamodb", "firestore",
    "supabase", "planetscale", "neon", "cockroach", "clickhouse", "influxdb", "redis", "memcached", "elasticsearch", "meilisearch", "kafka", "rabbitmq",
    "pulsar", "nats", "cloud", "aws", "azure", "gcp", "gcloud", "heroku", "vercel", "netlify", "cloudflare", "fastly",
    "akamai", "cloudfront", "s3", "bucket", "storage", "blob", "container", "function", "lambda", "serverless", "edge", "worker",
    "docker", "kubernetes", "k8s", "pod", "ingress", "helm", "chart", "deployment", "statefulset", "daemonset", "namespace", "configmap",
    "secret", "volume", "claim", "nginx", "haproxy", "traefik", "caddy", "apache", "iis", "tomcat", "jetty", "wildfly",
    "payara", "glassfish", "websphere", "weblogic", "jboss", "aws-ec2", "aws-lambda", "aws-s3", "aws-rds", "aws-dynamodb", "aws-sqs", "aws-sns",
    "aws-step", "aws-cloudwatch", "aws-iam", "aws-vpc", "aws-route53", "aws-elb", "aws-ecs", "aws-eks", "azure-vm", "azure-func", "azure-blob", "azure-sql",
    "azure-cosmos", "azure-vnet", "azure-dns", "azure-aks", "gcp-compute", "gcp-func", "gcp-storage", "gcp-sql", "gcp-pubsub", "gcp-gke", "gcp-cloudrun",
];
pub const TOP_PORTS: &[(u16, &str)] = &[
    (21,"FTP"), (22,"SSH"), (23,"Telnet"), (25,"SMTP"), (53,"DNS"), (69,"TFTP"), (70,"Gopher"), (79,"Finger"),
    (80,"HTTP"), (81,"HTTP-Alt"), (88,"Kerberos"), (102,"Iso-tsap"), (110,"POP3"), (111,"RPC"), (113,"Ident"), (119,"NNTP"),
    (123,"NTP"), (135,"EPMAP"), (137,"NetBIOS-NS"), (138,"NetBIOS-DGM"), (139,"NetBIOS-SSN"), (143,"IMAP"), (161,"SNMP"), (162,"SNMP-Trap"),
    (177,"XDMCP"), (179,"BGP"), (194,"IRC"), (201,"Apple-RTMP"), (264,"BGMP"), (318,"PKIX"), (350,"MATIP"), (366,"ODMR"),
    (369,"RPC2"), (370,"Codaauth"), (389,"LDAP"), (399,"Digiman"), (401,"UPS"), (427,"SLP"), (443,"HTTPS"), (444,"SNPP"),
    (445,"SMB"), (464,"kpasswd"), (465,"SMTPS"), (497,"Dantz"), (500,"ISAKMP"), (502,"Modbus"), (512,"Exec"), (513,"Login"),
    (514,"Syslog"), (515,"Printer"), (517,"Talk"), (518,"NTalk"), (520,"RIP"), (521,"RIPng"), (523,"IBM-DB2"), (524,"NCP"),
    (525,"Timed"), (526,"Tempo"), (529,"IRC-Serv"), (530,"Courier"), (531,"Chat"), (532,"Netnews"), (533,"Netwall"), (540,"UUCP"),
    (541,"UUCP-Rlogin"), (542,"Commerce"), (543,"Klogin"), (544,"Kshell"), (545,"AppleQTC"), (546,"DHCPv6-Client"), (547,"DHCPv6-Server"), (548,"AFP"),
    (550,"New-RWHO"), (554,"RTSP"), (556,"RemoteFS"), (557,"OpenVMS"), (560,"Rmonitor"), (561,"Monitor"), (563,"NNTP-TLS"), (564,"9PFS"),
    (565,"Whoami"), (566,"Streettalk"), (567,"Banyan-RPC"), (568,"Shuttle"), (569,"Rome"), (570,"Meter"), (571,"UMeter"), (572,"Sonar"),
    (573,"Banyan-VIP"), (574,"FTP-Proxy"), (581,"BNews"), (585,"XMPP"), (586,"Password-Chg"), (587,"Submission"), (588,"Cal"), (589,"EyeLink"),
    (590,"TNS-CML"), (591,"HTTP-Alt2"), (593,"HTTP-RPC"), (601,"Syslog-Conn"), (604,"Tunnel"), (623,"ASF-RMCP"), (625,"Apple-Xsan"), (631,"IPP"),
    (635,"RLZ-DBase"), (636,"LDAPS"), (639,"MSDP"), (646,"LDP"), (647,"DHCP-Failover"), (648,"RRP"), (649,"Cadview-3D"), (650,"OBEX"),
    (651,"IEEE-MMS"), (653,"Repscmd"), (654,"AODV"), (655,"Tinc"), (657,"RSVP"), (658,"Remark"), (660,"Samba"), (666,"Doom"),
    (674,"ACAP"), (682,"XFR"), (683,"CORBA-IIOP"), (684,"CORBA-IIOP-SSL"), (685,"MDC"), (686,"HCP"), (687,"ASIP"), (688,"Realm-RUSD"),
    (690,"VATP"), (691,"MS-Exchange"), (692,"Hyperwave"), (694,"HA-Cluster"), (695,"IEEE-MMS-SSL"), (696,"RUSHD"), (697,"UUIDgen"), (698,"OLSR"),
    (699,"AccessNetwork"), (700,"Buddy"), (701,"TELNET-CP"), (702,"IRIS-BEEP"), (706,"SILC"), (710,"Cisco-TDP"), (711,"SNMP-Conf"), (712,"Promocmp"),
    (720,"Netview"), (722,"Netrcs"), (723,"FlexLM"), (727,"Dixie"), (729,"Netview"), (730,"Netview"), (731,"Netview"), (741,"NetGW"),
    (742,"Netrcs"), (744,"FlexLM"), (747,"FlexLM"), (749,"Kerberos-Admin"), (750,"Kerberos"), (751,"Kerberos-Master"), (752,"QRH"), (753,"RRH"),
    (754,"Tell"), (758,"NLogin"), (759,"Con"), (760,"KRB-Update"), (761,"Kreg"), (762,"NLogin"), (763,"Con"), (764,"KRB-Prop"),
    (765,"KRB-Update"), (766,"Kreg"), (767,"NLogin"), (768,"Con"), (769,"VID"), (770,"Cadlock"), (771,"RTIP"), (772,"CycleServ"),
    (773,"Submit"), (774,"Rpasswd"), (775,"Entomb"), (776,"Wpages"), (777,"Multiling"), (778,"Wpgs"), (780,"Wpgs"), (800,"MDBS-Daemon"),
    (801,"Device"), (802,"MBAP"), (810,"FCP"), (828,"ITM-MCell"), (829,"PKIX"), (830,"Netconf-SSH"), (831,"Netconf-BEEP"), (832,"Netconf-SOAP"),
    (833,"Netconf-SOAP-BEEP"), (843,"ADV"), (844,"Dyncorp"), (845,"RTSP-Alt"), (846,"DHCP-Failover"), (847,"DHCP-Failover"), (848,"GDOI"), (853,"DNS-over-TLS"),
    (860,"iSCSI"), (861,"OWAMP"), (862,"TWAMP"), (873,"RSync"), (886,"ICLCNET"), (887,"ICLCNET"), (888,"AccessBuilder"), (898,"Sun-ManageConsole"),
    (900,"SCTP"), (901,"Samba-SWAT"), (902,"VMware"), (903,"VMware"), (904,"VMware"), (905,"VMware"), (910,"Kink"), (911,"Xact-Backup"),
    (912,"Apex-Mesh"), (913,"Apex-Edge"), (950,"OFTEP"), (953,"RNDC"), (975,"SecureNetPro"), (980,"FP-DB"), (981,"SafetyNet"), (987,"MMS"),
    (989,"FTPS-Data"), (990,"FTPS"), (991,"NAS"), (992,"Telnets"), (993,"IMAPS"), (994,"IRCS"), (995,"POP3S"), (999,"Garcon"),
    (1000,"Cadlock"), (1001,"WebPush"), (1010,"Surf"), (1011,"NFS"), (1021,"Exp1"), (1022,"Exp2"), (1023,"Reserved"), (1024,"KDM"),
    (1025,"Blackjack"), (1026,"CAP"), (1027,"IAD"), (1028,"IAD"), (1029,"IAD"), (1030,"IAD"), (1031,"IAD"), (1032,"IAD"),
    (1033,"NetInfo"), (1034,"NetInfo"), (1035,"MXXRLogin"), (1036,"NSSTP"), (1037,"AMS"), (1038,"MTQP"), (1039,"SBL"), (1040,"NetARX"),
    (1041,"Danf-AK2"), (1042,"Afrog"), (1043,"BOINC"), (1044,"DCUtility"), (1045,"FPITP"), (1046,"WFRemoteRT"), (1047,"NeoD1"), (1048,"NeoD2"),
    (1049,"TD-Postman"), (1050,"Java-ORB"), (1051,"Optima-VNet"), (1052,"DDT"), (1053,"Remote-AS"), (1054,"BRVRead"), (1055,"ANSYS-LM"), (1056,"VFO"),
    (1057,"Startron"), (1058,"NIM"), (1059,"NIMReg"), (1060,"Polestar"), (1061,"Kiosk"), (1062,"Veracity"), (1063,"KyoceraNetDev"), (1064,"JSTEL"),
    (1065,"SysComLAN"), (1066,"FPO-FNS"), (1067,"Instl-BootC"), (1068,"Instl-BootC"), (1069,"Cognex"), (1070,"GMRUpdate"), (1071,"BSquare-VoIP"), (1072,"Cardax"),
    (1073,"BridgeControl"), (1074,"FastTech"), (1075,"RDRMSHC"), (1076,"DAB-STI-C"), (1077,"IMGames"), (1078,"Avocent-Proxy"), (1079,"ASP"), (1080,"SOCKS"),
    (1081,"PVU"), (1082,"AMT-ESD"), (1083,"Ansoft-LM1"), (1084,"Ansoft-LM2"), (1085,"WebObjects"), (1086,"CPLScrambler"), (1087,"CPLScrambler"), (1088,"CPLScrambler"),
    (1089,"FF-Annunc"), (1090,"FF-FMS"), (1091,"FF-SM"), (1092,"OBRPD"), (1093,"ProofD"), (1094,"RootD"), (1095,"Nicelink"), (1096,"CNRProtocol"),
    (1097,"SunCluster"), (1098,"RMI-Activation"), (1099,"RMI-Registry"), (1100,"MCTP"), (1102,"Adobe-Server1"), (1103,"Adobe-Server2"), (1104,"XRL"), (1105,"FT-RanHC"),
    (1106,"ISO-IPSIG"), (1107,"ISO-IPSIG"), (1108,"Ratio-ADP"), (1109,"POP2"), (1110,"NFSD-Status"), (1111,"LM-Social"), (1112,"MS-SQL"), (1113,"Lisp-Data"),
    (1114,"Mini-SQL"), (1115,"Ardus-Trns"), (1116,"Ardus-Cntl"), (1117,"Ardus-Mtrns"), (1118,"Sacred"), (1119,"BNetGame"), (1120,"BNetFile"), (1121,"RMPP"),
    (1122,"Availant"), (1123,"Murray"), (1124,"HP-VMM"), (1125,"HP-VMM"), (1126,"HP-VMM"), (1127,"Supfiledbg"), (1128,"SAPv1"), (1129,"SAPv2"),
    (1130,"CIFS"), (1131,"OSAgent"), (1138,"Encrypted-Admin"), (1140,"AutoNOC"), (1141,"MX-OMSS"), (1142,"EdTools"), (1143,"IMyX"), (1144,"FScript"),
    (1145,"X9-ICUE"), (1146,"Audit-Transfer"), (1147,"CAPI"), (1148,"Elfiq-Repl"), (1149,"BVT-Sonar"), (1150,"Blaze"), (1151,"Unizensus"), (1152,"WinPopLAN"),
    (1153,"Codel"), (1154,"ResaComm"), (1155,"NFA"), (1156,"IAS-Control"), (1157,"IAS-Control"), (1158,"Snap-Discovery"), (1159,"DB-Control"), (1160,"DB-Control"),
    (1161,"Health-Poll"), (1162,"Health-Trap"), (1163,"SD-DUP"), (1164,"QDB-CAP"), (1165,"QDB"), (1166,"QDB-LM"), (1167,"QDB-SS"), (1168,"QDB-Xref"),
    (1169,"QDB-Xref"), (1175,"QDB-Xref"), (1180,"MC-Client"), (1181,"MC-Server"), (1182,"Acetech"), (1183,"Acetech"), (1184,"LLM"), (1185,"LLM"),
    (1186,"LLM"), (1187,"LLM"), (1188,"LLM"), (1190,"OMG"), (1191,"OMG"), (1192,"OMG"), (1193,"OMG"), (1194,"OMG"),
    (1195,"OMG"), (1196,"OMG"), (1197,"OMG"), (1198,"OMG"), (1199,"OMG"), (1200,"Codel"), (1214,"FastTrack"), (1220,"QT-Server"),
    (1221,"QT-Server"), (1222,"QT-Server"), (1234,"VNC"), (1241,"Nessus"), (1248,"NSI"), (1249,"NSI"), (1250,"NSI"), (1251,"NSI"),
    (1252,"NSI"), (1253,"NSI"), (1254,"NSI"), (1255,"NSI"), (1256,"NSI"), (1257,"NSI"), (1258,"NSI"), (1259,"NSI"),
    (1260,"NSI"), (1261,"NSI"), (1270,"KKC"), (1280,"KKC"), (1281,"KKC"), (1290,"KKC"), (1291,"KKC"), (1292,"KKC"),
    (1293,"IPSEC"), (1294,"IPSEC"), (1295,"IPSEC"), (1296,"IPSEC"), (1297,"IPSEC"), (1298,"IPSEC"), (1299,"IPSEC"), (1300,"IPSEC"),
    (1301,"IPSEC"), (1302,"IPSEC"), (1303,"IPSEC"), (1304,"IPSEC"), (1305,"IPSEC"), (1306,"IPSEC"), (1307,"IPSEC"), (1308,"IPSEC"),
    (1309,"IPSEC"), (1310,"IPSEC"), (1311,"IPSEC"), (1312,"IPSEC"), (1313,"IPSEC"), (1314,"IPSEC"), (1315,"IPSEC"), (1316,"IPSEC"),
    (1317,"IPSEC"), (1318,"IPSEC"), (1319,"IPSEC"), (1320,"IPSEC"), (1321,"IPSEC"), (1322,"IPSEC"), (1323,"IPSEC"), (1324,"IPSEC"),
    (1325,"IPSEC"), (1326,"IPSEC"), (1327,"IPSEC"), (1328,"IPSEC"), (1329,"IPSEC"), (1330,"IPSEC"), (1331,"IPSEC"), (1332,"IPSEC"),
    (1333,"IPSEC"), (1334,"IPSEC"), (1335,"IPSEC"), (1336,"IPSEC"), (1337,"MenandMice-DNS"), (1338,"MenandMice-DNS"), (1339,"MenandMice-DNS"), (1340,"MenandMice-DNS"),
    (1341,"QNX"), (1342,"QNX"), (1343,"QNX"), (1344,"QNX"), (1345,"QNX"), (1346,"QNX"), (1347,"QNX"), (1348,"QNX"),
    (1349,"QNX"), (1350,"QNX"), (1351,"QNX"), (1352,"LotusNotes"), (1353,"LotusNotes"), (1354,"LotusNotes"), (1355,"LotusNotes"), (1356,"LotusNotes"),
    (1357,"LotusNotes"), (1358,"LotusNotes"), (1359,"LotusNotes"), (1360,"Mimer"), (1361,"Mimer"), (1362,"Mimer"), (1363,"Mimer"), (1364,"Mimer"),
    (1365,"Mimer"), (1366,"Mimer"), (1367,"Mimer"), (1368,"Mimer"), (1369,"Mimer"), (1370,"Mimer"), (1371,"Mimer"), (1372,"FE-License"),
    (1373,"FE-License"), (1374,"FE-License"), (1375,"SU-Sec-Ed"), (1376,"SU-Sec-Ed"), (1377,"SU-Sec-Ed"), (1378,"SU-Sec-Ed"), (1379,"SU-Sec-Ed"), (1380,"SU-Sec-Ed"),
    (1381,"SU-Sec-Ed"), (1382,"SU-Sec-Ed"), (1383,"SU-Sec-Ed"), (1384,"SU-Sec-Ed"), (1385,"SU-Sec-Ed"), (1386,"SU-Sec-Ed"), (1387,"SU-Sec-Ed"), (1388,"SU-Sec-Ed"),
    (1389,"SU-Sec-Ed"), (1390,"SU-Sec-Ed"), (1391,"SU-Sec-Ed"), (1392,"SU-Sec-Ed"), (1393,"SU-Sec-Ed"), (1394,"SU-Sec-Ed"), (1395,"SU-Sec-Ed"), (1396,"SU-Sec-Ed"),
    (1397,"SU-Sec-Ed"), (1398,"SU-Sec-Ed"), (1399,"SU-Sec-Ed"), (1400,"Cadkey-LM"), (1401,"SGI-ESP"), (1402,"Printer-Agent"), (1414,"IBM-MQSeries"), (1415,"IBM-MQSeries"),
    (1416,"IBM-MQSeries"), (1417,"IBM-MQSeries"), (1433,"MS-SQL-S"), (1434,"MS-SQL-M"), (1443,"ICS-LM"), (1455,"ESI-License"), (1461,"BMC-PM"), (1481,"AIX-HTTP"),
    (1492,"Stone-Design"), (1494,"Citrix-ICA"), (1495,"CSA-LM"), (1496,"CSA-LM"), (1497,"CSA-LM"), (1498,"CSA-LM"), (1499,"CSA-LM"), (1500,"VLS-License"),
    (1501,"SAS-License"), (1502,"SAS-License"), (1503,"SAS-License"), (1504,"SAS-License"), (1505,"SAS-License"), (1506,"SAS-License"), (1507,"SAS-License"), (1508,"SAS-License"),
    (1509,"SAS-License"), (1510,"SAS-License"), (1511,"SAS-License"), (1512,"WINS"), (1513,"FAN-License"), (1514,"FAN-License"), (1515,"FAN-License"), (1516,"FAN-License"),
    (1517,"FAN-License"), (1518,"FAN-License"), (1519,"FAN-License"), (1520,"FAN-License"), (1521,"Oracle-TNS"), (1522,"Oracle-TNS"), (1523,"Oracle-TNS"), (1524,"Oracle-TNS"),
    (1525,"Oracle-TNS"), (1526,"Oracle-TNS"), (1527,"Oracle-TNS"), (1528,"Oracle-TNS"), (1529,"Oracle-TNS"), (1530,"Oracle-TNS"), (1531,"Oracle-TNS"), (1532,"Oracle-TNS"),
    (1533,"Oracle-TNS"), (1534,"Oracle-TNS"), (1540,"1st-Server"), (1541,"1st-Server"), (1542,"1st-Server"), (1543,"1st-Server"), (1544,"1st-Server"), (1545,"1st-Server"),
    (1546,"1st-Server"), (1547,"1st-Server"), (1548,"1st-Server"), (1549,"1st-Server"), (1550,"WebCache"), (1556,"Veritas"), (1560,"Veritas"), (1561,"Veritas"),
    (1562,"Veritas"), (1563,"Veritas"), (1564,"Veritas"), (1565,"Veritas"), (1566,"Veritas"), (1567,"Veritas"), (1568,"Veritas"), (1569,"Veritas"),
    (1570,"Veritas"), (1571,"Veritas"), (1572,"Veritas"), (1580,"IBM-MQ"), (1581,"IBM-MQ"), (1582,"IBM-MQ"), (1583,"IBM-MQ"), (1584,"IBM-MQ"),
    (1585,"IBM-MQ"), (1586,"IBM-MQ"), (1587,"IBM-MQ"), (1588,"IBM-MQ"), (1589,"IBM-MQ"), (1590,"IBM-MQ"), (1591,"IBM-MQ"), (1600,"ISSD"),
    (1601,"AAS"), (1602,"AAS"), (1603,"AAS"), (1604,"AAS"), (1605,"AAS"), (1606,"AAS"), (1610,"KAA"), (1611,"KAA"),
    (1612,"KAA"), (1620,"LMSRV"), (1621,"LMSRV"), (1622,"LMSRV"), (1625,"SVS-HTTP"), (1626,"SVS-HTTP"), (1627,"SVS-HTTP"), (1628,"SVS-HTTP"),
    (1629,"SVS-HTTP"), (1630,"Oracle-Net"), (1631,"Oracle-Net"), (1632,"Oracle-Net"), (1633,"Oracle-Net"), (1634,"Oracle-Net"), (1640,"Digi"), (1641,"Digi"),
    (1642,"Digi"), (1645,"RADIUS"), (1646,"RADIUS"), (1647,"RADIUS"), (1648,"RADIUS"), (1649,"RADIUS"), (1650,"RADIUS"), (1660,"Netview"),
    (1661,"Netview"), (1666,"Perf-Port"), (1667,"Perf-Port"), (1670,"Netview"), (1671,"Netview"), (1677,"GroupWise"), (1678,"GroupWise"), (1679,"GroupWise"),
    (1680,"GroupWise"), (1681,"GroupWise"), (1682,"GroupWise"), (1683,"GroupWise"), (1684,"GroupWise"), (1685,"GroupWise"), (1686,"GroupWise"), (1687,"GroupWise"),
    (1688,"GroupWise"), (1689,"GroupWise"), (1690,"GroupWise"), (1691,"GroupWise"), (1692,"GroupWise"), (1693,"GroupWise"), (1694,"GroupWise"), (1695,"GroupWise"),
    (1696,"GroupWise"), (1697,"GroupWise"), (1698,"GroupWise"), (1699,"GroupWise"), (1700,"Lucent-MS"), (1701,"L2TP"), (1702,"Lucent-MS"), (1703,"Lucent-MS"),
    (1704,"Lucent-MS"), (1705,"HSL-Storm"), (1706,"HSL-Storm"), (1707,"HSL-Storm"), (1708,"HSL-Storm"), (1709,"HSL-Storm"), (1710,"HSL-Storm"), (1711,"HSL-Storm"),
    (1712,"HSL-Storm"), (1717,"PPT-Conference"), (1718,"H323-Discover"), (1719,"H323-Gatekeeper"), (1720,"H323-Hostcall"), (1721,"H323-Call-Secure"), (1722,"H323-Call-Secure"), (1723,"PPTP"),
    (1741,"Cisco-NetMgmt"), (1742,"Cisco-NetMgmt"), (1745,"Remote-Winsock"), (1746,"Remote-Winsock"), (1750,"SSLP"), (1751,"SSLP"), (1752,"SSLP"), (1754,"Oracle-EM1"),
    (1755,"MS-Streaming"), (1756,"MS-Streaming"), (1760,"CFT-0"), (1761,"CFT-1"), (1762,"CFT-2"), (1763,"CFT-3"), (1764,"CFT-4"), (1765,"CFT-5"),
    (1766,"CFT-6"), (1767,"CFT-7"), (1768,"CFT-8"), (1769,"CFT-9"), (1770,"BNR-HTTP"), (1771,"BNR-HTTP"), (1777,"Westell"), (1778,"Westell"),
    (1780,"SNMP-PP"), (1781,"SNMP-PP"), (1782,"HP-SMI"), (1783,"HP-SMI"), (1784,"HP-SMI"), (1790,"NMS-TopConf"), (1791,"NMS-TopConf"), (1792,"IBM-App"),
    (1793,"IBM-App"), (1794,"IBM-App"), (1795,"IBM-App"), (1796,"IBM-App"), (1797,"IBM-App"), (1798,"IBM-App"), (1799,"IBM-App"), (1800,"IBM-App"),
    (1801,"IBM-App"), (1802,"IBM-App"), (1803,"IBM-App"), (1804,"IBM-App"), (1805,"IBM-App"), (1806,"IBM-App"), (1807,"IBM-App"), (1808,"IBM-App"),
    (1809,"IBM-App"), (1810,"IBM-App"), (1811,"IBM-App"), (1812,"IBM-App"), (1813,"IBM-App"), (1816,"HP-SMI"), (1817,"HP-SMI"), (1840,"Netopia-VoIP"),
    (1841,"Netopia-VoIP"), (1850,"Oracle-WP"), (1851,"Oracle-WP"), (1860,"Sun-SR-HTTPS"), (1861,"Sun-SR-HTTPS"), (1862,"Sun-SR-HTTPS"), (1863,"MSNP"), (1864,"MSNP"),
    (1865,"MSNP"), (1870,"Sun-SR-HTTPS"), (1871,"Sun-SR-HTTPS"), (1875,"Sun-SR-HTTPS"), (1880,"IBM-MQ"), (1881,"IBM-MQ"), (1882,"IBM-MQ"), (1883,"MQTT"),
    (1884,"MQTT"), (1885,"MQTT"), (1890,"IBM-MQ"), (1891,"IBM-MQ"), (1892,"IBM-MQ"), (1893,"IBM-MQ"), (1894,"IBM-MQ"), (1895,"IBM-MQ"),
    (1896,"IBM-MQ"), (1897,"IBM-MQ"), (1898,"IBM-MQ"), (1899,"IBM-MQ"), (1900,"UPNP"), (1901,"IBM-MQ"), (1902,"IBM-MQ"), (1903,"IBM-MQ"),
    (1904,"IBM-MQ"), (1905,"IBM-MQ"), (1906,"IBM-MQ"), (1907,"IBM-MQ"), (1908,"IBM-MQ"), (1909,"IBM-MQ"), (1910,"IBM-MQ"), (1911,"IBM-MQ"),
    (1912,"IBM-MQ"), (1913,"IBM-MQ"), (1914,"IBM-MQ"), (1915,"IBM-MQ"), (1916,"IBM-MQ"), (1917,"IBM-MQ"), (1918,"IBM-MQ"), (1919,"IBM-MQ"),
    (1920,"IBM-MQ"), (1930,"IBM-MQ"), (1931,"IBM-MQ"), (1935,"RTMP"), (1936,"RTMP"), (1937,"RTMP"), (1940,"IBM-MQ"), (1941,"IBM-MQ"),
    (1944,"Close-Combat"), (1945,"Close-Combat"), (1947,"Sentinel-LM"), (1948,"Sentinel-LM"), (1950,"IBM-MQ"), (1951,"IBM-MQ"), (1955,"Abacom"), (1956,"Abacom"),
    (1960,"IBM-MQ"), (1961,"IBM-MQ"), (1962,"IBM-MQ"), (1963,"IBM-MQ"), (1964,"IBM-MQ"), (1965,"IBM-MQ"), (1966,"IBM-MQ"), (1967,"IBM-MQ"),
    (1968,"IBM-MQ"), (1969,"IBM-MQ"), (1970,"IBM-MQ"), (1971,"IBM-MQ"), (1972,"IBM-MQ"), (1975,"IBM-MQ"), (1980,"IBM-MQ"), (1981,"IBM-MQ"),
    (1982,"IBM-MQ"), (1983,"IBM-MQ"), (1984,"IBM-MQ"), (1985,"IBM-MQ"), (1986,"IBM-MQ"), (1987,"IBM-MQ"), (1988,"IBM-MQ"), (1989,"IBM-MQ"),
    (1990,"IBM-MQ"), (1991,"IBM-MQ"), (1992,"IBM-MQ"), (1993,"IBM-MQ"), (1994,"IBM-MQ"), (1995,"IBM-MQ"), (1996,"IBM-MQ"), (1997,"IBM-MQ"),
    (1998,"IBM-MQ"), (1999,"IBM-MQ"), (2000,"Cisco-SCCP"), (2001,"DC"), (2002,"Globe"), (2003,"Finger"), (2004,"BR-RTR"), (2005,"DesLogin"),
    (2006,"DesLogin"), (2007,"DesLogin"), (2008,"DesLogin"), (2009,"DesLogin"), (2010,"DesLogin"), (2011,"DesLogin"), (2012,"DesLogin"), (2013,"DesLogin"),
    (2014,"DesLogin"), (2015,"DesLogin"), (2016,"DesLogin"), (2017,"DesLogin"), (2018,"DesLogin"), (2019,"DesLogin"), (2020,"DesLogin"), (2021,"DesLogin"),
    (2022,"DesLogin"), (2023,"Xinu-Page"), (2024,"Xinu-Exp"), (2025,"Xinu-Exp"), (2026,"Xinu-Exp"), (2027,"Xinu-Exp"), (2028,"Xinu-Exp"), (2029,"Xinu-Exp"),
    (2030,"Device2"), (2031,"Device2"), (2032,"Device2"), (2033,"Device2"), (2034,"Device2"), (2035,"Device2"), (2036,"Device2"), (2037,"Device2"),
    (2038,"Device2"), (2039,"Device2"), (2040,"Device2"), (2041,"Device2"), (2042,"Device2"), (2043,"Device2"), (2044,"Device2"), (2045,"Device2"),
    (2046,"Device2"), (2047,"Device2"), (2048,"DLS-Monitor"), (2049,"NFS"), (2050,"DLS-Monitor"), (2051,"DLS-Monitor"), (2053,"KNetd"), (2054,"KNetd"),
    (2055,"KNetd"), (2060,"Telenium"), (2061,"Telenium"), (2065,"DLS-Monitor"), (2067,"DLS-Monitor"), (2070,"AH-ESP"), (2071,"AH-ESP"), (2074,"Veritas"),
    (2075,"Veritas"), (2076,"Veritas"), (2077,"Veritas"), (2078,"Veritas"), (2080,"Autodesk-LM"), (2081,"Autodesk-LM"), (2082,"Infowave"), (2083,"Infowave"),
    (2084,"Infowave"), (2085,"Infowave"), (2086,"Autodesk-LM"), (2087,"Autodesk-LM"), (2088,"Autodesk-LM"), (2090,"Autodesk-LM"), (2091,"Autodesk-LM"), (2095,"NXBasic"),
    (2096,"NXBasic"), (2100,"AmigaNetFS"), (2101,"AmigaNetFS"), (2102,"Zephyr-Srv"), (2103,"Zephyr-Clt"), (2104,"Zephyr-HM"), (2105,"EKLogin"), (2106,"EKLogin"),
    (2107,"EKLogin"), (2108,"EKLogin"), (2109,"EKLogin"), (2110,"EKLogin"), (2111,"EKLogin"), (2112,"EKLogin"), (2115,"EKLogin"), (2120,"CA-License"),
    (2121,"CA-License"), (2122,"CA-License"), (2125,"CA-License"), (2126,"CA-License"), (2127,"CA-License"), (2128,"CA-License"), (2129,"CA-License"), (2130,"CA-License"),
    (2131,"CA-License"), (2140,"IAS-Diag"), (2141,"IAS-Diag"), (2142,"IAS-Diag"), (2143,"IAS-Diag"), (2144,"IAS-Diag"), (2150,"IAS-Diag"), (2151,"IAS-Diag"),
    (2152,"IAS-Diag"), (2159,"GDB"), (2160,"GDB"), (2161,"APC"), (2162,"APC"), (2170,"VMware"), (2171,"VMware"), (2180,"MN-HTTP"),
    (2181,"MN-HTTP"), (2190,"TI-Highway"), (2191,"TI-Highway"), (2200,"ICI"), (2201,"ICI"), (2202,"ICI"), (2203,"ICI"), (2204,"ICI"),
    (2210,"NOAAPort"), (2211,"NOAAPort"), (2212,"EMI-1"), (2213,"EMI-2"), (2214,"EMI-3"), (2215,"EMI-4"), (2216,"EMI-5"), (2220,"NetIQ"),
    (2221,"NetIQ"), (2222,"EtherIP"), (2223,"EtherIP"), (2224,"SNMP"), (2225,"SNMP"), (2226,"SNMP"), (2230,"Meetings"), (2232,"IVS-Video"),
    (2233,"IVS-Video"), (2240,"DSM"), (2241,"DSM"), (2250,"Remote-Collab"), (2251,"Remote-Collab"), (2255,"VPN"), (2256,"VPN"), (2260,"APC"),
    (2261,"APC"), (2270,"School"), (2271,"School"), (2272,"School"), (2273,"School"), (2279,"XMQuery"), (2280,"LNV-Status"), (2281,"LNV-Status"),
    (2288,"NetPerf"), (2289,"NetPerf"), (2290,"NetPerf"), (2300,"CVMMon"), (2301,"CVMMon"), (2302,"CVMMon"), (2303,"CVMMon"), (2304,"CVMMon"),
    (2305,"CVMMon"), (2306,"CVMMon"), (2307,"CVMMon"), (2308,"CVMMon"), (2310,"CVMMon"), (2320,"CVMMon"), (2321,"CVMMon"), (2322,"CVMMon"),
    (2323,"CVMMon"), (2330,"CVMMon"), (2332,"CVMMon"), (2333,"CVMMon"), (2334,"CVMMon"), (2335,"CVMMon"), (2336,"CVMMon"), (2337,"CVMMon"),
    (2338,"CVMMon"), (2339,"CVMMon"), (2340,"CVMMon"), (2341,"CVMMon"), (2342,"CVMMon"), (2343,"CVMMon"), (2344,"CVMMon"), (2345,"CVMMon"),
    (2350,"CVMMon"), (2360,"CVMMon"), (2370,"CVMMon"), (2371,"CVMMon"), (2372,"CVMMon"), (2380,"CVMMon"), (2381,"CVMMon"), (2382,"CVMMon"),
    (2383,"CVMMon"), (2384,"CVMMon"), (2390,"CVMMon"), (2391,"CVMMon"), (2392,"CVMMon"), (2393,"CVMMon"), (2394,"CVMMon"), (2395,"CVMMon"),
    (2396,"CVMMon"), (2397,"CVMMon"), (2398,"CVMMon"), (2399,"CVMMon"), (2400,"CVMMon"), (2401,"CVMMon"), (2402,"CVMMon"), (2403,"CVMMon"),
    (2404,"CVMMon"), (2420,"CVMMon"), (2424,"CVMMon"), (2425,"CVMMon"), (2426,"CVMMon"), (2427,"CVMMon"), (2428,"CVMMon"), (2429,"CVMMon"),
    (2430,"CVMMon"), (2431,"CVMMon"), (2432,"CVMMon"), (2433,"CVMMon"), (2434,"CVMMon"), (2440,"CVMMon"), (2441,"CVMMon"), (2442,"CVMMon"),
    (2443,"CVMMon"), (2444,"CVMMon"), (2450,"CVMMon"), (2451,"CVMMon"), (2452,"CVMMon"), (2453,"CVMMon"), (2454,"CVMMon"), (2455,"CVMMon"),
    (2456,"CVMMon"), (2457,"CVMMon"), (2458,"CVMMon"), (2459,"CVMMon"), (2460,"CVMMon"), (2470,"CVMMon"), (2471,"CVMMon"), (2472,"CVMMon"),
    (2473,"CVMMon"), (2474,"CVMMon"), (2475,"CVMMon"), (2476,"CVMMon"), (2477,"CVMMon"), (2478,"CVMMon"), (2479,"CVMMon"), (2480,"CVMMon"),
    (2481,"CVMMon"), (2482,"CVMMon"), (2483,"CVMMon"), (2484,"CVMMon"), (2485,"CVMMon"), (2486,"CVMMon"), (2487,"CVMMon"), (2488,"CVMMon"),
    (2489,"CVMMon"), (2490,"CVMMon"), (2491,"CVMMon"), (2492,"CVMMon"), (2493,"CVMMon"), (2494,"CVMMon"), (2495,"CVMMon"), (2496,"CVMMon"),
    (2497,"CVMMon"), (2498,"CVMMon"), (2499,"CVMMon"), (2500,"CVMMon"), (2501,"CVMMon"), (2531,"CVMMon"), (2540,"CVMMon"), (2541,"CVMMon"),
    (2542,"CVMMon"), (2543,"CVMMon"), (2544,"CVMMon"), (2545,"CVMMon"), (2555,"CVMMon"), (2556,"CVMMon"), (2560,"CVMMon"), (2561,"CVMMon"),
    (2562,"CVMMon"), (2563,"CVMMon"), (2564,"CVMMon"), (2565,"CVMMon"), (2566,"CVMMon"), (2567,"CVMMon"), (2568,"CVMMon"), (2569,"CVMMon"),
    (2570,"CVMMon"), (2571,"CVMMon"),
];
pub const SENSITIVE_PATHS: &[&str] = &[
    ".env", ".git/config", ".git/HEAD", ".git/index", ".gitignore", ".htaccess", ".htpasswd", "admin/", "administrator/", "backup/",
    "wp-admin/", "wp-content/", "wp-includes/", "config.php", "configuration.php", "settings.php", "db.php", "database.php", "conn.php", "connection.php",
    "config.inc.php", "config.inc", "config.json", "config.yml", "config.yaml", "config.xml", "config.js", "config.ts", "config.py", "config.rb",
    "config.go", "credentials.json", "credentials.yml", "key.json", "service-account.json", "aws.json", "aws.yml", "aws-config.json", "s3.json", "s3.yml",
    "bucket.json", "docker-compose.yml", "docker-compose.yaml", "Dockerfile", "docker-compose.override.yml", ".docker/config.json", "kubeconfig", "kube-config", "kube/config", "kubectl-config",
    "admin.conf", ".kube/config", "helm/values.yaml", "terraform.tfstate", "terraform.tfvars", "terraform.tfstate.backup", ".terraform/", "server.crt", "server.key", "cert.pem",
    "key.pem", "fullchain.pem", "privkey.pem", "certificate.crt", "private.key", "ssl.crt", "ssl.key", "certificate.p12", "keystore.jks", "id_rsa",
    "id_rsa.pub", "id_dsa", "id_ecdsa", "id_ed25519", "authorized_keys", "known_hosts", ".ssh/config", "ssh_config", "ssh/config", "openvpn.conf",
    "ovpn", "client.ovpn", ".npmrc", "npmrc", "yarn.lock", "package-lock.json", "composer.json", "composer.lock", "Gemfile", "Gemfile.lock",
    "go.mod", "go.sum", "Cargo.toml", "Cargo.lock", "build.gradle", "pom.xml", "settings.gradle", "gradle.properties", "Makefile", "CMakeLists.txt",
    "requirements.txt", "Pipfile", "Pipfile.lock", "pyproject.toml", "setup.py", "setup.cfg", "tox.ini", "conda.ini", "environment.yml", "Dockerfile.prod",
    "Dockerfile.dev", "nginx.conf", "apache.conf", "httpd.conf", "httpd-vhosts.conf", "vhost.conf", ".htaccess.bak", "web.config", "app.config", "web.xml",
    "application.yml", "application.properties", "application.yaml", "application.json", "application.conf", "bootstrap.yml", "bootstrap.properties", "log4j.properties", "log4j2.xml", "logback.xml",
    "logging.properties", "prometheus.yml", "alertmanager.yml", "grafana.ini", "telegraf.conf", "docker-compose.prod.yml", "docker-compose.dev.yml", "kubernetes/deployment.yaml", "service.yaml", "ingress.yaml",
    "configmap.yaml", "secret.yaml", "values.yaml", "Chart.yaml", "templates/", "charts/", "version.txt", "VERSION", "CHANGELOG", "CHANGELOG.md",
    "RELEASE", "RELEASE.md", "readme.md", "README.md", "INSTALL", "INSTALL.md", "UPGRADE", "UPGRADE.md", "robots.txt", "sitemap.xml",
    "sitemap_index.xml", "crossdomain.xml", "clientaccesspolicy.xml", "security.txt", "humans.txt", "ads.txt", "app-ads.txt", "phpinfo.php", "info.php", "test.php",
    "debug.php", "status.php", "health.php", "api/", "api/v1", "api/v2", "swagger.json", "swagger.yaml", "openapi.json", "openapi.yaml",
    "api-docs", "docs/api", "graphql", "graphiql", "playground", "phpmyadmin/", "phpMyAdmin/", "pma/", "adminer/", "mysql/",
    "sqlite/", "phpPgAdmin/", "server-status", "server-info", "mod_status", "mod_info", "cgi-bin/", "cgi-bin/test.cgi", "cgi-bin/status", "cgi-bin/php",
    "actuator", "actuator/health", "actuator/info", "actuator/metrics", "actuator/env", "actuator/beans", "actuator/mappings", "actuator/configprops", "actuator/threaddump", "actuator/heapdump",
    "actuator/logfile", "actuator/loggers", ".well-known/", "well-known/security.txt", ".well-known/acme-challenge/", ".gitattributes", "git-ftp-ignore", "git-ftp-include", "console/", "manager/",
    "management/", "monitor/", "monitoring/", "status/", "health/", "metrics/", "prometheus/", "influxdb/", "grafana/", "kibana/",
    "elasticsearch/", "jenkins/", "jira/", "confluence/", "bamboo/", "bitbucket/", "gitlab/", "sonar/", "sonarqube/", "nexus/",
    "artifactory/", "harbor/", "registry/", "webdav/", "dav/", "files/", "uploads/", "upload/", "download/", "downloads/",
    "log/", "logs/", "logfile/", "error_log", "access_log", "error.log", "access.log", "debug.log", "app.log", "server.log",
    "syslog", "messages", "dmesg", "tmp/", "temp/", "test/", "tests/", "testing/", "dev/", "develop/",
    "stage/", "staging/", "demo/", "sandbox/", "playground/", "examples/", "example/", "sample/", "samples/", "node_modules/",
    "vendor/", "bower_components/", "components/", "lib/", "libs/", "src/", "source/", "dist/", "build/", "out/",
    "target/", "release/", "debug/", ".cache/", "cache/", "cacheb/", "var/cache/", "var/log/", "var/run/", "var/tmp/",
    ".idea/", ".vscode/", ".vs/", ".settings/", ".project", ".classpath", ".DS_Store", "Thumbs.db", "desktop.ini", "shell.php",
    "cmd.php", "exec.php", "eval.php", "system.php", "passthru.php", "webshell.php", "backdoor.php", "shell.jsp", "cmd.jsp", "cmd.aspx",
    "shell.aspx", "muieblackcat", "phpmyadmin", "pma", "adminer", "admin", "login", "wp-login", "signup", "register",
    "user", "users", "profile", "account", "me", "api/swagger", "api/docs", "api/v1/swagger", "api/v2/swagger", ".gitlab-ci.yml",
    ".travis.yml", "circleci/config.yml", "Jenkinsfile", ".github/", "actions/", "workflows/", "pipeline/", "debug", "internal", "private",
    "secret", "hidden", "confidential", "dashboard", "panel", "cpanel", "whm", "plesk", "webmin", "phpunit/",
    "phpunit.xml", "phpunit.xml.dist", "codeception.yml", "behat.yml", "phpspec.yml", "robots.txt", "security.txt", "humans.txt",
];
pub const CMS_PATHS: &[(&str, &str)] = &[
    ("WordPress","/wp-admin/"), ("WordPress","/wp-content/"), ("WordPress","/wp-includes/"), ("WordPress","/wp-login.php"), ("WordPress","/xmlrpc.php"), ("WordPress","/wp-cron.php"),
    ("WordPress","/wp-json/"), ("WordPress","/wp-json/wp/v2/"), ("Joomla","/administrator/"), ("Joomla","/components/"), ("Joomla","/modules/"), ("Joomla","/templates/"),
    ("Joomla","/includes/"), ("Joomla","/language/"), ("Joomla","/plugins/"), ("Joomla","/cache/"), ("Joomla","/tmp/"), ("Joomla","/logs/"),
    ("Joomla","/xmlrpc/"), ("Joomla","/libraries/"), ("Joomla","/media/"), ("Drupal","/core/"), ("Drupal","/modules/"), ("Drupal","/themes/"),
    ("Drupal","/profiles/"), ("Drupal","/sites/"), ("Drupal","/sites/default/"), ("Drupal","/sites/all/"), ("Drupal","/includes/"), ("Drupal","/misc/"),
    ("Drupal","/scripts/"), ("Drupal","/index.php"), ("Magento","/admin/"), ("Magento","/skin/"), ("Magento","/js/"), ("Magento","/lib/"),
    ("Magento","/app/"), ("Magento","/var/"), ("Magento","/media/"), ("Magento","/errors/"), ("Magento","/downloader/"), ("Magento","/cron.php"),
    ("Magento","/index.php/admin/"), ("Shopify","/admin/"), ("Shopify","/admin/auth/"), ("Shopify","/admin/settings/"), ("Shopify","/admin/products/"), ("Laravel","/artisan"),
    ("Laravel","/storage/"), ("Laravel","/vendor/"), ("Laravel","/public/"), ("Laravel","/resources/"), ("Laravel","/routes/"), ("Laravel","/app/"),
    ("Laravel","/config/"), ("Laravel","/database/"), ("Laravel","/bootstrap/"), ("Laravel","/server.php"), ("Symfony","/app.php"), ("Symfony","/app_dev.php"),
    ("Symfony","/config/"), ("Symfony","/src/"), ("Symfony","/vendor/"), ("Symfony","/var/"), ("Symfony","/bin/console"), ("Symfony","/web/"),
    ("Symfony","/bundles/"), ("Django","/admin/"), ("Django","/static/"), ("Django","/media/"), ("Django","/accounts/"), ("Django","/api/"),
    ("Flask","/static/"), ("Flask","/uploads/"), ("Express","/static/"), ("Express","/public/"), ("Next.js","/_next/"), ("Next.js","/api/"),
    ("Nuxt.js","/_nuxt/"), ("Nuxt.js","/api/"), ("Gatsby","/static/"), ("Gatsby","/page-data/"), ("Vue","/js/"), ("Vue","/css/"),
    ("Vue","/img/"), ("React","/static/js/"), ("React","/static/css/"), ("Angular","/runtime.js"), ("Angular","/polyfills.js"), ("Angular","/styles.js"),
    ("Angular","/vendor.js"), ("Svelte","/_app/"), ("Svelte","/build/"), ("Ghost","/ghost/"), ("Ghost","/content/"), ("OctoberCMS","/backend/"),
    ("OctoberCMS","/modules/"), ("Concrete5","/concrete/"), ("Concrete5","/packages/"), ("TYPO3","/typo3/"), ("TYPO3","/typo3conf/"), ("TYPO3","/typo3temp/"),
    ("TYPO3","/uploads/"), ("PrestaShop","/admin/"), ("PrestaShop","/modules/"), ("PrestaShop","/themes/"), ("PrestaShop","/override/"), ("PrestaShop","/translations/"),
    ("OpenCart","/admin/"), ("OpenCart","/catalog/"), ("OpenCart","/system/"), ("WHMCS","/admin/"), ("WHMCS","/includes/"), ("WHMCS","/templates/"),
    ("WHMCS","/modules/"), ("WHMCS","/downloads/"), ("phpMyAdmin","/phpmyadmin/"), ("phpMyAdmin","/phpMyAdmin/"), ("phpMyAdmin","/pma/"), ("phpPgAdmin","/phppgadmin/"),
    ("phpPgAdmin","/phpPgAdmin/"), ("Adminer","/adminer.php"), ("Adminer","/adminer/"), ("cPanel","/cpanel/"), ("cPanel","/cpsess/"), ("cPanel","/webmail/"),
    ("Plesk","/plesk/"), ("Plesk","/smb/"), ("Plesk","/admin/"), ("Webmin","/webmin/"), ("Webmin","/session_login.cgi"), ("Jenkins","/jenkins/"),
    ("Jenkins","/login"), ("Jenkins","/script"), ("Jenkins","/manage"), ("Jenkins","/job/"), ("Jenkins","/computer/"), ("GitLab","/users/sign_in"),
    ("GitLab","/explore"), ("GitLab","/admin"), ("GitLab","/help"), ("Jira","/secure/Dashboard.jspa"), ("Jira","/browse/"), ("Jira","/rest/api/2/"),
    ("Jira","/rest/api/latest/"), ("Confluence","/dashboard.action"), ("Confluence","/spaces/"), ("Confluence","/rest/api/"), ("SonarQube","/sonar/"), ("SonarQube","/about"),
    ("SonarQube","/api/"), ("SonarQube","/sessions/new"), ("Grafana","/grafana/"), ("Grafana","/login"), ("Grafana","/api/"), ("Kibana","/kibana/"),
    ("Kibana","/app/kibana"), ("Kibana","/api/status"), ("Prometheus","/graph"), ("Prometheus","/targets"), ("Prometheus","/alerts"), ("Prometheus","/api/v1/"),
    ("Nexus","/nexus/"), ("Nexus","/repository/"), ("Artifactory","/artifactory/"), ("Artifactory","/ui/"), ("Harbor","/harbor/"), ("Harbor","/api/"),
    ("Harbor","/c/"), ("RabbitMQ","/rabbitmq/"), ("RabbitMQ","/api/"), ("Consul","/v1/"), ("Consul","/ui/"), ("Vault","/v1/"),
    ("Vault","/ui/"), ("Kubernetes","/api/"), ("Kubernetes","/healthz"), ("Kubernetes","/version"), ("Kubernetes","/openapi/v2"), ("Docker Registry","/v2/"),
    ("Docker Registry","/v2/_catalog"), ("AWS S3","/s3/"), ("AWS S3","/bucket/"), ("MinIO","/minio/"), ("MinIO","/api/"), ("Hadoop","/dfs/"),
    ("Hadoop","/cluster"), ("Spark","/spark/"), ("Spark","/jobs/"), ("Elasticsearch","/_cat"), ("Elasticsearch","/_search"), ("Elasticsearch","/_cluster"),
    ("Elasticsearch","/_nodes"), ("Elasticsearch","/_aliases"), ("Elasticsearch","/_mapping"), ("Redis","/redis/"), ("Redis","/redis-cli"), ("MongoDB","/mongo/"),
    ("MongoDB","/_mongo"), ("CouchDB","/_utils"), ("CouchDB","/_all_dbs"), ("CouchDB","/_config"), ("Tomcat","/manager/html"), ("Tomcat","/examples/"),
    ("Tomcat","/docs/"), ("Tomcat","/status"), ("JBoss","/jmx-console/"), ("JBoss","/web-console/"), ("JBoss","/admin-console/"), ("WebLogic","/console/"),
    ("WebLogic","/bea_wls/"), ("WebSphere","/ibm/console/"), ("WebSphere","/ibm/"), ("IIS","/iisstart.htm"), ("IIS","/iis-86.png"), ("Nginx","/nginx-status"),
    ("Nginx","/nginx.conf"), ("Apache","/icons/"), ("Apache","/manual/"), ("PHP","/index.php"), ("PHP","/info.php"), ("PHP","/phpmyadmin/"),
];
pub const PLATFORM_SIGNATURES: &[(&str, &[&str])] = &[
    ("Cloudflare", &["cloudflare", "__cfduid", "cf-ray", "cf-cache-status", "server: cloudflare"]),
    ("AWS", &["aws", "amazonaws", "s3.amazonaws", "cloudfront", "x-amz-", "aws-alb"]),
    ("AWS ELB", &["aws-elb", "elasticloadbalancing", "awseb-"]),
    ("AWS EC2", &["ec2-", "compute.amazonaws", "amazonlinux"]),
    ("AWS CloudFront", &["cloudfront.net", "x-amz-cf-"]),
    ("Azure", &["azure", "azurewebsites", "azureedge", "azurefd", "x-ms-"]),
    ("Azure App Service", &["azurewebsites.net", "azurewebsites.windows.net"]),
    ("Azure CDN", &["azureedge.net", "azurefd.net"]),
    ("Azure Front Door", &["x-azure-ref", "x-cdn-provider: azure"]),
    ("Google Cloud", &["gcloud", "googleapis", "compute.googleapis", "appspot.com"]),
    ("Google Cloud CDN", &["cloud.google.com/cdn", "x-goog-"]),
    ("Google App Engine", &["appspot.com", "gae"]),
    ("GCP", &["gcp", "googlecloud", "cloud.google"]),
    ("Heroku", &["heroku", "herokuapp", "herokudns"]),
    ("Vercel", &["vercel", "now.sh", "zeit"]),
    ("Netlify", &["netlify", "netlify.app"]),
    ("GitHub Pages", &["github.io", "github.com"]),
    ("GitLab Pages", &["gitlab.io"]),
    ("CloudFront", &["cloudfront.net"]),
    ("Fastly", &["fastly", "fastly.net", "x-fastly-"]),
    ("Akamai", &["akamai", "akamaiedge", "akamaitechnologies"]),
    ("Akamai CDN", &["akamai.net", "akamaiedge.net"]),
    ("Incapsula", &["incapsula", "x-iinfo"]),
    ("Sucuri", &["sucuri", "sucuri.net"]),
    ("StackPath", &["stackpath", "stackpathcdn"]),
    ("KeyCDN", &["keycdn", "keycdn.com"]),
    ("Bunny CDN", &["bunnycdn", "b-cdn.net"]),
    ("CDN77", &["cdn77", "cdn77.com"]),
    ("OVH", &["ovh", "ovh.net"]),
    ("DigitalOcean", &["digitalocean", "do-"]),
    ("Linode", &["linode", "linode.com"]),
    ("Vultr", &["vultr", "vultr.com"]),
    ("Hetzner", &["hetzner", "hetzner.cloud"]),
    ("ArvanCloud", &["arvancloud"]),
    ("Nginx", &["nginx", "nginx/"]),
    ("Apache", &["apache", "apache/", "Apache"]),
    ("IIS", &["iis", "microsoft-iis", "x-powered-by: asp.net"]),
    ("Tomcat", &["tomcat", "apache-tomcat"]),
    ("JBoss", &["jboss", "jboss-as"]),
    ("WebLogic", &["weblogic", "oracle-weblogic"]),
    ("WebSphere", &["websphere", "ibm-websphere"]),
    ("Jetty", &["jetty", "eclipse-jetty"]),
    ("Caddy", &["caddy", "caddy/"]),
    ("Traefik", &["traefik", "traefik/"]),
    ("HAProxy", &["haproxy", "haproxy/"]),
    ("OpenResty", &["openresty", "openresty/"]),
    ("Node.js", &["node.js", "nodejs", "express"]),
    ("Express", &["express", "express/"]),
    ("Koa", &["koa"]),
    ("Fastify", &["fastify"]),
    ("Next.js", &["next.js", "next/", "x-nextjs"]),
    ("Nuxt.js", &["nuxt", "nuxt/"]),
    ("Gatsby", &["gatsby", "gatsby/"]),
    ("Angular", &["angular", "angular/"]),
    ("React", &["react", "react/"]),
    ("Vue.js", &["vue", "vue.js", "vuejs"]),
    ("Svelte", &["svelte"]),
    ("Django", &["django", "python/3.", "wsgi"]),
    ("Flask", &["flask", "werkzeug"]),
    ("FastAPI", &["fastapi", "uvicorn"]),
    ("Laravel", &["laravel", "laravel/"]),
    ("Symfony", &["symfony", "symfony/"]),
    ("WordPress", &["wordpress", "wp-content", "wp-includes", "wp-json"]),
    ("Joomla", &["joomla", "joomla/"]),
    ("Drupal", &["drupal", "drupal/", "sites/default"]),
    ("Magento", &["magento", "magento/"]),
    ("Shopify", &["shopify", "myshopify"]),
    ("Wix", &["wix", "wix.com"]),
    ("Squarespace", &["squarespace", "squarespace.com"]),
    ("Weebly", &["weebly", "weebly.com"]),
    ("Ghost", &["ghost", "ghost/"]),
    ("Umbraco", &["umbraco"]),
    ("Concrete CMS", &["concrete5"]),
    ("TYPO3", &["typo3"]),
    ("PrestaShop", &["prestashop"]),
    ("OpenCart", &["opencart"]),
    ("WHMCS", &["whmcs"]),
    ("Wagtail", &["wagtail"]),
    ("Strapi", &["strapi"]),
    ("Directus", &["directus"]),
    ("Keystone", &["keystone"]),
    ("Contentful", &["contentful"]),
    ("Prismic", &["prismic"]),
    ("Sanity", &["sanity"]),
    ("GraphQL", &["graphql", "graphiql"]),
    ("REST API", &["rest", "rest-api"]),
    ("WebSocket", &["websocket", "ws://", "wss://"]),
    ("gRPC", &["grpc", "grpc/"]),
    ("PHP", &["php", "php/", "x-powered-by: php"]),
    ("Python", &["python", "python/"]),
    ("Ruby", &["ruby", "ruby/", "rails"]),
    ("Java", &["java", "java/", "x-powered-by: jsp"]),
    ("Go", &["go", "golang"]),
    ("Rust", &["rust", "rust/"]),
    (".NET", &[".net", "asp.net", "x-aspnet"]),
    ("Perl", &["perl", "perl/"]),
    ("Elixir", &["elixir", "phoenix"]),
    ("Haskell", &["haskell", "warp"]),
    ("Scala", &["scala", "play!"]),
    ("Kotlin", &["kotlin", "ktor"]),
    ("Dart", &["dart", "flutter"]),
    ("Deno", &["deno", "deno/"]),
    ("Bun", &["bun", "bun/"]),
    ("MySQL", &["mysql", "mysql/"]),
    ("MariaDB", &["mariadb"]),
    ("PostgreSQL", &["postgresql", "postgres", "pgsql"]),
    ("MongoDB", &["mongodb", "mongo"]),
    ("Redis", &["redis"]),
    ("Elasticsearch", &["elasticsearch", "es/"]),
    ("Memcached", &["memcached"]),
    ("SQLite", &["sqlite"]),
    ("Oracle DB", &["oracle", "oracle/"]),
    ("MS SQL", &["mssql", "sql server"]),
    ("Cassandra", &["cassandra"]),
    ("CouchDB", &["couchdb"]),
    ("Neo4j", &["neo4j"]),
    ("InfluxDB", &["influxdb"]),
    ("ClickHouse", &["clickhouse"]),
    ("Docker", &["docker", "docker/"]),
    ("Kubernetes", &["kubernetes", "k8s", "kube"]),
    ("K3s", &["k3s"]),
    ("Podman", &["podman"]),
    ("OpenShift", &["openshift"]),
    ("Rancher", &["rancher"]),
    ("Nomad", &["nomad"]),
    ("Consul", &["consul"]),
    ("Vault", &["vault", "hashicorp-vault"]),
    ("Terraform", &["terraform"]),
    ("Ansible", &["ansible"]),
    ("Puppet", &["puppet"]),
    ("Chef", &["chef"]),
    ("SaltStack", &["salt", "saltstack"]),
    ("Jenkins", &["jenkins", "jenkins/"]),
    ("GitLab CI", &["gitlab-ci"]),
    ("GitHub Actions", &["github-actions"]),
    ("CircleCI", &["circleci"]),
    ("Travis CI", &["travis-ci"]),
    ("TeamCity", &["teamcity"]),
    ("Bamboo", &["bamboo"]),
    ("Drone CI", &["drone"]),
    ("Argo CD", &["argo-cd", "argocd"]),
    ("Spinnaker", &["spinnaker"]),
    ("New Relic", &["newrelic", "new relic"]),
    ("Datadog", &["datadog"]),
    ("Sentry", &["sentry", "sentry/"]),
    ("Splunk", &["splunk"]),
    ("ELK Stack", &["elastic", "logstash", "kibana"]),
    ("Prometheus", &["prometheus"]),
    ("Grafana", &["grafana"]),
    ("Nagios", &["nagios"]),
    ("Zabbix", &["zabbix"]),
    ("PagerDuty", &["pagerduty"]),
    ("Stripe", &["stripe"]),
    ("PayPal", &["paypal"]),
    ("Braintree", &["braintree"]),
    ("Adyen", &["adyen"]),
    ("Square", &["square"]),
    ("Twilio", &["twilio"]),
    ("SendGrid", &["sendgrid"]),
    ("Mailgun", &["mailgun"]),
    ("Mailchimp", &["mailchimp"]),
    ("Postmark", &["postmark"]),
    ("Algolia", &["algolia"]),
    ("Meilisearch", &["meilisearch"]),
    ("Typesense", &["typesense"]),
    ("Solr", &["solr"]),
    ("Sphinx", &["sphinx"]),
    ("Auth0", &["auth0"]),
    ("Okta", &["okta"]),
    ("Firebase", &["firebase", "firebaseio"]),
    ("Supabase", &["supabase"]),
    ("PlanetScale", &["planetscale"]),
    ("Neon", &["neon"]),
    ("CockroachDB", &["cockroach"]),
    ("CloudAMQP", &["cloudamqp"]),
    ("CloudMQTT", &["cloudmqtt"]),
    ("Aiven", &["aiven"]),
    ("MongoDB Atlas", &["mongodb.net", "atlas"]),
    ("DigitalOcean Spaces", &["digitaloceanspaces"]),
    ("Wasabi", &["wasabi"]),
    ("Backblaze B2", &["backblaze"]),
    ("Linode Object Storage", &["linodeobjects"]),
    ("Vultr Object Storage", &["vultrobjects"]),
    ("Google reCAPTCHA", &["recaptcha", "g-recaptcha"]),
    ("Cloudflare Turnstile", &["turnstile", "cf-turnstile"]),
    ("hCaptcha", &["hcaptcha"]),
    ("FingerprintJS", &["fingerprintjs"]),
    ("jsDelivr", &["jsdelivr"]),
    ("unpkg", &["unpkg"]),
    ("cdnjs", &["cdnjs"]),
    ("Google Tag Manager", &["googletagmanager", "gtm-"]),
    ("Google Analytics", &["google-analytics", "ga-", "gtag"]),
    ("Facebook Pixel", &["facebook-pixel", "fbq"]),
    ("Hotjar", &["hotjar"]),
    ("Intercom", &["intercom"]),
    ("LiveChat", &["livechat"]),
    ("Tawk.to", &["tawk"]),
    ("Zendesk", &["zendesk"]),
    ("Freshdesk", &["freshdesk"]),
    ("HubSpot", &["hubspot"]),
    ("Salesforce", &["salesforce"]),
    ("Marketo", &["marketo"]),
    ("Pardot", &["pardot"]),
    ("MailerLite", &["mailerlite"]),
    ("ConvertKit", &["convertkit"]),
    ("ActiveCampaign", &["activecampaign"]),
    ("GetResponse", &["getresponse"]),
    ("AWeber", &["aweber"]),
    ("Constant Contact", &["constantcontact"]),
    ("Campaign Monitor", &["campaignmonitor"]),
    ("Disqus", &["disqus"]),
    ("Facebook Comments", &["facebook.com/plugins"]),
    ("Spotify", &["spotify.com"]),
    ("YouTube", &["youtube.com", "youtu.be"]),
    ("Vimeo", &["vimeo"]),
    ("Twitch", &["twitch"]),
    ("SoundCloud", &["soundcloud"]),
    ("TikTok", &["tiktok"]),
    ("Instagram", &["instagram"]),
    ("Twitter", &["twitter", "x.com"]),
    ("LinkedIn", &["linkedin"]),
    ("Pinterest", &["pinterest"]),
    ("Snapchat", &["snapchat"]),
    ("Reddit", &["reddit"]),
    ("Medium", &["medium"]),
    ("Substack", &["substack"]),
    ("Discord", &["discord", "discordapp"]),
    ("Slack", &["slack"]),
    ("Microsoft Teams", &["teams.microsoft"]),
    ("Telegram", &["telegram"]),
    ("WhatsApp", &["whatsapp"]),
    ("Signal", &["signal"]),
    ("Zoom", &["zoom.us"]),
    ("Google Meet", &["meet.google"]),
    ("Webex", &["webex"]),
    ("Jitsi", &["jitsi"]),
];
pub const SECRET_PATTERNS: &[(&str, &str)] = &[
    ("AWS Access Key", r"AKIA[0-9A-Z]{16}"),
    ("AWS Secret Key", r#"(?i)aws(.{0,20})?(?-i)['"][0-9a-zA-Z/+]{40}['"]"#),
    ("AWS Session Token", r#"(?i)aws(.{0,20})?(?-i)['"][0-9a-zA-Z/+]{40,}['"]"#),
    ("Azure Storage Key", r#"(?i)(AccountKey|account-key|storageaccountkey)[^=]*=[a-zA-Z0-9+/]{80,}={1,2}"#),
    ("Azure Connection String", r#"(?i)DefaultEndpointsProtocol=(https|http);AccountName=[^;]+;AccountKey=[^;]+"#),
    ("GCP Service Account", r#""type": "service_account""#),
    ("GCP API Key", r"AIza[0-9A-Za-z\-_]{35}"),
    ("Google OAuth", r"[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com"),
    ("GitHub Token", r"gh[pousr]_[A-Za-z0-9_]{36,38}"),
    ("GitHub Old Token", r"[0-9a-f]{40}"),
    ("GitLab Token", r"glpat-[0-9A-Za-z\-_]{20,30}"),
    ("GitLab CI Job Token", r"glcbt-[0-9A-Za-z\-_]{20,30}"),
    ("JWT Token", r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"),
    ("JWT in JSON", r#""access_token":\s*"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}""#),
    ("Generic API Key", r#"(?i)(api[_-]?key|apikey|api[_-]?secret|api_secret)\s*[:=]\s*['"][0-9A-Za-z]{16,45}['"]"#),
    ("Slack Token", r"xox[bapr]-[0-9a-zA-Z-]{10,48}"),
    ("Slack Webhook", r"https://hooks\.slack\.com/services/T[A-Z0-9]{8,10}/B[A-Z0-9]{8,10}/[a-zA-Z0-9]{24}"),
    ("Discord Webhook", r"https://discord\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+"),
    ("Discord Token", r"[MN][A-Za-z0-9_-]{23,25}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27}"),
    ("Telegram Bot Token", r"[0-9]{8,10}:[A-Za-z0-9_-]{35}"),
    ("Twilio API Key", r"SK[0-9a-fA-F]{32}"),
    ("Twilio Auth Token", r"[a-fA-F0-9]{32}"),
    ("SendGrid API Key", r"SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}"),
    ("Mailgun API Key", r"key-[0-9a-zA-Z]{32}"),
    ("Mailchimp API Key", r"[0-9a-f]{32}-us[0-9]{1,2}"),
    ("Postmark Server Token", r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"),
    ("Stripe Live Key", r"sk_live_[0-9a-zA-Z]{24,48}"),
    ("Stripe Test Key", r"sk_test_[0-9a-zA-Z]{24,48}"),
    ("Stripe Publishable Key", r"pk_live_[0-9a-zA-Z]{24,48}"),
    ("PayPal Secret", r"E[A-Za-z0-9_-]{30,50}"),
    ("PayPal Client ID", r"A[A-Za-z0-9_-]{40,60}"),
    ("Heroku API Key", r#"[hH][eE][rR][oO][kK][uU].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}"#),
    ("Heroku OAuth", r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"),
    ("Docker Hub Password", r#"(?i)docker.*password.*=.*['"][A-Za-z0-9]{20,}['"]"#),
    ("NPM Token", r"npm_[A-Za-z0-9]{36}"),
    ("NPMRC Auth", r#"_auth\s*=\s*[A-Za-z0-9+/=]{20,}"#),
    ("PyPI Token", r"pypi-[A-Za-z0-9]{20,40}"),
    ("Rubygems API Key", r"rubygems_[a-f0-9]{48}"),
    ("SonarQube Token", r#"(?i)sonar.*token.*=.*['"][a-f0-9]{40,}['"]"#),
    ("SSH Private Key", r"-----BEGIN [A-Z ]+ PRIVATE KEY-----"),
    ("SSH OpenSSH Key", r"-----BEGIN OPENSSH PRIVATE KEY-----"),
    ("PGP Private Key", r"-----BEGIN PGP PRIVATE KEY BLOCK-----"),
    ("Generic Password", r#"(?i)(password|passwd|pwd|pass)\s*[:=]\s*['"][^'"]{6,}['"]"#),
    ("Generic Secret", r#"(?i)(secret|token|credential|cred)\s*[:=]\s*['"][^'"]{8,}['"]"#),
    ("Connection String", r#"(?i)(connectionstring|conn_string|connstr)\s*[:=]\s*['"][^'"]{20,}['"]"#),
    ("Database URL", r#"(?i)(postgresql|mysql|mongodb|sqlite|oracle|mssql|sqlserver|redshift)://[^@]+@[^/\s]+"#),
    ("Redis URL", r"redis://[^@]+@[^/\s]+"),
    ("RabbitMQ URL", r"amqp://[^@]+@[^/\s]+"),
    ("JDB Connection", r"jdbc:(mysql|postgresql|oracle|sqlserver|h2|sqlite)://[^\s]+"),
    ("MongoDB Connection", r"mongodb://[^@]+@[^\s]+"),
    ("S3 Bucket", r#"(?i)(s3|bucket)\s*[:=]\s*['"][a-z0-9.-]{3,63}['"]"#),
    ("S3 Access Key", r#"(?i)(aws_access_key|access_key|aws_access_key_id)\s*[:=]\s*['"][A-Za-z0-9]{16,32}['"]"#),
    ("S3 Secret Key", r#"(?i)(aws_secret|secret_access|aws_secret_access_key)\s*[:=]\s*['"][A-Za-z0-9/+]{40}['"]"#),
    ("JWT in Header", r#"Authorization:\s*Bearer\s+eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"#),
    ("OAuth Token", r#"(?i)(oauth|bearer)\s+[A-Za-z0-9_\-]{20,50}"#),
    ("Session Cookie", r#"(?i)(session|sess|sid|jsessionid|phpsessid|aspsessionid)\s*[:=]\s*['"][a-zA-Z0-9]{16,64}['"]"#),
    ("Cloudflare Key", r#"(?i)(cf_api|cloudflare.*key)\s*[:=]\s*['"][a-zA-Z0-9_\-]{30,50}['"]"#),
    ("Cloudflare Token", r"CF[A-Za-z0-9_\-]{30,50}"),
    ("Datadog API Key", r#"(?i)datadog.*key\s*[:=]\s*['"][a-f0-9]{40}['"]"#),
    ("New Relic API Key", r#"(?i)new_relic.*key\s*[:=]\s*['"][a-f0-9]{40}['"]"#),
    ("New Relic License", r#"(?i)new_relic.*license\s*[:=]\s*['"][a-f0-9]{40}['"]"#),
    ("Sentry DSN", r"https://[a-f0-9]{32}@[a-f0-9]{16}\.ingest\.sentry\.io/[0-9]+"),
    ("PagerDuty Key", r#"(?i)pagerduty.*key\s*[:=]\s*['"][a-zA-Z0-9]{20,40}['"]"#),
    ("Sumo Logic Key", r#"(?i)sumo.*key\s*[:=]\s*['"][a-zA-Z0-9]{64}['"]"#),
    ("Logz.io Token", r#"(?i)logz.*token\s*[:=]\s*['"][a-zA-Z0-9]{40,60}['"]"#),
    ("Papertrail Key", r#"(?i)papertrail.*key\s*[:=]\s*['"][a-z0-9]{32}['"]"#),
    ("FingerprintJS Key", r#"(?i)fingerprint.*key\s*[:=]\s*['"][a-zA-Z0-9]{32}['"]"#),
    ("Algolia API Key", r#"(?i)algolia.*key\s*[:=]\s*['"][a-zA-Z0-9]{32}['"]"#),
    ("Meilisearch Key", r#"(?i)meili.*key\s*[:=]\s*['"][a-zA-Z0-9]{40}['"]"#),
    ("Typesense Key", r#"(?i)typesense.*key\s*[:=]\s*['"][a-zA-Z0-9]{40}['"]"#),
    ("Elasticsearch Password", r#"(?i)elastic.*password\s*[:=]\s*['"][^'"]{8,}['"]"#),
    ("Contentful Space ID", r#"(?i)contentful.*space\s*[:=]\s*['"][a-z0-9]{12}['"]"#),
    ("Contentful Access Token", r#"(?i)contentful.*token\s*[:=]\s*['"][a-zA-Z0-9]{43}['"]"#),
    ("Firebase URL", r"(?i)[a-z0-9-]+\.firebaseio\.com"),
    ("Firebase Cloud Messaging", r"AAA[A-Za-z0-9_-]{100,200}"),
    ("Supabase URL", r"(?i)https://[a-z0-9-]+\.supabase\.co"),
    ("Supabase Anon Key", r"eyJ[A-Za-z0-9_-]{30,}\.eyJ[A-Za-z0-9_-]{30,}\.[A-Za-z0-9_-]{30,}"),
    ("Auth0 Domain", r"(?i)[a-z0-9-]+\.auth0\.com"),
    ("RS256 Private Key", r"-----BEGIN RSA PRIVATE KEY-----"),
    ("EC Private Key", r"-----BEGIN EC PRIVATE KEY-----"),
    ("DSA Private Key", r"-----BEGIN DSA PRIVATE KEY-----"),
    ("Encrypted Private Key", r"-----BEGIN ENCRYPTED PRIVATE KEY-----"),
    ("PKCS8 Private Key", r"-----BEGIN PRIVATE KEY-----"),
    ("Certificate", r"-----BEGIN CERTIFICATE-----"),
    ("Certificate Request", r"-----BEGIN CERTIFICATE REQUEST-----"),
    ("PKCS12", r"-----BEGIN PKCS12-----"),
    ("Nginx SSL Config", r#"(?i)ssl_certificate\s+[^;]+;"#),
    ("Apache SSL Config", r#"(?i)SSLCertificateFile\s+[^\s]+"#),
    ("Docker Config", r#"(?i)"auths":\s*\{[^}]*"auth":\s*"[A-Za-z0-9+/=]+""#),
    ("Kubeconfig", r"(?i)current-context:\s*[a-z0-9-]+"),
    ("Kubernetes Secret", r"(?i)kind:\s*Secret"),
    ("Kubernetes Token", r#"(?i)"kubernetes.io/service-account-token""#),
    (".env File", r#"(?i)^[A-Z][A-Z0-9_]+=.*$"#),
    ("Authorization Header", r"Authorization:\s*Basic\s+[A-Za-z0-9+/=]{10,}"),
    ("Bearer Token", r"Bearer\s+[A-Za-z0-9_\-\.]{20,100}"),
    ("AWS Config", r#"(?i)\[profile\s+[a-z0-9-]+\]"#),
    ("Terraform State", r"(?i)terraform\.tfstate"),
    ("Environment Variable", r#"(?i)(export|set)\s+[A-Z][A-Z0-9_]+="#),
    ("Hash SHA256", r"[a-f0-9]{64}"),
    ("Hash MD5", r"[a-f0-9]{32}"),
    ("Hash SHA1", r"[a-f0-9]{40}"),
    ("IP Address", r"(?:\d{1,3}\.){3}\d{1,3}"),
    ("Internal IP", r"(10\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3})"),
    ("Email Address", r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"),
    ("URL", r#"https?://[^\s/'"<>]+"#),
    ("API Endpoint", r"(?i)/api/v[0-9]+/[a-z0-9/_-]+"),
    ("GraphQL Endpoint", r"/graphql"),
    ("GraphQL Query", r#"(?i)(query|mutation)\s+[a-zA-Z0-9_]+\s*\{"#),
    ("Webhook URL", r"https?://[^\s]+/hooks?/[^\s]+"),
    ("Callback URL", r#"(?i)(callback|redirect|return_url|webhook)\s*[:=]\s*['"]https?://[^'"]+['"]"#),
    ("Private IP in Config", r#"(?i)(host|server|url|endpoint)\s*[:=]\s*['"](10\.|172\.|192\.168\.)[^'"]+['"]"#),
    ("Debug Mode", r#"(?i)(debug|dev_mode|development)\s*[:=]\s*(true|1|yes)"#),
    ("CORS Origin", r"Access-Control-Allow-Origin:\s*\*"),
    ("Cookie Without Secure", r#"(?i)(session|token|auth)\s*=\s*[^;]+;\s*(?!.*[Ss]ecure)"#),
    ("Server Header Leak", r"Server:\s*[A-Za-z0-9_\-]+/[0-9]+\.[0-9]+"),
    ("X-Powered-By Leak", r"X-Powered-By:\s*[A-Za-z0-9_\-]+"),
    ("S3 Bucket URL", r"https?://[a-z0-9.-]+\.s3\.amazonaws\.com"),
    ("CloudFront URL", r"https?://[a-z0-9]+\.cloudfront\.net"),
    ("Cloud Storage URL", r"https?://storage\.googleapis\.com/[a-z0-9_-]+"),
    ("Azure Blob URL", r"https?://[a-z0-9]+\.blob\.core\.windows\.net"),
    ("Database Dump", r#"(?i)(INSERT INTO|CREATE TABLE|DROP TABLE|SELECT \* FROM)"#),
    ("SQL in Code", r#"(?i)(SELECT|INSERT|UPDATE|DELETE)\s+.+\s+FROM\s+.+"#),
];
pub const PLATFORMS: &[(&str, &str)] = &[
    ("GitHub", "https://github.com/{}"),
    ("GitLab", "https://gitlab.com/{}"),
    ("Twitter", "https://twitter.com/{}"),
    ("LinkedIn", "https://linkedin.com/in/{}"),
    ("Instagram", "https://instagram.com/{}"),
    ("Facebook", "https://facebook.com/{}"),
    ("YouTube", "https://youtube.com/@{}"),
    ("Twitch", "https://twitch.tv/{}"),
    ("TikTok", "https://tiktok.com/@{}"),
    ("Reddit", "https://reddit.com/user/{}"),
    ("Medium", "https://medium.com/@{}"),
    ("Dev.to", "https://dev.to/{}"),
    ("HackerNews", "https://news.ycombinator.com/user?id={}"),
    ("StackOverflow", "https://stackoverflow.com/users/{}"),
    ("Keybase", "https://keybase.io/{}"),
    ("Telegram", "https://t.me/{}"),
    ("Discord", "https://discord.com/users/{}"),
    ("Pinterest", "https://pinterest.com/{}"),
    ("Snapchat", "https://snapchat.com/add/{}"),
    ("WhatsApp", "https://wa.me/{}"),
    ("Signal", "https://signal.me/#p/{}"),
    ("WeChat", "https://wechat.com/{}"),
    ("YouTube Channel", "https://youtube.com/channel/{}"),
    ("Vimeo", "https://vimeo.com/{}"),
    ("Dribbble", "https://dribbble.com/{}"),
    ("Behance", "https://behance.net/{}"),
    ("Flickr", "https://flickr.com/people/{}"),
    ("500px", "https://500px.com/{}"),
    ("SoundCloud", "https://soundcloud.com/{}"),
    ("Bandcamp", "https://bandcamp.com/{}"),
    ("Mixcloud", "https://mixcloud.com/{}"),
    ("Spotify", "https://open.spotify.com/user/{}"),
    ("AngelList", "https://angel.co/{}"),
    ("Crunchbase", "https://crunchbase.com/person/{}"),
    ("ProductHunt", "https://producthunt.com/@{}"),
    ("HackerOne", "https://hackerone.com/{}"),
    ("Bugcrowd", "https://bugcrowd.com/{}"),
    ("TryHackMe", "https://tryhackme.com/p/{}"),
    ("HackTheBox", "https://hackthebox.com/profile/{}"),
    ("RootMe", "https://root-me.org/{}"),
    ("CTFtime", "https://ctftime.org/user/{}"),
    ("Wikipedia", "https://wikipedia.org/wiki/User:{}"),
    ("GitHub Gist", "https://gist.github.com/{}"),
    ("GitLab Snippets", "https://gitlab.com/snippets/{}"),
    ("Replit", "https://replit.com/@{}"),
    ("CodePen", "https://codepen.io/{}"),
    ("JSFiddle", "https://jsfiddle.net/user/{}"),
    ("CodeSandbox", "https://codesandbox.io/u/{}"),
    ("StackBlitz", "https://stackblitz.com/@{}"),
    ("NPM", "https://npmjs.com/~{}"),
    ("PyPI", "https://pypi.org/user/{}"),
    ("RubyGems", "https://rubygems.org/profiles/{}"),
    ("Crates.io", "https://crates.io/users/{}"),
    ("Docker Hub", "https://hub.docker.com/u/{}"),
    ("Homebrew", "https://github.com/Homebrew/homebrew-core/blob/master/Formula/{}.rb"),
    ("Scoop", "https://github.com/ScoopInstaller/Main/blob/master/bucket/{}.json"),
    ("Chocolatey", "https://chocolatey.org/profiles/{}"),
    ("Furaffinity", "https://furaffinity.net/user/{}"),
    ("DeviantArt", "https://deviantart.com/{}"),
    ("ArtStation", "https://artstation.com/{}"),
    ("Imgur", "https://imgur.com/user/{}"),
    ("VSCO", "https://vsco.co/{}"),
    ("Figma", "https://figma.com/@{}"),
    ("Notion", "https://notion.so/{}"),
    ("Slack", "https://slack.com/team/{}"),
    ("Zendesk", "https://{}.zendesk.com"),
    ("Intercom", "https://intercom.io/{}"),
    ("Calendly", "https://calendly.com/{}"),
    ("Zoom", "https://zoom.us/u/{}"),
    ("Google Meet", "https://meet.google.com/{}"),
    ("Microsoft Teams", "https://teams.microsoft.com/l/chat/0/0?users={}"),
    ("Google Scholar", "https://scholar.google.com/citations?user={}"),
    ("ResearchGate", "https://researchgate.net/profile/{}"),
    ("Academia", "https://academia.edu/{}"),
    ("ORCID", "https://orcid.org/{}"),
    ("PubMed", "https://pubmed.ncbi.nlm.nih.gov/?term={}"),
    ("arXiv", "https://arxiv.org/a/{}"),
    ("Trello", "https://trello.com/{}"),
    ("Asana", "https://app.asana.com/0/profile/{}"),
    ("Jira", "https://{}.atlassian.net"),
    ("Notion", "https://notion.so/{}"),
    ("Miro", "https://miro.com/{}"),
    ("Figma Community", "https://figma.com/@{}"),
    ("Gravatar", "https://gravatar.com/{}"),
    ("About.me", "https://about.me/{}"),
    ("Linktree", "https://linktr.ee/{}"),
    ("Bio.link", "https://bio.link/{}"),
    ("Carrd", "https://{}.carrd.co"),
    ("Substack", "https://substack.com/@{}"),
    ("Buy Me a Coffee", "https://buymeacoffee.com/{}"),
    ("Ko-fi", "https://ko-fi.com/{}"),
    ("Patreon", "https://patreon.com/{}"),
    ("Open Collective", "https://opencollective.com/{}"),
    ("GoFundMe", "https://gofundme.com/{}"),
    ("Kickstarter", "https://kickstarter.com/projects/{}"),
    ("Indiegogo", "https://indiegogo.com/individuals/{}"),
    ("Etsy", "https://etsy.com/shop/{}"),
    ("Shopify", "https://{}.myshopify.com"),
    ("Wix", "https://{}.wixsite.com"),
    ("Squarespace", "https://{}.squarespace.com"),
    ("WordPress", "https://{}.wordpress.com"),
    ("Blogger", "https://{}.blogspot.com"),
    ("Tumblr", "https://{}.tumblr.com"),
    ("Ghost", "https://{}.ghost.io"),
    ("Medium Publication", "https://medium.com/{}/"),
    ("Google Play", "https://play.google.com/store/apps/developer?id={}"),
    ("App Store", "https://apps.apple.com/developer/id{}"),
    ("Steam", "https://steamcommunity.com/id/{}"),
    ("Epic Games", "https://epicgames.com/{}"),
    ("Xbox", "https://xbox.com/{}"),
    ("PlayStation", "https://playstation.com/{}"),
    ("Nintendo", "https://nintendo.com/{}"),
    ("Battle.net", "https://battle.net/{}"),
    ("Riot Games", "https://riotgames.com/{}"),
    ("Chess.com", "https://chess.com/member/{}"),
    ("Lichess", "https://lichess.org/@/{}"),
    ("Speedrun.com", "https://speedrun.com/user/{}"),
    ("MyAnimeList", "https://myanimelist.net/profile/{}"),
    ("AniList", "https://anilist.co/user/{}"),
    ("IMDb", "https://imdb.com/user/{}"),
    ("Letterboxd", "https://letterboxd.com/{}"),
    ("Trakt", "https://trakt.tv/users/{}"),
    ("Goodreads", "https://goodreads.com/{}"),
    ("LibraryThing", "https://librarything.com/profile/{}"),
    ("Strava", "https://strava.com/athletes/{}"),
    ("Fitbit", "https://fitbit.com/user/{}"),
    ("MyFitnessPal", "https://myfitnesspal.com/profile/{}"),
    ("Runkeeper", "https://runkeeper.com/user/{}"),
    ("Komoot", "https://komoot.com/user/{}"),
    ("AllTrails", "https://alltrails.com/members/{}"),
];
