use crate::common::{WafResult, build_client};

const WAF_SIGNATURES: &[(&str, &[(&str, &[&str])])] = &[
    // ── CDNs / Reverse Proxies ──
    ("Cloudflare", &[
        ("header", &["cf-ray", "cf-cache-status", "cf-request-id", "server: cloudflare", "__cfduid"]),
        ("cookie", &["__cfduid"]),
        ("body", &["just a moment", "attention required! | cloudflare", "cf-error-page", "cloudflare ray id"]),
    ]),
    ("AWS CloudFront", &[
        ("header", &["x-amz-cf-id", "x-amz-cf-pop", "server: cloudfront"]),
        ("cookie", &["CloudFront-Policy", "CloudFront-Signature", "CloudFront-Key-Pair-Id"]),
    ]),
    ("AWS WAF", &[
        ("header", &["x-amzn-RequestId", "x-amzn-ErrorType", "x-amz-waf"]),
        ("body", &["AWS WAF", "waf", "request blocked", "405 method not allowed"]),
    ]),
    ("Akamai", &[
        ("header", &["x-akamai-transformed", "x-akamai-request-id", "server: akamai"]),
        ("cookie", &["abrl*", "akamai*"]),
    ]),
    ("Akamai WAF", &[
        ("header", &["x-akamai-staging", "x-akamai-config"]),
        ("body", &["akamai", "akamaighost", "reference #"]),
    ]),
    ("Fastly", &[
        ("header", &["x-fastly-request-id", "x-served-by", "x-cache", "x-cache-hits", "x-timer", "server: fastly"]),
        ("body", &["fastly error:"]),
    ]),
    ("StackPath", &[
        ("header", &["x-stackpath-*", "server: stackpath"]),
        ("body", &["stackpath"]),
    ]),
    ("LiteSpeed", &[
        ("header", &["server: litespeed", "x-litespeed-*"]),
        ("body", &["litespeed"]),
    ]),
    ("Varnish", &[
        ("header", &["x-varnish", "via: varnish"]),
        ("cookie", &["varnish*"]),
    ]),
    ("Varnish Cache (WAF)", &[
        ("header", &["x-varnish-cache"]),
        ("body", &["varnish"]),
    ]),
    ("Edgecast (Verizon)", &[
        ("header", &["x-ec-*", "server: edgecast"]),
        ("body", &["edgecast", "verizon digital media"]),
    ]),
    ("Section.io", &[
        ("header", &["x-section-*"]),
        ("body", &["section.io"]),
    ]),
    ("OpenResty", &[
        ("header", &["server: openresty"]),
        ("body", &["openresty"]),
    ]),
    ("SiteGround", &[
        ("header", &["x-sg-*", "server: sg"]),
        ("cookie", &["sg*"]),
        ("body", &["siteground"]),
    ]),

    // ── WAF-only products ──
    ("ModSecurity", &[
        ("header", &["server: modsecurity", "x-mod-*"]),
        ("body", &["modsecurity", "mod_security", "not acceptable", "access denied with code"]),
    ]),
    ("ModSecurity CRS", &[
        ("body", &["modsecurity: access denied", "modsecurity: warning", "this error was generated by modsecurity"]),
    ]),
    ("F5 BIG-IP ASM", &[
        ("header", &["x-asm-*", "x-f5-*"]),
        ("cookie", &["asm*", "f5*"]),
        ("body", &["the requested url was rejected", "f5 big-ip", "bigip"]),
    ]),
    ("F5 BIG-IP APM", &[
        ("header", &["x-apm-*"]),
        ("cookie", &["mrhsession", "mrh*", "f5*"]),
    ]),
    ("Barracuda WAF", &[
        ("header", &["x-barracuda-*", "barracuda"]),
        ("cookie", &["barra_counter*", "bni*"]),
        ("body", &["barracuda"]),
    ]),
    ("Imperva (Incapsula)", &[
        ("header", &["x-iinfo", "x-cdn", "x-incapsula-*"]),
        ("cookie", &["incap_ses_*", "visid_incap_*", "imperva*"]),
        ("body", &["incapsula", "imperva"]),
    ]),
    ("Sucuri", &[
        ("header", &["x-sucuri-id", "x-sucuri-cache", "x-sucuri-*"]),
        ("cookie", &["sucuri*"]),
        ("body", &["sucuri websites firewall", "sucuri.net", "cloudproxy"]),
    ]),
    ("Wordfence", &[
        ("cookie", &["wordfence*"]),
        ("body", &["wordfence", "this response was generated by wordfence"]),
    ]),
    ("Radware AppWall", &[
        ("header", &["x-radware-*", "x-rw-*"]),
        ("cookie", &["radware*"]),
        ("body", &["radware", "appwall"]),
    ]),
    ("Fortinet FortiWeb", &[
        ("header", &["x-fortiweb-*", "fortiweb"]),
        ("cookie", &["forti*"]),
        ("body", &["fortiweb"]),
    ]),
    ("Citrix NetScaler", &[
        ("header", &["x-netscaler-*", "via: netscaler"]),
        ("cookie", &["nsc_*", "netscaler*"]),
        ("body", &["netscaler"]),
    ]),
    ("AQTRONIX WebKnight", &[
        ("header", &["server: webknight"]),
        ("body", &["webknight", "aqtronix"]),
    ]),
    ("Comodo WAF", &[
        ("header", &["server: comodo"]),
        ("cookie", &["comodo*"]),
        ("body", &["comodo"]),
    ]),
    ("URLScan", &[
        ("header", &["x-uriscan-*"]),
        ("body", &["urlscan", "url scan"]),
    ]),
    ("SecKing WAF", &[
        ("header", &["server: secking", "x-secking-*"]),
        ("body", &["secking"]),
    ]),
    ("Yundun WAF", &[
        ("header", &["x-yundun-*", "yundun"]),
        ("cookie", &["yundun*"]),
        ("body", &["yundun"]),
    ]),
    ("SafeLine WAF", &[
        ("header", &["x-safeline-*"]),
        ("body", &["safeline"]),
    ]),
    ("NAXSI WAF", &[
        ("header", &["x-naxsi-*", "naxsi"]),
        ("body", &["naxsi"]),
    ]),
    ("DotDefender", &[
        ("header", &["x-dotdefender-*"]),
        ("body", &["dotdefender"]),
    ]),
    ("Palo Alto WAF", &[
        ("header", &["x-paloalto-*", "pa-*"]),
        ("body", &["palo alto", "paloalto"]),
    ]),
    ("Reblaze", &[
        ("header", &["x-reblaze-*"]),
        ("cookie", &["reblaze*"]),
    ]),
    ("NinjaFirewall", &[
        ("header", &["x-ninjafirewall-*"]),
        ("cookie", &["nfw*"]),
        ("body", &["ninjafirewall"]),
    ]),
    ("Airlock WAF", &[
        ("header", &["x-airlock-*", "server: airlock"]),
        ("cookie", &["airlock*"]),
        ("body", &["airlock"]),
    ]),
    ("Profense", &[
        ("header", &["x-profense-*"]),
        ("cookie", &["profense*"]),
    ]),
    ("Armor Defense", &[
        ("header", &["x-armor-*"]),
        ("cookie", &["armor*"]),
        ("body", &["armor defense", "armor"]),
    ]),
    ("Distil Networks", &[
        ("header", &["x-distil-*"]),
        ("body", &["distil", "blocked by distil"]),
    ]),
    ("Kona WAF (Akamai)", &[
        ("header", &["x-kona-*"]),
        ("body", &["kona", "akamaighost"]),
    ]),
    ("PT Application Firewall", &[
        ("header", &["x-pt-*"]),
        ("body", &["pt application firewall"]),
    ]),
    ("CacheWall", &[
        ("header", &["x-cachewall-*"]),
        ("body", &["cachewall"]),
    ]),
    ("SafeDNS WAF", &[
        ("header", &["x-safedns-*"]),
        ("body", &["safedns"]),
    ]),
    ("WebARX", &[
        ("header", &["x-webarx-*"]),
        ("body", &["webarx"]),
    ]),

    // ── WordPress-specific WAFs ──
    ("Wordfence", &[
        ("cookie", &["wordfence*"]),
        ("body", &["wordfence", "this response was generated by wordfence"]),
    ]),
    ("BulletProof Security", &[
        ("body", &["bulletproof security", ".htaccess firewall"]),
    ]),
    ("Shield Security", &[
        ("cookie", &["shield*"]),
        ("body", &["shield security"]),
    ]),
    ("All In One WP Security", &[
        ("body", &["all in one wp security", "aios"]),
    ]),
    ("6Scan WAF", &[
        ("body", &["6scan"]),
    ]),
    ("Sitelock", &[
        ("body", &["sitelock", "trueshield"]),
    ]),
    ("CleanTalk", &[
        ("cookie", &["cleantalk*"]),
        ("body", &["cleantalk"]),
    ]),

    // ── Other WAFs ──
    ("Myra Security", &[
        ("header", &["x-myra-*"]),
        ("body", &["myra"]),
    ]),
    ("Qrator", &[
        ("header", &["x-qrator-*"]),
        ("body", &["qrator"]),
    ]),
    ("Rblx", &[
        ("header", &["x-rblx-*"]),
        ("body", &["rblx"]),
    ]),
    ("Trafodion", &[
        ("header", &["x-trafodion-*"]),
        ("body", &["trafodion"]),
    ]),
    ("Beloved", &[
        ("cookie", &["beloved*"]),
        ("body", &["beloved"]),
    ]),
    ("eEye SecureIIS", &[
        ("body", &["secureiis", "secure iis"]),
    ]),
    ("SquidGuard", &[
        ("body", &["squidguard"]),
    ]),
];

const CDN_NAMES: &[&str] = &[
    "Cloudflare",
    "AWS CloudFront",
    "Akamai",
    "Fastly",
    "StackPath",
    "LiteSpeed",
    "Varnish",
    "Edgecast (Verizon)",
    "Section.io",
    "OpenResty",
    "SiteGround",
];

const GENERIC_BLOCK_PATTERNS: &[&str] = &[
    "blocked by",
    "access denied",
    "access blocked",
    "your request has been blocked",
    "malicious request",
    "suspicious activity detected",
    "this request has been blocked",
    "request rejected",
    "please try again later",
    "ip has been blocked",
    "www.blocked",
];

pub async fn detect(url: &str) -> WafResult {
    let full_url = if url.starts_with("http") {
        url.to_string()
    } else {
        format!("https://{}", url)
    };
    let mut indicators: Vec<String> = Vec::new();
    let mut detected_waf: Option<String> = None;
    let mut detected_cdn: Option<String> = None;

    let client = match build_client(10) {
        Some(c) => c,
        None => {
            return WafResult {
                url: full_url,
                waf: None,
                cdn: None,
                detected: false,
                indicators,
            };
        }
    };

    let resp = match client.get(&full_url).send().await {
        Ok(r) => r,
        Err(_) => {
            return WafResult {
                url: full_url,
                waf: None,
                cdn: None,
                detected: false,
                indicators,
            };
        }
    };

    let headers: Vec<(String, String)> = resp
        .headers()
        .iter()
        .map(|(k, v)| {
            (
                k.as_str().to_lowercase(),
                v.to_str().unwrap_or("").to_lowercase(),
            )
        })
        .collect();

    let cookies: Vec<String> = resp
        .headers()
        .get_all("set-cookie")
        .iter()
        .filter_map(|v| v.to_str().ok())
        .map(|s| s.to_lowercase())
        .collect();

    // First pass: header and cookie matching against known WAF signatures
    for &(name, signatures) in WAF_SIGNATURES {
        let mut match_count = 0u32;
        for &(stype, patterns) in signatures {
            if stype == "body" {
                continue;
            }
            for &pattern in patterns {
                let (match_key, check_val) = if let Some(p) = pattern.split_once(": ") {
                    (p.0, Some(p.1))
                } else {
                    (pattern, None)
                };

                let matched = match stype {
                    "header" => headers.iter().any(|(k, v)| {
                        k.contains(match_key) || check_val.map_or(false, |cv| v.contains(cv))
                    }),
                    "cookie" => cookies.iter().any(|c| c.contains(match_key)),
                    _ => false,
                };

                if matched {
                    match_count += 1;
                    indicators.push(format!("{}: {}", name, pattern));
                }
            }
        }
        if match_count > 0 {
            if detected_waf.is_none() {
                detected_waf = Some(name.to_string());
            }
            if CDN_NAMES.contains(&name) {
                detected_cdn = Some(name.to_string());
            }
        }
    }

    // Second pass: body pattern matching
    if let Ok(body) = resp.text().await {
        let body_lower = body.to_lowercase();

        for &(name, signatures) in WAF_SIGNATURES {
            for &(stype, patterns) in signatures {
                if stype != "body" {
                    continue;
                }
                for &pattern in patterns {
                    if body_lower.contains(pattern) {
                        indicators.push(format!("{}: {} (body)", name, pattern));
                        if detected_waf.is_none() {
                            detected_waf = Some(name.to_string());
                        }
                    }
                }
            }
        }

        // Generic WAF block page patterns as fallback
        if detected_waf.is_none() {
            for &pattern in GENERIC_BLOCK_PATTERNS {
                if body_lower.contains(pattern) {
                    indicators.push(format!("Generic WAF: {} (body)", pattern));
                    if detected_waf.is_none() {
                        detected_waf = Some("Generic WAF".to_string());
                    }
                    break;
                }
            }
        }
    }

    indicators.sort();
    indicators.dedup();

    let detected = detected_waf.is_some();
    WafResult {
        url: full_url,
        waf: detected_waf,
        cdn: detected_cdn,
        detected,
        indicators,
    }
}
