use crate::common::{WafResult, build_client};

const WAF_SIGNATURES: &[(&str, &[(&str, &[&str])])] = &[
    ("Cloudflare", &[("header", &["cf-ray", "cf-cache-status", "cf-request-id", "server: cloudflare", "__cfduid"]), ("cookie", &["__cfduid"])]),
    ("AWS CloudFront", &[("header", &["x-amz-cf-id", "x-amz-cf-pop", "x-amz-cf-*-id", "server: CloudFront"]), ("cookie", &["CloudFront-Policy", "CloudFront-Signature", "CloudFront-Key-Pair-Id"])]),
    ("AWS WAF", &[("header", &["x-amzn-RequestId", "x-amzn-ErrorType", "x-amz-waf"]), ("body", &["AWS WAF", "waf"])]),
    ("Akamai", &[("header", &["x-akamai-transformed", "x-akamai-request-id", "x-akamai-*", "server: Akamai"]), ("cookie", &["abrl*", "akamai*"])]),
    ("Akamai WAF", &[("header", &["x-akamai-staging", "x-akamai-config"]), ("body", &["akamai", "AkamaiGHost"])]),
    ("Fastly", &[("header", &["x-fastly-request-id", "x-served-by", "x-cache", "x-cache-hits", "x-timer", "server: Fastly"]), ("body", &["Fastly error:"])]),
    ("Cloudflare WAF", &[("header", &["cf-waf-error", "cf-waf-*"]), ("body", &["Attention Required! | Cloudflare", "cf-error-page"])]),
    ("Sucuri", &[("header", &["x-sucuri-id", "x-sucuri-cache", "x-sucuri-*"]), ("cookie", &["sucuri*"]), ("body", &["Sucuri WebSite Firewall", "sucuri.net"])]),
    ("Incapsula", &[("header", &["x-iinfo", "x-cdn", "x-incapsula-*"]), ("cookie", &["incap_ses_*", "visid_incap_*"]), ("body", &["Incapsula", "incapsula"])]),
    ("Imperva (Incapsula)", &[("header", &["x-iinfo"]), ("cookie", &["imperva*"]), ("body", &["Imperva", "imperva"])]),
    ("Barracuda WAF", &[("header", &["x-barracuda-*", "barracuda"]), ("cookie", &["barra_counter*", "BNI*"]), ("body", &["Barracuda", "barracuda"])]),
    ("F5 BIG-IP ASM", &[("header", &["x-asm-*", "x-f5-*"]), ("cookie", &["ASM*", "F5*"]), ("body", &["The requested URL was rejected", "F5 BIG-IP"])]),
    ("F5 BIG-IP APM", &[("header", &["x-apm-*"]), ("cookie", &["MRHSession", "MRH*", "F5*"])]),
    ("ModSecurity", &[("header", &["server: ModSecurity", "x-mod-*"]), ("body", &["ModSecurity", "mod_security", "Not Acceptable"])]),
    ("ModSecurity CRS", &[("body", &["ModSecurity: Access denied", "ModSecurity: Warning", "This error was generated by ModSecurity"])]),
    ("NAXSI WAF", &[("header", &["x-naxsi-*", "naxsi"]), ("body", &["NAXSI", "naxsi", "Naxsi"])]),
    ("SafeLine WAF", &[("header", &["x-safeline-*"]), ("body", &["SafeLine", "safeline"])]),
    ("WebKnight", &[("header", &["server: WebKnight"]), ("body", &["WebKnight", "webknight", "AQTRONIX"])]),
    ("URLScan", &[("header", &["x-uriscan-*"]), ("body", &["urlscan", "URL Scan"])]),
    ("DotDefender", &[("header", &["x-dotdefender-*"]), ("body", &["dotdefender", "DotDefender"])]),
    ("Comodo WAF", &[("header", &["server: Comodo"]), ("cookie", &["comodo*"]), ("body", &["Comodo", "comodo"])]),
    ("Fortinet FortiWeb", &[("header", &["x-fortiweb-*", "fortiweb"]), ("cookie", &["forti*"]), ("body", &["FortiWeb", "fortiweb"])]),
    ("Citrix NetScaler", &[("header", &["x-netscaler-*", "via: NetScaler"]), ("cookie", &["NSC_*", "netscaler*"]), ("body", &["NetScaler", "netscaler"])]),
    ("Palo Alto WAF", &[("header", &["x-paloalto-*", "pa-*"]), ("body", &["Palo Alto", "paloalto"])]),
    ("Radware AppWall", &[("header", &["x-radware-*", "X-RW-*"]), ("cookie", &["radware*"]), ("body", &["Radware", "AppWall"])]),
    ("Reblaze", &[("header", &["x-reblaze-*"]), ("cookie", &["reblaze*"])]),
    ("StackPath", &[("header", &["x-stackpath-*", "server: StackPath"]), ("body", &["StackPath", "stackpath"])]),
    ("Varnish", &[("header", &["x-varnish", "via: varnish"]), ("cookie", &["varnish*"])]),
    ("Varnish Cache (WAF)", &[("header", &["x-varnish-cache"]), ("body", &["varnish", "Varnish"])]),
    ("Wordfence", &[("cookie", &["wordfence*"]), ("body", &["Wordfence", "wordfence", "This response was generated by Wordfence"])]),
    ("BulletProof Security", &[("body", &["BulletProof Security", ".htaccess firewall"])]),
    ("Shield Security", &[("cookie", &["shield*"]), ("body", &["Shield Security"])]),
    ("All In One WP Security", &[("body", &["All In One WP Security", "AIOS"])]),
    ("NinjaFirewall", &[("header", &["x-ninjafirewall-*"]), ("cookie", &["nfw*"]), ("body", &["NinjaFirewall", "ninjafirewall"])]),
    ("6Scan WAF", &[("body", &["6Scan", "6scan"])]),
    ("SiteGround", &[("header", &["x-sg-*", "server: SG"]), ("cookie", &["sg*"]), ("body", &["SiteGround", "siteground"])]),
    ("Sitelock", &[("body", &["SiteLock", "sitelock", "TrueShield"])]),
    ("Qrator", &[("header", &["x-qrator-*"]), ("body", &["Qrator", "qrator"])]),
    ("Myra Security", &[("header", &["x-myra-*"]), ("body", &["Myra", "myra"])]),
    ("Airlock WAF", &[("header", &["x-airlock-*", "server: Airlock"]), ("cookie", &["airlock*"]), ("body", &["Airlock", "airlock"])]),
    ("Profense", &[("header", &["x-profense-*"]), ("cookie", &["profense*"])]),
    ("Armor Defense", &[("header", &["x-armor-*"]), ("cookie", &["armor*"]), ("body", &["Armor Defense", "armor"])]),
    ("Distil Networks", &[("header", &["x-distil-*"]), ("body", &["Distil", "distil", "blocked by Distil"])]),
    ("Rblx", &[("header", &["x-rblx-*"]), ("body", &["Rblx", "rblx"])]),
    ("LiteSpeed", &[("header", &["server: LiteSpeed", "x-litespeed-*"]), ("body", &["LiteSpeed", "litespeed"])]),
    ("OpenResty", &[("header", &["server: openresty"]), ("body", &["openresty"])]),
    ("Trafodion", &[("header", &["x-trafodion-*"]), ("body", &["Trafodion"])]),
    ("Kona WAF (Akamai)", &[("header", &["x-kona-*"]), ("body", &["Kona", "AkamaiGHost"])]),
    ("Beloved", &[("cookie", &["beloved*"]), ("body", &["Beloved"])]),
    ("SafeDNS WAF", &[("header", &["x-safedns-*"]), ("body", &["SafeDNS", "safedns"])]),
    ("WebARX", &[("header", &["x-webarx-*"]), ("body", &["WebARX", "webarx"])]),
    ("PT Application Firewall", &[("header", &["x-pt-*"]), ("body", &["PT Application Firewall"])]),
    ("eEye SecureIIS", &[("body", &["SecureIIS", "Secure IIS"])]),
    ("SquidGuard", &[("body", &["SquidGuard", "squidguard"])]),
    ("CleanTalk", &[("cookie", &["cleantalk*"]), ("body", &["CleanTalk", "cleantalk"])]),
    ("CacheWall", &[("header", &["x-cachewall-*"]), ("body", &["CacheWall"])]),
    ("Edgecast (Verizon)", &[("header", &["x-ec-*", "server: Edgecast"]), ("body", &["Edgecast", "Verizon Digital Media"])]),
    ("Section.io", &[("header", &["x-section-*"]), ("body", &["Section.io"])]),
];

pub async fn detect(url: &str) -> WafResult {
    let full_url = if url.starts_with("http") { url.to_string() } else { format!("https://{}", url) };
    let mut indicators = Vec::new();
    let mut detected_waf: Option<String> = None;
    let mut detected_cdn: Option<String> = None;
    let client = match build_client(10) { Some(c) => c, None => return WafResult { url: full_url, waf: None, cdn: None, detected: false, indicators } };

    if let Ok(resp) = client.get(&full_url).send().await {
        let headers: Vec<(String, String)> = resp.headers().iter().map(|(k, v)| (k.as_str().to_lowercase(), v.to_str().unwrap_or("").to_lowercase())).collect();
        let cookies = resp.headers().get_all("set-cookie").iter().filter_map(|v| v.to_str().ok()).map(|s| s.to_lowercase()).collect::<Vec<_>>();

        for &(name, signatures) in WAF_SIGNATURES {
            let mut match_count = 0;
            for &(stype, patterns) in signatures {
                for &pattern in patterns {
                    let (match_key, check_val) = if let Some(p) = pattern.split_once(": ") {
                        (p.0, Some(p.1))
                    } else { (pattern, None) };

                    let matched = match stype {
                        "header" => headers.iter().any(|(k, v)| k.contains(match_key) || check_val.map_or(false, |cv| v.contains(cv))),
                        "cookie" => cookies.iter().any(|c| c.contains(match_key)),
                        "body" => false,
                        _ => false,
                    };
                    if matched { match_count += 1; indicators.push(format!("{}: {}", name, pattern)); }
                }
            }
            if match_count > 0 {
                if detected_waf.is_none() { detected_waf = Some(name.to_string()); }
                if matches!(name, "Cloudflare" | "AWS CloudFront" | "Akamai" | "Fastly" | "StackPath" | "LiteSpeed" | "Varnish") {
                    detected_cdn = Some(name.to_string());
                }
            }
        }

        // Body check
        if let Ok(body) = resp.text().await {
            let b = body.to_lowercase();
            for &(name, signatures) in WAF_SIGNATURES {
                for &(stype, patterns) in signatures {
                    if stype != "body" { continue; }
                    for &pattern in patterns {
                        if b.contains(pattern) {
                            indicators.push(format!("{}: {} (body)", name, pattern));
                            detected_waf.get_or_insert(name.to_string());
                        }
                    }
                }
            }
        }
    }

    // Test with malicious payload
    let malicious_url = format!("{}/?id=1' OR '1'='1&q=<script>alert(1)</script>&exec=cat%20/etc/passwd&redirect=//evil.com", full_url.trim_end_matches('/'));
    if let Ok(resp) = client.get(&malicious_url).send().await {
        let status = resp.status().as_u16();
        if status == 406 || status == 493 || status == 999 {
            indicators.push(format!("WAF blocked malicious request (HTTP {})", status));
            detected_waf.get_or_insert("Generic WAF".into());
        }
        if resp.headers().get("cf-ray").is_some() { detected_waf.get_or_insert("Cloudflare".into()); }
        if resp.headers().get("x-sucuri-id").is_some() { detected_waf.get_or_insert("Sucuri".into()); }
        if resp.headers().get("x-iinfo").is_some() { detected_waf.get_or_insert("Incapsula".into()); }
    }

    let detected = detected_waf.is_some();
    indicators.sort(); indicators.dedup();
    WafResult { url: full_url, waf: detected_waf, cdn: detected_cdn, detected, indicators }
}
