"""
Smart Analyzer - Deep Reconnaissance Engine for Dir Finder
Detects tech stack, WAF, JS endpoints, generates smart wordlists
"""
import argparse
import json
import os
import re
import sys
import urllib3
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

TECH_SIGNATURES = {
    "PHP": {"headers": {"X-Powered-By": r"PHP"}, "cookies": {}, "body": r"\.php\b"},
    "ASP.NET": {"headers": {"X-Powered-By": r"ASP\.NET", "X-AspNet-Version": r".*"}, "cookies": {"ASP.NET_SessionId": r".*"}},
    "Java/JSP": {"headers": {"X-Powered-By": r"JSP|Servlet"}, "cookies": {"JSESSIONID": r".*"}},
    "Node.js": {"headers": {"X-Powered-By": r"Express|Node"}, "body": r"__NEXT_DATA__|__NUXT__|__REACT_"},
    "Nginx": {"headers": {"Server": r"nginx(?:/([\d.]+))?"}},
    "Apache": {"headers": {"Server": r"Apache(?:/([\d.]+))?"}},
    "IIS": {"headers": {"Server": r"Microsoft-IIS|IIS"}, "body": r"IIS"},
    "Cloudflare": {"headers": {"Server": r"cloudflare", "CF-RAY": r".*"}, "cookies": {"__cfduid": r".*"}},
    "WordPress": {"cookies": {"wordpress_": r".*"}, "body": r"wp-content|wp-includes|wp-admin|wp-json"},
    "Drupal": {"headers": {"X-Drupal-Cache": r".*", "X-Generator": r"Drupal"}, "body": r"Drupal\.|drupal\.js|drupal\.css"},
    "Joomla": {"headers": {"X-Content-Encoded-By": r"Joomla"}, "body": r"/media/jui|/templates/|com_content|com_"},
    "Laravel": {"cookies": {"laravel_session": r".*", "XSRF-TOKEN": r".*"}, "headers": {"X-Powered-By": r"Laravel"}},
    "Symfony": {"cookies": {"symfony": r".*"}, "headers": {"X-Symfony": r".*"}, "body": r"_sf2_attributes|_symfony"},
    "CakePHP": {"cookies": {"CAKEPHP": r".*"}, "headers": {"X-Cake": r".*"}},
    "Django": {"cookies": {"csrftoken": r".*", "sessionid": r".*"}, "headers": {"X-Django": r".*"}},
    "Flask": {"cookies": {"session": r".*"}, "headers": {"X-Flask": r".*"}, "body": r"__FLASK"},
    "FastAPI": {"headers": {"server": r"uvicorn"}, "body": r"openapi\.json|docs|redoc"},
    "Ruby on Rails": {"cookies": {"_session_id": r".*", "_rails": r".*"}, "headers": {"X-Rails": r".*", "X-Runtime": r".*"}},
    "Tomcat": {"headers": {"Server": r"Tomcat|Apache-Coyote"}, "body": r"/manager/html|/examples/"},
    "JBoss": {"headers": {"X-Powered-By": r"JBoss"}, "body": r"JBoss"},
    "WebLogic": {"headers": {"Server": r"WebLogic"}, "body": r"WebLogic"},
    "Jenkins": {"headers": {"X-Jenkins": r".*", "X-Jenkins-Session": r".*"}, "body": r"/jenkins|/pluginManager|/script"},
    "GitLab": {"headers": {"X-Gitlab": r".*"}, "body": r"GitLab|gitlab"},
    "Kubernetes": {"headers": {"Server": r"Kubernetes|kube"}, "body": r"kubernetes|kube-system"},
    "Docker": {"headers": {"Server": r"Docker"}, "body": r"Docker"},
    "AWS": {"headers": {"Server": r"AmazonS3|awselb|CloudFront|nginx/1\..*amazon"}, "body": r"amazonaws\.com|s3\.amazonaws"},
    "GCP": {"headers": {"Server": r"Google|gws"}, "body": r"cloudfront\.net|googleapis\.com"},
    "Azure": {"headers": {"Server": r"Microsoft-Azure|Azure", "X-Azure-Ref": r".*"}, "body": r"azurewebsites\.net|azureedge"},
}

WAF_SIGNATURES = {
    "Cloudflare": {"cookies": {"__cfduid": r".*"}, "headers": {"CF-RAY": r".*", "Server": r"cloudflare"}, "body": r"Cloudflare|Ray ID:|cf-ray"},
    "Akamai": {"headers": {"Server": r"akamaighost|Akamai"}, "body": r"akamai|AkamaiGHost"},
    "AWS WAF": {"headers": {"Server": r"awselb|Amazon"}, "body": r"AWS WAF|Request blocked|waf"},
    "ModSecurity": {"headers": {"Server": r"ModSecurity|mod_security"}, "body": r"ModSecurity|Not Acceptable|NO modsecurity"},
    "F5 BIG-IP ASM": {"headers": {"Server": r"BigIP|F5"}, "body": r"The requested URL was rejected|F5|BigIP"},
    "Barracuda": {"headers": {"Server": r"Barracuda"}, "body": r"Barracuda|WAF"},
    "Sucuri": {"headers": {"X-Sucuri-ID": r".*", "X-Sucuri-Cache": r".*"}, "body": r"Sucuri|CloudProxy"},
    "Wordfence": {"headers": {}, "body": r"Wordfence|Generated by Wordfence"},
    "Stackpath": {"headers": {"Server": r"Stackpath"}, "body": r"Stackpath"},
    "Comodo": {"headers": {}, "body": r"Comodo WAF|Protected by Comodo"},
    "Imperva": {"headers": {"Server": r"Imperva|Incapsula"}, "body": r"Imperva|Incapsula|_incap_"},
    "Radware": {"headers": {"Server": r"Radware|AppWall"}, "body": r"Radware|AppWall"},
    "Fortinet": {"headers": {"Server": r"FortiWeb|Fortinet"}, "body": r"FortiWeb|Fortinet"},
    "Palo Alto": {"headers": {}, "body": r"PAN-OS|Palo Alto"},
    "Sangfor": {"headers": {}, "body": r"Sangfor|WAF"},
    "SafeLine": {"headers": {"Server": r"SafeLine"}, "body": r"SafeLine"},
    "Litespeed": {"headers": {"Server": r"LiteSpeed"}, "body": r"LiteSpeed"},
    "OpenResty": {"headers": {"Server": r"openresty"}, "body": r"openresty"},
    "Traefik": {"headers": {"Server": r"traefik"}, "body": r"traefik"},
    "Caddy": {"headers": {"Server": r"Caddy"}, "body": r"Caddy"},
}

COMMON_JS_FILES = [
    "main.js", "app.js", "index.js", "script.js", "bundle.js",
    "vendor.js", "common.js", "config.js", "api.js", "routes.js",
    "webpack.js", "build.js", "all.js", "core.js", "utils.js",
    "helpers.js", "components.js", "services.js", "controllers.js",
    "modules.js", "router.js", "store.js", "actions.js", "reducers.js",
]

BACKUP_EXTENSIONS = [".bak", ".old", ".tmp", ".zip", ".tar.gz", ".tgz", ".sql", ".conf", ".save",
                     ".backup", ".swp", ".swo", ".orig", ".copy", ".txt", ".7z", ".rar", ".gz"]

BACKUP_FILES = [
    "backup", "www", "web", "site", "app", "data", "db", "database",
    "wp-backup", "backup-db", "dump", "export", "sql-dump",
]

COMMON_ENDPOINTS = [
    "/api", "/api/v1", "/api/v2", "/graphql", "/rest",
    "/swagger.json", "/openapi.json", "/docs", "/redoc",
    "/.well-known/security.txt", "/sitemap.xml", "/robots.txt",
    "/crossdomain.xml", "/clientaccesspolicy.xml",
    "/.env", "/.git/config", "/.gitignore", "/.htaccess",
    "/admin", "/login", "/wp-admin", "/administrator",
    "/phpmyadmin", "/pma", "/console", "/manager",
]


class SmartAnalyzer:
    def __init__(self, target_url, timeout=10, threads=10):
        self.target_url = target_url.rstrip("/")
        self.timeout = timeout
        self.threads = threads
        self.session = requests.Session()
        self.session.verify = False
        self.session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
        })
        self.found_endpoints = set()
        self.tech_stack = []
        self.waf_detected = ""
        self.cms_detected = ""
        self.recommended_wordlists = []
        self.all_js_urls = []

    def detect_tech(self):
        """Detect technology stack using 30+ signatures"""
        print(f"[*] Detecting technology stack...")
        try:
            resp = self.session.get(self.target_url, timeout=self.timeout)
            html = resp.text.lower()
            headers = {k.lower(): v for k, v in resp.headers.items()}
            cookies = {k: v for k, v in resp.cookies.items()}

            for tech, sigs in TECH_SIGNATURES.items():
                found = False
                for header, pattern in sigs.get("headers", {}).items():
                    if header in headers and re.search(pattern, headers[header], re.I):
                        found = True
                        break
                if not found:
                    for cookie, pattern in sigs.get("cookies", {}).items():
                        if any(re.search(pattern, v) for k, v in cookies.items() if k.lower().startswith(cookie.lower())):
                            found = True
                            break
                if not found and sigs.get("body"):
                    if re.search(sigs["body"], html, re.I):
                        found = True
                if found:
                    self.tech_stack.append(tech)
                    self._add_wordlist_for_tech(tech)

            # Extract version info
            if "X-Powered-By" in resp.headers:
                self.tech_stack.append(f"X-Powered-By: {resp.headers['X-Powered-By']}")
            if "X-AspNet-Version" in resp.headers:
                self.tech_stack.append(f"ASP.NET: {resp.headers['X-AspNet-Version']}")
            if "X-Runtime" in resp.headers:
                self.tech_stack.append(f"Ruby: {resp.headers['X-Runtime']}")

            # CMS specific detection
            if "WordPress" in self.tech_stack:
                self.cms_detected = "WordPress"
            elif "Drupal" in self.tech_stack:
                self.cms_detected = "Drupal"
            elif "Joomla" in self.tech_stack:
                self.cms_detected = "Joomla"

            print(f"[+] Tech Stack: {', '.join(self.tech_stack) if self.tech_stack else 'Unknown'}")
        except Exception as e:
            print(f"[!] Tech detection failed: {e}")

    def _add_wordlist_for_tech(self, tech):
        """Map tech to recommended wordlist categories"""
        tech_to_cat = {
            "WordPress": ["php", "php/wordpress", "common"],
            "Drupal": ["php", "php/drupal", "common"],
            "Joomla": ["php", "php/joomla", "common"],
            "Laravel": ["php", "php/laravel", "common"],
            "Symfony": ["php", "php/symfony", "common"],
            "CakePHP": ["php", "php/cakephp", "common"],
            "CodeIgniter": ["php", "php/codeigniter", "common"],
            "Yii": ["php", "php/yii", "common"],
            "Magento": ["php", "php/magento", "common"],
            "ASP.NET": ["dotnet", "dotnet/aspx", "dotnet/mvc", "dotnet/core", "common"],
            "Django": ["python", "python/django", "common"],
            "Flask": ["python", "python/flask", "common"],
            "FastAPI": ["python", "python/fastapi", "common"],
            "Express": ["node", "node/express", "common"],
            "Node.js": ["node", "node/express", "common"],
            "Kubernetes": ["infra", "infra/k8s", "infra/docker", "common"],
            "Docker": ["infra", "infra/docker", "common"],
            "AWS": ["infra", "infra/aws", "common"],
            "Java/JSP": ["java", "java/jsp", "java/spring", "java/jsf", "common"],
            "Tomcat": ["java", "java/jsp", "common"],
            "Jenkins": ["common", "conf"],
        }
        if tech in tech_to_cat:
            for cat in tech_to_cat[tech]:
                if cat not in self.recommended_wordlists:
                    self.recommended_wordlists.append(cat)

    def detect_waf(self):
        """Detect WAF with 20+ signatures using probes"""
        print(f"[*] Detecting WAF...")
        waf_payloads = [
            ("?id=' OR 1=1--", "' OR 1=1--"),
            ("?id=<script>alert(1)</script>", "<script>alert(1)</script>"),
            ("?id=../../../etc/passwd", "../../../etc/passwd"),
            ("?id=UNION SELECT NULL--", "UNION SELECT NULL--"),
            ("/../../../etc/passwd", "../../../etc/passwd"),
            ("/CONFIG", "CONFIG"),
            ("/.env", ".env"),
        ]

        for path_suffix, payload in waf_payloads:
            try:
                test_url = f"{self.target_url}{path_suffix}"
                resp = self.session.get(test_url, timeout=self.timeout)

                if resp.status_code in (403, 406, 429, 501, 503):
                    headers = {k.lower(): v for k, v in resp.headers.items()}
                    body = resp.text.lower()
                    cookies = {k: v for k, v in resp.cookies.items()}

                    for waf, sigs in WAF_SIGNATURES.items():
                        for header, pattern in sigs.get("headers", {}).items():
                            if header in headers and re.search(pattern, headers[header], re.I):
                                self.waf_detected = waf
                                print(f"[+] WAF Detected: {waf} (via header)")
                                return waf
                        if sigs.get("body"):
                            for pattern in (sigs["body"] if isinstance(sigs["body"], list) else [sigs["body"]]):
                                if re.search(pattern, body, re.I):
                                    self.waf_detected = waf
                                    print(f"[+] WAF Detected: {waf} (via body)")
                                    return waf

                    # Generic WAF by status
                    if not self.waf_detected:
                        self.waf_detected = f"Generic WAF (Blocked: {resp.status_code})"
                        print(f"[+] WAF Detected: {self.waf_detected}")
                        return self.waf_detected

            except Exception:
                continue

        self.waf_detected = "None"
        print("[+] No WAF detected")
        return "None"

    def extract_js_endpoints(self):
        """Extract endpoints from JS files - smart spidering"""
        print(f"[*] Extracting JS endpoints...")
        try:
            resp = self.session.get(self.target_url, timeout=self.timeout)
            soup = BeautifulSoup(resp.text, "html.parser")

            # Find all script tags
            js_urls = set()
            for script in soup.find_all("script", src=True):
                js_url = urljoin(self.target_url, script["src"])
                js_urls.add(js_url)
                self.all_js_urls.append(js_url)

            # Find inline JS
            inline_scripts = []
            for script in soup.find_all("script"):
                if script.string:
                    inline_scripts.append(script.string)

            # Also try common JS file names
            for js_file in COMMON_JS_FILES:
                js_url = urljoin(self.target_url, f"/{js_file}")
                js_urls.add(js_url)

            # Fetch and parse all JS files concurrently
            def fetch_js(js_url):
                try:
                    r = self.session.get(js_url, timeout=self.timeout)
                    if r.status_code == 200:
                        return js_url, r.text
                except Exception:
                    pass
                return js_url, None

            with ThreadPoolExecutor(max_workers=self.threads) as executor:
                futures = {executor.submit(fetch_js, url): url for url in js_urls}
                for future in as_completed(futures):
                    js_url, js_content = future.result()
                    if js_content:
                        self._parse_js_content(js_content, js_url)

            # Also parse inline scripts
            for inline in inline_scripts:
                self._parse_js_content(inline)

            if self.all_js_urls:
                print(f"[+] Found {len(self.all_js_urls)} JS files")
            print(f"[+] Extracted {len(self.found_endpoints)} potential endpoints from JS")

        except Exception as e:
            print(f"[!] JS extraction failed: {e}")

    def _parse_js_content(self, content, source_url=""):
        """Parse JS content for API endpoints, routes, and patterns"""
        patterns = [
            r'["\'](/[a-zA-Z0-9_\-./]+)["\']',     # "/api/v1/users"
            r'["\'](/[a-zA-Z0-9_\-./]+\.[a-z]{2,4})["\']',  # "/path/file.js"
            r'url\s*[:=]\s*["\'](/[^"\']+)["\']',   # url: "/api/users"
            r'path\s*[:=]\s*["\'](/[^"\']+)["\']',  # path: "/users/:id"
            r'endpoint\s*[:=]\s*["\'](/[^"\']+)["\']',  # endpoint: '/api'
            r'route\s*[:=]\s*["\'](/[^"\']+)["\']',  # route: '/home'
            r'api\s*[:=]\s*["\'](/[^"\']+)["\']',   # api: '/v2/users'
            r'fetch\(["\'](/[^"\']+)["\']',           # fetch('/api/users')
            r'axios\.\(["\'](/[^"\']+)["\']',          # axios('/api/users')
            r'axios\.get\(["\'](/[^"\']+)["\']',       # axios.get('/api/users')
            r'axios\.post\(["\'](/[^"\']+)["\']',      # axios.post('/api/users')
            r'\$\.ajax\(["\'](/[^"\']+)["\']',         # $.ajax('/api')
            r'\$\.get\(["\'](/[^"\']+)["\']',           # $.get('/api')
            r'\$\.post\(["\'](/[^"\']+)["\']',          # $.post('/api')
            r'XMLHttpRequest\.open\(["\'](?:GET|POST|PUT|DELETE)["\'],\s*["\'](/[^"\']+)["\']',  # XHR
            r'router\.(?:get|post|put|delete|patch|all)\(["\'](/[^"\']+)["\']',  # Express router
            r'apiVersion\s*=\s*["\']([^"\']+)["\']',  # API version strings
            r'controller\s*[:=]\s*["\']([^"\']+)["\']',  # controller names
            r'action\s*[:=]\s*["\']([^"\']+)["\']',   # action names
            r'templateUrl\s*[:=]\s*["\'](/[^"\']+)["\']',  # Angular templates
            r'component\s*[:=]\s*["\']([^"\']+)["\']', # component names
            r'resolver\s*[:=]\s*["\']([^"\']+)["\']',  # resolver paths
        ]

        for pattern in patterns:
            matches = re.findall(pattern, content)
            for m in matches:
                m = m.strip().split("?")[0].split("#")[0]
                if len(m) > 2 and not m.startswith("//"):
                    clean = m.lstrip("/")
                    if clean and clean not in self.found_endpoints:
                        # Filter out common false positives
                        if not any(fp in clean.lower() for fp in
                                   ["http://", "https://", "www.", ".com", ".org", ".net", "javascript:"]):
                            self.found_endpoints.add(clean)

    def find_backups(self):
        """Find backup/config files"""
        print(f"[*] Scanning for backup & config files...")
        domain = urlparse(self.target_url).netloc.replace("www.", "").split(".")[0]

        candidates = []
        for bf in BACKUP_FILES:
            for ext in BACKUP_EXTENSIONS:
                candidates.append(f"/{bf}{ext}")
                candidates.append(f"/{domain}{ext}")
                candidates.append(f"/backup/{bf}{ext}")
                candidates.append(f"/{bf}/{bf}{ext}")

        # Add common config files
        candidates.extend(COMMON_ENDPOINTS)

        def check_path(path):
            try:
                url = f"{self.target_url}{path}"
                resp = self.session.head(url, timeout=3)
                if resp.status_code in (200, 401, 403):
                    self.found_endpoints.add(path.lstrip("/"))
                    return path
                # Some servers don't support HEAD
                if resp.status_code == 405:
                    resp2 = self.session.get(url, timeout=3, stream=True)
                    if resp2.status_code in (200, 401, 403):
                        self.found_endpoints.add(path.lstrip("/"))
                        return path
            except Exception:
                pass
            return None

        checked = 0
        with ThreadPoolExecutor(max_workers=self.threads) as executor:
            futures = {executor.submit(check_path, p): p for p in candidates[:100]}
            for future in as_completed(futures):
                result = future.result()
                checked += 1
                if result:
                    print(f"  [+] Found: {result}")
                if checked % 25 == 0:
                    print(f"  [*] Checked {checked}/{min(len(candidates), 100)}...")

        if len(candidates) > 100:
            print(f"  [*] Plus {len(candidates) - 100} additional paths queued")

    def generate_smart_wordlist(self):
        """Generate smart wordlist based on detected tech"""
        print(f"[*] Generating smart wordlist...")
        tech_keywords = {
            "WordPress": ["wp-admin", "wp-content", "wp-includes", "wp-json", "wp-login",
                         "xmlrpc", "wp-cron", "wp-config", "wp-load", "wp-settings"],
            "Drupal": ["node", "user", "admin", "modules", "sites", "themes", "profiles",
                      "includes", "misc", "scripts"],
            "Joomla": ["administrator", "components", "modules", "plugins", "templates",
                      "language", "images", "media", "cache", "logs"],
            "Laravel": ["storage", "vendor", "public", "resources", "routes", "app",
                       "bootstrap", "config", "database", "artisan"],
            "ASP.NET": ["web.config", "bin", "App_Data", "App_Code", "App_Start",
                       "Content", "Scripts", "Views", "Controllers", "Models"],
            "Django": ["static", "media", "admin", "api", "templates", "settings",
                      "urls", "views", "models", "migrations"],
            "Express": ["routes", "views", "public", "middleware", "controllers",
                       "models", "config", "api", "static", "uploads"],
            "Java/JSP": ["WEB-INF", "META-INF", "classes", "lib", "resources",
                        "templates", "static", "api", "swagger", "actuator"],
            "Kubernetes": ["api", "apis", "healthz", "metrics", "swagger",
                          "openapi", "version", "namespace", "configmap"],
        }

        for tech in self.tech_stack:
            if tech in tech_keywords:
                for kw in tech_keywords[tech]:
                    self.found_endpoints.add(kw)

        # Add common sensitive files for any target
        for ep in COMMON_ENDPOINTS:
            self.found_endpoints.add(ep.lstrip("/"))

    def run_smart_analysis(self):
        """Run full analysis pipeline"""
        print(f"\n{'='*60}")
        print(f"  Smart Analysis: {self.target_url}")
        print(f"{'='*60}\n")

        waf = self.detect_waf()
        self.detect_tech()
        self.generate_smart_wordlist()
        self.extract_js_endpoints()
        # self.find_backups()  # Optionally enable for deeper analysis

        # Deduplicate
        self.found_endpoints = set(
            ep for ep in self.found_endpoints
            if ep and len(ep) > 1 and not ep.startswith("http")
        )

        return {
            "waf": self.waf_detected,
            "cms": self.cms_detected,
            "tech": self.tech_stack,
            "endpoints": sorted(self.found_endpoints),
            "recommended_wordlists": self.recommended_wordlists,
            "js_files": self.all_js_urls,
        }

    def save_analysis(self, output_path="smart_analysis.json"):
        """Save analysis to JSON for Go engine consumption"""
        results = self.run_smart_analysis()
        with open(output_path, "w") as f:
            json.dump(results, f, indent=2)
        print(f"\n[+] Smart analysis saved to: {output_path}")
        print(f"[+] Endpoints discovered: {len(results['endpoints'])}")
        print(f"[+] Tech stack: {len(results['tech'])} items")
        print(f"[+] Recommended categories: {results['recommended_wordlists']}")
        return results


def main():
    parser = argparse.ArgumentParser(description="Smart Analyzer - Deep Recon Engine")
    parser.add_argument("-u", "--url", required=True, help="Target URL")
    parser.add_argument("-o", "--output", default="smart_analysis.json", help="Output file")
    parser.add_argument("-t", "--timeout", type=int, default=10, help="Request timeout")
    parser.add_argument("--threads", type=int, default=10, help="Concurrent threads")
    args = parser.parse_args()

    analyzer = SmartAnalyzer(args.url, timeout=args.timeout, threads=args.threads)
    results = analyzer.save_analysis(args.output)

    # Print summary
    print(f"\n{'='*60}")
    print("  ANALYSIS SUMMARY")
    print(f"{'='*60}")
    print(f"  Target:       {args.url}")
    print(f"  WAF:          {results['waf']}")
    print(f"  CMS:          {results['cms']}")
    print(f"  Tech Stack:   {', '.join(results['tech'][:5])}")
    print(f"  Endpoints:    {len(results['endpoints'])}")
    print(f"  Wordlists:    {', '.join(results['recommended_wordlists'][:5])}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
