local socket = require("socket")
local http = require("socket.http")
local json = require("json")

local plugin = {
    name = "Firewall Detection",
    version = "1.0.0",
    description = "WAF detection (Cloudflare, ModSecurity, AWS WAF), rate limiting analysis, RST pattern analysis, SYN flood protection detection",
    author = "HackIT Team"
}

local waf_signatures = {
    cloudflare = {
        headers = { "cf-ray", "cf-cache-status", "cf-request-id", "cloudflare" },
        body = { "Cloudflare", "Attention Required!", "DDoS protection by Cloudflare", "cf-error-code" },
        cookies = { "__cfduid", "__cf_bm", "cf_clearance" },
        name = "Cloudflare",
        response_code = { 403, 503 }
    },
    modsecurity = {
        headers = { "mod_security", "ModSecurity", "NOYB" },
        body = { "ModSecurity", "This error was generated by Mod_Security", "Not Acceptable" },
        cookies = {},
        name = "ModSecurity",
        response_code = { 403, 406, 501 }
    },
    aws_waf = {
        headers = { "x-amzn-requestid", "x-amzn-waf", "x-amzn-trace-id", "x-amz-cf-id" },
        body = { "AWS WAF", "Request blocked", "403 ERROR" },
        cookies = { "aws-waf-token" },
        name = "AWS WAF",
        response_code = { 403 }
    },
    imperva = {
        headers = { "x-iinfo", "x-cdn", "incapsula" },
        body = { "Incapsula", "_Incapsula_Resource", "Blocked because of" },
        cookies = { "incap_ses", "visid_incap" },
        name = "Imperva/Incapsula",
        response_code = { 403, 509 }
    },
    akamai = {
        headers = { "x-akamai", "x-akamai-transformed", "akamai-ssl" },
        body = { "AkamaiGHost", "Reference #[0-9]+\.[0-9a-f]+" },
        cookies = { "ak_bmsc", "bm_sv", "akavpau_ppsd" },
        name = "Akamai",
        response_code = { 403, 401 }
    },
    f5_bigip = {
        headers = { "x-cnection", "x-application", "bigip", "BIG-IP" },
        body = { "BigIP", "F5 Networks", "TMHS" },
        cookies = { "BIGipServer", "TS" },
        name = "F5 BIG-IP ASM",
        response_code = { 403, 404, 501 }
    },
    sucuri = {
        headers = { "x-sucuri", "x-sucuri-cache", "sucuri" },
        body = { "Sucuri", "cloudproxy", "sucuri.net" },
        cookies = {},
        name = "Sucuri CloudProxy",
        response_code = { 403 }
    },
    barracuda = {
        headers = { "barracuda", "x-barracuda" },
        body = { "Barracuda", "Barracuda Web Filter" },
        cookies = {},
        name = "Barracuda WAF",
        response_code = { 403, 500 }
    },
    wordfence = {
        headers = {},
        body = { "Wordfence", "blocked by Wordfence", "Generated by Wordfence" },
        cookies = { "wfvt" },
        name = "Wordfence (WordPress WAF)",
        response_code = { 403 }
    },
    fortinet = {
        headers = { "x-fortigate", "fortiwaf" },
        body = { "FortiGate", "FortiWeb", "Powered by Fortinet" },
        cookies = {},
        name = "Fortinet FortiWeb",
        response_code = { 403, 404 }
    }
}

local probe_paths = {
    "/etc/passwd",
    "/.git/config",
    "/wp-admin",
    "/admin",
    "/../../etc/passwd",
    "?id=1'%20OR%20'1'='1",
    "/../",
    "/.env",
    "/aws.yml",
    "/server-status",
    "/phpinfo.php",
    "/debug",
    "/console",
    "/actuator",
    "/*",
    "/%00",
    "/..%00",
    "/%2e%2e/",
    "/sql.php",
    "/setup.php",
    "/config.php",
    "/.htaccess",
    "/web.config",
    "/crossdomain.xml",
    "/clientaccesspolicy.xml",
    "/robots.txt",
    "/sitemap.xml"
}

local function fetch_with_headers(target, port, path, use_ssl)
    local url = (use_ssl and "https" or "http") .. "://" .. target
    if (use_ssl and port ~= 443) or (not use_ssl and port ~= 80) then
        url = url .. ":" .. port
    end
    url = url .. path

    local response_body = {}
    local response_headers = {}
    local response_code

    local ok, result = pcall(function()
        local rbody, rcode, rheaders = http.request {
            url = url,
            method = "GET",
            headers = {
                ["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                ["Accept"] = "*/*"
            },
            sink = ltn12.sink.table(response_body),
            redirect = false,
            timeout = 5000
        }
        if rcode then
            response_code = rcode
            response_headers = rheaders or {}
            if rbody then
                table.insert(response_body, rbody)
            end
        end
    end)

    if not ok then return nil, nil, nil end
    return table.concat(response_body), response_code, response_headers
end

local function check_waf(target, port)
    local findings = {}

    for waf_name, waf_sig in pairs(waf_signatures) do
        local detected = false
        local detection_methods = {}

        for _, path in ipairs(probe_paths) do
            local content, code, headers = fetch_with_headers(target, port, path, false)
            if content or code then
                if headers then
                    for _, hdr in ipairs(waf_sig.headers) do
                        if headers[hdr:lower()] then
                            detected = true
                            table.insert(detection_methods, "header:" .. hdr)
                        end
                    end
                end

                if content and #waf_sig.body > 0 then
                    for _, pat in ipairs(waf_sig.body) do
                        if content:find(pat) then
                            detected = true
                            table.insert(detection_methods, "body_pattern:" .. pat)
                        end
                    end
                end

                if code and #waf_sig.response_code > 0 then
                    for _, rc in ipairs(waf_sig.response_code) do
                        if code == rc then
                            detected = true
                            table.insert(detection_methods, "response_code:" .. rc)
                        end
                    end
                end

                if detected then break end
            end
        end

        if detected then
            table.insert(findings, "WAF detected: " .. waf_sig.name .. " (via " .. table.concat(detection_methods, ", ") .. ")")
        end
    end

    return findings
end

local function check_rate_limiting(target, port)
    local findings = {}
    local response_times = {}
    local status_codes = {}

    for i = 1, 20 do
        local start = socket.gettime()
        local content, code, headers = fetch_with_headers(target, port, "/", false)
        local elapsed = (socket.gettime() - start) * 1000
        table.insert(response_times, elapsed)
        if code then table.insert(status_codes, code) end

        if i == 20 and content == nil then
            break
        end
    end

    if #response_times > 1 then
        local total = 0
        for _, t in ipairs(response_times) do table.insert(findings, string.format("Request %d: %.2fms", _, t)) end
        for _, t in ipairs(response_times) do total = total + t end
        local avg = total / #response_times
        table.insert(findings, string.format("Average response time: %.2fms", avg))

        if #response_times >= 20 then
            local last_3 = {response_times[#response_times-2], response_times[#response_times-1], response_times[#response_times]}
            local last_avg = (last_3[1] + last_3[2] + last_3[3]) / 3
            if last_avg > avg * 3 then
                table.insert(findings, "Rate limiting detected: response times increased significantly after repeated requests")
                return findings, true
            end
        end

        if #status_codes >= 5 then
            local last_statuses = {}
            for i = math.max(1, #status_codes - 5), #status_codes do
                table.insert(last_statuses, status_codes[i])
            end
            local count_429 = 0
            for _, sc in ipairs(last_statuses) do
                if sc == 429 then count_429 = count_429 + 1 end
            end
            if count_429 >= 3 then
                table.insert(findings, "HTTP 429 Too Many Requests - rate limiting active")
                return findings, true
            end
        end
    end

    return findings, false
end

local function check_rst_patterns(target, port)
    local findings = {}
    local syn_fail_count = 0
    local test_ports = {1, 7, 13, 19, 37, 80, 443, 8080, 8443}

    for _, test_port in ipairs(test_ports) do
        local ok, err = pcall(function()
            local sock = socket.tcp()
            sock:settimeout(2000)
            local ok_conn, conn_err = sock:connect(target, test_port)
            sock:close()
            return ok_conn
        end)

        if ok == false then
            syn_fail_count = syn_fail_count + 1
        end
    end

    if syn_fail_count == #test_ports then
        table.insert(findings, "All test ports blocked: aggressive firewall likely present")
        return findings, true
    elseif syn_fail_count >= #test_ports * 0.7 then
        table.insert(findings, "Most test ports blocked: firewall detected (" .. syn_fail_count .. "/" .. #test_ports .. " closed)")
        return findings, true
    elseif syn_fail_count > 0 then
        table.insert(findings, "Some ports filtered: firewall may be present (" .. syn_fail_count .. "/" .. #test_ports .. " closed)")
        return findings, false
    end

    return findings, false
end

local function check_syn_flood_protection(target, port)
    local findings = {}
    local completion_times = {}

    for i = 1, 5 do
        local start = socket.gettime()
        local sock = socket.tcp()
        sock:settimeout(3000)
        local ok, err = sock:connect(target, port)
        if ok then
            sock:close()
        end
        local elapsed = (socket.gettime() - start) * 1000
        table.insert(completion_times, elapsed)
    end

    if #completion_times > 0 then
        local avg = 0
        for _, t in ipairs(completion_times) do avg = avg + t end
        avg = avg / #completion_times

        local max = completion_times[1]
        for _, t in ipairs(completion_times) do if t > max then max = t end end
        local min = completion_times[1]
        for _, t in ipairs(completion_times) do if t < min then min = t end end

        table.insert(findings, string.format("TCP connect times (5 probes): min=%.2fms avg=%.2fms max=%.2fms", min, avg, max))

        if max > 2000 and min < 100 then
            table.insert(findings, "Possible SYN flood protection: highly variable connection times (" .. min .. "ms - " .. max .. "ms)")
            return findings, true
        end
    end

    return findings, false
end

function plugin.run(target, port, banner, opts)
    opts = opts or {}
    local findings = {}
    local risk_score = 0

    table.insert(findings, "Firewall/WAF analysis for " .. target .. ":" .. port)

    local waf_findings = check_waf(target, port)
    if #waf_findings > 0 then
        for _, wf in ipairs(waf_findings) do
            table.insert(findings, wf)
            risk_score = math.min(100, risk_score + 20)
        end
    else
        table.insert(findings, "No known WAF detected via passive signatures")
    end

    local rl_findings, rl_detected = check_rate_limiting(target, port)
    for _, rf in ipairs(rl_findings) do
        table.insert(findings, rf)
    end
    if rl_detected then
        risk_score = math.min(100, risk_score + 25)
    end

    local rst_findings, rst_detected = check_rst_patterns(target, port)
    for _, rf in ipairs(rst_findings) do
        table.insert(findings, rf)
    end
    if rst_detected then
        risk_score = math.min(100, risk_score + 15)
    end

    local syn_findings, syn_detected = check_syn_flood_protection(target, port)
    for _, sf in ipairs(syn_findings) do
        table.insert(findings, sf)
    end
    if syn_detected then
        risk_score = math.min(100, risk_score + 10)
    end

    if banner and #banner > 0 then
        table.insert(findings, "Banner: " .. banner:sub(1, 200))
        if banner:find("cloudflare") or banner:find("Cloudflare") then
            table.insert(findings, "Cloudflare detected in banner")
            risk_score = math.min(100, risk_score + 10)
        end
        if banner:find("mod_security") or banner:find("ModSecurity") then
            table.insert(findings, "ModSecurity detected in banner")
            risk_score = math.min(100, risk_score + 10)
        end
    end

    return {
        status = "completed",
        findings = findings,
        risk_score = risk_score
    }
end

return plugin
