"""
Additional public profile sources for HackIt OSINT.

The scanner treats these as public URL probes only. Some services use numeric
IDs instead of usernames, so a miss does not prove absence.
"""

ADDITIONAL_SOURCES = [
    {"name": "GitHub Gist", "category": "Developer", "url": "https://gist.github.com/{username}"},
    {"name": "GitLab Snippets", "category": "Developer", "url": "https://gitlab.com/snippets/{username}"},
    {"name": "Bitbucket Snippets", "category": "Developer", "url": "https://bitbucket.org/snippets/{username}/"},
    {"name": "CodeSandbox", "category": "Developer", "url": "https://codesandbox.io/u/{username}"},
    {"name": "StackBlitz", "category": "Developer", "url": "https://stackblitz.com/@{username}"},
    {"name": "JSFiddle", "category": "Developer", "url": "https://jsfiddle.net/user/{username}/"},
    {"name": "Glitch", "category": "Developer", "url": "https://glitch.com/@{username}"},
    {"name": "ObservableHQ", "category": "Developer", "url": "https://observablehq.com/@{username}"},
    {"name": "HackerRank", "category": "Developer", "url": "https://www.hackerrank.com/{username}"},
    {"name": "CodeChef", "category": "Developer", "url": "https://www.codechef.com/users/{username}"},
    {"name": "SPOJ", "category": "Developer", "url": "https://www.spoj.com/users/{username}/"},
    {"name": "AtCoder", "category": "Developer", "url": "https://atcoder.jp/users/{username}"},
    {"name": "Coderbyte", "category": "Developer", "url": "https://coderbyte.com/profile/{username}"},
    {"name": "Codewars", "category": "Developer", "url": "https://www.codewars.com/users/{username}"},
    {"name": "Exercism", "category": "Developer", "url": "https://exercism.org/profiles/{username}"},
    {"name": "CodinGame", "category": "Developer", "url": "https://www.codingame.com/profile/{username}"},
    {"name": "HackerEarth", "category": "Developer", "url": "https://www.hackerearth.com/@{username}"},
    {"name": "Rosalind", "category": "Developer", "url": "http://rosalind.info/users/{username}/"},
    {"name": "DMOJ", "category": "Developer", "url": "https://dmoj.ca/user/{username}"},
    {"name": "Kattis", "category": "Developer", "url": "https://open.kattis.com/users/{username}"},
    {"name": "OverTheWire", "category": "Security", "url": "https://overthewire.org/profiles/{username}"},
    {"name": "HackThisSite", "category": "Security", "url": "https://www.hackthissite.org/user/view/{username}"},
    {"name": "CyberDefenders", "category": "Security", "url": "https://cyberdefenders.org/p/{username}"},
    {"name": "LetsDefend", "category": "Security", "url": "https://letsdefend.io/user/{username}"},
    {"name": "Blue Team Labs Online", "category": "Security", "url": "https://blueteamlabs.online/user/{username}"},
    {"name": "PicoCTF", "category": "Security", "url": "https://play.picoctf.org/users/{username}"},
    {"name": "BugBase", "category": "Security", "url": "https://bugbase.in/user/{username}"},
    {"name": "Vero", "category": "Social", "url": "https://www.vero.co/{username}"},
    {"name": "Parler", "category": "Social", "url": "https://parler.com/profile/{username}"},
    {"name": "Gettr", "category": "Social", "url": "https://gettr.com/user/{username}"},
    {"name": "MeWe", "category": "Social", "url": "https://mewe.com/i/{username}"},
    {"name": "Minds", "category": "Social", "url": "https://www.minds.com/{username}/"},
    {"name": "Gab", "category": "Social", "url": "https://gab.com/{username}"},
    {"name": "WT Social", "category": "Social", "url": "https://wt.social/wt/{username}"},
    {"name": "Ello", "category": "Social", "url": "https://ello.co/{username}"},
    {"name": "Pillowfort", "category": "Social", "url": "https://www.pillowfort.social/{username}"},
    {"name": "Steemit", "category": "Social", "url": "https://steemit.com/@{username}"},
    {"name": "Hive Blog", "category": "Social", "url": "https://hive.blog/@{username}"},
    {"name": "PeakD", "category": "Social", "url": "https://peakd.com/@{username}"},
    {"name": "Ecency", "category": "Social", "url": "https://ecency.com/@{username}"},
    {"name": "Odysee", "category": "Social", "url": "https://odysee.com/@{username}"},
    {"name": "Rumble", "category": "Social", "url": "https://rumble.com/user/{username}"},
    {"name": "BitChute", "category": "Social", "url": "https://www.bitchute.com/channel/{username}/"},
    {"name": "QQ", "category": "Regional", "url": "https://user.qzone.qq.com/{username}"},
    {"name": "Baidu Tieba", "category": "Regional", "url": "https://tieba.baidu.com/home/main?un={username}"},
    {"name": "Douban", "category": "Regional", "url": "https://www.douban.com/people/{username}/"},
    {"name": "Zhihu", "category": "Regional", "url": "https://www.zhihu.com/people/{username}"},
    {"name": "Xiaohongshu", "category": "Regional", "url": "https://www.xiaohongshu.com/user/profile/{username}"},
    {"name": "Bilibili", "category": "Regional", "url": "https://space.bilibili.com/{username}"},
    {"name": "Douyin", "category": "Regional", "url": "https://www.douyin.com/user/{username}"},
    {"name": "Naver Blog", "category": "Regional", "url": "https://blog.naver.com/{username}"},
    {"name": "KakaoStory", "category": "Regional", "url": "https://story.kakao.com/{username}"},
    {"name": "Line", "category": "Regional", "url": "https://line.me/ti/p/{username}"},
    {"name": "Zalo", "category": "Regional", "url": "https://zalo.me/{username}"},
    {"name": "Ameba", "category": "Regional", "url": "https://profile.ameba.jp/ameba/{username}"},
    {"name": "Hatena Blog", "category": "Regional", "url": "https://{username}.hatenablog.com/"},
    {"name": "Note", "category": "Regional", "url": "https://note.com/{username}"},
    {"name": "Pixiv", "category": "Regional", "url": "https://www.pixiv.net/users/{username}"},
    {"name": "TwitCasting", "category": "Regional", "url": "https://twitcasting.tv/{username}"},
    {"name": "LiveJournal", "category": "Regional", "url": "https://{username}.livejournal.com/"},
    {"name": "Yandex Zen", "category": "Regional", "url": "https://zen.yandex.ru/{username}"},
    {"name": "Rutube", "category": "Regional", "url": "https://rutube.ru/channel/{username}/"},
    {"name": "TamTam", "category": "Regional", "url": "https://tamtam.chat/{username}"},
    {"name": "Taringa", "category": "Regional", "url": "https://www.taringa.net/{username}"},
    {"name": "Hi5", "category": "Social", "url": "https://hi5.com/{username}"},
    {"name": "Badoo", "category": "Social", "url": "https://badoo.com/profile/{username}"},
    {"name": "Hacker News", "category": "Forum", "url": "https://news.ycombinator.com/user?id={username}"},
    {"name": "Lobsters", "category": "Forum", "url": "https://lobste.rs/~{username}"},
    {"name": "Slashdot", "category": "Forum", "url": "https://slashdot.org/~{username}"},
    {"name": "MacRumors", "category": "Forum", "url": "https://forums.macrumors.com/members/{username}/"},
    {"name": "NeoGAF", "category": "Forum", "url": "https://www.neogaf.com/members/{username}/"},
    {"name": "ResetEra", "category": "Forum", "url": "https://www.resetera.com/members/{username}/"},
    {"name": "TechPowerUp", "category": "Forum", "url": "https://www.techpowerup.com/forums/members/{username}/"},
    {"name": "Linus Tech Tips", "category": "Forum", "url": "https://linustechtips.com/profile/{username}/"},
    {"name": "Quora", "category": "Forum", "url": "https://www.quora.com/profile/{username}"},
    {"name": "Substack", "category": "Blog", "url": "https://{username}.substack.com/"},
    {"name": "Ghost", "category": "Blog", "url": "https://{username}.ghost.io/"},
    {"name": "Jekyll Pages", "category": "Blog", "url": "https://{username}.github.io/"},
    {"name": "Write.as", "category": "Blog", "url": "https://write.as/{username}/"},
    {"name": "Speaker Deck", "category": "Blog", "url": "https://speakerdeck.com/{username}"},
    {"name": "Issuu", "category": "Blog", "url": "https://issuu.com/{username}"},
    {"name": "DeviantArt", "category": "Design", "url": "https://www.deviantart.com/{username}"},
    {"name": "ArtStation", "category": "Design", "url": "https://www.artstation.com/{username}"},
    {"name": "Pexels", "category": "Media", "url": "https://www.pexels.com/@{username}/"},
    {"name": "Pixabay", "category": "Media", "url": "https://pixabay.com/users/{username}/"},
    {"name": "Imgur", "category": "Media", "url": "https://imgur.com/user/{username}"},
    {"name": "VSCO", "category": "Media", "url": "https://vsco.co/{username}/"},
    {"name": "EyeEm", "category": "Media", "url": "https://www.eyeem.com/u/{username}"},
    {"name": "Vimeo", "category": "Media", "url": "https://vimeo.com/{username}"},
    {"name": "Dailymotion", "category": "Media", "url": "https://www.dailymotion.com/{username}"},
    {"name": "DLive", "category": "Media", "url": "https://dlive.tv/{username}"},
    {"name": "Trovo", "category": "Media", "url": "https://trovo.live/{username}"},
    {"name": "Discogs", "category": "Music", "url": "https://www.discogs.com/user/{username}"},
    {"name": "Audiomack", "category": "Music", "url": "https://audiomack.com/{username}"},
    {"name": "ReverbNation", "category": "Music", "url": "https://www.reverbnation.com/{username}"},
    {"name": "BandLab", "category": "Music", "url": "https://www.bandlab.com/{username}"},
    {"name": "Splice", "category": "Music", "url": "https://splice.com/{username}"},
    {"name": "Genius", "category": "Music", "url": "https://genius.com/{username}"},
    {"name": "Apple Music", "category": "Music", "url": "https://music.apple.com/profile/{username}"},
    {"name": "Deezer", "category": "Music", "url": "https://www.deezer.com/user/{username}"},
    {"name": "GOG", "category": "Gaming", "url": "https://www.gog.com/u/{username}"},
    {"name": "Game Jolt", "category": "Gaming", "url": "https://gamejolt.com/@{username}"},
    {"name": "Nexus Mods", "category": "Gaming", "url": "https://www.nexusmods.com/users/{username}"},
    {"name": "Planet Minecraft", "category": "Gaming", "url": "https://www.planetminecraft.com/member/{username}/"},
    {"name": "LibraryThing", "category": "Books", "url": "https://www.librarything.com/profile/{username}"},
    {"name": "BookWyrm", "category": "Books", "url": "https://bookwyrm.social/user/{username}"},
    {"name": "The StoryGraph", "category": "Books", "url": "https://app.thestorygraph.com/profile/{username}"},
    {"name": "Xing", "category": "Professional", "url": "https://www.xing.com/profile/{username}"},
    {"name": "ResearchGate", "category": "Professional", "url": "https://www.researchgate.net/profile/{username}"},
    {"name": "Academia.edu", "category": "Professional", "url": "https://independent.academia.edu/{username}"},
    {"name": "AngelList", "category": "Professional", "url": "https://angel.co/u/{username}"},
    {"name": "PeoplePerHour", "category": "Freelance", "url": "https://www.peopleperhour.com/freelancer/{username}"},
    {"name": "Guru", "category": "Freelance", "url": "https://www.guru.com/freelancers/{username}"},
    {"name": "99designs", "category": "Freelance", "url": "https://99designs.com/profiles/{username}"},
    {"name": "Coursera", "category": "Education", "url": "https://www.coursera.org/user/{username}"},
    {"name": "Udemy", "category": "Education", "url": "https://www.udemy.com/user/{username}/"},
    {"name": "Skillshare", "category": "Education", "url": "https://www.skillshare.com/user/{username}"},
    {"name": "Khan Academy", "category": "Education", "url": "https://www.khanacademy.org/profile/{username}/"},
    {"name": "Quizlet", "category": "Education", "url": "https://quizlet.com/{username}"},
    {"name": "DataCamp", "category": "Education", "url": "https://www.datacamp.com/profile/{username}"},
    {"name": "Fitbit", "category": "Fitness", "url": "https://www.fitbit.com/user/{username}"},
    {"name": "Runkeeper", "category": "Fitness", "url": "https://runkeeper.com/user/{username}"},
    {"name": "MyFitnessPal", "category": "Fitness", "url": "https://www.myfitnesspal.com/profile/{username}"},
    {"name": "Garmin Connect", "category": "Fitness", "url": "https://connect.garmin.com/modern/profile/{username}"},
    {"name": "Untappd", "category": "Food", "url": "https://untappd.com/user/{username}"},
    {"name": "Vivino", "category": "Food", "url": "https://www.vivino.com/users/{username}"},
    {"name": "Allrecipes", "category": "Food", "url": "https://www.allrecipes.com/cook/{username}/"},
    {"name": "Couchsurfing", "category": "Travel", "url": "https://www.couchsurfing.com/people/{username}"},
    {"name": "Foursquare", "category": "Travel", "url": "https://foursquare.com/{username}"},
    {"name": "Komoot", "category": "Travel", "url": "https://www.komoot.com/user/{username}"},
    {"name": "Etsy", "category": "Shopping", "url": "https://www.etsy.com/people/{username}"},
    {"name": "eBay", "category": "Shopping", "url": "https://www.ebay.com/usr/{username}"},
    {"name": "Poshmark", "category": "Shopping", "url": "https://poshmark.com/closet/{username}"},
    {"name": "Depop", "category": "Shopping", "url": "https://www.depop.com/{username}/"},
    {"name": "Mercari", "category": "Shopping", "url": "https://www.mercari.com/u/{username}/"},
    {"name": "Liberapay", "category": "Creator", "url": "https://liberapay.com/{username}/"},
    {"name": "GitHub Sponsors", "category": "Creator", "url": "https://github.com/sponsors/{username}"},
    {"name": "Open Collective", "category": "Creator", "url": "https://opencollective.com/{username}"},
    {"name": "Kickstarter", "category": "Creator", "url": "https://www.kickstarter.com/profile/{username}"},
    {"name": "Indiegogo", "category": "Creator", "url": "https://www.indiegogo.com/individuals/{username}"},
    {"name": "Rarible", "category": "Crypto", "url": "https://rarible.com/{username}"},
    {"name": "SuperRare", "category": "Crypto", "url": "https://superrare.com/{username}"},
    {"name": "Zora", "category": "Crypto", "url": "https://zora.co/@{username}"},
    {"name": "TradingView", "category": "Crypto", "url": "https://www.tradingview.com/u/{username}/"},
    {"name": "StockTwits", "category": "Crypto", "url": "https://stocktwits.com/{username}"},
    {"name": "Flipboard", "category": "News", "url": "https://flipboard.com/@{username}"},
    {"name": "Mix", "category": "News", "url": "https://mix.com/{username}"},
    {"name": "Digg", "category": "News", "url": "https://digg.com/@{username}"},
    {"name": "Diigo", "category": "News", "url": "https://www.diigo.com/profile/{username}"},
    {"name": "Instructables", "category": "DIY", "url": "https://www.instructables.com/member/{username}/"},
    {"name": "Thingiverse", "category": "DIY", "url": "https://www.thingiverse.com/{username}/designs"},
    {"name": "Hackaday.io", "category": "DIY", "url": "https://hackaday.io/{username}"},
    {"name": "Hackster.io", "category": "DIY", "url": "https://www.hackster.io/{username}"},
    {"name": "BoardGameGeek", "category": "Hobby", "url": "https://boardgamegeek.com/user/{username}"},
    {"name": "Anime-Planet", "category": "Hobby", "url": "https://www.anime-planet.com/users/{username}"},
    {"name": "MyDramaList", "category": "Hobby", "url": "https://mydramalist.com/profile/{username}"},
    {"name": "Trakt", "category": "Hobby", "url": "https://trakt.tv/users/{username}"},
    {"name": "Kitsu", "category": "Hobby", "url": "https://kitsu.io/users/{username}"},
    {"name": "MangaDex", "category": "Hobby", "url": "https://mangadex.org/user/{username}"},
    {"name": "Trello", "category": "Productivity", "url": "https://trello.com/{username}"},
    {"name": "Calendly", "category": "Productivity", "url": "https://calendly.com/{username}"},
    {"name": "IFTTT", "category": "Automation", "url": "https://ifttt.com/p/{username}"},
    {"name": "Bento.me", "category": "Identity", "url": "https://bento.me/{username}"},
    {"name": "Bio.fm", "category": "Identity", "url": "https://bio.fm/{username}"},
    {"name": "Campsite.bio", "category": "Identity", "url": "https://campsite.bio/{username}"},
    {"name": "Beacons", "category": "Identity", "url": "https://beacons.ai/{username}"},
    {"name": "Solo.to", "category": "Identity", "url": "https://solo.to/{username}"},
    {"name": "Lnk.Bio", "category": "Identity", "url": "https://lnk.bio/{username}"},
    {"name": "Kaskus", "category": "Forum", "url": "https://www.kaskus.co.id/@{username}"},
]

