SOCIAL_SOURCES = [
    {"name": "GitHub", "category": "Developer", "url": "https://github.com/{username}"},
    {"name": "GitLab", "category": "Developer", "url": "https://gitlab.com/{username}"},
    {"name": "Bitbucket", "category": "Developer", "url": "https://bitbucket.org/{username}"},
    {"name": "Stack Overflow", "category": "Developer", "url": "https://stackoverflow.com/users/{username}"},
    {"name": "HackerOne", "category": "Security", "url": "https://hackerone.com/{username}"},
    {"name": "Bugcrowd", "category": "Security", "url": "https://bugcrowd.com/{username}"},
    {"name": "Keybase", "category": "Identity", "url": "https://keybase.io/{username}"},
    {"name": "Twitter/X", "category": "Social", "url": "https://x.com/{username}"},
    {"name": "Instagram", "category": "Social", "url": "https://www.instagram.com/{username}/"},
    {"name": "TikTok", "category": "Social", "url": "https://www.tiktok.com/@{username}"},
    {"name": "Facebook", "category": "Social", "url": "https://www.facebook.com/{username}"},
    {"name": "Threads", "category": "Social", "url": "https://www.threads.net/@{username}"},
    {"name": "Reddit", "category": "Forum", "url": "https://www.reddit.com/user/{username}"},
    {"name": "Pinterest", "category": "Social", "url": "https://www.pinterest.com/{username}/"},
    {"name": "Tumblr", "category": "Blog", "url": "https://{username}.tumblr.com/"},
    {"name": "Medium", "category": "Blog", "url": "https://medium.com/@{username}"},
    {"name": "Dev.to", "category": "Developer", "url": "https://dev.to/{username}"},
    {"name": "Hashnode", "category": "Developer", "url": "https://hashnode.com/@{username}"},
    {"name": "Product Hunt", "category": "Startup", "url": "https://www.producthunt.com/@{username}"},
    {"name": "Kaggle", "category": "Data", "url": "https://www.kaggle.com/{username}"},
    {"name": "Replit", "category": "Developer", "url": "https://replit.com/@{username}"},
    {"name": "CodePen", "category": "Developer", "url": "https://codepen.io/{username}"},
    {"name": "npm", "category": "Developer", "url": "https://www.npmjs.com/~{username}"},
    {"name": "PyPI", "category": "Developer", "url": "https://pypi.org/user/{username}/"},
    {"name": "Docker Hub", "category": "Developer", "url": "https://hub.docker.com/u/{username}"},
    {"name": "TryHackMe", "category": "Security", "url": "https://tryhackme.com/p/{username}"},
    {"name": "Hack The Box", "category": "Security", "url": "https://app.hackthebox.com/profile/{username}"},
    {"name": "Root Me", "category": "Security", "url": "https://www.root-me.org/{username}"},
    {"name": "CTFtime", "category": "Security", "url": "https://ctftime.org/user/{username}"},
    {"name": "YouTube", "category": "Media", "url": "https://www.youtube.com/@{username}"},
    {"name": "Twitch", "category": "Media", "url": "https://www.twitch.tv/{username}"},
    {"name": "SoundCloud", "category": "Media", "url": "https://soundcloud.com/{username}"},
    {"name": "Spotify", "category": "Media", "url": "https://open.spotify.com/user/{username}"},
    {"name": "Steam", "category": "Gaming", "url": "https://steamcommunity.com/id/{username}"},
    {"name": "Roblox", "category": "Gaming", "url": "https://www.roblox.com/user.aspx?username={username}"},
    {"name": "Chess.com", "category": "Gaming", "url": "https://www.chess.com/member/{username}"},
    {"name": "Lichess", "category": "Gaming", "url": "https://lichess.org/@/{username}"},
    {"name": "Dribbble", "category": "Design", "url": "https://dribbble.com/{username}"},
    {"name": "Behance", "category": "Design", "url": "https://www.behance.net/{username}"},
    {"name": "Flickr", "category": "Media", "url": "https://www.flickr.com/people/{username}/"},
    {"name": "About.me", "category": "Identity", "url": "https://about.me/{username}"},
    {"name": "LinkedIn", "category": "Professional", "url": "https://www.linkedin.com/in/{username}/"},
    {"name": "Mastodon.social", "category": "Social", "url": "https://mastodon.social/@{username}"},
    {"name": "Mastodon.online", "category": "Social", "url": "https://mastodon.online/@{username}"},
    {"name": "Bluesky", "category": "Social", "url": "https://bsky.app/profile/{username}"},
    {"name": "VK", "category": "Social", "url": "https://vk.com/{username}"},
    {"name": "OK.ru", "category": "Social", "url": "https://ok.ru/{username}"},
    {"name": "Weibo", "category": "Social", "url": "https://weibo.com/{username}"},
    {"name": "Telegram", "category": "Messaging", "url": "https://t.me/{username}"},
    {"name": "Snapchat", "category": "Social", "url": "https://www.snapchat.com/add/{username}"},
    {"name": "WhatsApp", "category": "Messaging", "url": "https://wa.me/{username}"},
    {"name": "Signal", "category": "Messaging", "url": "https://signal.me/{username}"},
    {"name": "Discord", "category": "Messaging", "url": "https://discord.com/users/{username}"},
    {"name": "Slack", "category": "Messaging", "url": "https://{username}.slack.com/"},
    {"name": "Blogger", "category": "Blog", "url": "https://{username}.blogspot.com/"},
    {"name": "WordPress", "category": "Blog", "url": "https://{username}.wordpress.com/"},
    {"name": "Wattpad", "category": "Writing", "url": "https://www.wattpad.com/user/{username}"},
    {"name": "Goodreads", "category": "Books", "url": "https://www.goodreads.com/{username}"},
    {"name": "Letterboxd", "category": "Media", "url": "https://letterboxd.com/{username}/"},
    {"name": "Unsplash", "category": "Media", "url": "https://unsplash.com/@{username}"},
    {"name": "500px", "category": "Media", "url": "https://500px.com/p/{username}"},
    {"name": "Bandcamp", "category": "Music", "url": "https://bandcamp.com/{username}"},
    {"name": "BuyMeACoffee", "category": "Creator", "url": "https://www.buymeacoffee.com/{username}"},
    {"name": "Patreon", "category": "Creator", "url": "https://www.patreon.com/{username}"},
    {"name": "Ko-fi", "category": "Creator", "url": "https://ko-fi.com/{username}"},
    {"name": "Linktree", "category": "Identity", "url": "https://linktr.ee/{username}"},
    {"name": "Carrd", "category": "Identity", "url": "https://{username}.carrd.co/"},
    {"name": "OnlyFans", "category": "Creator", "url": "https://onlyfans.com/{username}"},
    {"name": "Fiverr", "category": "Freelance", "url": "https://www.fiverr.com/{username}"},
    {"name": "Freelancer", "category": "Freelance", "url": "https://www.freelancer.com/u/{username}"},
    {"name": "Upwork", "category": "Freelance", "url": "https://www.upwork.com/freelancers/~{username}"},
    {"name": "Cracked.io", "category": "Forum", "url": "https://cracked.io/{username}"},
    {"name": "HackForums", "category": "Forum", "url": "https://hackforums.net/member.php?action=profile&uid={username}"},
    {"name": "MyAnimeList", "category": "Media", "url": "https://myanimelist.net/profile/{username}"},
    {"name": "AniList", "category": "Media", "url": "https://anilist.co/user/{username}/"},
    {"name": "Duolingo", "category": "Education", "url": "https://www.duolingo.com/profile/{username}"},
    {"name": "Codecademy", "category": "Education", "url": "https://www.codecademy.com/profiles/{username}"},
    {"name": "LeetCode", "category": "Developer", "url": "https://leetcode.com/{username}/"},
    {"name": "Codeforces", "category": "Developer", "url": "https://codeforces.com/profile/{username}"},
    {"name": "Topcoder", "category": "Developer", "url": "https://www.topcoder.com/members/{username}"},
    {"name": "CodeChef", "category": "Developer", "url": "https://www.codechef.com/users/{username}"},
    {"name": "HackerRank", "category": "Developer", "url": "https://www.hackerrank.com/{username}"},
    {"name": "Hugging Face", "category": "AI", "url": "https://huggingface.co/{username}"},
    {"name": "OpenSea", "category": "Crypto", "url": "https://opensea.io/{username}"},
    {"name": "Foundation", "category": "Crypto", "url": "https://foundation.app/@{username}"},
    {"name": "TripAdvisor", "category": "Travel", "url": "https://www.tripadvisor.com/Profile/{username}"},
    {"name": "Strava", "category": "Fitness", "url": "https://www.strava.com/athletes/{username}"},
    {"name": "GitLab Snippets", "category": "Developer", "url": "https://gitlab.com/snippets/{username}"},
    {"name": "Bitbucket Snippets", "category": "Developer", "url": "https://bitbucket.org/snippets/{username}/"},
    {"name": "CodeSandbox", "category": "Developer", "url": "https://codesandbox.io/u/{username}"},
    {"name": "StackBlitz", "category": "Developer", "url": "https://stackblitz.com/@{username}"},
    {"name": "JSFiddle", "category": "Developer", "url": "https://jsfiddle.net/user/{username}/"},
    {"name": "Glitch", "category": "Developer", "url": "https://glitch.com/@{username}"},
    {"name": "ObservableHQ", "category": "Developer", "url": "https://observablehq.com/@{username}"},
    {"name": "SPOJ", "category": "Developer", "url": "https://www.spoj.com/users/{username}/"},
    {"name": "AtCoder", "category": "Developer", "url": "https://atcoder.jp/users/{username}"},
    {"name": "Coderbyte", "category": "Developer", "url": "https://coderbyte.com/profile/{username}"},
    {"name": "Codewars", "category": "Developer", "url": "https://www.codewars.com/users/{username}"},
    {"name": "Exercism", "category": "Developer", "url": "https://exercism.org/profiles/{username}"},
    {"name": "CodinGame", "category": "Developer", "url": "https://www.codingame.com/profile/{username}"},
    {"name": "HackerEarth", "category": "Developer", "url": "https://www.hackerearth.com/@{username}"},
    {"name": "Rosalind", "category": "Developer", "url": "http://rosalind.info/users/{username}/"},
    {"name": "DMOJ", "category": "Developer", "url": "https://dmoj.ca/user/{username}"},
    {"name": "Kattis", "category": "Developer", "url": "https://open.kattis.com/users/{username}"},
    {"name": "GeeksforGeeks", "category": "Developer", "url": "https://auth.geeksforgeeks.org/user/{username}/"},
    {"name": "InterviewBit", "category": "Developer", "url": "https://www.interviewbit.com/profile/{username}"},
    {"name": "SourceForge", "category": "Developer", "url": "https://sourceforge.net/u/{username}"},
    {"name": "Launchpad", "category": "Developer", "url": "https://launchpad.net/~{username}"},
    {"name": "OverTheWire", "category": "Security", "url": "https://overthewire.org/profiles/{username}"},
    {"name": "HackThisSite", "category": "Security", "url": "https://www.hackthissite.org/user/view/{username}"},
    {"name": "CyberDefenders", "category": "Security", "url": "https://cyberdefenders.org/p/{username}"},
    {"name": "LetsDefend", "category": "Security", "url": "https://letsdefend.io/user/{username}"},
    {"name": "Blue Team Labs Online", "category": "Security", "url": "https://blueteamlabs.online/user/{username}"},
    {"name": "PicoCTF", "category": "Security", "url": "https://play.picoctf.org/users/{username}"},
    {"name": "BugBase", "category": "Security", "url": "https://bugbase.in/user/{username}"},
    {"name": "VulnHub", "category": "Security", "url": "https://www.vulnhub.com/author/{username}"},
    {"name": "PentesterLab", "category": "Security", "url": "https://pentesterlab.com/profile/{username}"},
    {"name": "RingZer0", "category": "Security", "url": "https://ringzer0ctf.com/profile/{username}"},
    {"name": "WeChall", "category": "Security", "url": "https://www.wechall.net/profile/{username}"},
    {"name": "Enigmagroup", "category": "Security", "url": "https://www.enigmagroup.org/profile/{username}"},
    {"name": "NewbieContest", "category": "Security", "url": "https://www.newbiecontest.net/index.php?page=profile&id={username}"},
    {"name": "Vero", "category": "Social", "url": "https://www.vero.co/{username}"},
    {"name": "Parler", "category": "Social", "url": "https://parler.com/profile/{username}"},
    {"name": "Gettr", "category": "Social", "url": "https://gettr.com/user/{username}"},
    {"name": "MeWe", "category": "Social", "url": "https://mewe.com/i/{username}"},
    {"name": "Minds", "category": "Social", "url": "https://www.minds.com/{username}/"},
    {"name": "Gab", "category": "Social", "url": "https://gab.com/{username}"},
    {"name": "WT Social", "category": "Social", "url": "https://wt.social/user/{username}"},
    {"name": "Ello", "category": "Social", "url": "https://ello.co/{username}"},
    {"name": "Pillowfort", "category": "Social", "url": "https://www.pillowfort.social/{username}"},
    {"name": "Steemit", "category": "Social", "url": "https://steemit.com/@{username}"},
    {"name": "Hive Blog", "category": "Social", "url": "https://hive.blog/@{username}"},
    {"name": "PeakD", "category": "Social", "url": "https://peakd.com/@{username}"},
    {"name": "Ecency", "category": "Social", "url": "https://ecency.com/@{username}"},
    {"name": "Odysee", "category": "Social", "url": "https://odysee.com/@{username}"},
    {"name": "Rumble", "category": "Social", "url": "https://rumble.com/user/{username}"},
    {"name": "BitChute", "category": "Social", "url": "https://www.bitchute.com/channel/{username}/"},
    {"name": "DTube", "category": "Social", "url": "https://d.tube/#!/c/{username}"},
    {"name": "3Speak", "category": "Social", "url": "https://3speak.tv/user/{username}"},
    {"name": "LBRY", "category": "Social", "url": "https://lbry.tv/@{username}"},
    {"name": "PeerTube", "category": "Social", "url": "https://peertube.tv/accounts/{username}"},
    {"name": "QQ", "category": "Regional", "url": "https://user.qzone.qq.com/{username}"},
    {"name": "Baidu Tieba", "category": "Regional", "url": "https://tieba.baidu.com/home/main?un={username}"},
    {"name": "Douban", "category": "Regional", "url": "https://www.douban.com/people/{username}/"},
    {"name": "Zhihu", "category": "Regional", "url": "https://www.zhihu.com/people/{username}"},
    {"name": "Xiaohongshu", "category": "Regional", "url": "https://www.xiaohongshu.com/user/profile/{username}"},
    {"name": "Bilibili", "category": "Regional", "url": "https://space.bilibili.com/{username}"},
    {"name": "Douyin", "category": "Regional", "url": "https://www.douyin.com/user/{username}"},
    {"name": "Naver Blog", "category": "Regional", "url": "https://blog.naver.com/{username}"},
    {"name": "KakaoStory", "category": "Regional", "url": "https://story.kakao.com/{username}"},
    {"name": "KakaoTalk", "category": "Regional", "url": "https://open.kakao.com/o/{username}"},
    {"name": "Line", "category": "Regional", "url": "https://line.me/ti/p/{username}"},
    {"name": "Zalo", "category": "Regional", "url": "https://zalo.me/{username}"},
    {"name": "Ameba", "category": "Regional", "url": "https://profile.ameba.jp/ameba/{username}"},
    {"name": "Hatena Blog", "category": "Regional", "url": "https://{username}.hatenablog.com/"},
    {"name": "Note", "category": "Regional", "url": "https://note.com/{username}"},
    {"name": "Pixiv", "category": "Regional", "url": "https://www.pixiv.net/users/{username}"},
    {"name": "TwitCasting", "category": "Regional", "url": "https://twitcasting.tv/{username}"},
    {"name": "LiveJournal", "category": "Regional", "url": "https://{username}.livejournal.com/"},
    {"name": "Yandex Zen", "category": "Regional", "url": "https://zen.yandex.ru/{username}"},
    {"name": "Yandex Music", "category": "Regional", "url": "https://music.yandex.ru/users/{username}/"},
    {"name": "Rutube", "category": "Regional", "url": "https://rutube.ru/channel/{username}/"},
    {"name": "TamTam", "category": "Regional", "url": "https://tamtam.chat/{username}"},
    {"name": "Taringa", "category": "Regional", "url": "https://www.taringa.net/{username}"},
    {"name": "Hi5", "category": "Social", "url": "https://hi5.com/{username}"},
    {"name": "Badoo", "category": "Social", "url": "https://badoo.com/en/{username}"},
    {"name": "Hacker News", "category": "Forum", "url": "https://news.ycombinator.com/user?id={username}"},
    {"name": "Lobsters", "category": "Forum", "url": "https://lobste.rs/~{username}"},
    {"name": "Slashdot", "category": "Forum", "url": "https://slashdot.org/~{username}"},
    {"name": "MacRumors", "category": "Forum", "url": "https://forums.macrumors.com/members/{username}/"},
    {"name": "NeoGAF", "category": "Forum", "url": "https://www.neogaf.com/members/{username}/"},
    {"name": "ResetEra", "category": "Forum", "url": "https://www.resetera.com/members/{username}/"},
    {"name": "TechPowerUp", "category": "Forum", "url": "https://www.techpowerup.com/forums/members/{username}/"},
    {"name": "Linus Tech Tips", "category": "Forum", "url": "https://linustechtips.com/profile/{username}/"},
    {"name": "Quora", "category": "Forum", "url": "https://www.quora.com/profile/{username}"},
    {"name": "Substack", "category": "Blog", "url": "https://{username}.substack.com/"},
    {"name": "Ghost", "category": "Blog", "url": "https://{username}.ghost.io/"},
    {"name": "Jekyll Pages", "category": "Blog", "url": "https://{username}.github.io/"},
    {"name": "Write.as", "category": "Blog", "url": "https://write.as/{username}/"},
    {"name": "Speaker Deck", "category": "Blog", "url": "https://speakerdeck.com/{username}"},
    {"name": "Issuu", "category": "Blog", "url": "https://issuu.com/{username}"},
    {"name": "DeviantArt", "category": "Design", "url": "https://www.deviantart.com/{username}"},
    {"name": "ArtStation", "category": "Design", "url": "https://www.artstation.com/{username}"},
    {"name": "Pexels", "category": "Media", "url": "https://www.pexels.com/@{username}/"},
    {"name": "Pixabay", "category": "Media", "url": "https://pixabay.com/users/{username}/"},
    {"name": "Imgur", "category": "Media", "url": "https://imgur.com/user/{username}"},
    {"name": "VSCO", "category": "Media", "url": "https://vsco.co/{username}/"},
    {"name": "EyeEm", "category": "Media", "url": "https://www.eyeem.com/u/{username}"},
    {"name": "Vimeo", "category": "Media", "url": "https://vimeo.com/{username}"},
    {"name": "Dailymotion", "category": "Media", "url": "https://www.dailymotion.com/{username}"},
    {"name": "DLive", "category": "Media", "url": "https://dlive.tv/{username}"},
    {"name": "Trovo", "category": "Media", "url": "https://trovo.live/{username}"},
    {"name": "Discogs", "category": "Music", "url": "https://www.discogs.com/user/{username}"},
    {"name": "Audiomack", "category": "Music", "url": "https://audiomack.com/{username}"},
    {"name": "ReverbNation", "category": "Music", "url": "https://www.reverbnation.com/{username}"},
    {"name": "BandLab", "category": "Music", "url": "https://www.bandlab.com/{username}"},
    {"name": "Splice", "category": "Music", "url": "https://splice.com/{username}"},
    {"name": "Genius", "category": "Music", "url": "https://genius.com/{username}"},
    {"name": "Apple Music", "category": "Music", "url": "https://music.apple.com/profile/{username}"},
    {"name": "Deezer", "category": "Music", "url": "https://www.deezer.com/user/{username}"},
    {"name": "Beatport", "category": "Music", "url": "https://www.beatport.com/artist/{username}/"},
    {"name": "Mixcloud", "category": "Music", "url": "https://www.mixcloud.com/{username}/"},
    {"name": "Last.fm", "category": "Music", "url": "https://www.last.fm/user/{username}"},
    {"name": "Shazam", "category": "Music", "url": "https://www.shazam.com/artist/{username}"},
    {"name": "GOG", "category": "Gaming", "url": "https://www.gog.com/u/{username}"},
    {"name": "Game Jolt", "category": "Gaming", "url": "https://gamejolt.com/@{username}"},
    {"name": "Nexus Mods", "category": "Gaming", "url": "https://www.nexusmods.com/users/{username}"},
    {"name": "Planet Minecraft", "category": "Gaming", "url": "https://www.planetminecraft.com/member/{username}/"},
    {"name": "Epic Games", "category": "Gaming", "url": "https://www.epicgames.com/id/{username}"},
    {"name": "Xbox Live", "category": "Gaming", "url": "https://account.xbox.com/en-us/profile?gamertag={username}"},
    {"name": "PlayStation", "category": "Gaming", "url": "https://my.playstation.com/profile/{username}"},
    {"name": "Nintendo", "category": "Gaming", "url": "https://en-americas-support.nintendo.com/app/user/profile/{username}"},
    {"name": "Battle.net", "category": "Gaming", "url": "https://battle.net/{username}"},
    {"name": "Origin", "category": "Gaming", "url": "https://www.origin.com/usa/en-us/profile/{username}"},
    {"name": "Riot Games", "category": "Gaming", "url": "https://www.riotgames.com/en/user/{username}"},
    {"name": "Wargaming", "category": "Gaming", "url": "https://wargaming.net/profile/{username}"},
    {"name": "Minecraft", "category": "Gaming", "url": "https://namemc.com/profile/{username}"},
    {"name": "Hypixel", "category": "Gaming", "url": "https://hypixel.net/player/{username}/"},
    {"name": "Speedrun.com", "category": "Gaming", "url": "https://www.speedrun.com/users/{username}"},
    {"name": "RetroAchievements", "category": "Gaming", "url": "https://retroachievements.org/user/{username}"},
    {"name": "TrueAchievements", "category": "Gaming", "url": "https://www.trueachievements.com/gamer/{username}"},
    {"name": "TrueTrophies", "category": "Gaming", "url": "https://www.truetrophies.com/gamer/{username}"},
    {"name": "Exophase", "category": "Gaming", "url": "https://www.exophase.com/user/{username}/"},
    {"name": "SteamGrid", "category": "Gaming", "url": "https://www.steamgriddb.com/profile/{username}"},
    {"name": "ModDB", "category": "Gaming", "url": "https://www.moddb.com/members/{username}"},
    {"name": "IndieDB", "category": "Gaming", "url": "https://www.indiedb.com/members/{username}"},
    {"name": "Itch.io", "category": "Gaming", "url": "https://itch.io/profile/{username}"},
    {"name": "Kongregate", "category": "Gaming", "url": "https://www.kongregate.com/accounts/{username}"},
    {"name": "Armor Games", "category": "Gaming", "url": "https://armorgames.com/user/{username}"},
    {"name": "Newgrounds", "category": "Gaming", "url": "https://newgrounds.com/{username}"},
    {"name": "LibraryThing", "category": "Books", "url": "https://www.librarything.com/profile/{username}"},
    {"name": "BookWyrm", "category": "Books", "url": "https://bookwyrm.social/user/{username}"},
    {"name": "The StoryGraph", "category": "Books", "url": "https://app.thestorygraph.com/profile/{username}"},
    {"name": "BookCrossing", "category": "Books", "url": "https://www.bookcrossing.com/mybookshelf/{username}"},
    {"name": "A Good Library", "category": "Books", "url": "https://agoodlibrary.com/profile/{username}"},
    {"name": "Xing", "category": "Professional", "url": "https://www.xing.com/profile/{username}"},
    {"name": "ResearchGate", "category": "Professional", "url": "https://www.researchgate.net/profile/{username}"},
    {"name": "Academia.edu", "category": "Professional", "url": "https://independent.academia.edu/{username}"},
    {"name": "AngelList", "category": "Professional", "url": "https://angel.co/u/{username}"},
    {"name": "Crunchbase", "category": "Professional", "url": "https://www.crunchbase.com/person/{username}"},
    {"name": "PeoplePerHour", "category": "Freelance", "url": "https://www.peopleperhour.com/freelancer/{username}"},
    {"name": "Guru", "category": "Freelance", "url": "https://www.guru.com/freelancers/{username}"},
    {"name": "99designs", "category": "Freelance", "url": "https://99designs.com/profiles/{username}"},
    {"name": "Toptal", "category": "Freelance", "url": "https://www.toptal.com/resume/{username}"},
    {"name": "Coursera", "category": "Education", "url": "https://www.coursera.org/user/{username}"},
    {"name": "Udemy", "category": "Education", "url": "https://www.udemy.com/user/{username}/"},
    {"name": "Skillshare", "category": "Education", "url": "https://www.skillshare.com/user/{username}"},
    {"name": "Khan Academy", "category": "Education", "url": "https://www.khanacademy.org/profile/{username}/"},
    {"name": "Quizlet", "category": "Education", "url": "https://quizlet.com/{username}"},
    {"name": "DataCamp", "category": "Education", "url": "https://www.datacamp.com/profile/{username}"},
    {"name": "edX", "category": "Education", "url": "https://profile.edx.org/u/{username}"},
    {"name": "FutureLearn", "category": "Education", "url": "https://www.futurelearn.com/profiles/{username}"},
    {"name": "Udacity", "category": "Education", "url": "https://www.udacity.com/profile/{username}"},
    {"name": "Pluralsight", "category": "Education", "url": "https://app.pluralsight.com/profile/{username}"},
    {"name": "Brilliant", "category": "Education", "url": "https://brilliant.org/profiles/{username}/"},
    {"name": "Memrise", "category": "Education", "url": "https://www.memrise.com/user/{username}/"},
    {"name": "Busuu", "category": "Education", "url": "https://www.busuu.com/profile/{username}"},
    {"name": "Fitbit", "category": "Fitness", "url": "https://www.fitbit.com/user/{username}"},
    {"name": "Runkeeper", "category": "Fitness", "url": "https://runkeeper.com/user/{username}"},
    {"name": "MyFitnessPal", "category": "Fitness", "url": "https://www.myfitnesspal.com/profile/{username}"},
    {"name": "Garmin Connect", "category": "Fitness", "url": "https://connect.garmin.com/modern/profile/{username}"},
    {"name": "Endomondo", "category": "Fitness", "url": "https://www.endomondo.com/profile/{username}"},
    {"name": "MapMyRun", "category": "Fitness", "url": "https://www.mapmyrun.com/profile/{username}/"},
    {"name": "Zwift", "category": "Fitness", "url": "https://www.zwift.com/athlete/{username}"},
    {"name": "Peloton", "category": "Fitness", "url": "https://members.onepeloton.com/members/{username}"},
    {"name": "TrainerRoad", "category": "Fitness", "url": "https://www.trainerroad.com/athlete/{username}"},
    {"name": "Sweatcoin", "category": "Fitness", "url": "https://sweatco.in/i/{username}"},
    {"name": "Untappd", "category": "Food", "url": "https://untappd.com/user/{username}"},
    {"name": "Vivino", "category": "Food", "url": "https://www.vivino.com/users/{username}"},
    {"name": "Allrecipes", "category": "Food", "url": "https://www.allrecipes.com/cook/{username}/"},
    {"name": "Yummly", "category": "Food", "url": "https://www.yummly.com/profile/{username}"},
    {"name": "Epicurious", "category": "Food", "url": "https://www.epicurious.com/user/{username}"},
    {"name": "Food.com", "category": "Food", "url": "https://www.food.com/user/{username}"},
    {"name": "Couchsurfing", "category": "Travel", "url": "https://www.couchsurfing.com/people/{username}"},
    {"name": "Foursquare", "category": "Travel", "url": "https://foursquare.com/{username}"},
    {"name": "Komoot", "category": "Travel", "url": "https://www.komoot.com/user/{username}"},
    {"name": "Wanderlog", "category": "Travel", "url": "https://wanderlog.com/profile/{username}"},
    {"name": "Atlas Obscura", "category": "Travel", "url": "https://www.atlasobscura.com/users/{username}"},
    {"name": "Polarsteps", "category": "Travel", "url": "https://polarsteps.com/{username}"},
    {"name": "Etsy", "category": "Shopping", "url": "https://www.etsy.com/people/{username}"},
    {"name": "eBay", "category": "Shopping", "url": "https://www.ebay.com/usr/{username}"},
    {"name": "Poshmark", "category": "Shopping", "url": "https://poshmark.com/closet/{username}"},
    {"name": "Depop", "category": "Shopping", "url": "https://www.depop.com/{username}/"},
    {"name": "Mercari", "category": "Shopping", "url": "https://www.mercari.com/u/{username}/"},
    {"name": "Vinted", "category": "Shopping", "url": "https://www.vinted.com/member/{username}"},
    {"name": "Grailed", "category": "Shopping", "url": "https://www.grailed.com/{username}"},
    {"name": "StockX", "category": "Shopping", "url": "https://stockx.com/{username}"},
    {"name": "GOAT", "category": "Shopping", "url": "https://www.goat.com/user/{username}"},
    {"name": "Reverb", "category": "Shopping", "url": "https://reverb.com/shop/{username}"},
    {"name": "Liberapay", "category": "Creator", "url": "https://liberapay.com/{username}/"},
    {"name": "GitHub Sponsors", "category": "Creator", "url": "https://github.com/sponsors/{username}"},
    {"name": "Open Collective", "category": "Creator", "url": "https://opencollective.com/{username}"},
    {"name": "Kickstarter", "category": "Creator", "url": "https://www.kickstarter.com/profile/{username}"},
    {"name": "Indiegogo", "category": "Creator", "url": "https://www.indiegogo.com/individuals/{username}"},
    {"name": "Rarible", "category": "Crypto", "url": "https://rarible.com/{username}"},
    {"name": "SuperRare", "category": "Crypto", "url": "https://superrare.com/{username}"},
    {"name": "Zora", "category": "Crypto", "url": "https://zora.co/@{username}"},
    {"name": "TradingView", "category": "Finance", "url": "https://www.tradingview.com/u/{username}/"},
    {"name": "StockTwits", "category": "Finance", "url": "https://stocktwits.com/{username}"},
    {"name": "CoinMarketCap", "category": "Crypto", "url": "https://coinmarketcap.com/community/profile/{username}/"},
    {"name": "CoinGecko", "category": "Crypto", "url": "https://www.coingecko.com/en/profile/{username}"},
    {"name": "Binance", "category": "Crypto", "url": "https://www.binance.com/en/profile/{username}"},
    {"name": "Flipboard", "category": "News", "url": "https://flipboard.com/@{username}"},
    {"name": "Mix", "category": "News", "url": "https://mix.com/{username}"},
    {"name": "Digg", "category": "News", "url": "https://digg.com/@{username}"},
    {"name": "Diigo", "category": "News", "url": "https://www.diigo.com/profile/{username}"},
    {"name": "Instructables", "category": "DIY", "url": "https://www.instructables.com/member/{username}/"},
    {"name": "Thingiverse", "category": "DIY", "url": "https://www.thingiverse.com/{username}/"},
    {"name": "Hackaday.io", "category": "DIY", "url": "https://hackaday.io/{username}"},
    {"name": "Hackster.io", "category": "DIY", "url": "https://www.hackster.io/{username}"},
    {"name": "Printables", "category": "DIY", "url": "https://www.printables.com/@{username}"},
    {"name": "MyMiniFactory", "category": "DIY", "url": "https://www.myminifactory.com/users/{username}"},
    {"name": "Cults3D", "category": "DIY", "url": "https://cults3d.com/en/users/{username}"},
    {"name": "BoardGameGeek", "category": "Hobby", "url": "https://boardgamegeek.com/user/{username}"},
    {"name": "Anime-Planet", "category": "Hobby", "url": "https://www.anime-planet.com/users/{username}"},
    {"name": "MyDramaList", "category": "Hobby", "url": "https://mydramalist.com/profile/{username}"},
    {"name": "Trakt", "category": "Hobby", "url": "https://trakt.tv/users/{username}"},
    {"name": "Kitsu", "category": "Hobby", "url": "https://kitsu.io/users/{username}"},
    {"name": "MangaDex", "category": "Hobby", "url": "https://mangadex.org/user/{username}"},
    {"name": "MangaUpdates", "category": "Hobby", "url": "https://www.mangaupdates.com/member/{username}"},
    {"name": "TV Time", "category": "Hobby", "url": "https://www.tvtime.com/en/user/{username}/profile"},
    {"name": "Serializd", "category": "Hobby", "url": "https://www.serializd.com/user/{username}"},
    {"name": "Trello", "category": "Productivity", "url": "https://trello.com/{username}"},
    {"name": "Calendly", "category": "Productivity", "url": "https://calendly.com/{username}"},
    {"name": "Notion", "category": "Productivity", "url": "https://www.notion.so/{username}"},
    {"name": "IFTTT", "category": "Automation", "url": "https://ifttt.com/p/{username}"},
    {"name": "Zapier", "category": "Automation", "url": "https://zapier.com/developer/public/{username}"},
    {"name": "Bento.me", "category": "Identity", "url": "https://bento.me/{username}"},
    {"name": "Bio.fm", "category": "Identity", "url": "https://bio.fm/{username}"},
    {"name": "Campsite.bio", "category": "Identity", "url": "https://campsite.bio/{username}"},
    {"name": "Beacons", "category": "Identity", "url": "https://beacons.ai/{username}"},
    {"name": "Solo.to", "category": "Identity", "url": "https://solo.to/{username}"},
    {"name": "Lnk.Bio", "category": "Identity", "url": "https://lnk.bio/{username}"},
    {"name": "Taplink", "category": "Identity", "url": "https://taplink.cc/{username}"},
    {"name": "Milkshake", "category": "Identity", "url": "https://msha.ke/{username}/"},
    {"name": "AllMyLinks", "category": "Identity", "url": "https://allmylinks.com/{username}"},
    {"name": "Flowcode", "category": "Identity", "url": "https://www.flowcode.com/{username}"},
    {"name": "Kaskus", "category": "Forum", "url": "https://www.kaskus.co.id/@{username}"},
    {"name": "VNG", "category": "Regional", "url": "https://id.vng.com/{username}"},
    {"name": "WeChat", "category": "Regional", "url": "https://web.wechat.com/{username}"},
    {"name": "Sina Visitor", "category": "Regional", "url": "https://weibo.com/u/{username}"},
    {"name": "Rakuten", "category": "Regional", "url": "https://www.rakuten.com/profile/{username}"},
    {"name": "MercadoLibre", "category": "Regional", "url": "https://www.mercadolibre.com/perfil/{username}"},
    {"name": "Fotolog", "category": "Social", "url": "https://www.fotolog.com/{username}"},
    {"name": "Bebo", "category": "Social", "url": "https://bebo.com/{username}"},
    {"name": "MySpace", "category": "Social", "url": "https://myspace.com/{username}"},
    {"name": "Friendster", "category": "Social", "url": "https://friendster.com/{username}"},
    {"name": "Classmates", "category": "Social", "url": "https://www.classmates.com/site-ui/profile/{username}"},
    {"name": "Nextdoor", "category": "Social", "url": "https://nextdoor.com/profile/{username}"},
    {"name": "Periscope", "category": "Social", "url": "https://www.periscope.tv/{username}"},
    {"name": "Houseparty", "category": "Social", "url": "https://houseparty.com/{username}"},
    {"name": "Clubhouse", "category": "Social", "url": "https://www.clubhouse.com/@{username}"},
    {"name": "Skype", "category": "Messaging", "url": "https://join.skype.com/invite/{username}"},
    {"name": "Zoom", "category": "Messaging", "url": "https://zoom.us/u/{username}"},
    {"name": "Google Meet", "category": "Messaging", "url": "https://meet.google.com/lookup/{username}"},
    {"name": "Microsoft Teams", "category": "Messaging", "url": "https://teams.microsoft.com/l/chat/{username}"},
    {"name": "Telegram Group", "category": "Messaging", "url": "https://t.me/joinchat/{username}"},
    {"name": "Viber", "category": "Messaging", "url": "https://chats.viber.com/{username}"},
    {"name": "LINE OpenChat", "category": "Messaging", "url": "https://line.me/R/ti/p/{username}"},
    {"name": "WeChat ID", "category": "Messaging", "url": "https://web.wechat.com/{username}"},
    {"name": "Kik", "category": "Messaging", "url": "https://kik.me/{username}"},
    {"name": "Wire", "category": "Messaging", "url": "https://app.wire.com/user/{username}"},
    {"name": "Element", "category": "Messaging", "url": "https://app.element.io/#/user/@{username}"},
    {"name": "Session", "category": "Messaging", "url": "https://getsession.org/id/{username}"},
    {"name": "Tox", "category": "Messaging", "url": "https://tox.chat/{username}"},
    {"name": "Riot", "category": "Messaging", "url": "https://riot.im/app/#/user/@{username}"},
    {"name": "IRC Freenode", "category": "Messaging", "url": "https://webchat.freenode.net/?nick={username}"},
    {"name": "IRC Libera", "category": "Messaging", "url": "https://web.libera.chat/?nick={username}"},
    {"name": "Matrix", "category": "Messaging", "url": "https://matrix.to/#/@{username}"},
    {"name": "Pastebin", "category": "Developer", "url": "https://pastebin.com/u/{username}"},
    {"name": "GitHub Gist", "category": "Developer", "url": "https://gist.github.com/{username}"},
    {"name": "GitLab Snippets", "category": "Developer", "url": "https://gitlab.com/snippets/{username}"},
    {"name": "Rentry.co", "category": "Developer", "url": "https://rentry.co/{username}"},
    {"name": "Hastebin", "category": "Developer", "url": "https://hastebin.com/{username}"},
    {"name": "GitHub Pages", "category": "Developer", "url": "https://{username}.github.io/"},
    {"name": "GitLab Pages", "category": "Developer", "url": "https://{username}.gitlab.io/"},
    {"name": "Netlify", "category": "Developer", "url": "https://{username}.netlify.app/"},
    {"name": "Vercel", "category": "Developer", "url": "https://{username}.vercel.app/"},
    {"name": "Heroku", "category": "Developer", "url": "https://{username}.herokuapp.com/"},
    {"name": "Render", "category": "Developer", "url": "https://{username}.onrender.com/"},
    {"name": "Cloudflare Pages", "category": "Developer", "url": "https://{username}.pages.dev/"},
    {"name": "Railway", "category": "Developer", "url": "https://{username}.railway.app/"},
    {"name": "Fly.io", "category": "Developer", "url": "https://{username}.fly.dev/"},
    {"name": "Deno Deploy", "category": "Developer", "url": "https://{username}.deno.dev/"},
    {"name": "Surge.sh", "category": "Developer", "url": "https://{username}.surge.sh/"},
    {"name": "Neocities", "category": "Developer", "url": "https://{username}.neocities.org/"},
    {"name": "Tiiny.host", "category": "Developer", "url": "https://{username}.tiiny.host/"},
    {"name": "PythonAnywhere", "category": "Developer", "url": "https://{username}.pythonanywhere.com/"},
    {"name": "Repl.it", "category": "Developer", "url": "https://replit.com/@{username}"},
    {"name": "Codepen", "category": "Developer", "url": "https://codepen.io/{username}"},
    {"name": "JSBIN", "category": "Developer", "url": "https://jsbin.com/{username}"},
    {"name": "JS Bin", "category": "Developer", "url": "https://jsbin.com/{username}"},
    {"name": "CodeSandbox", "category": "Developer", "url": "https://codesandbox.io/u/{username}"},
    {"name": "Stackblitz", "category": "Developer", "url": "https://stackblitz.com/@{username}"},
    {"name": "Gitpod", "category": "Developer", "url": "https://gitpod.io/#https://github.com/{username}"},
    {"name": "Codeberg", "category": "Developer", "url": "https://codeberg.org/{username}"},
    {"name": "NotABug.org", "category": "Developer", "url": "https://notabug.org/{username}"},
    {"name": "Gitea", "category": "Developer", "url": "https://gitea.com/{username}"},
    {"name": "Gogs", "category": "Developer", "url": "https://gogs.io/{username}"},
    {"name": "Bitwise", "category": "Developer", "url": "https://bitwise.com/{username}"},
    {"name": "Semaphore CI", "category": "Developer", "url": "https://semaphoreci.com/{username}"},
    {"name": "Circle CI", "category": "Developer", "url": "https://app.circleci.com/pipelines/github/{username}"},
    {"name": "Travis CI", "category": "Developer", "url": "https://travis-ci.com/{username}"},
    {"name": "Jenkins", "category": "Developer", "url": "https://{username}.jenkins.io/"},
    {"name": "Docker Hub", "category": "Developer", "url": "https://hub.docker.com/u/{username}"},
    {"name": "Quay.io", "category": "Developer", "url": "https://quay.io/user/{username}"},
    {"name": "GitLab Container", "category": "Developer", "url": "https://gitlab.com/users/{username}/container_registry"},
    {"name": "npm", "category": "Developer", "url": "https://www.npmjs.com/~{username}"},
    {"name": "PyPI", "category": "Developer", "url": "https://pypi.org/user/{username}/"},
    {"name": "RubyGems", "category": "Developer", "url": "https://rubygems.org/profiles/{username}"},
    {"name": "Crates.io", "category": "Developer", "url": "https://crates.io/users/{username}"},
    {"name": "Packagist", "category": "Developer", "url": "https://packagist.org/packages/{username}"},
    {"name": "NuGet", "category": "Developer", "url": "https://www.nuget.org/profiles/{username}"},
    {"name": "Maven Central", "category": "Developer", "url": "https://search.maven.org/contributors/{username}"},
    {"name": "Homebrew", "category": "Developer", "url": "https://github.com/Homebrew/homebrew-core/blob/master/Formula/{username}.rb"},
    {"name": "Scoop", "category": "Developer", "url": "https://github.com/ScoopInstaller/Main/tree/master/bucket/{username}.json"},
    {"name": "Chocolatey", "category": "Developer", "url": "https://chocolatey.org/profiles/{username}"},
    {"name": "Snapcraft", "category": "Developer", "url": "https://snapcraft.io/{username}"},
    {"name": "Flathub", "category": "Developer", "url": "https://flathub.org/apps/author/{username}"},
    {"name": "Gumroad", "category": "Creator", "url": "https://gumroad.com/{username}"},
    {"name": "Gumlet", "category": "Creator", "url": "https://app.gumlet.com/profile/{username}"},
    {"name": "ConvertKit", "category": "Creator", "url": "https://convertkit.com/{username}"},
    {"name": "Mailchimp", "category": "Creator", "url": "https://mailchimp.com/{username}"},
    {"name": "SendFox", "category": "Creator", "url": "https://sendfox.com/{username}"},
    {"name": "Buttondown", "category": "Creator", "url": "https://buttondown.email/{username}"},
    {"name": "Tally", "category": "Creator", "url": "https://tally.so/{username}"},
    {"name": "Typeform", "category": "Creator", "url": "https://www.typeform.com/profile/{username}"},
    {"name": "Google Forms", "category": "Creator", "url": "https://docs.google.com/forms/d/e/{username}"},
    {"name": "Notion Forms", "category": "Creator", "url": "https://notion.so/{username}"},
    {"name": "Airtable", "category": "Productivity", "url": "https://airtable.com/{username}"},
    {"name": "Monday.com", "category": "Productivity", "url": "https://{username}.monday.com/"},
    {"name": "Asana", "category": "Productivity", "url": "https://app.asana.com/0/profile/{username}"},
    {"name": "ClickUp", "category": "Productivity", "url": "https://app.clickup.com/{username}"},
    {"name": "Basecamp", "category": "Productivity", "url": "https://{username}.basecamphq.com/"},
    {"name": "Wrike", "category": "Productivity", "url": "https://www.wrike.com/workspace/{username}"},
    {"name": "Todoist", "category": "Productivity", "url": "https://todoist.com/showProject?id={username}"},
    {"name": "Remember the Milk", "category": "Productivity", "url": "https://www.rememberthemilk.com/home/{username}/"},
    {"name": "Any.do", "category": "Productivity", "url": "https://www.any.do/profile/{username}"},
    {"name": "TickTick", "category": "Productivity", "url": "https://ticktick.com/webapp/#p/{username}"},
    {"name": "Habitica", "category": "Productivity", "url": "https://habitica.com/profile/{username}"},
    {"name": "Focusmate", "category": "Productivity", "url": "https://www.focusmate.com/profile/{username}"},
    {"name": "Forest App", "category": "Productivity", "url": "https://www.forestapp.cc/profile/{username}"},
    {"name": "Pomofocus", "category": "Productivity", "url": "https://pomofocus.io/{username}"},
    {"name": "Tinder", "category": "Dating", "url": "https://tinder.com/@{username}"},
    {"name": "Bumble", "category": "Dating", "url": "https://bumble.com/profile/{username}"},
    {"name": "Hinge", "category": "Dating", "url": "https://hinge.co/profile/{username}"},
    {"name": "OkCupid", "category": "Dating", "url": "https://www.okcupid.com/profile/{username}"},
    {"name": "Plenty of Fish", "category": "Dating", "url": "https://www.pof.com/profile/{username}"},
    {"name": "Match.com", "category": "Dating", "url": "https://www.match.com/profile/{username}"},
    {"name": "eHarmony", "category": "Dating", "url": "https://www.eharmony.com/profile/{username}"},
    {"name": "Zoosk", "category": "Dating", "url": "https://www.zoosk.com/profile/{username}"},
    {"name": "Grindr", "category": "Dating", "url": "https://grindr.com/profile/{username}"},
    {"name": "HER", "category": "Dating", "url": "https://weareher.com/profile/{username}"},
    {"name": "Feeld", "category": "Dating", "url": "https://feeld.com/profile/{username}"},
    {"name": "Happn", "category": "Dating", "url": "https://www.happn.com/profile/{username}"},
    {"name": "Coffee Meets Bagel", "category": "Dating", "url": "https://coffeemeetsbagel.com/profile/{username}"},
    {"name": "Badoo Dating", "category": "Dating", "url": "https://badoo.com/profile/{username}"},
    {"name": "Jaumo", "category": "Dating", "url": "https://www.jaumo.com/profile/{username}"},
    {"name": "Lovoo", "category": "Dating", "url": "https://www.lovoo.com/profile/{username}"},
    {"name": "Twoo", "category": "Dating", "url": "https://www.twoo.com/profile/{username}"},
    {"name": "Skout", "category": "Dating", "url": "https://www.skout.com/profile/{username}"},
    {"name": "Tagged", "category": "Social", "url": "https://www.tagged.com/{username}"},
    {"name": "MeetMe", "category": "Social", "url": "https://www.meetme.com/{username}"},
    {"name": "Yubo", "category": "Social", "url": "https://yubo.live/profile/{username}"},
    {"name": "Wizz", "category": "Social", "url": "https://wizzapp.com/profile/{username}"},
    {"name": "Yik Yak", "category": "Social", "url": "https://yikyak.com/profile/{username}"},
    {"name": "Sarahah", "category": "Social", "url": "https://sarahah.com/{username}"},
    {"name": "Tellonym", "category": "Social", "url": "https://tellonym.me/{username}"},
    {"name": "Curious Cat", "category": "Social", "url": "https://curiouscat.live/{username}"},
    {"name": "Ask.fm", "category": "Social", "url": "https://ask.fm/{username}"},
    {"name": "Spring.me", "category": "Social", "url": "https://spring.me/{username}"},
    {"name": "Formspring", "category": "Social", "url": "https://formspring.me/{username}"},
    {"name": "Flixster", "category": "Social", "url": "https://www.flixster.com/user/{username}"},
    {"name": "IMDb", "category": "Media", "url": "https://www.imdb.com/user/{username}/"},
    {"name": "Rotten Tomatoes", "category": "Media", "url": "https://www.rottentomatoes.com/user/id/{username}"},
    {"name": "Metacritic", "category": "Media", "url": "https://www.metacritic.com/user/{username}"},
    {"name": "TV Guide", "category": "Media", "url": "https://www.tvguide.com/profile/{username}/"},
    {"name": "JustWatch", "category": "Media", "url": "https://www.justwatch.com/profile/{username}"},
    {"name": "Canva", "category": "Design", "url": "https://www.canva.com/{username}"},
    {"name": "Figma", "category": "Design", "url": "https://www.figma.com/@{username}"},
    {"name": "Sketch", "category": "Design", "url": "https://www.sketch.com/{username}"},
    {"name": "Adobe Behance", "category": "Design", "url": "https://www.behance.net/{username}"},
    {"name": "Adobe Portfolio", "category": "Design", "url": "https://{username}.myportfolio.com/"},
    {"name": "Dribbble", "category": "Design", "url": "https://dribbble.com/{username}"},
    {"name": "Design Crowd", "category": "Design", "url": "https://www.designcrowd.com/designers/{username}"},
    {"name": "Wix", "category": "Design", "url": "https://{username}.wixsite.com/"},
    {"name": "Squarespace", "category": "Design", "url": "https://{username}.squarespace.com/"},
    {"name": "Weebly", "category": "Design", "url": "https://{username}.weebly.com/"},
    {"name": "Jimdo", "category": "Design", "url": "https://{username}.jimdo.com/"},
    {"name": "Webflow", "category": "Design", "url": "https://webflow.com/@{username}"},
    {"name": "Adobe Fonts", "category": "Design", "url": "https://fonts.adobe.com/profile/{username}"},
    {"name": "Google Fonts", "category": "Design", "url": "https://fonts.google.com/?user={username}"},
    {"name": "Freepik", "category": "Design", "url": "https://www.freepik.com/author/{username}"},
    {"name": "Flaticon", "category": "Design", "url": "https://www.flaticon.com/authors/{username}"},
    {"name": "Vecteezy", "category": "Design", "url": "https://www.vecteezy.com/members/{username}"},
    {"name": "IconFinder", "category": "Design", "url": "https://www.iconfinder.com/{username}"},
    {"name": "Noun Project", "category": "Design", "url": "https://thenounproject.com/{username}/"},
    {"name": "Creative Market", "category": "Design", "url": "https://creativemarket.com/{username}"},
    {"name": "Envato", "category": "Design", "url": "https://elements.envato.com/user/{username}"},
    {"name": "AudioJungle", "category": "Design", "url": "https://audiojungle.net/user/{username}"},
    {"name": "VideoHive", "category": "Design", "url": "https://videohive.net/user/{username}"},
    {"name": "GraphicRiver", "category": "Design", "url": "https://graphicriver.net/user/{username}"},
    {"name": "PhotoDune", "category": "Design", "url": "https://photodune.net/user/{username}"},
    {"name": "CodeCanyon", "category": "Design", "url": "https://codecanyon.net/user/{username}"},
    {"name": "ThemeForest", "category": "Design", "url": "https://themeforest.net/user/{username}"},
    {"name": "3DOcean", "category": "Design", "url": "https://3docean.net/user/{username}"},
    {"name": "ActiveState", "category": "Developer", "url": "https://www.activestate.com/user/{username}"},
    {"name": "Anaconda", "category": "Developer", "url": "https://anaconda.org/{username}"},
    {"name": "Papers with Code", "category": "AI", "url": "https://paperswithcode.com/user/{username}"},
    {"name": "arXiv", "category": "AI", "url": "https://arxiv.org/search/?query={username}"},
    {"name": "Google Scholar", "category": "AI", "url": "https://scholar.google.com/citations?user={username}"},
    {"name": "ORCID", "category": "Identity", "url": "https://orcid.org/{username}"},
    {"name": "Scopus", "category": "Identity", "url": "https://www.scopus.com/authid/detail.uri?authorId={username}"},
    {"name": "PubMed", "category": "AI", "url": "https://pubmed.ncbi.nlm.nih.gov/?term={username}"},
    {"name": "Semantic Scholar", "category": "AI", "url": "https://www.semanticscholar.org/author/{username}"},
    {"name": "DBLP", "category": "AI", "url": "https://dblp.org/pid/{username}"},
    {"name": "ResearchGate", "category": "AI", "url": "https://www.researchgate.net/profile/{username}"},
    {"name": "Mendeley", "category": "AI", "url": "https://www.mendeley.com/profiles/{username}/"},
    {"name": "Zotero", "category": "AI", "url": "https://www.zotero.org/{username}"},
    {"name": "Google Patents", "category": "AI", "url": "https://patents.google.com/?inventor={username}"},
    {"name": "Justia Patents", "category": "AI", "url": "https://patents.justia.com/inventor/{username}"},
    {"name": "FreePatentsOnline", "category": "AI", "url": "https://www.freepatentsonline.com/result.html?sort=relevance&srch={username}"},
    {"name": "AngelList", "category": "Professional", "url": "https://angel.co/u/{username}"},
    {"name": "Wellfound", "category": "Professional", "url": "https://wellfound.com/u/{username}"},
    {"name": "LinkedIn Company", "category": "Professional", "url": "https://www.linkedin.com/company/{username}/"},
    {"name": "Glassdoor", "category": "Professional", "url": "https://www.glassdoor.com/Overview/{username}"},
    {"name": "Indeed", "category": "Professional", "url": "https://www.indeed.com/r/{username}"},
    {"name": "Monster", "category": "Professional", "url": "https://www.monster.com/profile/{username}"},
    {"name": "CareerBuilder", "category": "Professional", "url": "https://www.careerbuilder.com/profile/{username}"},
    {"name": "ZipRecruiter", "category": "Professional", "url": "https://www.ziprecruiter.com/profile/{username}"},
    {"name": "Dice", "category": "Professional", "url": "https://www.dice.com/profile/{username}"},
    {"name": "Hired", "category": "Professional", "url": "https://hired.com/profile/{username}"},
    {"name": "Vettery", "category": "Professional", "url": "https://www.vettery.com/profile/{username}"},
    {"name": "Ladders", "category": "Professional", "url": "https://www.theladders.com/profile/{username}"},
    {"name": "Plaxo", "category": "Professional", "url": "https://www.plaxo.com/profile/{username}"},
    {"name": "Ryze", "category": "Professional", "url": "https://www.ryze.com/profile/{username}"},
    {"name": "Viadeo", "category": "Professional", "url": "https://www.viadeo.com/profile/{username}"},
    {"name": "Zhihu", "category": "Regional", "url": "https://www.zhihu.com/people/{username}"},
    {"name": "Jianshu", "category": "Regional", "url": "https://www.jianshu.com/u/{username}"},
    {"name": "CSDN", "category": "Regional", "url": "https://blog.csdn.net/{username}"},
    {"name": "SegmentFault", "category": "Regional", "url": "https://segmentfault.com/u/{username}"},
    {"name": "V2EX", "category": "Regional", "url": "https://www.v2ex.com/member/{username}"},
    {"name": "Cnblogs", "category": "Regional", "url": "https://www.cnblogs.com/{username}/"},
    {"name": "OSChina", "category": "Regional", "url": "https://my.oschina.net/{username}"},
    {"name": "Gitee", "category": "Regional", "url": "https://gitee.com/{username}"},
    {"name": "Tencent Cloud", "category": "Regional", "url": "https://cloud.tencent.com/developer/user/{username}"},
    {"name": "Aliyun", "category": "Regional", "url": "https://developer.aliyun.com/profile/{username}"},
    {"name": "Huawei Cloud", "category": "Regional", "url": "https://developer.huaweicloud.com/profile/{username}"},
    {"name": "Qiita", "category": "Regional", "url": "https://qiita.com/{username}"},
    {"name": "Zenn", "category": "Regional", "url": "https://zenn.dev/{username}"},
    {"name": "Waninblog", "category": "Regional", "url": "https://waninblog.com/{username}"},
    {"name": "Hatena", "category": "Regional", "url": "https://profile.hatena.ne.jp/{username}/"},
    {"name": "Mastodon", "category": "Social", "url": "https://mastodon.social/@{username}"},
    {"name": "Pleroma", "category": "Social", "url": "https://pleroma.site/{username}"},
    {"name": "Misskey", "category": "Social", "url": "https://misskey.io/@{username}"},
    {"name": "Friendica", "category": "Social", "url": "https://friendica.net/profile/{username}"},
    {"name": "Hubzilla", "category": "Social", "url": "https://hubzilla.org/channel/{username}"},
    {"name": "Diaspora", "category": "Social", "url": "https://diaspodon.com/u/{username}"},
    {"name": "Triberr", "category": "Social", "url": "https://triberr.com/{username}"},
    {"name": "Scoop.it", "category": "Social", "url": "https://www.scoop.it/u/{username}"},
    {"name": "Paper.li", "category": "Social", "url": "https://paper.li/{username}"},
    {"name": "RebelMouse", "category": "Social", "url": "https://rebelmouse.com/{username}/"},
    {"name": "Twitter Archive", "category": "Social", "url": "https://archive.org/details/@twitter-{username}"},
    {"name": "Facebook Archive", "category": "Social", "url": "https://archive.org/details/@facebook-{username}"},
    {"name": "Instagram Archive", "category": "Social", "url": "https://archive.org/details/@instagram-{username}"},
    {"name": "LinkedIn Archive", "category": "Social", "url": "https://archive.org/details/@linkedin-{username}"},
    {"name": "Reddit Archive", "category": "Social", "url": "https://archive.org/details/@reddit-{username}"},
    {"name": "Archive.org", "category": "History", "url": "https://archive.org/search?query={username}"},
    {"name": "Wayback Machine", "category": "History", "url": "https://web.archive.org/web/*/{username}"},
    {"name": "Google Cache", "category": "History", "url": "https://webcache.googleusercontent.com/search?q=cache:{username}"},
    {"name": "Bing Cache", "category": "History", "url": "https://cc.bingj.com/cache.aspx?d=1&s={username}"},
    {"name": "Google Groups", "category": "History", "url": "https://groups.google.com/g/{username}"},
    {"name": "Usenet Archives", "category": "History", "url": "https://groups.google.com/g/{username}"},
    {"name": "Mail-archive.com", "category": "History", "url": "https://mail-archive.com/search?q={username}"},
    {"name": "Public WWW", "category": "History", "url": "https://publicwww.com/websites/{username}/"},
    {"name": "BuiltWith", "category": "History", "url": "https://builtwith.com/{username}"},
    {"name": "SimilarWeb", "category": "History", "url": "https://www.similarweb.com/website/{username}/"},
    {"name": "Alexa", "category": "History", "url": "https://www.alexa.com/siteinfo/{username}"},
    {"name": "Censys", "category": "History", "url": "https://search.censys.io/search?resource=hosts&q={username}"},
    {"name": "Shodan", "category": "History", "url": "https://www.shodan.io/search?query={username}"},
    {"name": "ZoomEye", "category": "History", "url": "https://www.zoomeye.org/searchResult?q={username}"},
    {"name": "Fofa", "category": "History", "url": "https://fofa.info/result?qbase64={username}"},
    {"name": "ONYPHE", "category": "History", "url": "https://www.onyphe.io/search?q={username}"},
    {"name": "BinaryEdge", "category": "History", "url": "https://app.binaryedge.io/services/query?query={username}"},
    {"name": "RiskIQ", "category": "History", "url": "https://community.riskiq.com/search/{username}"},
    {"name": "VirusTotal", "category": "History", "url": "https://www.virustotal.com/gui/search/{username}"},
    {"name": "UrlScan.io", "category": "History", "url": "https://urlscan.io/search/#{username}"},
    {"name": "AbuseIPDB", "category": "History", "url": "https://www.abuseipdb.com/check/{username}"},
    {"name": "IPinfo", "category": "History", "url": "https://ipinfo.io/{username}"},
    {"name": "IPQualityScore", "category": "History", "url": "https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/{username}"},
    {"name": "WhatIsMyIP", "category": "History", "url": "https://whatismyipaddress.com/ip/{username}"},
    {"name": "DNSlytics", "category": "History", "url": "https://dnslytics.com/search?q={username}"},
    {"name": "DomainTools", "category": "History", "url": "https://whois.domaintools.com/{username}"},
    {"name": "Who.is", "category": "History", "url": "https://who.is/whois/{username}"},
    {"name": "Whois.com", "category": "History", "url": "https://www.whois.com/whois/{username}"},
    {"name": "WhoisXMLAPI", "category": "History", "url": "https://www.whoisxmlapi.com/whois-lookup/{username}"},
    {"name": "ViewDNS", "category": "History", "url": "https://viewdns.info/iphistory/?domain={username}"},
    {"name": "MXToolbox", "category": "History", "url": "https://mxtoolbox.com/SuperTool.aspx?action=ptr%3a{username}"},
    {"name": "DNS Watch", "category": "History", "url": "https://www.dnswatch.info/dns/dp/{username}"},
    {"name": "IntoDNS", "category": "History", "url": "https://intodns.com/{username}"},
    {"name": "WhatsMyDNS", "category": "History", "url": "https://whatsmydns.net/#A/{username}"},
    {"name": "Robtex", "category": "History", "url": "https://www.robtex.com/dns-lookup/{username}"},
    {"name": "SecurityTrails", "category": "History", "url": "https://securitytrails.com/domain/{username}/dns"},
    {"name": "CRT.sh", "category": "History", "url": "https://crt.sh/?q={username}"},
    {"name": "SpyOnWeb", "category": "History", "url": "https://spyonweb.com/{username}"},
    {"name": "MyWOT", "category": "History", "url": "https://www.mywot.com/scorecard/{username}"},
    {"name": "Trustpilot", "category": "History", "url": "https://www.trustpilot.com/review/{username}"},
    {"name": "Sitejabber", "category": "History", "url": "https://www.sitejabber.com/reviews/{username}"},
    {"name": "G2", "category": "History", "url": "https://www.g2.com/products/{username}"},
    {"name": "Capterra", "category": "History", "url": "https://www.capterra.com/p/{username}/"},
    {"name": "GetApp", "category": "History", "url": "https://www.getapp.com/{username}/"},
    {"name": "Reddit Metis", "category": "History", "url": "https://redditmetis.com/u/{username}"},
    {"name": "Reddit Karma", "category": "History", "url": "https://redditkarma.com/user/{username}"},
    {"name": "Redective", "category": "History", "url": "https://www.redective.com/search/?q={username}"},
    {"name": "Social Blade", "category": "History", "url": "https://socialblade.com/instagram/user/{username}"},
    {"name": "Social Searcher", "category": "History", "url": "https://www.social-searcher.com/social-buzz/?q={username}"},
    {"name": "Mention", "category": "History", "url": "https://mention.com/en/search/?q={username}"},
    {"name": "Brand24", "category": "History", "url": "https://brand24.com/search?q={username}"},
    {"name": "Brandwatch", "category": "History", "url": "https://www.brandwatch.com/search/?q={username}"},
    {"name": "Talkwalker", "category": "History", "url": "https://www.talkwalker.com/social-media-search?q={username}"},
    {"name": "Keyhole", "category": "History", "url": "https://keyhole.co/search/?q={username}"},
    {"name": "Hashtagify", "category": "History", "url": "https://hashtagify.me/hashtag/{username}"},
    {"name": "Ritetag", "category": "History", "url": "https://ritetag.com/hashtag/{username}"},
    {"name": "Trendsmap", "category": "History", "url": "https://www.trendsmap.com/search?q={username}"},
    {"name": "Tweet Binder", "category": "History", "url": "https://www.tweetbinder.com/search?q={username}"},
    {"name": "TweetDeck", "category": "History", "url": "https://tweetdeck.twitter.com/{username}"},
    {"name": "Nitter", "category": "History", "url": "https://nitter.net/{username}"},
    {"name": "Bibliogram", "category": "History", "url": "https://bibliogram.art/u/{username}"},
    {"name": "Invidious", "category": "History", "url": "https://invidious.snopyta.org/feed/channel/{username}"},
    {"name": "Teddit", "category": "History", "url": "https://teddit.net/user/{username}"},
    {"name": "Libreddit", "category": "History", "url": "https://libreddit.net/user/{username}"},
    {"name": "Yotter", "category": "History", "url": "https://yotter.xyz/user/{username}"},
    {"name": "CloudVision", "category": "History", "url": "https://cloudvision.com/{username}"},
    {"name": "DuckDuckGo", "category": "Search", "url": "https://duckduckgo.com/?q={username}"},
    {"name": "Google Search", "category": "Search", "url": "https://www.google.com/search?q={username}"},
    {"name": "Bing Search", "category": "Search", "url": "https://www.bing.com/search?q={username}"},
    {"name": "Yahoo Search", "category": "Search", "url": "https://search.yahoo.com/search?p={username}"},
    {"name": "Yandex Search", "category": "Search", "url": "https://yandex.com/search/?text={username}"},
    {"name": "Baidu Search", "category": "Search", "url": "https://www.baidu.com/s?wd={username}"},
    {"name": "Naver Search", "category": "Search", "url": "https://search.naver.com/search.naver?query={username}"},
    {"name": "Sogou Search", "category": "Search", "url": "https://www.sogou.com/web?query={username}"},
    {"name": "Qwant Search", "category": "Search", "url": "https://www.qwant.com/?q={username}"},
    {"name": "Searx Search", "category": "Search", "url": "https://searx.be/search?q={username}"},
    {"name": "Mojeek Search", "category": "Search", "url": "https://www.mojeek.com/search?q={username}"},
    {"name": "Startpage Search", "category": "Search", "url": "https://www.startpage.com/do/dsearch?query={username}"},
    {"name": "Gibiru Search", "category": "Search", "url": "https://gibiru.com/results.html?q={username}"},
    {"name": "Swisscows Search", "category": "Search", "url": "https://swisscows.com/web?query={username}"},
    {"name": "MetaGer Search", "category": "Search", "url": "https://metager.org/meta/meta.ger3?eingabe={username}"},
    {"name": "EXALEAD Search", "category": "Search", "url": "https://www.exalead.com/search/web/results/?q={username}"},
    {"name": "Brave Search", "category": "Search", "url": "https://search.brave.com/search?q={username}"},
    {"name": "Boardreader", "category": "Search", "url": "https://boardreader.com/s/{username}"},
    {"name": "Social Mention", "category": "Search", "url": "https://socialmention.com/search?q={username}"},
    {"name": "Netvibes", "category": "Search", "url": "https://www.netvibes.com/search/{username}"},
    {"name": "Giphy", "category": "Social", "url": "https://giphy.com/{username}"},
    {"name": "Tenor", "category": "Social", "url": "https://tenor.com/users/{username}"},
    {"name": "Imgflip", "category": "Social", "url": "https://imgflip.com/user/{username}"},
    {"name": "Know Your Meme", "category": "Social", "url": "https://knowyourmeme.com/users/{username}"},
    {"name": "Memedroid", "category": "Social", "url": "https://www.memedroid.com/members/{username}"},
    {"name": "9GAG", "category": "Social", "url": "https://9gag.com/u/{username}"},
    {"name": "Cheezburger", "category": "Social", "url": "https://cheezburger.com/{username}"},
    {"name": "Funny or Die", "category": "Social", "url": "https://www.funnyordie.com/people/{username}"},
    {"name": "CollegeHumor", "category": "Social", "url": "https://www.collegehumor.com/user/{username}"},
    {"name": "Break", "category": "Social", "url": "https://www.break.com/user/{username}"},
    {"name": "eBaum's World", "category": "Social", "url": "https://www.ebaumsworld.com/users/{username}/"},
    {"name": "YTMND", "category": "Social", "url": "https://ytmnd.com/users/{username}"},
    {"name": "RedGIFs", "category": "Social", "url": "https://redgifs.com/users/{username}"},
    {"name": "Gfycat", "category": "Social", "url": "https://gfycat.com/{username}"},
    {"name": "Coub", "category": "Social", "url": "https://coub.com/{username}"},
    {"name": "GIPHY", "category": "Social", "url": "https://giphy.com/channel/{username}"},
    {"name": "Burst", "category": "Social", "url": "https://burst.shopify.com/@{username}"},
    {"name": "Kaboompics", "category": "Social", "url": "https://kaboompics.com/photographer/{username}"},
    {"name": "Stocksy", "category": "Social", "url": "https://www.stocksy.com/contributor/{username}"},
    {"name": "Twenty20", "category": "Social", "url": "https://twenty20.com/{username}"},
    {"name": "Offset", "category": "Social", "url": "https://www.offset.com/photos/{username}"},
]

SEARCH_LEADS = [
    {"name": "🌐 Google exact", "url": "https://www.google.com/search?q=%22{query}%22"},
    {"name": "🌐 Google social", "url": "https://www.google.com/search?q=%22{query}%22+%28instagram+OR+github+OR+linkedin+OR+twitter%29"},
    {"name": "🌐 Bing exact", "url": "https://www.bing.com/search?q=%22{query}%22"},
    {"name": "🌐 DuckDuckGo", "url": "https://duckduckgo.com/?q=%22{query}%22"},
    {"name": "🌐 Yandex exact", "url": "https://yandex.com/search/?text=%22{query}%22"},
    {"name": "🌐 Baidu exact", "url": "https://www.baidu.com/s?wd=%22{query}%22"},
    {"name": "🌐 Naver exact", "url": "https://search.naver.com/search.naver?query=%22{query}%22"},
    {"name": "🌐 Qwant exact", "url": "https://www.qwant.com/?q=%22{query}%22"},
    {"name": "🌐 Brave search", "url": "https://search.brave.com/search?q=%22{query}%22"},
    {"name": "🌐 Swisscows", "url": "https://swisscows.com/web?query=%22{query}%22"},
    {"name": "🌐 MetaGer", "url": "https://metager.org/meta/meta.ger3?eingabe=%22{query}%22"},
    {"name": "🌐 Searx", "url": "https://searx.be/search?q=%22{query}%22"},
    {"name": "💻 GitHub users", "url": "https://github.com/search?q=%22{query}%22&type=users"},
    {"name": "💻 GitHub code", "url": "https://github.com/search?q=%22{query}%22&type=code"},
    {"name": "💻 GitLab search", "url": "https://gitlab.com/search?search=%22{query}%22"},
    {"name": "📱 Reddit mentions", "url": "https://www.reddit.com/search/?q=%22{query}%22"},
    {"name": "💼 LinkedIn search", "url": "https://www.google.com/search?q=site%3Alinkedin.com%2Fin+%22{query}%22"},
    {"name": "📸 Instagram search", "url": "https://www.google.com/search?q=site%3Ainstagram.com+%22{query}%22"},
    {"name": "🎵 TikTok search", "url": "https://www.google.com/search?q=site%3Atiktok.com+%22{query}%22"},
    {"name": "🐦 Twitter search", "url": "https://www.google.com/search?q=site%3Atwitter.com+%22{query}%22"},
    {"name": "📘 Facebook search", "url": "https://www.google.com/search?q=site%3Afacebook.com+%22{query}%22"},
    {"name": "▶️ YouTube search", "url": "https://www.google.com/search?q=site%3Ayoutube.com+%22{query}%22"},
    {"name": "💬 Stack Overflow", "url": "https://www.google.com/search?q=site%3Astackoverflow.com+%22{query}%22"},
    {"name": "📝 Medium search", "url": "https://www.google.com/search?q=site%3Amedium.com+%22{query}%22"},
    {"name": "🖥️ Dev.to search", "url": "https://www.google.com/search?q=site%3Adev.to+%22{query}%22"},
    {"name": "📋 Pastebin traces", "url": "https://www.google.com/search?q=%22{query}%22+site%3Apastebin.com"},
    {"name": "📄 Documents", "url": "https://www.google.com/search?q=%22{query}%22+filetype%3Apdf+OR+filetype%3Adocx+OR+filetype%3Atxt"},
    {"name": "🔒 Breach traces", "url": "https://www.google.com/search?q=%22{query}%22+%28leak+OR+breach+OR+dump+OR+compromised%29"},
    {"name": "🌑 Dark web", "url": "https://www.google.com/search?q=%22{query}%22+%28darknet+OR+darkweb+OR+onion%29"},
    {"name": "📧 Email traces", "url": "https://www.google.com/search?q=%22{query}%22+%40+email+contact"},
    {"name": "📱 Phone traces", "url": "https://www.google.com/search?q=%22{query}%22+phone+number+contact"},
    {"name": "📍 Address traces", "url": "https://www.google.com/search?q=%22{query}%22+address+location+home"},
    {"name": "💬 Forum mentions", "url": "https://www.google.com/search?q=%22{query}%22+%28forum+OR+thread+OR+member%29"},
    {"name": "📰 News mentions", "url": "https://www.google.com/search?q=%22{query}%22+news+article"},
    {"name": "📝 Blog mentions", "url": "https://www.google.com/search?q=%22{query}%22+blog+post"},
    {"name": "💼 Job/Resume", "url": "https://www.google.com/search?q=%22{query}%22+%28resume+OR+CV+OR+portfolio+OR+hiring%29"},
    {"name": "🎓 Education", "url": "https://www.google.com/search?q=%22{query}%22+%28school+OR+university+OR+college+OR+student%29"},
    {"name": "🏠 Address search", "url": "https://www.google.com/search?q=%22{query}%22+%28address+OR+street+OR+city+OR+zip%29"},
    {"name": "📊 Public records", "url": "https://www.google.com/search?q=%22{query}%22+%28public+record+OR+bio+OR+about%29"},
    {"name": "🔄 Username check", "url": "https://www.google.com/search?q=%22{query}%22+username+profile"},
]

def get_social_sources():
    from .validators import normalize_source
    clean = []
    seen = set()
    for source in SOCIAL_SOURCES:
        source = normalize_source(source)
        if not source:
            continue
        key = source["url"]
        if key not in seen:
            seen.add(key)
            clean.append(source)
    return clean
