package core

import (
	"fmt"
	"net/http"
	"regexp"
	"strings"
)

type DBFingerprint struct {
	Name      string
	Patterns  []string
	ErrorPats []string
	Priority  int
}

var dbFingerprints = []DBFingerprint{
	{
		Name: "MySQL", Priority: 10,
		Patterns:  []string{"SQL syntax.*MySQL", "Warning.*mysql_", "valid MySQL result", "MySqlClient.", "MariaDB"},
		ErrorPats: []string{"MySQL", "mysql_", "mysql_fetch", "MariaDB", "You have an error in your SQL syntax"},
	},
	{
		Name: "MariaDB", Priority: 10,
		Patterns:  []string{"MariaDB", "mysqlnd", "MariaDB server"},
		ErrorPats: []string{"MariaDB", "mysqlnd"},
	},
	{
		Name: "MSSQL", Priority: 9,
		Patterns:  []string{"Driver.*SQL Server", "OLE DB.*SQL Server", "SQL Server.*Driver", "Microsoft SQL Native Client", "Warning.*mssql_", "Driver.*SQL Server", "SQLServer JDBC Driver"},
		ErrorPats: []string{"Microsoft OLE DB Provider for SQL Server", "SQL Server", "Unclosed quotation mark after the character string", "mssql_"},
	},
	{
		Name: "PostgreSQL", Priority: 8,
		Patterns:  []string{"PostgreSQL.*ERROR", "Warning.*pg_", "valid PostgreSQL result", "Npgsql.", "PostgreSQL"},
		ErrorPats: []string{"PostgreSQL", "pg_query", "syntax error at or near", "pg_"},
	},
	{
		Name: "Oracle", Priority: 7,
		Patterns:  []string{"ORA-[0-9][0-9][0-9][0-9][0-9]", "Oracle error", "Oracle.*Driver", "Warning.*oci_", "PL/SQL"},
		ErrorPats: []string{"ORA-", "Oracle", "oci_", "PLS-"},
	},
	{
		Name: "SQLite", Priority: 6,
		Patterns:  []string{"SQLite/JDBCDriver", "SQLite.Exception", "System.Data.SQLite", "Warning.*sqlite_", "sqlite3"},
		ErrorPats: []string{"SQLite", "sqlite_", "sqlite3"},
	},
	{
		Name: "ClickHouse", Priority: 5,
		Patterns:  []string{"ClickHouse", "DB::Exception"},
		ErrorPats: []string{"ClickHouse", "DB::Exception", "Received from ClickHouse"},
	},
	{
		Name: "DuckDB", Priority: 5,
		Patterns:  []string{"DuckDB", "duckdb"},
		ErrorPats: []string{"DuckDB", "duckdb", "Catalog Error"},
	},
	{
		Name: "CockroachDB", Priority: 5,
		Patterns:  []string{"CockroachDB", "crdb_internal"},
		ErrorPats: []string{"CockroachDB", "crdb_", "runtime error:"},
	},
	{
		Name: "Snowflake", Priority: 4,
		Patterns:  []string{"Snowflake", "SNOWFLAKE", "SnowflakeError"},
		ErrorPats: []string{"Snowflake", "SNOWFLAKE", "Execution error in"},
	},
	{
		Name: "BigQuery", Priority: 4,
		Patterns:  []string{"BigQuery", "Google BigQuery"},
		ErrorPats: []string{"BigQuery", "Unrecognized token"},
	},
	{
		Name: "Firebird", Priority: 3,
		Patterns:  []string{"Firebird", "Firebird/InterBase", "isc_"},
		ErrorPats: []string{"Firebird", "isc_", "Dynamic SQL Error"},
	},
	{
		Name: "Sybase", Priority: 3,
		Patterns:  []string{"Sybase", "Sybase SQL Server", "Adaptive Server"},
		ErrorPats: []string{"Sybase", "SQL Anywhere"},
	},
	{
		Name: "H2", Priority: 2,
		Patterns:  []string{"H2 JDBC Driver", "org.h2", "H2 Database"},
		ErrorPats: []string{"H2", "General error", "Unique index or primary key violation"},
	},
}

type WAFInfo struct {
	Detected bool
	Name     string
	Details  string
}

var wafSignatures = []struct {
	Name      string
	Headers   []string
	BodyPats  []string
	CookiePats []string
}{
	{
		Name: "Cloudflare",
		Headers:  []string{"Cf-Ray", "CF-RAY", "cf-ray"},
		BodyPats: []string{"cloudflare-nginx", "Cloudflare", "Attention Required! | Cloudflare"},
	},
	{
		Name: "Cloudflare (challenge)",
		Headers:  []string{"Cf-Chl-Bypass"},
		BodyPats: []string{"cf-browser-verification", "challenge-platform"},
	},
	{
		Name: "Akamai",
		Headers:  []string{"X-Akamai-Transformed", "X-Akamai-Request-ID"},
	},
	{
		Name: "ModSecurity",
		Headers:  []string{"Server"},
		BodyPats: []string{"Mod_Security", "ModSecurity", "NOYB", "This error was generated by Mod_Security"},
	},
	{
		Name: "AWS WAF",
		Headers:  []string{"x-amzn-RequestId", "x-amzn-ErrorType"},
		BodyPats: []string{"AWS WAF", "waf-", "Request blocked by AWS WAF"},
	},
	{
		Name: "F5 BIG-IP ASM",
		Headers:  []string{"X-Content-Type-Options", "X-XSS-Protection"},
		BodyPats: []string{"The requested URL was rejected", "TS65", "F5 Networks"},
	},
	{
		Name: "FortiWeb",
		Headers:  []string{"FortiWeb"},
	},
	{
		Name: "Imperva Incapsula",
		Headers:  []string{"X-Iinfo", "X-CDN"},
		BodyPats: []string{"Incapsula", "imperva", "_Incapsula_Resource"},
	},
	{
		Name: "Sucuri",
		Headers:  []string{"X-Sucuri-ID", "X-Sucuri-Cache"},
		BodyPats: []string{"Sucuri WebSite Firewall", "cloudproxy"},
	},
	{
		Name: "Barracuda",
		BodyPats: []string{"Barracuda", "barracuda"},
	},
	{
		Name: "Cisco ACE XML Gateway",
		BodyPats: []string{"ACE XML Gateway"},
	},
	{
		Name: "WebKnight",
		Headers:  []string{"Server"},
		BodyPats: []string{"WebKnight", "webknight"},
	},
	{
		Name: "URLScan",
		Headers:  []string{"X-URLScan"},
	},
	{
		Name: "Naxsi",
		Headers:  []string{"X-Naxsi"},
		BodyPats: []string{"Naxsi", "naxsi"},
	},
	{
		Name: "SafeDog",
		Headers:  []string{"Wzws-", "WZWS-"},
		BodyPats: []string{"SafeDog", "safedog"},
	},
	{
		Name: "Yundun",
		Headers:  []string{"Yundun"},
	},
	{
		Name: "Aliyun (AliCloud)",
		Headers:  []string{"Aliyun"},
		BodyPats: []string{"aliyun", "Yunjiasu"},
	},
	{
		Name: "Baidu Yunjiasu",
		Headers:  []string{"Yunjiasu"},
	},
}

func DetectDBMS(body string, headers http.Header) string {
	bodyLower := strings.ToLower(body)
	scores := make(map[string]int)

	// Check each DB fingerprint
	for _, fp := range dbFingerprints {
		for _, pat := range fp.ErrorPats {
			if strings.Contains(bodyLower, strings.ToLower(pat)) {
				scores[fp.Name] += 3
			}
		}
		for _, pat := range fp.Patterns {
			matched, _ := regexp.MatchString("(?i)"+pat, body)
			if matched {
				scores[fp.Name] += 5
			}
		}
	}

	// Check server header
	server := headers.Get("Server")
	serverLower := strings.ToLower(server)
	xpowered := headers.Get("X-Powered-By")
	xpoweredLower := strings.ToLower(xpowered)

	if strings.Contains(serverLower, "mysql") || strings.Contains(xpoweredLower, "php") {
		scores["MySQL"] += 2
		scores["MariaDB"] += 2
	}
	if strings.Contains(serverLower, "postgres") {
		scores["PostgreSQL"] += 4
	}
	if strings.Contains(serverLower, "microsoft-iis") || strings.Contains(xpoweredLower, "asp.net") {
		scores["MSSQL"] += 3
	}

	// Find best match
	bestScore := 0
	bestDB := "Unknown"
	for db, score := range scores {
		if score > bestScore {
			bestScore = score
			bestDB = db
		}
	}

	if bestScore >= 3 {
		return bestDB
	}
	return "Unknown"
}

func DetectWAF(headers http.Header, body string) WAFInfo {
	bodyLower := strings.ToLower(body)

	for _, waf := range wafSignatures {
		score := 0

		// Check headers
		for _, h := range waf.Headers {
			if headers.Get(h) != "" {
				score += 3
			}
			// Check all headers for pattern
			for k, v := range headers {
				if strings.Contains(strings.ToLower(k), strings.ToLower(h)) {
					score += 2
				}
				for _, vv := range v {
					if strings.Contains(strings.ToLower(vv), strings.ToLower(h)) {
						score += 1
					}
				}
			}
		}

		// Check body patterns
		for _, pat := range waf.BodyPats {
			if strings.Contains(bodyLower, strings.ToLower(pat)) {
				score += 3
				break
			}
		}

		// Check cookie patterns
		// No cookies available, skip

		if score >= 2 {
			info := WAFInfo{Detected: true, Name: waf.Name}
			if strings.Contains(waf.Name, "Cloudflare") {
				info.Details = "CF-Ray present or challenge page detected"
			} else if score >= 6 {
				info.Details = "Multiple WAF signatures matched"
			} else {
				info.Details = fmt.Sprintf("Signature confidence: %d/10", score)
			}
			return info
		}
	}

	return WAFInfo{Detected: false, Name: "Unknown"}
}

func DetectTechStack(headers http.Header) map[string]string {
	tech := make(map[string]string)

	server := headers.Get("Server")
	if server != "" {
		tech["Web Server"] = server
	}
	xpowered := headers.Get("X-Powered-By")
	if xpowered != "" {
		tech["Powered By"] = xpowered
	}
	xaspnet := headers.Get("X-AspNet-Version")
	if xaspnet != "" {
		tech["ASP.NET"] = xaspnet
	}
	xfw := headers.Get("X-Frame-Options")
	if xfw != "" {
		tech["Frame Options"] = xfw
	}
	xssprot := headers.Get("X-XSS-Protection")
	if xssprot != "" {
		tech["XSS Protection"] = xssprot
	}
	contenttype := headers.Get("Content-Type")
	if contenttype != "" {
		tech["Content Type"] = contenttype
	}
	setcookie := headers.Get("Set-Cookie")
	if setcookie != "" {
		if strings.Contains(setcookie, "session") {
			tech["Session Mgmt"] = "Session cookies present"
		}
	}

	return tech
}

func (e *Engine) DetectOS() string {
	server := e.LastResponseHeaders.Get("Server")
	if server == "" {
		return "Unknown"
	}
	serverLower := strings.ToLower(server)
	if strings.Contains(serverLower, "win") || strings.Contains(serverLower, "windows") || strings.Contains(serverLower, "iis") {
		return "Windows"
	}
	if strings.Contains(serverLower, "ubuntu") || strings.Contains(serverLower, "debian") || strings.Contains(serverLower, "centos") || strings.Contains(serverLower, "red hat") || strings.Contains(serverLower, "linux") || strings.Contains(serverLower, "unix") || strings.Contains(serverLower, "apache") || strings.Contains(serverLower, "nginx") {
		return "Linux/Unix"
	}
	if strings.Contains(serverLower, "darwin") || strings.Contains(serverLower, "mac") || strings.Contains(serverLower, "apple") {
		return "macOS"
	}
	return "Unknown"
}

